### ISSUE TITLE
Total Reset - WP admin label isn't accurate

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#10]
Total Reset - Doesn't Reset

**To Reproduce**
1. Make a Header Template
2. Go to To Breakdance > Settings > Tools
3. Scroll down to Total Reset
4. Header Template is still there after pressing the total reset button

**Comment by louisreingold** [comment]
It's deliberate - that button isn't supposed to delete your headers, footers, templates or pages you created with Breakdance. 

Those must be deleted manually.

It's just supposed to reset your install to the way it was in its default state, without destroying most of the work you did in Breakdance.

**Comment by louisreingold** [comment]
We should probably update "Pages and Templates you created in Breakdance must still be deleted manually." to say "Content you crated in Breakdance must still be deleted manually."

**Comment by louisreingold** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/6425257/175481334-4c972108-fcfa-458b-bb04-20b055526fa8.png">

**Comment by misslaidlaw** [comment]
Sorry i don't know why my brain didn't comprehend the text under the button properly. I am so use to using a database reset plugin that when I see Total Reset I think of a reset of everything

**Comment by louisreingold** [comment]
Wording will be updated in the next beta.
