### ISSUE TITLE
Backend / Frontend - discrepancy with section background overlays and dividers

### ISSUE THREAD

**Issue by RickCimmino** [soflyy/breakdance-bugs#100]
The result of the overlay is different between backend and frontend (video). Same thing for dividers (images). No cache. Browser Hard refreshed.

https://user-images.githubusercontent.com/74974813/180639181-c45fba5c-85ed-4a4f-a7ce-fe3bfb23fded.mp4

https://user-images.githubusercontent.com/74974813/180639267-db950bb4-d39c-4c4d-883b-1b5f09a8add2.mp4

![CleanShot 2022-07-24 at 08 05 39@2x](https://user-images.githubusercontent.com/74974813/180639289-0ac5c5d9-2221-4ae6-ac0e-587cd9e1a255.jpg)

![CleanShot 2022-07-24 at 08 06 06@2x](https://user-images.githubusercontent.com/74974813/180639277-2ad62700-7b75-4e07-b444-6a047d11a5b3.jpg)

plasticstore.it

**Comment by louisreingold** [comment]
@RickCimmino I believe we fixed this in beta 4. Do you still encounter this problem?

**Comment by RickCimmino** [comment]
The overlay on the background works, but the dividers that are correctly seen in the backend in the frontend do not hold their position.

https://user-images.githubusercontent.com/74974813/181238132-8c7169e0-91d2-4a68-bf67-309630adc922.mp4

**Comment by alemacielsilva** [comment]
> @RickCimmino I believe we fixed this in beta 4. Do you still encounter this problem?

Hy, Louis. I'm using Beta 4 and the Shape Dividers issue continues. The Shape Dividers result is not working as it should when adding two Shapes (top and bottom). The builder displays correctly, but on the frontend it appears inverted. (RUNNING IN LOCALHOST)

https://user-images.githubusercontent.com/21241956/181791610-f6bed826-717f-49af-ae87-c31b8ba89f9e.mp4

**Comment by RickCimmino** [comment]
Thanks for the video, in fact I also inserted some dividers in a later section without problems. I don't know if the problem is that in that particular section which has a background image and an overlay color, the position of the divider placed at the bottom is correct in the backend and wrong in the backend (see images already sent). The overlay color losing transparency in beta 4 has been fixed.

**Comment by alemacielsilva** [comment]
It seems to me that the problem only appears when inserting two Shapes in the same section, for example.

**Comment by louisreingold** [comment]
Thanks for the detailed reports. I've reproduced this and we'll fix it in beta 7/8.

**Comment by louisreingold** [comment]
This is now fixed.
