### ISSUE TITLE
Table of Contents element doesn't highlight correct heading when "scroll to offset"  is above 10px

### ISSUE THREAD

**Issue by joshkho** [soflyy/breakdance-bugs#1002]
1. Create a section with the id "toc"
2. Place two columns in the section 
3. Place a "Rich Text" element on the right column with an article with some h3 and h4 heads.. some paragraphs of text under each heading.
4. Place a "Table of Contents" element in the left column that references #toc to create the headings table.
5. Make the table of contents sticky to the top so that it scrolls with the browser window as the user scrolls down the rich text content.
6. When you click on the headings in the table of contents, notice how it highlights the current/clicked heading that is currently in view.
7. Change the scroll offset of the table of contents to a number above 10 pixels, like 80 pixels for example.
8. When you click on the headings, notice how the highlighted heading is no longer consistent with the heading that was clicked on.  The scroll offset changes how far the window scrolls relative to the heading, but does not offset how far down the page it checks to see where the current content is.

I am using Breakdance 1.6, on Firefox on Windows

**Comment by breakdancemoderator** [comment]
While we were unable to reproduce this exact issue, we made significant updates and fixes to the TOC element in Breakdance 2.0 Beta 1.

**Comment by chris-ard** [comment]
This issue still appears to exist in 2.0. I don't think it takes into account the custom offset when determining what link as the active state on it. For example offset 150px scrolls correctly, but the active state for the link (.is-active-link) does not account for the offset. Using this as a sticky sidebar, for example, is an easy way to replicate the problem.

**Comment by marlousureta** [comment]
This is still an issue until today.
