### ISSUE TITLE
Site Breaks when activating Advanced Custom Fields Pro with Breakdance Blank Theme

### ISSUE THREAD

**Issue by EdwardBlack** [soflyy/breakdance-bugs#1009]
### To reproduce the bug
_(new, blank wp install)_
1. Install Breakdance, Themeless configuration.
2. Upload Advanced Custom Fields Pro (ACF), Activate ACF.
3. Site Breaks with following error-message (from wp-debug).

### Workaround I found
- Before activating ACF, go into Appearance and **delete all other themes** but the Breakdance blank Theme.
- Now activate ACF without problems.

### Error Message
`Warning: require(/home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-content/plugins/breakdance/plugin/themeless/themes/breakdance-zero/inc/block-patterns.php): Failed to open stream: No such file or directory in /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-content/themes/twentytwentytwo/functions.php on line 65`

`Warning: require(/home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-content/plugins/breakdance/plugin/themeless/themes/breakdance-zero/inc/block-patterns.php): Failed to open stream: No such file or directory in /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-content/themes/twentytwentytwo/functions.php on line 65`

`Fatal error: Uncaught Error: Failed opening required '/home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-content/plugins/breakdance/plugin/themeless/themes/breakdance-zero/inc/block-patterns.php' (include_path='.:/usr/share/php') in /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-content/themes/twentytwentytwo/functions.php:65 Stack trace: #0 /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-settings.php(611): include() #1 /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-config.php(96): require_once('/home/555555.cl...') #2 /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-load.php(50): require_once('/home/555555.cl...') #3 /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-admin/admin.php(34): require_once('/home/555555.cl...') #4 /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-admin/index.php(10): require_once('/home/555555.cl...') #5 {main} thrown in /home/555555.cloudwaysapps.com/ylkhodsfhsh/public_html/wp-content/themes/twentytwentytwo/functions.php on line 65`

I'm in no way a programmer, but it seems that this is more on the Breakdance side then on the ACF side to fix. Possible a problem with the switch from twentytwentytwo to the blank theme?

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing support@breakdance.com. Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance you may need.
