### ISSUE TITLE
Section Slideshow not displayed on the frontend

### ISSUE THREAD

**Issue by antonijo01** [soflyy/breakdance-bugs#101]
Hi,

please check the video:
https://www.loom.com/share/e7152a1a1ff14ce088fc92a9e4fb3fb0

The front page is blank.

BD version: 1.0.0-beta.3
Wordpress: 6.0.1
PHP: 8.1.8

**Comment by antonijo01** [comment]
I was not able to reproduce the error in the beta 4 version.
I guess it's solved then.

**Comment by louisreingold** [comment]
Yes, this is solved in beta 4.
