### ISSUE TITLE
Line Thickness on hover results in "Array to string conversion failed" in icon list

### ISSUE THREAD

**Issue by EdwardBlack** [soflyy/breakdance-bugs#1012]
This is what I built in my footer and what the error is rotating around:
![FireShot Capture 069 - Breakdance - Footer Main](https://github.com/soflyy/breakdance-bugs/assets/3930642/3a73d82e-0707-4c84-8682-36ab63381f62)

How to reproduce

1. Put an icon list in footer (haven't tried other places)
2. Set up attributes as shown in the following screenshot
3. If thickness (on hover) is untouched, it saves well. If I put in a thickness (on hover), I get an error 500 (see below). --> Thickness brakes it
4. Just a thickness without hover is unproblematic and results in the same visual result in my case. But if I, for example, would like to thicken up the underline on hover, it wouldn't work because of this bug.

![FireShot Capture 070 - Breakdance - Footer Main2](https://github.com/soflyy/breakdance-bugs/assets/3930642/15edfc7a-d8c2-4f77-96ad-a43e86f9ffa6)

`Breakdance\AJAX\BreakdanceAjaxHandlerException: An exception has been thrown during the rendering of a template ("Array to string conversion") in "9e73ae5d9d9217880b339fcf816907bcce77dd74" at line 82. in /home/55555.cloudwaysapps.com/ybbbbbbbbbdbbbh/public_html/wp-content/plugins/breakdance/plugin/ajax/api.php on 113`

Apache error log:
`[proxy_fcgi:error [pid 20935:tid 140344372954880 [client 277.277.277.46:0 AH01071: Got error 'PHP message: Breakdance\\AJAX\\BreakdanceAjaxHandlerException thrown with message "An exception has been thrown during t............fee2decd/twig-auto-generated-cache/ae/ae452eb312328f6c9e069009c9e0df11.php:12507\n#22 __TwigTemplate_4ba8f9257ca43d2fb2eb5b0c03522a55:macro_typographyPropertiesFromHover in /home/555555.cl...', referer: https://my.site/?breakdance=builder&id=303`

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
