### ISSUE TITLE
ACF Relationship field not found within the Post Loop Builder

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#1015]
1. create a page
2. Create an ACF relationship field for a CPT and have it show up for this particular page only
3. build up this page in breakdance and add a post loop builder. Edit the query and pick 'ACF Relationship' as a source. Breakdance now says that 'no relationship fields have been found'.

<img width="1509" alt="SCR-20231210-kwas" src="https://github.com/soflyy/breakdance-bugs/assets/7188497/649daec7-ade8-43df-b51e-037cad54dc28">

<img width="1354" alt="SCR-20231210-kuqk" src="https://github.com/soflyy/breakdance-bugs/assets/7188497/19a9f5f5-f3a3-463d-8735-d344eb78f458">

You should also include the following information:
 - Breakdance version: v1.7.0 beta 2
 - Safari - Mac OS - all latest version

**Comment by ajlcomputers** [comment]
I have this problem too.

**Comment by binaryduke** [comment]
+1

**Comment by fronzta** [comment]
me too

**Comment by kbcelik** [comment]
+1

![ss-1](https://github.com/soflyy/breakdance-bugs/assets/52469338/deccaee6-1f17-4c74-bdf0-f6e91e95aee5)
![ss-2](https://github.com/soflyy/breakdance-bugs/assets/52469338/4d209986-0d18-45ae-9b24-09deb8d5c510)

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
