### ISSUE TITLE
Bug: Form Builder: "Active Campaign" Action: Not all Active Campaign fields available in field mapping

### ISSUE THREAD

**Issue by GregorTr** [soflyy/breakdance-bugs#1016]
## Summary
Only 20 custom Active Campaign fields are fetched from the ActiveCampaign API. Therefore not all ActiveCampaign fields are available to be mapped to Breakdance form inputs.

As far as I could find out, this is due to the omitted "limit" param in your backend API request:
``https://<activecampaign-dashboard>.api-us1.com/api/3/fields``
instead of (for example):
``https://<activecampaign-dashboard>.api-us1.com/api/3/fields?limit=100``

I assume that either ActiveCampaign changed their API behavior to only return 20 fields instead of all fields if the param is omitted or you didn't test this with an ActiveCampaign account with more than 20 custom fields.

## Steps to reproduce:
1. Add ActiveCampaign API key & url in Breakdance settings
2. Create Form with Form Builder element in Breakdance
3. Add action "Active Campaign"
4. Check the available fields in the "Field" dropdown of the action dialog. Only 20 field are available. (FYI: At least for me it seems as if the API returns 20 seemingly random fields, so don't check if your 21. field is missing, as another one might be the missing one)

### Additional info
Breakdance Version: 1.6.1  
WP Version: 6.4.1  
Browser: Chrome 119  
OS: Mac OS Ventura

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
