### ISSUE TITLE
Bug: Form Builder: "Active Campaign" Action: Form error is shown in frontend if email is already stored in ActiveCampaign list

### ISSUE THREAD

**Issue by GregorTr** [soflyy/breakdance-bugs#1017]
## Summary
If a form (which is connected to ActiveCampaign) is submitted multiple times OR an email which is already stored in the connected ActiveCampaign list is entered, a visible form error is shown to visitors in the frontend after the form submission.

Other actions that are also added to the same form, like "Store Submission" or "Email" still work properly, however an added "Redirect URL" is not opened due to the error.

> I understand that this could be interpreted as a form error (as which it gets logged in the stored submission), but think that this particular error shouldn't be communicated to website visitors.

> Depending on the type of form that is connected to ActiveCampaign, or if multiple different forms are connected to the same ActiveCampaign list, this error might be shown regularly.

## Steps to reproduce
1. Add ActiveCampaign API key & url in Breakdance settings
2. Create Form with Form Builder element in Breakdance
3. Add Redirect URL
4. Add action "Active Campaign"
5. Use the field mappings in the action dialog to map at least an email field from Breakdance to an email field of ActiveCampaign.
6. Save
7. Visit the page in the frontend and submit the form (twice, using the same email)
8. On the second submit a form error is shown to the user and no redirect happens

### Additional info
Breakdance Version: 1.6.1  
WP Version: 6.4.1  
Browser: Chrome 119  
OS: Mac OS Ventura

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
