### ISSUE TITLE
IO-TS decoding failed in Beta 3

### ISSUE THREAD

**Issue by alemacielsilva** [soflyy/breakdance-bugs#102]
IO-TS error in Beta 3 when I tried to include the Social Icons element. The widget is working fine.

![image](https://user-images.githubusercontent.com/21241956/180663880-7a9dabc7-939d-44e0-bd99-c85ec7a60cb1.png)

**Comment by louisreingold** [comment]
@alemacielsilva I can't reproduce this. 

Please email support@breakdance.com with your WP admin login details and we'll take a look.

Alternatively, if you see the message again, open another bug report here and include a screenshot of the errors in your browser console.
