### ISSUE TITLE
Add line number to php/css/js editors, global code css and js scripts

### ISSUE THREAD

**Issue by ElinaMacichina** [soflyy/breakdance-bugs#1020]
There is no line number on code block editors, global code css and scripts.
When error message pop up, in message you can see line number where to find problem, it would be convenient not to count by eye.
![image](https://github.com/soflyy/breakdance-bugs/assets/92719267/aeedbb0e-a6fe-41fd-b574-60eac5eb92ce)

**Comment by louisreingold** [comment]
https://breakdance.canny.io/features/p/php-code-editor-please-make-it-wrap-and-show-lines-numbers
