### ISSUE TITLE
Control Slider Action not working

### ISSUE THREAD

**Issue by codingharz** [soflyy/breakdance-bugs#1028]
**What version of Breakdance are you using?**
Since version 1.5

**What browser are you using?**
Chrome, Firefox

**What operating system are you using?**
Windows 10

**Reproduction Steps**
1. Create repeater field
2. Select global block
3. Select repeater field
4. Set layout to slider
6. Create icon
7. Link > Action > Control Slider > Select repeater field > select next slide
8. Save

The slider cannot be controlled in the frontend. Please watch my video.

**Reproduction Video**
https://www.loom.com/share/81c0a34de7f342b18b67d37bd3b80f51?sid=dce82d48-b01d-4cc9-994c-fd0c7c6f3d53

The bug has already been described here:

https://github.com/soflyy/breakdance-bugs/issues/959

**Comment by codingharz** [comment]
Is there anything new here yet? :-)

**Comment by mtenreiro** [comment]
I'm having this exact same issue with 2.0, as described in your text and loom video.

It looks like the Control Slider action only works with Advanced Slider.

**Comment by vnshah** [comment]
I am having the exact same issue - did you find any fix for this?

**Comment by vnshah** [comment]
@louisreingold - I have also raised a support ticket for the same

**Comment by vnshah** [comment]
@codingharz Did you manage to fix this issue? I am stuck and not able to use the repeater field with Control Slider action

**Comment by breakdancemoderator** [comment]
This is fixed in Breakdance 2.3.
