### ISSUE TITLE
Post List element - image apparently doesn't work

### ISSUE THREAD

**Issue by alemacielsilva** [soflyy/breakdance-bugs#103]
In the Post List element, the image apparently doesn't work if we remove the Title.

![image](https://user-images.githubusercontent.com/21241956/180671241-bfb1607f-eae9-4ad0-8b4d-8ad6f528c446.png)
![image](https://user-images.githubusercontent.com/21241956/180671267-996a6709-3026-455d-ac1a-1daae88b05cd.png)

**Comment by louisreingold** [comment]
I can't reproduce this: https://www.loom.com/share/a39ac6450c2a488a9bc6188a13ff55ce

Please email support@breakdance.com with your WP admin login details and we'll take a look.
