### ISSUE TITLE
Forms: I18N For Checkbox Validation Error Message

### ISSUE THREAD

**Issue by ElinaMacichina** [soflyy/breakdance-bugs#1031]
#814 

Hello, 
Please make message for checkbox validation same as others validations (from browser side) or make it customizable or translatable with WPML, because it is not suitable for non english websites or multilanguage websites. I had to change it inside your breakdance plugin and it is not appropriate solution for my situation.
![image](https://github.com/soflyy/breakdance-bugs/assets/92719267/8d975601-7fd4-4596-8722-63b96d2161c9)

![image](https://github.com/soflyy/breakdance-bugs/assets/92719267/1565c893-d5a3-44c4-8592-0ec972964fc7)

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
