### ISSUE TITLE
Reduced motion UI-setting breaks popups.

### ISSUE THREAD

**Issue by bouveng** [soflyy/breakdance-bugs#1035]
The “Reduced Motion” UI-setting in iOS breaks any popup with entrance/exit animations.

Instead of just returning from the init(); function, just revert the animation if set to none so popups open with no animation if devices is preferring reduced motion.

To reproduce: 

1, Add a popup with entrance animation.
2, On iOS, go to Settings -> Accessibility -> Motion and turn on "reduced motion".
3, Try to open previous popup.

BD 1.7
iOS / Safari

Br.

/J

**Comment by louisreingold** [comment]
Thanks for the report. This will be addressed in 2.0.

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
