### ISSUE TITLE
Crtl + Z removes everything from TinyMCE

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#1036]
BD 1.7 with Zero theme

If I add text to a rich text element that has TinyMCE enabled, press Crtl + Z and open the richt text element again, all my text in the TinyMCE editor is gone!

**Comment by louisreingold** [comment]
Yes, if you make a change to any control, and then press CTRL+Z, which is the keyboard shortcut for undo, your change will be undone. That is correct behavior. If I'm missing something, please open a new issue with a Loom clearly showing the problem.
