### ISSUE TITLE
Time Conditions

### ISSUE THREAD

**Issue by Bonnie-Clyde** [soflyy/breakdance-bugs#1043]
For example:
1. Create a page
2. Open the page with Breakdance
3. Add an element - one that supports conditions
4. Choose 'Current time' base condition
5. Set as 'before'
6. Select 'and'
7. Unable to select same  'Current time' base to select 'after'
Unless there is another way to achieve this.
This would be handy say for Open Hours and show Closed after hours.

**Comment by louisreingold** [comment]
Feature requests most be posted at https://breakdance.canny.io/
