### ISSUE TITLE
"Breakdance Global Blocks" don't render in post editor without Section element 

### ISSUE THREAD

**Issue by Nicscott01** [soflyy/breakdance-bugs#1044]
Breakdance Global Blocks that do not have a Section element will not render in the WP post editor (Gutenberg). It's not even that the content needs to be nested in the Section element, it just appears to need to be somewhere on the block.

This was reproduced and tested on breakdance.com/try

https://oxygen-q8bh736tjrhxl.oxygen-demo.qsandbox.org/
code: 3252

**Comment by breakdancemoderator** [comment]
We couldn't reproduce this. 

We kindly request that you contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com). Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.
