### ISSUE TITLE
Menu Builder element, Keep Menu Selected while styling does not work

### ISSUE THREAD

**Issue by maxproway** [soflyy/breakdance-bugs#1045]
Hi, 
Menu Builder element, **"Keep Menu Selected while styling"** does not work (toggle does not save a state)

![image](https://github.com/soflyy/breakdance-bugs/assets/98363451/ee7356d5-956b-4942-8605-41af0ddca3e2)

After making toggle "ON" and back its again in "OFF" position:

![image](https://github.com/soflyy/breakdance-bugs/assets/98363451/f2a5e994-91c9-43f9-a314-e2cee6a42e4b)

Dropdown menu not visible accordingly.

**Comment by louisreingold** [comment]
Correct behavior.

**Comment by maxproway** [comment]
how to edit menu then? need to jump back and forward to visible check out changes?
