### ISSUE TITLE
Lightbox link on image does the same as Full Size Image

### ISSUE THREAD

**Issue by paulherzlich** [soflyy/breakdance-bugs#105]
Place an image element in a column.
Set the Link to Lightbox. 

Click image on the front end
Instead of getting a Lightbox, I get the full size image file (as seen in the address bar).

(Tested Beta 4 on Local on macOS with Safari and Chrome.

**Comment by misslaidlaw** [comment]
Same for me

**Comment by louisreingold** [comment]
Solved in beta 5.

**Comment by Gille666** [comment]
It is not solved, I opened a new ticket. Pls fix this.
