### ISSUE TITLE
Mini Cart Conflict With WooCommerce PayPal Payments Plugin: This element doesn't have a ssr.php file

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/breakdance-bugs#1054]
When enabling WooCommerce PayPal Payments: https://en-gb.wordpress.org/plugins/woocommerce-paypal-payments/

The mini cart breaks on the basket page and on the checkout page, it still works on the single product page.

It seems there is a conflict between the plugin and the Breakdance Mini Cart code as when disabling the plugin it works fine again.

When the plugin is enabled on the basket and checkout page rather than rendering the mini cart it shows a red error message stating: **This element doesn't have a ssr.php file**

 - Breakdance version: 1.7.0
 - Browser & OS: Chrome, Windows 11
 - PHP version: 8.1
 - WordPress version: 6.5

1. Install WooCommerce and import sample products
2. Install WooCommerce PayPal Payments: https://en-gb.wordpress.org/plugins/woocommerce-paypal-payments/
3. Turn WooCommerce PayPal Payments on as a payment method (Requires being connected to PayPal)
4. Create a checkout page in Breakdance
5. Add a mini cart to a header template in Breakdance
6. View checkout and see that the mini cart now displays: **This element doesn't have a ssr.php file** rather than showing the cart

**Comment by coes123** [comment]
It happened to me too. 

`
### WordPress Environment ###

WordPress address (URL): http://shopsoule.com
Site address (URL): http://shopsoule.com
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.44-48-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.8.3
WC Database Prefix: iui_
Total Database Size: 12.92MB
Database Data Size: 10.83MB
Database Index Size: 2.09MB
iui_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iui_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iui_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iui_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iui_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
iui_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
iui_breakdance_icons: Data: 2.52MB + Index: 0.27MB + Engine InnoDB
iui_breakdance_icon_sets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iui_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
iui_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_options: Data: 4.02MB + Index: 0.08MB + Engine InnoDB
iui_postmeta: Data: 3.08MB + Index: 0.13MB + Engine InnoDB
iui_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
iui_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
iui_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
iui_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
iui_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iui_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
iui_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iui_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
iui_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
iui_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
iui_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
iui_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
iui_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
iui_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 12
acf-field-group: 3
attachment: 72
breakdance_footer: 1
breakdance_header: 1
breakdance_template: 14
customize_changeset: 1
page: 15
post: 2
product: 10
product_variation: 32
revision: 52
shop_order_placehold: 2
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Advanced Custom Fields PRO: by WP Engine – 6.2.9
Breakdance: by Breakdance – 1.7.1
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.31
WooCommerce PayPal Payments: by WooCommerce – 2.7.0
WooCommerce: by Automattic – 8.8.3

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 5 KB

### WC Pages ###

Shop base: #58 - /shop/
Cart: #59 - /carrito/
Checkout: #60 - /finalizar-compra/
My account: #61 - /mi-cuenta/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Breakdance Zero Theme
Version: 1.0.0
Author URL: https://breakdance.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/cart/cart-totals.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/cart/mini-cart.php version 7.8.0 is out of date. The core version is 7.9.0
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-billing.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-checkout.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-login.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/form-shipping.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/checkout/payment.php version 7.8.0 is out of date. The core version is 8.1.0
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/content-product.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/global/form-login.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/global/quantity-input.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/loop/loop-start.php
/home/customer/www/shopsoule.com/public_html/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/templates/loop/rating.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-02 20:08:03 -06:00
Options: ✔
Notes: 68
Onboarding: -

### Action Scheduler ###

Complete: 110
Oldest: 2024-04-26 20:09:50 +0000
Newest: 2024-05-02 15:05:04 +0000

Failed: 1
Oldest: 2024-04-30 00:38:47 +0000
Newest: 2024-04-30 00:38:47 +0000

Pending: 2
Oldest: 2024-05-02 22:08:03 +0000
Newest: 2024-05-03 02:25:14 +0000


### Status report information ###

Generated at: 2024-05-02 09:06:41 -06:00
`

**Comment by piegiova** [comment]
Same here.

### wp-core ###

version: 6.4.4
site_language: it_IT
user_language: en_GB
timezone: +01:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/xurcnsak/vinoalvino.appennino.studio
wordpress_size: 60,87 MB (63830328 bytes)
uploads_path: /home/xurcnsak/vinoalvino.appennino.studio/wp-content/uploads
uploads_size: 3,52 MB (3686833 bytes)
themes_path: /home/xurcnsak/vinoalvino.appennino.studio/wp-content/themes
themes_size: 3,21 MB (3367958 bytes)
plugins_path: /home/xurcnsak/vinoalvino.appennino.studio/wp-content/plugins
plugins_size: 90,90 MB (95317088 bytes)
database_size: 42,39 MB (44449792 bytes)
total_size: 200,89 MB (210651999 bytes)

### wp-active-theme ###

name: Breakdance Zero Theme (breakdance-zero)
version: 1.0.0
author: Breakdance Builder
author_website: https://breakdance.com/
parent_theme: none
theme_features: core-block-patterns, menus, widgets-block-editor, post-thumbnails, title-tag, woocommerce, wc-product-gallery-zoom, wc-product-gallery-slider, wc-product-gallery-lightbox
theme_path: /home/xurcnsak/vinoalvino.appennino.studio/wp-content/plugins/breakdance/plugin/themeless/themes/breakdance-zero
auto_update: Disabled

### wp-plugins-active (12) ###

Advanced Custom Fields PRO: version: 6.3.0.1, author: WP Engine, Auto-updates disabled
Breakdance: version: 1.7.2, author: Breakdance, Auto-updates disabled
Debug Log Manager: version: 2.3.3, author: Bowo, Auto-updates disabled
Health Check & Troubleshooting: version: 1.7.0, author: The WordPress.org community, Auto-updates disabled
Nexi XPay: version: 7.3.3, author: Nexi SpA, Auto-updates disabled
Polylang4Breakdance: version: 2.0.0, author: Michael Thomas aka SUPAMIKE, Auto-updates disabled
Polylang for WooCommerce: version: 1.9.4, author: WP SYNTEX, Auto-updates disabled
Polylang Pro: version: 3.6.1, author: WP SYNTEX, Auto-updates disabled
Smash Balloon Instagram Feed: version: 6.3.1, author: Smash Balloon, Auto-updates disabled
WooCommerce: version: 8.9.1, author: Automattic, Auto-updates disabled
WooCommerce PayPal Payments: version: 2.7.1, author: WooCommerce, Auto-updates disabled
WPCode Lite: version: 2.1.12, author: WPCode, Auto-updates disabled

### wp-plugins-inactive (3) ###

Admin and Site Enhancements (ASE): version: 6.9.13.2, author: wpase.com (latest version: 7.0.0), Auto-updates disabled
LiteSpeed Cache: version: 6.2.0.1, author: LiteSpeed Technologies, Auto-updates disabled
WP phpMyAdmin: version: 5.2.1.12, author: Puvox.software, Auto-updates disabled

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.77.el7.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 8.1.28 64bit
php_sapi: litespeed
max_input_variables: 100000
time_limit: 300
memory_limit: 1024M
max_input_time: 600
upload_max_filesize: 8M
php_post_max_size: 256M
curl_version: 8.7.1 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-05-31T10:26:11+00:00
utc-time: Friday, 31-May-24 10:26:11 UTC
server-time: 2024-05-31T11:26:09+01:00

### wp-database ###

extension: mysqli
server_version: 10.6.17-MariaDB-cll-lve-log
client_version: mysqlnd 8.1.28
max_allowed_packet: 268435456
max_connections: 100000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/xurcnsak/vinoalvino.appennino.studio/wp-content
WP_PLUGIN_DIR: /home/xurcnsak/vinoalvino.appennino.studio/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

<img width="1399" alt="screenshot" src="https://github.com/soflyy/breakdance-bugs/assets/171336729/a73d4ddd-601e-4319-b9c4-6fd620bfd28b">

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
