### ISSUE TITLE
Social Share element needs the Twitter icon replacing with the X icon

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#1057]
Breakdance: 1.7

Twitter rebranded to X on July 23rd, 2023. The social share element still has the twitter bird icon and there is no way to replace it with a custom icon. Either provide X as a social network, or allow the means to add custom icons.

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
