### ISSUE TITLE
Missing parameter in WP filter leading to incompatibility with YITH Ajax Product filter

### ISSUE THREAD

**Issue by rickydwilson-dcs** [soflyy/breakdance-bugs#1059]
I have been diagnosing an incompatibility with YITH Ajax Filter plugin and Breakdance. This manifests itself on post archive page (blog).

The YITH support team shared the information at the bottom of this bug report explaining their view of the issue ... essentially there code expects 2 elements to be present in the hook but Breakdance doesn't provide them both. They have "amended" Breakdance hook so this works in this staging site as part of their investigation.

For example:
1. Visit Blog page https://www.staging3.cuddleplushfabrics.co.uk/blog/.
2. No header or any page elements other than some oversized images are loaded

The blog page returns an error in Breakdance builder:
ArgumentCountError: Too few arguments to function YITH_WCAN_Variations_Filtering::filter_loop_title(), 1 passed in /home/customer/www/[staging3.cuddleplushfabrics.co.uk/public_html/wp-includes/class-wp-hook.php](http://staging3.cuddleplushfabrics.co.uk/public_html/wp-includes/class-wp-hook.php) on line 324 and exactly 2 expected in /home/customer/www/[staging3.cuddleplushfabrics.co.uk/public_html/wp-content/plugins/yith-woocommerce-ajax-product-filter-premium/includes/class-yith-wcan-variations-filtering.php](http://staging3.cuddleplushfabrics.co.uk/public_html/wp-content/plugins/yith-woocommerce-ajax-product-filter-premium/includes/class-yith-wcan-variations-filtering.php) on 192

[Screenshot](https://p29.zdusercontent.com/attachment/242287/PH5kb9G3Z1Z7fGNdGNgK6m93u?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..-keHgn9ubMh33YjivuXvuQ.qerISBr_sGeUDjc9DrrBty6GuRcy9A3i4zRPPCD6G86qzdO72aWcgGYm0TblcI5a0RpCBE2O50YYiE1CU8gmeCGK6wUBaN4L8FsfLIaL-mo3FMQypjyi-IcFZYzzfuG4P84GrkMwh2Ebz9NvR6RgUfiqgrGJPXCPR85CBgvb5ws7mMhb3CujEAsOWRNfPFCgk90qBJL5lCtIkYbLkIFz1wEmsChYMYrFWZ3CzGu1DfR3ZmAsFR3wK9IHDh_fsVxAqCUdy_mJ16lbyKLA5tRKQKzjW_mbMG7Fs2lB-m7NDas.QvuoJUPyG18YqCGm9LWryw)

-------- YITH SUPPORT REPORT -----------
YITH Support Team (YITH Support Team)
Apr 28, 2024, 10:29 GMT+2

Hi there,
 
Thank you for reaching out and tell us your issue.
 
We took a look at your problem and we could see that there is a problem between our "Variation filtering" from our plugin and your page builder element for the posts ( if you disable this option from our plugin, the problem dissapears ).
 
This problem requires to talk about WordPress hooks and might seems a bit technical:
 
After taking a quick look at your page builder, we could see that is using WordPress filters in their elements, but they don't provide the parameters that WordPress does, parameters that our plugin expects. If you take a look into the the hook that your page builder use:
 
https://developer.wordpress.org/reference/hooks/the_title/#:~:text=the_title%20is%20a%20filter%20applied,string)%20from%20the%20filter%20function.
 
[Screenshot](https://yithemes.zendesk.com/attachments/token/hxGoAhC87PL1NlI4qfWveb8BB/?name=image.png)
 
It gives two parameters, the title and the post ID ( in our case the post ID or the object post will work for our functions ). However your page builder only offers the title:
 
[Screenshot](https://yithemes.zendesk.com/attachments/token/BTtT0F1Xx31MK1LbPV5vVZ5ad/?name=image.png)

 
For that reason as our function is expecting those 2 parameters ( the second specially, to know if the object is a post or a product ), so the notifies this through an error as it breaks our functionality.
 
I added the second parameter in the element of the page builder and now the page works with our plugin and the variation filtering enabled:
 

[Screenshot ](https://yithemes.zendesk.com/attachments/token/R2MLly3M2fCdmsqEI07p1tXJN/?name=image.png)

[Screenshot](https://yithemes.zendesk.com/attachments/token/6oHx2jgiJHQ2fUWbUTpUEk8C2/?name=image.png)

 
However this changes will be removed when you update the page builder plugin ( also we are not sure if other elements have this problem too ) so I suggest to contact your page builder developers and ask them to follow the same structure of WordPress and add this second parameter.

----- END OF YITH SUPPORT -----

You should also include the following information:
 - Breakdance 1.7.0
 - Safari Mac
 - Wordpress 6.5.2 PHP 8.1.28

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
