### ISSUE TITLE
Shortcodes in heading, texts, and other elements are not processed when using Breakdace templates

### ISSUE THREAD

**Issue by ci2014** [soflyy/breakdance-bugs#1060]
Shortcodes in heading, texts, and other elements are not processed when using Breakdace templates

Clear description of the bug:

1. Use any theme, or breakdance-zero-theme: [soflyy/breakdance-zero-theme (github.com)](https://github.com/soflyy/breakdance-zero-theme)
2. add to functions php

add_shortcode('my_custom_shortcode', 'my_custom_shortcode_function');
function my_custom_shortcode_function() {
  return "World";
}

3. Use [my_custom_shortcode] anywhere in a page created with breakdance, for example, a heading with the Text  "Hello [my_custom_shortcode]!". Result will be Hello World!

4. Create a template using breakdance and apply it to any page. Use the same heading in the template "Hello [my_custom_shortcode]!" will return "Hello [my_custom_shortcode]!" instead of Hello World!

 - Breakdance version: 1.7
 - Browser & OS: Microsoft Edge on Mac

**Comment by breakdancemoderator** [comment]
To use shortcodes in Breakdance, either:
 - use the Shortcode element
 - use the Shortcode Wrapper element
 - to use shortcodes in the manner you've described (without using the Shortcode/Shortcode Wrapper element), in the WP admin, go to Breakdance > Settings > Advanced and enable the `Apply the_content filter to Breakdance content` option

**Comment by ci2014** [comment]
@breakdancemoderator You marked it as completed, but you did not understand the issue, that the shortcodes are processed in a page, but not processed in a template. They are handled differently, and that is a bug.

**Comment by breakdancemoderator** [comment]
Thank you for contacting us. We've received your request and will get back
to you with a response as quickly as possible.

*If you have given us any login credentials, you should change them once
your ticket is solved.*

Note: To remain focused and help you get the best support possible, we will
only address issues raised in the original message you sent us. If you have
any new questions or unrelated issues, please submit them as separate
tickets.

Best Regards,
The Breakdance Team
{#HS:2609550969-14096#}
