### ISSUE TITLE
Dashboard update installs version 1.0.0 instead of latest version ( 1.7.2 )

### ISSUE THREAD

**Issue by MrBushid0** [soflyy/breakdance-bugs#1066]
Hi, 

Pretty sure this problem just started today 2024/05/26 but it seems that when updating BD via the WP Dashboard, it just keeps updating to version 1.0.0 instead of the latest version ( currently 1.7.2 ) 

You can see the behavior in a local install in the video

https://github.com/soflyy/breakdance-bugs/assets/3267657/4546e583-7dcf-40cd-b02e-e28698bf4514

Thanks

**Comment by louisreingold** [comment]
Fixed. Thank you!

**Comment by MrBushid0** [comment]
Thanks for the quick fix!
