### ISSUE TITLE
WooCommerce Featured Image

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#107]
**I am trying to create this layout**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/7070435/180785790-7bd38847-ce72-44f2-a615-b60cb8665422.png">

**When adding an image element it doesn't pull from the WooCommerce Featured Image** 

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/7070435/180785891-b0e03245-0405-4513-901a-f908285a26fb.png">

**This is what it looks like on the front en**d. 
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/7070435/180786055-2a88afd8-a0a3-435e-96ee-777e2b1d2dfe.png">

**Comment by louisreingold** [comment]
Solved in beta 5.

**Comment by misslaidlaw** [comment]
Thank you
