### ISSUE TITLE
Adding dynamic mode for title when in advanced accordion

### ISSUE THREAD

**Issue by nico-lino** [soflyy/breakdance-bugs#1071]
Impossible to edit title in dynamic way when in advanced accordion.
So no way to use this wiidget properly with repeater fields allolwing to add super extra content.

**Comment by breakdancemoderator** [comment]
Thank you for your suggestion and your interest in improving Breakdance. We appreciate your engagement and the effort to contribute.

Please note, all feature requests must be submitted through our dedicated suggestions platform on our [Canny board](https://breakdance.canny.io/). This is the only channel where we collect and review user suggestions. If your feature request is not posted there, it will not be considered.

Before submitting, please check if a similar request already exists to avoid duplication. If it does, you can support it by adding your vote and comments.

We look forward to seeing your ideas on our Canny board. Thank you for helping us continue to refine and enhance Breakdance.
