### ISSUE TITLE
Visibility issue with Menu Custom Area

### ISSUE THREAD

**Issue by Dixfractions** [soflyy/breakdance-bugs#1072]
When you set visibility to Hide in Mobile Menu for Menu Custom Area elements, they disappear right away when you collapse the mobile menu. They should only disappear once the menu is closed.

I am using the latest beta version of Breakdance, 2.0.

The problem occurs in all browsers.

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
