### ISSUE TITLE
Can't update from latest stable to 2.0 beta from within wordpress

### ISSUE THREAD

**Issue by cassianmx** [soflyy/breakdance-bugs#1075]
had the latest stable version and tried to update to 2.0 from inside wordpress so I did the following

1. Enabled "Receive beta version updates" from BD settings
2. went to installed pllugins and selected "update now" when it said "View version 2.0.0-beta.1 details"
3. It downloads and says "updated!" but it remains a 1.7.0-beta.1
4. Tried the same thing multiple times with the same result

**Comment by breakdancemoderator** [comment]
Thanks for the report. We've resolved this and you can now update to 2.0 Beta 1 in a click.
