### ISSUE TITLE
Single Page / Post Settings

### ISSUE THREAD

**Issue by marius-robotdance** [soflyy/breakdance-bugs#1077]
It would be nice if Breakdance has not only global settings... instead breakdance should also have single page / post settings for custom css / js... so it is possible to inject css (also responsive ) and js only for one page....

At the moment it is only possible to do this via a code block.

**Comment by breakdancemoderator** [comment]
Thank you for your suggestion and your interest in improving Breakdance. We appreciate your engagement and the effort to contribute.

Please note, all feature requests must be submitted through our dedicated suggestions platform on our [Canny board](https://breakdance.canny.io/). This is the only channel where we collect and review user suggestions. If your feature request is not posted there, it will not be considered.

Before submitting, please check if a similar request already exists to avoid duplication. If it does, you can support it by adding your vote and comments.

We look forward to seeing your ideas on our Canny board. Thank you for helping us continue to refine and enhance Breakdance.
