### ISSUE TITLE
2.0 Design Presets Override by Element Instance

### ISSUE THREAD

**Issue by marius-robotdance** [soflyy/breakdance-bugs#1078]
Design Presets are great, but if you attach a design preset to an element the design options of that instance are removed.
It should be possible to override these Design Preset on Instance basis.

For example you have 6 Icon Boxes with a Design Preset attached... only one Icon Box has another Background and Font Color.
Instead of setup a new Design Preset it is then possible to simply override these Settings.

**Comment by breakdancemoderator** [comment]
Thank you for your suggestion and your interest in improving Breakdance. We appreciate your engagement and the effort to contribute.

Please note, all feature requests must be submitted through our dedicated suggestions platform on our [Canny board](https://breakdance.canny.io/). This is the only channel where we collect and review user suggestions. If your feature request is not posted there, it will not be considered.

Before submitting, please check if a similar request already exists to avoid duplication. If it does, you can support it by adding your vote and comments.

We look forward to seeing your ideas on our Canny board. Thank you for helping us continue to refine and enhance Breakdance.
