### ISSUE TITLE
WooCommerce Product List

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#108]
I do not know why there is no ability to manipulate the alignment of the text (center, left-right) or the size of images (ratio) on the product list.  Not sure if this is a feature but it seems to be a must rather than an option. 

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/7070435/180787293-934f3072-a8e7-4aa9-b7d8-ee799d28ba3e.png">

<img width="389" alt="image" src="https://user-images.githubusercontent.com/7070435/180787703-1e50be4b-2b24-4546-9d61-713358efcbc8.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/7070435/180787754-9404f9bb-6d72-42e8-9ceb-b7148f77fcbc.png">

**Comment by louisreingold** [comment]
Image Ratio - here's how to do it currently: https://www.loom.com/share/634f7a5791034cff987168c99b12b40c. Thoughts? Should we add a dedicated option for it? What do other builders do? 

Text Align: planned

**Comment by louisreingold** [comment]
In beta 5, we added styling controls to tweak the following to each product in a list of products:
 - text align
 - background
 - border
 - shadow
 - padding

**Comment by misslaidlaw** [comment]
Sorry I am late to respond. Github doesn't send me notifications. In other builders the options are available in the builder. I've never had to go into the customiser to edit anything to do with woocommerce unless the theme I am using has forced it like Blocksy.
