### ISSUE TITLE
2.0 Grid Child Span Range Slider

### ISSUE THREAD

**Issue by marius-robotdance** [soflyy/breakdance-bugs#1080]
It would be nice to have a range slider (e.g. 12) for column width (gird-column) and row height (grid-row) so you don't need to write custom "span X", so it's easier and faster to define the column width and row height.

**Comment by breakdancemoderator** [comment]
Thank you for your suggestion and your interest in improving Breakdance. We appreciate your engagement and the effort to contribute.

Please note, all feature requests must be submitted through our dedicated suggestions platform on our [Canny board](https://breakdance.canny.io/). This is the only channel where we collect and review user suggestions. If your feature request is not posted there, it will not be considered.

Before submitting, please check if a similar request already exists to avoid duplication. If it does, you can support it by adding your vote and comments.

We look forward to seeing your ideas on our Canny board. Thank you for helping us continue to refine and enhance Breakdance.
