### ISSUE TITLE
Pricing Table element: accent properties set to display none in preset controls

### ISSUE THREAD

**Issue by udoro** [soflyy/breakdance-bugs#1082]
1. Create a page
2. Add the pricing table
3. Create preset from design
4. Edit preset
5. The control for editing the accent is not available, it is set to display none.

Screenshot:
![image](https://github.com/soflyy/breakdance-bugs/assets/22454125/7c13b906-833a-4aa6-bf80-5248980cae82)

You should also include the following information:
 - Breakdance version 2.0 Alpha Beta 1
 - Browser & OS -   Chrome on Windows 10

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 2.
