### ISSUE TITLE
Breakdance Alpha 2.0 Presets:  modified values do not display when the modified button is selected

### ISSUE THREAD

**Issue by udoro** [soflyy/breakdance-bugs#1083]
You MUST include a clear description of the bug and EXACT steps to reproduce the bug or IT WILL BE CLOSED:

For example:
1. Create a page
2. add any element
3. add styles and create preset from style
4.  One the preset edit panel, click on modified at the bottom corner
5. Instead of seeing all the modified properties, the panel says 'no preset found'

![image](https://github.com/soflyy/breakdance-bugs/assets/22454125/f3e20c60-4dbd-4600-aae8-6adbfadd496f)

You should also include the following information:
 - Breakdance version - 2.0 Alpha - beta 1
 - Browser & OS - Chrome on Windows 10

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 2.
