### ISSUE TITLE
2.0 Vertical Tabs didn't remain vertical for Phone Landscape and lower resolution 

### ISSUE THREAD

**Issue by maxproway** [soflyy/breakdance-bugs#1084]
![image](https://github.com/soflyy/breakdance-bugs/assets/98363451/febeec51-6dcd-4f83-bb6c-f1aeb8f6e7c3)

![image](https://github.com/soflyy/breakdance-bugs/assets/98363451/342b0709-bae8-4ac2-bd55-59eda17d72e6)

BD v 2.0 beta 1
WIndows 11
Google Chrome

**Comment by breakdancemoderator** [comment]
By default, the vertical setting for the Tabs element changes to horizontal at the 'Phone Landscape' breakpoint. You may use the 'Horizontal At' property to change the breakpoint at which this occurs.
