### ISSUE TITLE
WPMenu item inside a menu custom Dropdown

### ISSUE THREAD

**Issue by iam39** [soflyy/breakdance-bugs#1085]
Not sure if this is a bug. Or I'm trying to do something impossible?
I'm using 2.0 beta
I have a WPMenu item inside a menu custom Dropdown. (To make it easier for the client to manage). 
I have this set to never show mobile menu, but it still does.
Any ideas?
Thanks
Dan

**Comment by breakdancemoderator** [comment]
Hello, 

Currently, placing a menu inside another menu is not supported.
