### ISSUE TITLE
A.I Plugin Does Not Work - Critical Error Message When Applying BreakdanceAI License & OpenAI License + 500 Error

### ISSUE THREAD

**Issue by mgexiled** [soflyy/breakdance-bugs#1087]
I had this occur on an existing website, and I tested on a fresh website with no other plugins instead but breakdance and breakdanceAI. 

1) After intalling the BreakdanceAPI plugin successfully, navigate to Breakdance > Settings > AI Assistant 
2) Input BreakdanceAPI key and OpenAI Key, and Save
3) Note that upon saving there is a "a critical error has occured on your website" message within the container of the Breakdance AI settings page. 
4) Navigating to Breakdance Page Builder on any page, a 500 error appears (see attached Screenshots)
5) This results in the Page Builder being frozen and unusable. 

![breakdanceAI500message3](https://github.com/soflyy/breakdance-bugs/assets/41072075/bbd18dad-5d3b-4210-a8ad-847dd5c9ac2a)
![breakdanceAI500message2](https://github.com/soflyy/breakdance-bugs/assets/41072075/687f8881-f8ef-4307-8f2c-d44961b9e2ed)
![breakdanceAI500message](https://github.com/soflyy/breakdance-bugs/assets/41072075/d2e7f652-45ef-4af8-b207-488d11e8c7f4)

**Comment by mgexiled** [comment]
I reached out to Cloudways using the Copy/Paste message module from the Breakdance Visual Page Builder when the 500 error occured. They responded with:

"I have checked from my end, and found error related to the permission on breakdown."


[Tue Jun 04 12:13:04.808133 2024] [proxy_fcgi:error] [pid 2877723:tid 139967791613696] [client 125.253.110.40:0] AH01071: Got error 'PHP message: Breakdance\\AJAX\\BreakdanceAjaxHandlerException thrown with message "Invalid permission passed as argument."\n\nStacktrace:\n#12 Breakdance\\AJAX\\BreakdanceAjaxHandlerException in /home/1184444.cloudwaysapps.com/atuftnzdmm/public_html/wp-content/plugins/breakdance/plugin/ajax/api.php:116\n#11 Exception in /home/1184444.cloudwaysapps.com/atuftnzdmm/public_html/wp-content/plugins/breakdance/plugin/permissions/permissions.php:265\n#10 Breakdance\\Permissions\\hasMinimumPermission in /home/1184444.cloudwaysapps.com/atuftnzdmm/public_html/wp-content/plugins/breakdance-ai/utils.php:86\n#9 Breakdance\\AI\\disableAiIfNotEnoughPermissions in /home/1184444.cloudwaysapps.com/atuftnzdmm/public_html/wp-includes/class-wp-hook.php:324\n#8 WP_Hook:apply_filters in /home/1184444.cloudwaysapps.com/atuftnzdmm/public_html/wp-includes/plugin.php:205\n#7 apply_filters in /home/1184444.cloudwaysapps.com/atuftnzdmm/public_html/wp-content/plugins/breakdance/plugin/data/load.php:479\n#6 Breakdance\\Data\\getAiData in /home/118...', referer: https://runintorecovery.com.au/?breakdance=builder&id=2

**Comment by louisreingold** [comment]
Does this still happen after installing beta 2 and deactivating/reactivating?

**Comment by mgexiled** [comment]
I'd love to check, but i can only see beta 1 in my portal. What's the best way to track down and install beta 2?

**Comment by el-salto** [comment]
Hi, I couldn't get it to work, and now I've realised that it doesn't work in .local. It would be important to make it work.
There is a problem that constantly asks me to update the plugin to beta 2, it does it and then asks again, I reinstall it, etc., whatever I do it is always the same.
I used an active installation and it does work. 
I duplicated a section with a header, text and two buttons and told it to rewrite with other ideas based on the theme. It rewrote the headline and buttons and made the text disappear, it left it empty.
Then, I told it to rewrite only the text from the right panel without any indication and it did it but in English !!!! my language is Spanish. At the beginning I had done it in Spanish.
Then I told it to do it in Spanish and it did it. It is something to correct, I think.
I'll keep testing and let you know what I see.

**Comment by el-salto** [comment]
I keep getting the same error message.
I got it on a test site, now I put it all the same on a production site and it fails again.
It throws this error: "Failed to get a response from OpenAI API, please try again".
I don't know why, it should work.
And it keeps asking to update all the time.
It would be nice if you could check everything to try again. Thank you.

**Comment by breakdancemoderator** [comment]
These issues should have been fixed in Breakdance 2.0 Beta 2 and Breakdance 2.0 Beta 3. If you haven't already, please update to Breakdance 2.0 Beta 3 and see if everything works correctly. 

If you're still encountering this issue, please contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com).
