### ISSUE TITLE
Woocommerce thumbnail images are still blurry mess. BD 2.0 B1

### ISSUE THREAD

**Issue by Joonas12334** [soflyy/breakdance-bugs#1089]
Nothing else to say. Images are blurry.

Would be helpful if the images were customizable in position, size, aspect with effects.

![image](https://github.com/soflyy/breakdance-bugs/assets/62062088/a764ea01-bb5c-4096-9c12-a3d0a921afc2)

Breakdance 2.0 Beta 1

**Comment by breakdancemoderator** [comment]
Hello, 

> Images are blurry.

This can be changed using a WooCommerce hook such as `woocommerce_get_image_size_gallery_thumbnail`([reference](https://developer.woocommerce.com/docs/image-sizing-for-theme-developers/#2-changing-image-sizes-via-hooks))

**Comment by Joonas12334** [comment]
Appreciate the link but it should be an option inside breakdance. Thank you!
