### ISSUE TITLE
Section margin right displayed correctly?

### ISSUE THREAD

**Issue by paulherzlich** [soflyy/breakdance-bugs#109]
On beta 4.

Add 50px margin all around a full width top level section (Height is set to Viewport, Width is not set).

In Breakdance, the right margin doesn't display even when Scale content to fit is active. Also you get a horizontal scroll bar.
On the front end, you get a horizontal scroll bar and you can see the right margin.

Changing the Width of the section to a custom value of calc(100vw - 100px) changes how the columns within the section are displayed, but not the situation with the outer margin.

I'm not sure this isn't what you'd expect, but it seems odd to me. In any case, I'm not clear where I've ever set the Section to be full width, or why setting the section width suddenly allows the columns within to change width. (But that's a separate issue.)

<img width="1735" alt="Screenshot 2022-07-25 at 15 27 43" src="https://user-images.githubusercontent.com/7724692/180791505-6b2ccaf6-d294-4817-b409-fa0c43904dce.png">

**Comment by louisreingold** [comment]
> I'm not sure this isn't what you'd expect, but it seems odd to me. 

Agreed. In beta 5, here's what I'm gonna do:
 - remove left and right margin options from the Section's design controls. To set these, go to Settings > Advanced > Wrapper. Setting it there will make it more clear that the margin is applying to the outer element of the section. You can also set width from there (using calc) to prevent the section from x-overflowing the 100% width body.
 - rename "Custom Width" to "Container Width". Maybe I should call it "Inner Width" instead. "Container Width" does seem to be customary though.
