### ISSUE TITLE
Vertical Layout top & bottom seem swapped, work opposite of expectation in 2.0 beta 1

### ISSUE THREAD

**Issue by d19dotca** [soflyy/breakdance-bugs#1091]
Breakdance version: 2.0 beta 1
Browser: Safari
OS: MacOS

In 2.0 beta 1, I found what appears to be a bug where the Vertical Layout property on a Section element seems to have top and bottom mixed up. 

To reproduce this issue:
1) Install Breakdance 2.0 Beta 1.
2) Create and edit a Header template in Breakdance.
3) Add a Section element and a Menu Builder element into the section.
4) Select the Section element, and set Vertical Layout (under Design > Layout) to Top (the far-left option). You'll find the menu sits at the bottom of the section instead. 
5) Now switch it from Top to Bottom, and you'll find the menu now sits at the top of the section, opposite of what the setting is meant to do. 

<img width="2056" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/8153796/56d53cf9-4c3b-42cd-84f7-99da175fbcec">

**Comment by louisreingold** [comment]
Section has size and spacing settings which are not visible. Please provide complete steps to reproduce.

https://www.loom.com/share/074a1cf990674949a740588797db8720
