### ISSUE TITLE
2.0.0-beta.1 | Typography Presets used in Element Presets for a Heading-Element does not assign the correct font size in front end view

### ISSUE THREAD

**Issue by AThoss** [soflyy/breakdance-bugs#1092]
The font size for a headline is not applied correctly in the frontend view if the font size is set in a typography preset, which is used in an element preset.

For example:
1. Create a custom Typography-Preset and set a custom font size for the preset.
2. Insert a Heading-Element in the builder. 
3. Assign the Typography-Preset to the heading.
4. Now create an Element-Preset the same headline.
5. The new Element-Preset still uses the Typography-Preset 
6. The Headline has the correct font size in the Breakdance-Editor.
7. Save the page and open front end view.
8. Now the Headline has standard h1 font size and not the size from the Typo-Preset anymore.

Breakdance version: 2.0.0-beta.1
WordPress version: 6.5.4

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
