### ISSUE TITLE
2.0.0-beta.1 | Design preset for columns element does not apply "Stack Vertically" value

### ISSUE THREAD

**Issue by AThoss** [soflyy/breakdance-bugs#1094]
If you assign a value to a columns element under “Layout” > “Stack Vertically”, this value is stops working when you create a design preset for it.

For example:
1. Add a Columns element
2. Set "Stack Vertically" to "Never"
3. Create a design preset from it
4. Stack Vertically” no longer works

Breakdance version: 2.0.0-beta.1

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
