### ISSUE TITLE
Breakdance Beta 2.0 animations are not running

### ISSUE THREAD

**Issue by danramzdev** [soflyy/breakdance-bugs#1095]
The animation features do not work, I was trying to make animations and none of them are triggered, neither the parallax or other animations, I have a block similar to this in version 1.7 that works fine.

![image](https://github.com/soflyy/breakdance-bugs/assets/32352812/19f000e9-ba0a-4068-89dd-f58947a1c30f)

But in beta 2.0 it doesn't work, even on the main Breakdance page that same animation doesn't run.

For example:
1. Create a page
2. Add some elements
3. At Settings > Add scrolling animation to element
4. No animation runs

 - Breakdance version: 2.0 Beta
 - Browser & OS: Microsoft Edge & Windows 11
 - No error messages neither from PHP nor from JS.

**Comment by louisreingold** [comment]
Check your OS settings, maybe you disabled animations.

https://www.loom.com/share/85d2b59f3a6e419daaedd5c94286dd0d
