### ISSUE TITLE
2.0.0-beta.2 - Dual Heading - Effect property lost on Design Preset

### ISSUE THREAD

**Issue by mtenreiro** [soflyy/breakdance-bugs#1096]
**Issue**: The effect type option assigned to Dual Heading is lost after converting it to a Design Preset.

**Steps to Reproduce:**

- Add a Dual Heading element.
- Change the effect type option on the secondary element.
- Create a Design Preset.

**Observed Behavior**: The effect type is reset to the component's default.

**Additional Issue**: If I try to edit this setting in the Design Preset edit panel, the builder freezes.

Breakdance 2.0.0-beta.2
Chromium: 126.0.6478.36
OS: Win10.

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
