### ISSUE TITLE
2.0.0-beta.2 - Page freezes when trying to edit design preset

### ISSUE THREAD

**Issue by danjs74** [soflyy/breakdance-bugs#1098]
1. Click on Icon with Design Preset applied
2. Click on Edit Preset
3. Page freezes

![design-preset-BD-bug](https://github.com/soflyy/breakdance-bugs/assets/107704016/cb9443c5-3a49-4ebe-8f2d-589a366d406a)

**Comment by mtenreiro** [comment]
Same here, but it happens on specific attributes, like reported here: https://github.com/soflyy/breakdance-bugs/issues/1096

**Comment by danjs74** [comment]
When you say "attributes" I assume you actually mean "elements" ?

**Comment by DigitalServicesLab** [comment]
I'm experiencing the same thing. 
Also when unlinking the preset, the settings are not retained except on the original element (the one on which the preset was created)

**Comment by mtenreiro** [comment]
> When you say "attributes" I assume you actually mean "elements" ?

It's the specific property of the element, like "effect type", for instance.

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
