### ISSUE TITLE
/documentation on bd website is downa

### ISSUE THREAD

**Issue by mdomedia** [soflyy/breakdance-bugs#110]
logged in user 
<img width="1409" alt="Screen Shot 2022-07-25 at 10 55 06 AM" src="https://user-images.githubusercontent.com/108284698/180807496-2443812a-ed5c-4c54-a175-d173783a35bb.png">

**Comment by neeckola** [comment]
Works for me (logged in).

**Comment by mdomedia** [comment]
This is fixed now.
