### ISSUE TITLE
2.0.0-beta.1 | Conditional toggle missing in File Upload field type in Form Builder

### ISSUE THREAD

**Issue by wtfz** [soflyy/breakdance-bugs#1100]
Steps to reproduce:
1. Add Form Builder element to page
2. Add field and change type to File Upload
3. Click Advanced edit icon
4. Conditional toggle is missing

Workaround:
1. Change field type other than File Upload
2. Toggle conditional and set requirement accordingly
3. Change back field type to File Upload

Other info:
 - **Breakdance version:** _2.0.0-beta-1_
 - **Browser & OS:** _Google Chrome / macOS Sonoma 14.0_
 - **Receive any kind of error message?:** _No error message in console_

![fileupload-conditional-missing](https://github.com/soflyy/breakdance-bugs/assets/9669062/ddf6435f-24e9-466b-a7b3-e1e084ffea85)

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
