### ISSUE TITLE
2.0 beta 2 - When trying to apply only certain border, it adds everywhere.

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#1101]
When you try to add for example TOP border, the builder is adding border to all sides, not only TOP.

For example:
1. Add top border to any element.

The full text of any error messages are helpful. Screenshots are also helpful.

You should also include the following information:
 - Breakdance version: **2.0 Beta 2**
 - Browser & OS: **Brave Browser & Windows 10**

You can see that from the image. I have added only a top border, but adding "solid" to all other border. 
![image](https://github.com/soflyy/breakdance-bugs/assets/110225636/e4ce7828-925f-43b7-9b03-5ec25dad94a5)

![image](https://github.com/soflyy/breakdance-bugs/assets/110225636/26aae782-b668-49f9-8409-90ec772e9d67)

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
