### ISSUE TITLE
YouTube Lightweight Video not working properly in the editor - BD 2.0 Beta 3

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#1108]
I just noticed that when set to lightweight mode, the video doesn't show up the red play button and the Icon and Title is not showed up.

You should also include the following information:
 - Breakdance version -  Ver. 2.0 Beta 3
 - Browser & OS - Brave - Windows 10

Here is a screenshot:

![image](https://github.com/soflyy/breakdance-bugs/assets/110225636/2c62c574-3d70-48d2-a834-ac558960065b)

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 RC 1.
