### ISSUE TITLE
Shop Filters: Price Filter

### ISSUE THREAD

**Issue by MrMartinM** [soflyy/breakdance-bugs#111]
With the default permalink settings (website url contains index.php), the Price Filter doesn't work. When I apply the filters I get the 404 page. As soon as I set the permalinks to Post Name, the filters work as expected.

**Comment by louisreingold** [comment]
I tested but was not able to reproduce.

Email support@breakdance.com and we'd be happy to take a link, although most likely this is related to your server.

https://www.loom.com/share/4057f593e5ca43a592070a227e4b0d8e
