### ISSUE TITLE
V2.0 Beta 3: JS Dependencies not loading and Actions not running in Builder Mode for Extensions ( Eg: Scroll, Entrance Animations ) 

### ISSUE THREAD

**Issue by MrBushid0** [soflyy/breakdance-bugs#1110]
In beta 3 of V2.0, a new bug was introduced where when an extension or a feature uses JS, the Dependencies are not loaded inside the builder and the Actions are not running. 

On the front end, everything works as expected.

You can see an example in the video with the BD Entrance Animations and the WebGL Fluid extension from Elements Hive.  The same behavior is true for other BD extensions like the Scrolling and Sticky features too.

https://github.com/soflyy/breakdance-bugs/assets/3267657/afb631df-7986-4b9c-b433-4f1f99e4f4ad

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 RC 1.

**Comment by MrBushid0** [comment]
It's working. Thanks!
