### ISSUE TITLE
AI Assistant settings are not saved

### ISSUE THREAD

**Issue by pixpainter** [soflyy/breakdance-bugs#1111]
1. Edit page in Breakdance
2. Open AI Assistant
3. In AI Preferences, fill all fields (qualifiers, Describe your business)
4. click save
5. refresh page
6. settings previously entered in AI Settings are not saved

The full text of any error messages are helpful. Screenshots are also helpful.

You should also include the following information:
 - Breakdance Version 2.0.0-beta.3
 - Breakdance AI Version v1.0.0-beta.2
 - Chrome Browser & MacOS
<img width="278" alt="Bildschirmfoto 2024-06-28 um 11 44 59" src="https://github.com/soflyy/breakdance-bugs/assets/173657782/01bfac41-002b-4d1f-a875-fa4535a570e0">

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 RC 1.
