### ISSUE TITLE
2.0.0-beta.3 - Duplicating a tab on Advanced Tabs doesn't duplicate its Tab Content

### ISSUE THREAD

**Issue by mtenreiro** [soflyy/breakdance-bugs#1112]
Issue: When I duplicate  a tab on Advanced tabs, it does not duplicate the "Tab Content" as expected.

Steps to Reproduce:

1 - Add an Advanced Tabs element.
2 - Duplicate the first tab.

Upon duplication, you will notice that the content of the second tab matches that of the third tab, and the last tab is left without any Tab Content. This behavior can be confusing and inconvenient for users, particularly those with "Edit Content" access, who usually have limited technical skills and lack the necessary permissions to manually duplicate Tab Content.

- Breakdance 2.0.0-beta.3 
- Wordpress 6.5.4

**Comment by breakdancemoderator** [comment]
Hello, 

This is the intended behavior at this time. Duplicating/Deleting a Tab is separate from Duplicating/Deleting Tab Content.

**Comment by mtenreiro** [comment]
> This is the intended behavior at this time. 

But anyone with "Edit Content" access can duplicate tabs, but can't duplicate the content. So. it's confusing.
