### ISSUE TITLE
can't change bg color of div on different screen sizes

### ISSUE THREAD

**Issue by bitsmyth** [soflyy/breakdance-bugs#1114]
I won't fill in those dumb questions for something so simple understandable.
You will see that only pseudo for hover is available for divs. There is no "responsive" icon.
Have to code that now.

![image](https://github.com/soflyy/breakdance-bugs/assets/30150915/7f363ea4-4a82-453b-9876-0e811efee294)

**Comment by breakdancemoderator** [comment]
Thank you for your suggestion and your interest in improving Breakdance. We appreciate your engagement and the effort to contribute.

Please note, all feature requests must be submitted through our dedicated suggestions platform on our [Canny board](https://breakdance.canny.io/). This is the only channel where we collect and review user suggestions. If your feature request is not posted there, it will not be considered.

Before submitting, please check if a similar request already exists to avoid duplication. If it does, you can support it by adding your vote and comments.

We look forward to seeing your ideas on our Canny board. Thank you for helping us continue to refine and enhance Breakdance.
