### ISSUE TITLE
Backround image to a section

### ISSUE THREAD

**Issue by MediaGozo** [soflyy/breakdance-bugs#112]
I had a section where i was using a bbackground image from the featured image, when i upgraded, it broke this [ which is fine ] however when i try and add the featured image as a background agin ... i cant seem to see how its done now.

https://m.facebook.com/groups/breakdanceofficial/permalink/5261729163862336/

**Comment by MediaGozo** [comment]
https://www.loom.com/share/ee3a67e6245247fbb15e8f1ea0f475b6

**Comment by louisreingold** [comment]
Solved in beta 5.

**Comment by MediaGozo** [comment]
Thank you Louis
