### ISSUE TITLE
Background Gradient on Button Error

### ISSUE THREAD

**Issue by onenyarko** [soflyy/breakdance-bugs#1120]
For example:
1. Create a page
2. Add a button, then customize it with a background gradient
3. Try saving it
4. 500 Error occurs.

You should also include the following information:
 - Breakdance version: V2 RC1 (local development)
 - Browser & OS: ARC Browser & MacOS Sonoma 14.5 
 - If you receive any kind of error message, you should also provide your PHP and WordPress version
         
  {
  "action": "breakdance_save",
  "id": 548,
  "tree": "{\"root\":{\"id\":1,\"data\":{\"type\":\"root\",\"properties\":[]},\"children\":[{\"id\":101,\"data\":{\"type\":\"EssentialElements\\\\Section\",\"properties\":{\"design\":{\"layout_v2\":{\"layout\":\"vertical\",\"v_align\":{\"breakpoint_base\":\"center\"},\"v_vertical_align\":{\"breakpoint_base\":\"center\"}},\"elements_hive_pro\":{\"backgrounds\":{\"background_type\":\"webgl_metaballs\",\"webgl_metaballs\":{\"shape_style\":\"1\",\"shading_mode\":\"scifi\",\"apply_to_page\":true,\"base_color\":\"#FFDBADFF\",\"light2_color\":\"#000000FF\"}}},\"size\":{\"height\":{\"breakpoint_base\":\"custom\"},\"min_height\":{\"breakpoint_base\":{\"number\":\"100dvh\",\"unit\":\"custom\",\"style\":\"100dvh\"}}},\"background\":{\"color\":\"#000000FF\"}},\"settings\":{\"advanced\":{\"wrapper\":{\"layout\":{\"advanced\":{\"overflow\":{\"breakpoint_base\":\"hidden\"}}}}}}}},\"children\":[{\"id\":120,\"data\":{\"type\":\"EssentialElements\\\\Div\",\"properties\":{\"settings\":{\"advanced\":{\"wrapper\":{\"layout\":{\"advanced\":{\"z_index\":{\"breakpoint_base\":2}}}}}},\"design\":{\"layout_v2\":{\"layout\":\"vertical\",\"v_align\":{\"breakpoint_base\":\"center\"},\"v_gap\":{\"breakpoint_base\":{\"number\":30,\"unit\":\"px\",\"style\":\"30px\"}}}}}},\"children\":[{\"id\":121,\"data\":{\"type\":\"EssentialElements\\\\Heading\",\"properties\":{\"content\":{\"content\":{\"text\":\"Desert expedition solutions for adventurous teams.\",\"tags\":\"h1\"}},\"design\":{\"typography\":{\"typography\":{\"custom\":{\"customTypography\":{\"fontSize\":{\"breakpoint_base\":{\"number\":\"clamp( 2.00rem, 0.868rem + 4.314vw, 4.75rem )\",\"unit\":\"custom\",\"style\":\"clamp( 2.00rem, 0.868rem + 4.314vw, 4.75rem )\"}},\"fontWeight\":{\"breakpoint_base\":\"300\"},\"advanced\":{\"lineHeight\":{\"breakpoint_base\":{\"number\":\"1\",\"unit\":\"custom\",\"style\":\"1\"}}}}}},\"color\":{\"breakpoint_base\":\"#FFFFFFFF\"}},\"size\":{\"width\":{\"breakpoint_base\":{\"number\":900,\"unit\":\"px\",\"style\":\"900px\"}}}},\"settings\":{\"elements_hive_pro\":{\"mouse_effects\":null}}}},\"children\":[],\"_parentId\":120},{\"id\":135,\"data\":{\"type\":\"EssentialElements\\\\Button\",\"properties\":{\"content\":{\"content\":{\"text\":\"Begin You Journey\"}},\"design\":{\"button\":{\"style\":\"custom\",\"custom\":{\"outline\":true,\"corners\":\"round\",\"background\":{\"points\":[{\"left\":0,\"red\":0,\"green\":0,\"blue\":0,\"alpha\":1},{\"left\":100,\"red\":255,\"green\":0,\"blue\":0,\"alpha\":1}],\"type\":\"linear\",\"degree\":0,\"svgValue\":\"<linearGradient x1=\\\"0.5\\\" y1=\\\"1\\\" x2=\\\"0.5\\\" y2=\\\"0\\\" id=\\\"%%GRADIENTID%%\\\"><stop stop-opacity=\\\"1\\\" stop-color=\\\"#000000\\\" offset=\\\"0\\\"></stop><stop stop-opacity=\\\"1\\\" stop-color=\\\"#ff0000\\\" offset=\\\"1\\\"></stop></linearGradient>\",\"value\":\"linear-gradient(0deg,rgba(0, 0, 0, 1) 0%,rgba(255, 0, 0, 1) 100%)\"},\"background_hover\":null}}}}},\"children\":[],\"_parentId\":120},{\"id\":125,\"data\":{\"type\":\"EssentialElements\\\\Div\",\"properties\":{\"design\":{\"container\":{\"width\":{\"breakpoint_base\":{\"number\":1000,\"unit\":\"px\",\"style\":\"1000px\"}}}},\"meta\":{\"friendlyName\":\"VideoContainer\"},\"settings\":{\"elements_hive_pro\":{\"mouse_effects\":null}}}},\"children\":[{\"id\":126,\"data\":{\"type\":\"EssentialElements\\\\Video\",\"properties\":{\"content\":{\"video\":{\"video\":{\"url\":\"http://localhost:10028/wp-content/uploads/2024/07/213837.mp4\",\"mime\":\"video/mp4\",\"embedUrl\":\"http://localhost:10028/wp-content/uploads/2024/07/213837.mp4\",\"format\":\"video\",\"type\":\"video\",\"source\":\"local\"}},\"youtube\":null,\"video_options\":{\"controls\":false,\"loop\":true}},\"design\":{\"container\":{\"width\":null,\"borders\":{\"radius\":{\"breakpoint_base\":{\"all\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"topLeft\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"topRight\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"bottomLeft\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"bottomRight\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"editMode\":\"all\"}}}}},\"settings\":{\"advanced\":{\"classes\":[\"thevideo\"],\"css\":{\"breakpoint_base\":\"%%SELECTOR%% {\\n  cursor: pointer;\\n}\"}},\"elements_hive_pro\":{\"interactions\":{\"interactions_list\":[{\"trigger_category\":\"element_triggers\",\"element_triggers\":\"click\",\"action\":\"media\",\"media_action\":\"pause\",\"target\":\"self\",\"action_delay\":{\"number\":20,\"unit\":\"ms\",\"style\":\"20ms\"}},{\"trigger_category\":\"element_triggers\",\"element_triggers\":\"click\",\"action\":\"toggle_dom_attribute\",\"dom_attribute_primitive_value\":\".divvideo-cs\",\"target\":\"selector\",\"target_selector\":\".divvideo\",\"action_delay\":{\"number\":20,\"unit\":\"ms\",\"style\":\"20ms\"},\"dom_attribute_primitive_type\":\"class\"},{\"trigger_category\":\"element_triggers\",\"element_triggers\":\"click\",\"action\":\"modify_text_content\",\"dom_attribute_primitive_value\":\"PAUSED\",\"action_delay\":{\"number\":20,\"unit\":\"ms\",\"style\":\"20ms\"},\"target\":\"selector\",\"target_selector\":\".vidtxt\"}]}}},\"meta\":{\"friendlyName\":\"Video Content\"}}},\"children\":[],\"_parentId\":125},{\"id\":127,\"data\":{\"type\":\"EssentialElements\\\\Heading\",\"properties\":{\"content\":{\"content\":{\"text\":\"Elementhive Demo\"}},\"design\":{\"typography\":{\"typography\":{\"custom\":{\"customTypography\":{\"fontSize\":{\"breakpoint_base\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"}},\"fontWeight\":{\"breakpoint_base\":\"400\"}}}}}},\"settings\":{\"advanced\":{\"wrapper\":{\"layout\":{\"advanced\":{\"position\":{\"position\":{\"breakpoint_base\":\"absolute\"},\"top\":{\"breakpoint_base\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}},\"left\":{\"breakpoint_base\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}}}}}}},\"meta\":{\"friendlyName\":\"Title\"}}},\"children\":[],\"_parentId\":125},{\"id\":128,\"data\":{\"type\":\"EssentialElements\\\\Div\",\"properties\":{\"design\":{\"container\":{\"padding\":{\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"right\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"top\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"bottom\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"}}}},\"borders\":{\"radius\":{\"breakpoint_base\":{\"all\":{\"number\":35,\"unit\":\"px\",\"style\":\"35px\"},\"topLeft\":{\"number\":35,\"unit\":\"px\",\"style\":\"35px\"},\"topRight\":{\"number\":35,\"unit\":\"px\",\"style\":\"35px\"},\"bottomLeft\":{\"number\":35,\"unit\":\"px\",\"style\":\"35px\"},\"bottomRight\":{\"number\":35,\"unit\":\"px\",\"style\":\"35px\"},\"editMode\":\"all\"}}}},\"background\":{\"color\":\"#FBFBFB1C\"},\"layout_v2\":{\"layout\":\"horizontal\",\"h_vertical_align\":{\"breakpoint_base\":\"center\"},\"h_gap\":{\"breakpoint_base\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"}}}},\"settings\":{\"advanced\":{\"css\":{\"breakpoint_base\":\"%%SELECTOR%% {\\n  pointer-events: none;\\ncursor: pointer;\\n}\"},\"wrapper\":{\"layout\":{\"advanced\":{\"position\":{\"position\":{\"breakpoint_base\":\"absolute\"},\"bottom\":{\"breakpoint_base\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}},\"left\":{\"breakpoint_base\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}}}}}}},\"meta\":{\"friendlyName\":\"Play Text\"}}},\"children\":[{\"id\":129,\"data\":{\"type\":\"EssentialElements\\\\Heading\",\"properties\":{\"content\":{\"content\":{\"text\":\"PAUSED\"}},\"design\":{\"typography\":{\"typography\":{\"custom\":{\"customTypography\":{\"fontSize\":{\"breakpoint_base\":{\"number\":0.75,\"unit\":\"rem\",\"style\":\"0.75rem\"}},\"fontWeight\":{\"breakpoint_base\":\"300\"}}}},\"color\":{\"breakpoint_base\":\"#FBFBFB6B\"}}},\"settings\":{\"advanced\":{\"classes\":[\"vidtxt\"]}}}},\"children\":[],\"_parentId\":128},{\"id\":130,\"data\":{\"type\":\"EssentialElements\\\\Heading\",\"properties\":{\"content\":{\"content\":{\"text\":\"|\"}},\"design\":{\"typography\":{\"typography\":{\"custom\":{\"customTypography\":{\"fontSize\":{\"breakpoint_base\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"}},\"fontWeight\":{\"breakpoint_base\":\"400\"}}}},\"color\":{\"breakpoint_base\":\"#FBFBFB6B\"}}}}},\"children\":[],\"_parentId\":128},{\"id\":131,\"data\":{\"type\":\"EssentialElements\\\\Icon\",\"properties\":{\"content\":{\"content\":{\"icon\":{\"slug\":\"icon-play3\",\"name\":\"icon-play3\",\"svgCode\":\"<svg xmlns=\\\"http://www.w3.org/2000/svg\\\" id=\\\"icon-play3\\\" viewBox=\\\"0 0 32 32\\\">\\n<path d=\\\"M6 4l20 12-20 12z\\\"/>\\n</svg>\",\"iconSetSlug\":\"IcoMoon Free\"}}},\"design\":{\"icon\":{\"size\":{\"breakpoint_base\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"}},\"color\":\"#FBFBFB6B\"}},\"meta\":{\"friendlyName\":\"Play\"},\"settings\":{\"advanced\":{\"classes\":[\"ts-play\"],\"wrapper\":{\"layout\":{\"advanced\":{\"position\":{\"position\":null}}}}}}}},\"children\":[],\"_parentId\":128}],\"_parentId\":125},{\"id\":132,\"data\":{\"type\":\"EssentialElements\\\\Div\",\"properties\":{\"design\":{\"container\":{\"width\":null,\"borders\":{\"radius\":null},\"min_height\":null},\"background\":{\"color\":null,\"color_hover\":null},\"layout_v2\":{\"layout\":null,\"v_align\":null,\"v_vertical_align\":null}},\"settings\":{\"advanced\":{\"wrapper\":{\"layout\":{\"advanced\":{\"position\":{\"position\":null}}}},\"classes\":[\"divvideo\"],\"css\":{\"breakpoint_base\":\"%%SELECTOR%% {\\n  cursor: pointer;\\n}\"}},\"elements_hive_pro\":{\"interactions\":{\"interactions_list\":[{\"trigger_category\":\"element_triggers\",\"element_triggers\":\"click\",\"action\":\"media\",\"media_action\":\"play\",\"action_delay\":{\"number\":20,\"unit\":\"ms\",\"style\":\"20ms\"},\"target\":\"selector\",\"target_selector\":\".thevideo\"},{\"trigger_category\":\"element_triggers\",\"element_triggers\":\"click\",\"action\":\"toggle_dom_attribute\",\"media_action\":\"pause\",\"action_delay\":{\"number\":20,\"unit\":\"ms\",\"style\":\"20ms\"},\"target\":\"selector\",\"target_selector\":\".divvideo\",\"dom_attribute_primitive_type\":\"class\",\"dom_attribute_primitive_value\":\".divvideo-cs\"},{\"trigger_category\":\"element_triggers\",\"element_triggers\":\"click\",\"action\":\"modify_text_content\",\"dom_attribute_primitive_value\":\"PLAYING\",\"action_delay\":{\"number\":20,\"unit\":\"ms\",\"style\":\"20ms\"},\"target\":\"selector\",\"target_selector\":\".vidtxt\"}]}}},\"meta\":{\"friendlyName\":\"Play Overlay\"}}},\"children\":[{\"id\":133,\"data\":{\"type\":\"EssentialElements\\\\Icon\",\"properties\":{\"content\":{\"content\":{\"icon\":{\"slug\":\"icon-play.\",\"name\":\"icon-play.\",\"svgCode\":\"<svg xmlns=\\\"http://www.w3.org/2000/svg\\\" viewBox=\\\"0 0 384 512\\\"><path d=\\\"M73 39c-14.8-9.1-33.4-9.4-48.5-.9S0 62.6 0 80V432c0 17.4 9.4 33.4 24.5 41.9s33.7 8.1 48.5-.9L361 297c14.3-8.7 23-24.2 23-41s-8.7-32.2-23-41L73 39z\\\"/></svg>\",\"iconSetSlug\":\"FontAwesome 6 Free - Solid\"}}},\"design\":{\"icon\":{\"size\":{\"breakpoint_base\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"}},\"style\":\"solid\",\"padding\":{\"breakpoint_base\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}},\"background\":\"#2B2B2B63\",\"corners\":\"round\",\"color\":\"#FFFFFFFF\"}},\"settings\":{\"advanced\":{\"wrapper\":{\"layout\":{\"advanced\":{\"position\":{\"position\":{\"breakpoint_base\":\"absolute\"}}}}}}}}},\"children\":[],\"_parentId\":132}],\"_parentId\":125}],\"_parentId\":120}],\"_parentId\":101}],\"_parentId\":1}]},\"_nextNodeId\":136,\"status\":\"exported\"}",
  "globalSettings": "{\"settings\":{\"colors\":{\"background\":\"#2B2B2BFF\",\"palette\":{\"colors\":[{\"cssVariableName\":\"bde-palette-dark-f536cefc-4613-48a0-a9f7-f5d60f9ab069-1\",\"label\":\"Dark\",\"value\":\"#2B2B2BFF\"},{\"cssVariableName\":\"bde-palette-white-f30f151b-dbbf-47d3-853d-0e877be08e5c-2\",\"label\":\"White\",\"value\":\"#FBFBFBFF\"}],\"gradients\":[{\"cssVariableName\":\"bde-palette-white-gold-47c8d565-5834-4f8a-9d3b-12a7655401fa-gradient-3\",\"label\":\"White Gold\",\"value\":{\"points\":[{\"left\":12.820512820512821,\"red\":247,\"green\":235,\"blue\":217,\"alpha\":1},{\"left\":86.15384615384616,\"red\":244,\"green\":220,\"blue\":181,\"alpha\":1},{\"left\":49.743589743589745,\"red\":255,\"green\":255,\"blue\":255,\"alpha\":1}],\"type\":\"linear\",\"degree\":90,\"svgValue\":\"<linearGradient x1=\\\"0\\\" y1=\\\"0.5\\\" x2=\\\"1\\\" y2=\\\"0.5\\\" id=\\\"%%GRADIENTID%%\\\"><stop stop-opacity=\\\"1\\\" stop-color=\\\"#f7ebd9\\\" offset=\\\"0.12820512820512822\\\"></stop><stop stop-opacity=\\\"1\\\" stop-color=\\\"#ffffff\\\" offset=\\\"0.49743589743589745\\\"></stop><stop stop-opacity=\\\"1\\\" stop-color=\\\"#f4dcb5\\\" offset=\\\"0.8615384615384616\\\"></stop></linearGradient>\",\"value\":\"linear-gradient(90deg,rgba(247, 235, 217, 1) 12.820512820512821%,rgba(255, 255, 255, 1) 49.743589743589745%,rgba(244, 220, 181, 1) 86.15384615384616%)\"}},{\"cssVariableName\":\"bde-palette-blue-grad-3955db80-007a-46bd-8223-c1f802733643-gradient-3\",\"label\":\"Blue Grad\",\"value\":{\"points\":[{\"left\":0,\"red\":112,\"green\":190,\"blue\":250,\"alpha\":1},{\"left\":100,\"red\":255,\"green\":255,\"blue\":255,\"alpha\":1}],\"type\":\"linear\",\"degree\":90,\"svgValue\":\"<linearGradient x1=\\\"0\\\" y1=\\\"0.5\\\" x2=\\\"1\\\" y2=\\\"0.5\\\" id=\\\"%%GRADIENTID%%\\\"><stop stop-opacity=\\\"1\\\" stop-color=\\\"#70befa\\\" offset=\\\"0\\\"></stop><stop stop-opacity=\\\"1\\\" stop-color=\\\"#ffffff\\\" offset=\\\"1\\\"></stop></linearGradient>\",\"value\":\"linear-gradient(90deg,rgba(112, 190, 250, 1) 0%,rgba(255, 255, 255, 1) 100%)\"}}]},\"text\":\"#FBFBFBFF\",\"headings\":\"#FBFBFBFF\"},\"buttons\":null,\"typography\":null,\"code\":{\"stylesheets\":[],\"scripts\":[]},\"containers\":{\"sections\":{\"container_width\":{\"number\":1440,\"unit\":\"px\",\"style\":\"1440px\"}}},\"elements_hive_pro\":null}}",
  "classes": "[{\"name\":\".themenuicon\",\"type\":\"class\",\"properties\":{\"custom_css\":{\"css\":{\"breakpoint_base\":null}}}},{\"name\":\".old-color\",\"type\":\"class\",\"properties\":{}},{\"name\":\".dropdown\",\"type\":\"class\",\"properties\":{\"layout\":{\"advanced\":{\"position\":{\"position\":{\"breakpoint_base\":\"relative\"}}},\"display\":{\"breakpoint_base\":\"inline-block\"}},\"borders\":{\"radius\":{\"breakpoint_base\":{\"all\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"topLeft\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"topRight\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"bottomLeft\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"bottomRight\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"editMode\":\"all\"}}}}},{\"name\":\".dropbtn\",\"type\":\"class\",\"properties\":{}},{\"name\":\".dropdown-content\",\"type\":\"class\",\"properties\":{\"layout\":{\"advanced\":{\"z_index\":null,\"position\":{\"position\":{\"breakpoint_base\":\"absolute\"}}},\"display\":{\"breakpoint_base\":\"flex\"},\"gap\":{\"breakpoint_base\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"}}},\"effects\":{\"transition\":{\"breakpoint_base\":[{\"duration\":{\"number\":300,\"unit\":\"ms\",\"style\":\"300ms\"},\"property\":\"all\",\"timing_function\":\"linear\"}]},\"transform\":{\"transforms\":{\"breakpoint_base\":[{\"type\":\"translate\",\"translate_y\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"}}]}},\"filter\":{\"breakpoint_base\":[]},\"opacity\":{\"breakpoint_base\":0}},\"background\":{\"color\":{\"breakpoint_base\":\"#000000FF\"}},\"spacing\":{\"margin\":{\"breakpoint_base\":{\"top\":{\"number\":5,\"unit\":\"px\",\"style\":\"5px\"}}},\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"},\"right\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"},\"top\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"},\"bottom\":{\"number\":16,\"unit\":\"px\",\"style\":\"16px\"}}}},\"size\":{\"width\":{\"breakpoint_base\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"}}},\"borders\":{\"radius\":{\"breakpoint_base\":{\"all\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"topLeft\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"topRight\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"bottomLeft\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"bottomRight\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"editMode\":\"all\"}}}}},{\"name\":\".dropdown-content-open\",\"type\":\"class\",\"properties\":{\"layout\":null,\"effects\":{\"opacity\":{\"breakpoint_base\":1},\"transition\":{\"breakpoint_base\":[{\"duration\":{\"number\":300,\"unit\":\"ms\",\"style\":\"300ms\"}}]},\"transform\":{\"transforms\":{\"breakpoint_base\":[{\"type\":\"translate\",\"translate_y\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"}}]}}}}},{\"name\":\".drop-icon\",\"type\":\"class\",\"properties\":{\"effects\":{\"transition\":{\"breakpoint_base\":[{\"duration\":{\"number\":300,\"unit\":\"ms\",\"style\":\"300ms\"},\"property\":\"all\",\"timing_function\":\"linear\"}]}}}},{\"name\":\".drop-icon-open\",\"type\":\"class\",\"properties\":{\"effects\":{\"transition\":{\"breakpoint_base\":[{\"duration\":{\"number\":300,\"unit\":\"ms\",\"style\":\"300ms\"},\"property\":\"all\"}]},\"transform\":{\"transforms\":{\"breakpoint_base\":[{\"type\":\"rotate\",\"translate_y\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"rotate_z\":{\"number\":180,\"unit\":\"deg\",\"style\":\"180deg\"}}]}}}}},{\"name\":\".ts-accordion\",\"type\":\"class\",\"properties\":{\"size\":{\"width\":{\"breakpoint_base\":{\"number\":700,\"unit\":\"px\",\"style\":\"700px\"}}}}},{\"name\":\".ts-accordion-item\",\"type\":\"class\",\"properties\":{\"size\":{\"width\":{\"breakpoint_base\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"}}},\"layout\":null}},{\"name\":\".ts-accordion-header\",\"type\":\"class\",\"properties\":{}},{\"name\":\".ts-accordion-content\",\"type\":\"class\",\"properties\":{\"spacing\":{\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"right\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"top\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"bottom\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"}}}},\"background\":{\"color\":{\"breakpoint_base\":\"#8258DEFF\"}},\"size\":{\"width\":{\"breakpoint_base\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"}},\"max_height\":null,\"height\":null,\"min_height\":null},\"layout\":{\"display\":null}}},{\"name\":\".op-accordion-content\",\"type\":\"class\",\"properties\":{\"layout\":{\"display\":{\"breakpoint_base\":\"block\"}}}},{\"name\":\".thevideo\",\"type\":\"class\",\"properties\":{}},{\"name\":\".divvideo\",\"type\":\"class\",\"properties\":{\"layout\":{\"display\":{\"breakpoint_base\":\"flex\"},\"flex_direction\":{\"breakpoint_base\":\"column\"},\"justify_content\":{\"breakpoint_base\":\"center\"},\"align_items\":{\"breakpoint_base\":\"center\"},\"align_content\":{\"breakpoint_base\":\"center\"},\"advanced\":{\"position\":{\"position\":{\"breakpoint_base\":\"absolute\"}}}},\"size\":{\"width\":{\"breakpoint_base\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"}},\"height\":{\"breakpoint_base\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"}}},\"borders\":{\"radius\":{\"breakpoint_base\":{\"all\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"topLeft\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"topRight\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"bottomLeft\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"bottomRight\":{\"number\":15,\"unit\":\"px\",\"style\":\"15px\"},\"editMode\":\"all\"}}},\"background\":{\"color\":{\"breakpoint_base\":\"#2B2B2B00\"}}}},{\"name\":\".divvideo-cs\",\"type\":\"class\",\"properties\":{\"layout\":{\"display\":{\"breakpoint_base\":\"none\"}},\"background\":null}},{\"name\":\".vidtxt\",\"type\":\"class\",\"properties\":{}}]",
  "presets": "[{\"id\":\"258c5eac-217a-4f50-9d12-2dd29d3edc0a\",\"name\":\"test\",\"availableForType\":\"EssentialElements\\\\Section\",\"design\":{\"layout_v2\":{\"layout\":\"vertical\"},\"background\":{\"color\":\"#632FD4FF\"},\"spacing\":{\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":50,\"unit\":\"px\",\"style\":\"50px\"},\"right\":{\"number\":50,\"unit\":\"px\",\"style\":\"50px\"},\"top\":{\"number\":50,\"unit\":\"px\",\"style\":\"50px\"},\"bottom\":{\"number\":50,\"unit\":\"px\",\"style\":\"50px\"}}}}}}]",
  "ai": "{\"businessName\":\"\",\"businessDescription\":\"\",\"qualifiers\":\"\",\"presets\":[]}"
}

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing support@breakdance.com. Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.
