### ISSUE TITLE
v2.0-rc1 - Post Loop - Slider - Custom Icons are not visible on builder

### ISSUE THREAD

**Issue by mtenreiro** [soflyy/breakdance-bugs#1122]
**Issue:**
When using the Slider layout in a Post Loop Builder, custom icons for the arrows are not displayed in the builder interface, though they appear correctly on the front-end.

**Steps to Reproduce:**

- Add a Post Loop Builder element.
- Set any query.
- Change the Layout to Slider.
- Go to Slider Settings > Arrows > Custom icons.
- Change the arrow icons to any custom icons.

**Observed Behavior:**
The custom icons are displayed on the front-end but are hidden in the builder interface. After saving and reloading, the icons become visible in the builder.

Breakdance v2.0-rc1

**Comment by breakdancemoderator** [comment]
After setting your custom icons, you can click the Refresh Element button on the Post Loop Builder element to see them in Breakdance:

![Screenshot 2024-07-17 at 11 27 56](https://github.com/user-attachments/assets/b888a240-1c04-4650-956d-6e84124e0a36)
