### ISSUE TITLE
No mobile version for Layout?

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#1126]
Hello!

I'm in BD 2.0 RC 1.

It seems that have a really annoying bug. If I have a div with layout display flex horizontal, I cant change to vertical, or make it a grid, or block on another breakpoint. I can only change align, vertical align ou gap...

<img width="280" alt="Screenshot 2024-07-15 at 21 09 22" src="https://github.com/user-attachments/assets/5765a89b-6ab7-4a40-8844-6818783e5962">

**Comment by DigitalServicesLab** [comment]
@quentalstudio this is intentional behaviour (BD support said so). You can use the advanced option (the two cogs) and change layout by breakpoint in there using the flex-direction setting.

![image](https://github.com/user-attachments/assets/0c60a279-8535-42d4-949b-808f5b15179c)
