### ISSUE TITLE
Post Loop Builder Load More Issue

### ISSUE THREAD

**Issue by kbcelik** [soflyy/breakdance-bugs#1137]
We are experiencing an issue with the Query Builder in Breakdance when using the Advanced Custom Fields (ACF) Relationship field. Here are the details:

Scenario:

- We have set up a relationship field using ACF to relate some accessories to a product.
- The Query Builder settings include selecting the ACF relationship for related accessories, setting posts per page to 2, and the total posts to 999.
- We have also enabled the "Load More" button for pagination.

Issue:

- In production, when we click the "Load More" button, nothing happens. The expected behavior is for additional related accessories to load, but the button appears to be unresponsive.
- Additionally, when testing with a standard query (post type: page, posts per page: 2, and enabling "Load More"), we encounter another problem. Initially, it loads the first two results correctly, but upon clicking "Load More," it repeatedly displays the same two results instead of loading the next set of results.
- This behavior is inconsistent; sometimes, it continues to load the correct upcoming results after a few clicks, but other times, it fails entirely.

We have tried adjusting various parameters but have not been able to resolve the issue. Could you please assist us in identifying the cause and provide a solution?

https://www.loom.com/share/591d6ca0cc0e477b9bc402654353b345?sid=c975daff-13c0-4e6f-8e96-4450fd7db7d0

**Comment by breakdancemoderator** [comment]
Hello, 

The ACF Relationship field in Breakdance's Custom Query does not support pagination. Using an Array Query may work for your needs.
