### ISSUE TITLE
Again issue with time in form builder mail

### ISSUE THREAD

**Issue by jvalks** [soflyy/breakdance-bugs#1138]
My server is in Europe, on the Amsterdam timezone. Also configured in WordPress. When a user fills in a form, select say 15:00 as the time, the time in the mail is noted as: 17:00! The stored form submission is correct, at 15:00.
So there is a 2 hour difference in the entered time, and the time mentioned in the email...

**Comment by jvalks** [comment]
Setting UTC+0 solves it for now...

**Comment by breakdancemoderator** [comment]
@jvalks, does this occur with Breakdance v2?

**Comment by jvalks** [comment]
Yes, version v2

**Comment by breakdancemoderator** [comment]
This is fixed in Breakdance 2.2, which is available for beta testing. You may learn how to test Breakdance Beta versions here: https://breakdance.com/documentation/advanced/enable-beta-updates/.
