### ISSUE TITLE
Postlist pagination 404 error

### ISSUE THREAD

**Issue by Nikzutiini** [soflyy/breakdance-bugs#114]
Postlist pagination is giving 404 error when moving from page 1 to next page.

**Comment by louisreingold** [comment]
Thanks for the report.

Please submit a ticket to support@breakdance.com with your admin login details and we'll take a look.

Unfortunately, I wasn't able to reproduce this. I tried using the Posts List element on a page, and on an archive, and I tried disabling pretty permalinks and enabling pretty permalinks. Nothing produced a 404.
