### ISSUE TITLE
What is the process of migrating a development site into production?

### ISSUE THREAD

**Issue by tapashdatta** [soflyy/breakdance-bugs#1142]
I have been building a site in dev environment running a different domain than live. I want to make it live now. Both Site are on same server WP 6.6.1, PHP 8.3, MariaDB 10.11. Here's the steps I have followed:

Deleted all old site files from live except for config files.
I have created a DB backup of dev site
Deleted the live DB and restored the backup of dev site
moved all file system from dev site in the live environment except for wp-config.php .
Recreated all CSS via breakdance Settings >> Tools
Recreated all directories via breakdance Settings >> Tools
Replaced old URL with new URL via breakdance Settings >> Tools
Although site loads fine, The styling seems to be broken and global styling is not loading. I had to make some changes by going to global settings and change some value and update it and then when the styling fixed for some things but some styling are still broken.

Some global block styling is not loading correctly. When tried to re-save, keep getting 500 ERROR often when flyingpress plugin is used.

Is there a guide of the migration process? Is it a known bug of this plugin?

Thanks

<img width="921" alt="Screenshot 2024-08-18 at 08 04 42" src="https://github.com/user-attachments/assets/04df13e7-a02b-49ba-91e9-70fe1792dad9">

**Comment by tapashdatta** [comment]
Response Code: 500
Request Time: Sun, 18 Aug 2024 02:34:04 GMT
Request Type: POST
Request URL: https://example.com/wp-admin/admin-ajax.php?_breakdance_doing_ajax=yes&_ajax_nonce=c1175664e9
Body:
{
  "action": "breakdance_save",
  "id": 29,
  "tree": "{\"root\":{\"id\":1,\"data\":{\"type\":\"root\",\"properties\":[]},\"children\":[{\"id\":107,\"data\":{\"type\":\"EssentialElements\\\\Section\",\"properties\":{\"design\":{\"layout_v2\":{\"layout\":\"vertical\",\"v_align\":{\"breakpoint_base\":\"center\"}},\"spacing\":{\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"},\"right\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"},\"top\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"},\"bottom\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}}}}}},\"children\":[{\"id\":100,\"data\":{\"type\":\"EssentialElements\\\\Image\",\"properties\":{\"content\":{\"content\":{\"image\":\"[breakdance_dynamic field='post_featured_image']\",\"image_dynamic_meta\":{\"field\":{\"category\":\"Post\",\"subcategory\":\"\",\"label\":\"Featured Image\",\"slug\":\"post_featured_image\",\"returnTypes\":[\"image_url\"],\"defaultAttributes\":[],\"controls\":[{\"slug\":\"advanced\",\"label\":\"Advanced\",\"children\":[{\"slug\":\"fallback_image\",\"label\":\"Fallback Image\",\"children\":[],\"options\":{\"type\":\"wpmedia\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]}],\"options\":{\"type\":\"section\",\"sectionOptions\":{\"type\":\"popout\"}},\"enableMediaQueries\":false,\"enableHover\":false}],\"proOnly\":true},\"shortcode\":\"[breakdance_dynamic field='post_featured_image']\",\"attributes\":[]},\"lazy_load\":true}},\"design\":{\"borders\":{\"radius\":{\"breakpoint_base\":{\"all\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"},\"topLeft\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"},\"topRight\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"},\"bottomLeft\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"},\"bottomRight\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"},\"editMode\":\"all\"}},\"border\":{\"breakpoint_base\":{\"top\":{\"width\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"color\":\"var(--bde-palette-color-1-f85f991b-0600-4774-b7fb-361712c76386)\",\"style\":\"\"},\"bottom\":{\"width\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"color\":\"var(--bde-palette-color-1-f85f991b-0600-4774-b7fb-361712c76386)\",\"style\":\"\"},\"left\":{\"width\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"color\":\"var(--bde-palette-color-1-f85f991b-0600-4774-b7fb-361712c76386)\",\"style\":\"\"},\"right\":{\"width\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"color\":\"var(--bde-palette-color-1-f85f991b-0600-4774-b7fb-361712c76386)\",\"style\":\"\"}}},\"shadow\":{\"breakpoint_base\":{\"shadows\":[{\"color\":\"#0000002B\",\"x\":\"0\",\"y\":\"0\",\"blur\":\"15\",\"spread\":\"0\",\"position\":\"outset\"}],\"style\":\"0px 0px 15px 0px #0000002B\"}}},\"image\":{\"width\":{\"breakpoint_base\":{\"number\":250,\"unit\":\"px\",\"style\":\"250px\"}}}}}},\"children\":[],\"_parentId\":107},{\"id\":101,\"data\":{\"type\":\"EssentialElements\\\\Div\",\"properties\":{\"design\":{\"background\":{\"color\":null,\"color_hover\":null},\"layout_v2\":{\"layout\":\"vertical\",\"v_align\":{\"breakpoint_base\":\"center\"},\"v_gap\":{\"breakpoint_base\":null}},\"container\":{\"borders\":{\"radius\":{\"breakpoint_base\":{\"all\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"topLeft\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"topRight\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"bottomLeft\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"bottomRight\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"editMode\":\"all\"}}},\"padding\":{\"padding\":null}},\"spacing\":{\"margin_top\":{\"breakpoint_base\":{\"number\":30,\"unit\":\"px\",\"style\":\"30px\"}}}}}},\"children\":[{\"id\":102,\"data\":{\"type\":\"EssentialElements\\\\Heading\",\"properties\":{\"content\":{\"content\":{\"text\":\"[breakdance_dynamic field='post_title']\",\"text_dynamic_meta\":{\"field\":{\"category\":\"Post\",\"subcategory\":\"\",\"label\":\"Post Title\",\"slug\":\"post_title\",\"returnTypes\":[\"string\"],\"defaultAttributes\":[],\"controls\":[{\"slug\":\"advanced\",\"label\":\"Advanced\",\"children\":[{\"slug\":\"beforeContent\",\"label\":\"Prepend\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"afterContent\",\"label\":\"Append\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"truncate\",\"label\":\"Limit Characters\",\"children\":[],\"options\":{\"type\":\"number\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"fallback\",\"label\":\"Fallback\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\",\"textOptions\":{\"multiline\":false}},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]}],\"options\":{\"type\":\"section\",\"sectionOptions\":{\"type\":\"popout\"}},\"enableMediaQueries\":false,\"enableHover\":false}],\"proOnly\":false},\"shortcode\":\"[breakdance_dynamic field='post_title']\",\"attributes\":[]},\"tags\":\"h5\"}},\"design\":{\"typography\":{\"text_align\":null,\"color\":{\"breakpoint_base\":\"var(--bde-brand-primary-color)\"}}},\"settings\":{\"advanced\":{\"wrapper\":{\"background\":{\"color\":{\"breakpoint_base\":\"var(--bde-palette-color-1-f85f991b-0600-4774-b7fb-361712c76386)\"}},\"size\":{\"width\":{\"breakpoint_base\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"}}},\"borders\":{\"radius\":{\"breakpoint_base\":{\"topLeft\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"editMode\":\"custom\",\"topRight\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}}},\"spacing\":{\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"right\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"top\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"bottom\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"}}}}}}}}},\"children\":[],\"_parentId\":101},{\"id\":104,\"data\":{\"type\":\"EssentialElements\\\\Text\",\"properties\":{\"content\":{\"content\":{\"text\":\"[breakdance_dynamic field='post_excerpt']\",\"text_dynamic_meta\":{\"field\":{\"category\":\"Post\",\"subcategory\":\"\",\"label\":\"Post Excerpt\",\"slug\":\"post_excerpt\",\"returnTypes\":[\"string\"],\"defaultAttributes\":[],\"controls\":[{\"slug\":\"advanced\",\"label\":\"Advanced\",\"children\":[{\"slug\":\"beforeContent\",\"label\":\"Prepend\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"afterContent\",\"label\":\"Append\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"truncate\",\"label\":\"Limit Characters\",\"children\":[],\"options\":{\"type\":\"number\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"fallback\",\"label\":\"Fallback\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\",\"textOptions\":{\"multiline\":false}},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]}],\"options\":{\"type\":\"section\",\"sectionOptions\":{\"type\":\"popout\"}},\"enableMediaQueries\":false,\"enableHover\":false}],\"proOnly\":false},\"shortcode\":\"[breakdance_dynamic field='post_excerpt']\",\"attributes\":[]}}},\"design\":{\"typography\":{\"text_align\":null}},\"settings\":{\"advanced\":{\"wrapper\":{\"background\":{\"color\":{\"breakpoint_base\":\"var(--bde-palette-color-1-f85f991b-0600-4774-b7fb-361712c76386)\"}},\"size\":{\"width\":{\"breakpoint_base\":{\"number\":100,\"unit\":\"%\",\"style\":\"100%\"}}},\"spacing\":{\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"right\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"top\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"},\"bottom\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"}}}}}}}}},\"children\":[],\"_parentId\":101},{\"id\":105,\"data\":{\"type\":\"EssentialElements\\\\Text\",\"properties\":{\"content\":{\"content\":{\"text\":\"[breakdance_dynamic field='post_content']\",\"text_dynamic_meta\":{\"field\":{\"category\":\"Post\",\"subcategory\":\"\",\"label\":\"Post Content\",\"slug\":\"post_content\",\"returnTypes\":[\"string\"],\"defaultAttributes\":[],\"controls\":[{\"slug\":\"advanced\",\"label\":\"Advanced\",\"children\":[{\"slug\":\"beforeContent\",\"label\":\"Prepend\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"afterContent\",\"label\":\"Append\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"truncate\",\"label\":\"Limit Characters\",\"children\":[],\"options\":{\"type\":\"number\",\"layout\":\"vertical\"},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]},{\"slug\":\"fallback\",\"label\":\"Fallback\",\"children\":[],\"options\":{\"type\":\"text\",\"layout\":\"vertical\",\"textOptions\":{\"multiline\":false}},\"enableMediaQueries\":false,\"enableHover\":false,\"keywords\":[]}],\"options\":{\"type\":\"section\",\"sectionOptions\":{\"type\":\"popout\"}},\"enableMediaQueries\":false,\"enableHover\":false}],\"proOnly\":false},\"shortcode\":\"[breakdance_dynamic field='post_content']\",\"attributes\":[]}}},\"design\":{\"typography\":{\"text_align\":{\"breakpoint_base\":\"justify\"},\"typography\":{\"custom\":{\"customTypography\":{\"fontWeight\":{\"breakpoint_base\":\"300\"},\"fontSize\":{\"breakpoint_base\":{\"number\":14,\"unit\":\"px\",\"style\":\"14px\"}}}}}},\"size\":{\"width\":null}},\"settings\":{\"advanced\":{\"wrapper\":{\"background\":{\"color\":{\"breakpoint_base\":\"var(--bde-background-color)\"}},\"spacing\":{\"padding\":{\"breakpoint_base\":{\"left\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"right\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"top\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"bottom\":{\"number\":0,\"unit\":\"px\",\"style\":\"0px\"}}}},\"borders\":{\"radius\":{\"breakpoint_base\":{\"bottomLeft\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"editMode\":\"custom\",\"bottomRight\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}}}}}}}},\"children\":[],\"_parentId\":101}],\"_parentId\":107}],\"_parentId\":1}]},\"_nextNodeId\":109,\"status\":\"exported\"}",
  "globalSettings": "{\"settings\":{\"colors\":{\"brand\":\"#b28e65\",\"text\":\"#6B6B6d\",\"headings\":\"#3C3628\",\"links\":\"#EBA55E\",\"background\":\"#FFFFFF\",\"palette\":{\"colors\":[{\"cssVariableName\":\"bde-palette-color-1-f85f991b-0600-4774-b7fb-361712c76386\",\"label\":\"BG3\",\"value\":\"#f8f1e3\"},{\"cssVariableName\":\"bde-palette-color-1-cce862f4-68f6-49cc-9b31-3dd2eefab420\",\"label\":\"BG1\",\"value\":\"#D8D8D8\"},{\"cssVariableName\":\"bde-palette-color-1-8c700260-adcd-42e4-a794-89ca18c9eb5a\",\"label\":\"Darkest Purple\",\"value\":\"#35253A\"},{\"cssVariableName\":\"bde-palette-color-2-e9396381-92c4-4c68-85d5-711796184131\",\"label\":\"BG2\",\"value\":\"#DDC2AB\"},{\"cssVariableName\":\"bde-palette-color-3-6baec9e8-b487-41ee-bbaa-b10911c68e36\",\"label\":\"Black\",\"value\":\"#000\"},{\"cssVariableName\":\"bde-palette-color-5-e1b4a237-7fcf-4898-bc73-91880d5cd8dd\",\"label\":\"Purple\",\"value\":\"#705479\"},{\"cssVariableName\":\"bde-palette-color-6-848c963a-cb0e-4e4d-8b70-fca42f05de1e\",\"label\":\"Dark Purple\",\"value\":\"#543d5c\"},{\"cssVariableName\":\"bde-palette-color-1-5b0e45cb-359c-45b6-a810-f001f5b3a06f\",\"label\":\"Color #1\",\"value\":\"#00000080\"}]}},\"buttons\":{\"primary\":{\"size\":{\"size\":{\"breakpoint_base\":\"custom\"},\"padding\":{\"breakpoint_base\":{\"top\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"left\":{\"number\":24,\"unit\":\"px\",\"style\":\"24px\"},\"right\":{\"number\":24,\"unit\":\"px\",\"style\":\"24px\"},\"bottom\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}}},\"background\":\"var(--bde-brand-primary-color)\",\"typography\":{\"color\":{\"breakpoint_base\":\"var(--bde-background-color)\"},\"typography\":{\"custom\":{\"customTypography\":{\"fontFamily\":{\"breakpoint_base\":\"custom_font_nunito-local\"},\"fontSize\":{\"breakpoint_base\":{\"number\":0.75,\"unit\":\"rem\",\"style\":\"0.75rem\"}},\"fontWeight\":{\"breakpoint_base\":\"700\"},\"advanced\":{\"lineHeight\":{\"breakpoint_base\":{\"number\":\"1\",\"unit\":\"custom\",\"style\":\"1\"}},\"letterSpacing\":{\"breakpoint_base\":{\"number\":2,\"unit\":\"px\",\"style\":\"2px\"}},\"textTransform\":{\"breakpoint_base\":\"uppercase\"}}}}},\"color_hover\":{\"breakpoint_base\":\"var(--bde-brand-primary-color)\"}},\"corners\":\"square\",\"background_hover\":\"var(--bde-palette-color-3-6baec9e8-b487-41ee-bbaa-b10911c68e36)\"},\"secondary\":{\"size\":{\"size\":{\"breakpoint_base\":\"custom\"},\"padding\":{\"breakpoint_base\":{\"top\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"},\"left\":{\"number\":24,\"unit\":\"px\",\"style\":\"24px\"},\"right\":{\"number\":24,\"unit\":\"px\",\"style\":\"24px\"},\"bottom\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}}},\"background\":\"var(--bde-background-color)\",\"corners\":\"square\",\"typography\":{\"color\":{\"breakpoint_base\":\"var(--bde-brand-primary-color)\"},\"typography\":{\"custom\":{\"customTypography\":{\"fontFamily\":{\"breakpoint_base\":\"custom_font_nunito-local\"},\"fontSize\":{\"breakpoint_base\":{\"number\":0.75,\"unit\":\"rem\",\"style\":\"0.75rem\"}},\"fontWeight\":{\"breakpoint_base\":\"700\"},\"advanced\":{\"letterSpacing\":{\"breakpoint_base\":{\"number\":2,\"unit\":\"px\",\"style\":\"2px\"}},\"lineHeight\":{\"breakpoint_base\":{\"number\":\"1\",\"unit\":\"custom\",\"style\":\"1\"}},\"textTransform\":{\"breakpoint_base\":\"uppercase\"}}}}}},\"background_hover\":\"var(--bde-palette-color-3-6baec9e8-b487-41ee-bbaa-b10911c68e36)\"}},\"typography\":{\"heading_font\":\"custom_font_cinzel-local\",\"body_font\":\"custom_font_nunito-local\",\"advanced\":{\"body\":{\"typography\":{\"custom\":{\"customTypography\":{\"fontWeight\":{\"breakpoint_base\":\"400\"}}}}},\"headings\":{\"all_headings\":{\"typography\":{\"custom\":{\"customTypography\":{\"fontWeight\":{\"breakpoint_base\":\"400\"}}}}}}},\"global_typography\":null,\"ratio\":{\"breakpoint_base\":1.37,\"breakpoint_phone_landscape\":1.2,\"breakpoint_tablet_landscape\":1.35,\"breakpoint_phone_portrait\":1.15}}}}",
  "classes": "[{\"name\":\".login-popup\",\"type\":\"class\",\"properties\":{}}]",
  "presets": "[]",
  "ai": "{\"businessName\":\"\",\"businessDescription\":\"\",\"qualifiers\":\"\",\"presets\":[]}"
}

**Comment by breakdancemoderator** [comment]
Hello @tapashdatta, 

Please open a support ticket at https://breakdance.com/support.
