### ISSUE TITLE
Can't edit template settings BD2.1 beta 1

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#1147]
BD2.1 beta1 (that was upgraded from BD2.0)

Unable to edit the settings of any templates

- add a new template
- click on settings
- popup appears, but clicking 'continue' does nothing

**Comment by mirkoschubert** [comment]
I can confirm that. I have the same bug. If I click on the settings of a Breakdance template, the advanced template settings modal appears, but clicking on `continue` does nothing.

I have the same result when creating a new template and use the `Custom Template` option. Btw, there are no errors in the console and every file is loading correctly. So it seems that the action of the `continue` button is missing.

**Comment by breakdancemoderator** [comment]
This is fixed in Breakdance 2.1 Beta 2 and may be downloaded via the [Breakdance Customer Portal](https://breakdance.com/portal).
