### ISSUE TITLE
HTML Field in form builder does not obey conditional rules

### ISSUE THREAD

**Issue by rossdav70** [soflyy/breakdance-bugs#1150]
1) Create a form and add any field that has a fixed value like a radio button or select.
2) Add an HTML field to the form and set the condition to only show when the first field is a certain option.

Note that it does not grey out.

3) Change the HTML field to a text field or any other field type (except step) and note how it does grey out as the condition is correctly applied.

**Comment by mirkoschubert** [comment]
Same here.

**Comment by davood89** [comment]
Same here.

**Comment by breakdancemoderator** [comment]
This is fixed in Breakdance 2.2, which is available for beta testing. You may learn how to test Breakdance Beta versions here: https://breakdance.com/documentation/advanced/enable-beta-updates/.
