### ISSUE TITLE
Advanced Tabs broken in 2.1.0

### ISSUE THREAD

**Issue by kickoffstudio** [soflyy/breakdance-bugs#1158]
Content from all tabs is displayed in the first tab.

System information:
 - Breakdance version: 2.1.0
 - Browser & OS: Chrome using macOS Sequoia

**Comment by DBuro1** [comment]
Confirm. The tab contents are just stacked, switching tabs does nothing.

**Comment by breakdancemoderator** [comment]
Please follow these steps to fix this issue:

- Regenerate Breakdance cache in the WordPress admin panel > Breakdance > Settings > Tools > Regenerate CSS Cache
- Clear any server-side, plugin-based, and browser caches

If that doesn't work, please submit a support ticket at https://breakdance.com/support.
