### ISSUE TITLE
There's no sound when section background is set to video

### ISSUE THREAD

**Issue by nkasic** [soflyy/breakdance-bugs#1163]
- Breakdance version 2.1.0
 - Browser & OS Chrome, Windows 10

When I set Section background to Video and insert URL from YouToube, video plays well, but there's no sound.
I don't see any mute command, and there is a sound in the video that I would like to be heard. User can always turn it off oh his PC or mobile if he doesn't want sound.
![image](https://github.com/user-attachments/assets/7471a84a-0a23-410d-ade4-1401d3efde44)

**Comment by breakdancemoderator** [comment]
Hello @nkasic, 

This isn't supported in Breakdance as most browsers don't allow sound to play when a video is set to autoplay. You may read more about this here: https://developer.chrome.com/blog/autoplay/.

**Comment by nkasic** [comment]
Indeed.
Here's what copilot says:

Yes, you can have a background video with sound on an HTML page, and the
sound can be played in Chrome. However, there are a few important
considerations:

   1.

   *Autoplay Restrictions*: Modern browsers, including Chrome, have
   restrictions on autoplaying videos with sound. To autoplay a video with
   sound, the user must interact with the page first (e.g., by clicking a
   button). Without interaction, the video will autoplay but be muted.

So, it autoplays muted as described above under 1, and in theory if we need
sound there should be some interaction with video (i.e. unmute button). So
if you add unmute button in the section element it should be possible to
hear the sound.

Best regards,

------------------------------

Nikola Kašić

tel.: +385 99 3178554
e-mail: ***@***.***

<https://wa.me/385993178554>
