### ISSUE TITLE
BD 2.1.0 "Include Custom Breakpoints in Breakpoint Dropdowns" not working

### ISSUE THREAD

**Issue by ectu** [soflyy/breakdance-bugs#1165]
Option "Include Custom Breakpoints in Breakpoint Dropdowns" activated but custom breakpoints are not included in the dropdown (BD 2.1.0, WP 6.6.2) 

<img width="302" alt="Bildschirmfoto 2024-10-25 um 13 46 26" src="https://github.com/user-attachments/assets/1647d766-0e87-4f87-95d5-4288535bd9ea">
<img width="857" alt="Bildschirmfoto 2024-10-25 um 13 46 19" src="https://github.com/user-attachments/assets/1d56881e-c31f-497c-9bd8-2dc9fbe7da99">
<img width="827" alt="Bildschirmfoto 2024-10-25 um 13 46 12" src="https://github.com/user-attachments/assets/88ab7796-2666-4e7c-93b3-689d50cedea3">

**Comment by breakdancemoderator** [comment]
Hi @ectu, 

The "Include Custom Breakpoints in Breakpoint Dropdowns" does not support Settings > Hide On Breakpoint. You may learn more about this here: https://breakdance.com/documentation/settings/preferences/custom-breakpoints/breakpoint-dropdown-limitations/
