### ISSUE TITLE
Element Enhancement: Pricing Table - Ability to add a ribbon/banner with some text.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#117]
Requested by user via Help Scout.

"Add a ribbon with editable text like 'best offer,' 'popular,' etc."

**Comment by louisreingold** [comment]
Pricing Table element currently supports a badge/ribbon on the top. It's not rotated 45 degrees though (which may be what the user wants). That can be done easily with custom CSS.
