### ISSUE TITLE
Mask feature is missing in new image widget

### ISSUE THREAD

**Issue by brandforwardnl** [soflyy/breakdance-bugs#1172]
Since the new image widget is in BD, there is no option to use a mask anymore. The old version of the widget still has the option. I don't know if it's a bug or on purpose but can the mask feature please return in the future?

Breakdance version: v2.1.0

**Comment by breakdancemoderator** [comment]
Hello @brandforwardnl - The new Image element doesn't include masking. Instead, you can place the new Image element inside a [Masker element](https://breakdance.com/documentation/reference/elements/blocks/masker/).
![image](https://github.com/user-attachments/assets/c14a5dfb-7587-41ff-ab78-bf841a360172)

**Comment by brandforwardnl** [comment]
Ah great, thanks for clearing this out 👍🏻
