### ISSUE TITLE
Popup > Background > Linear Gradient > Artifact (beta 4)

### ISSUE THREAD

**Issue by wpdv** [soflyy/breakdance-bugs#118]
Line artifact protrudes from gradient angle dial

https://user-images.githubusercontent.com/7375921/181043551-04258330-2333-4661-adb4-0368b57394c4.mov

**Comment by louisreingold** [comment]
What browser / browser version / OS?

**Comment by wpdv** [comment]
The latest Firefox Developer version - 104.0b1 (64-bit)

**Comment by wpdv** [comment]
Must be browser related. Tested in Chrome, works **fine** - Version 103.0.5060.134 (Official Build) (x86_64)

**Comment by louisreingold** [comment]
Firefox has a number of rendering issues when using advanced CSS tactics such as mask-image, etc. and we're using a 3rd party library for the gradient picker. It's likely Firefox will fix this in a future update.
