### ISSUE TITLE
BD 2.2.0: Replies to Comments Not Showing Up

### ISSUE THREAD

**Issue by ninjaseo** [soflyy/breakdance-bugs#1184]
After updating to version 2.2.0 (tested on multiple sites), replies to comments are no longer visible. When someone comments for the first time, it appears correctly, but when another user replies to that comment, it does not show up.

Nothing on these site has changed except for the update to BD 2.2.0.
I have tried the following , but the problem persists:
- Checked the comment settings in WordPress to ensure that the threaded comments option is enabled.
- Cleared the cache.
- Deactivated the cache.
- Deactivated all plugins except for BD 2.2.0.
- Tried in several browsers.
- Sites are on different servers, different versions of PHP, same problem.

**Reverting back to version 2.1.0 resolves the issue, and replies appear immediately.**

So I suspect that there is a problem somewhere in the comments code in version 2.2.0.

**Comment by breakdancemoderator** [comment]
This is fixed in Breakdance 2.3, which is available for beta testing. You may learn how to test Breakdance Beta versions here: https://breakdance.com/documentation/advanced/enable-beta-updates/.

**Comment by ninjaseo** [comment]
> This is fixed in Breakdance 2.3, which is available for beta testing. You may learn how to test Breakdance Beta versions here: https://breakdance.com/documentation/advanced/enable-beta-updates/.

Thanks for the reply. I tried BD 2.3 beta 1 and I can confirm that fixed this problem for me.

**Comment by Nicscott01** [comment]
I also had the problem, and 2.3 fixed it. thank you.
