### ISSUE TITLE
Blank Page when opening Breakdance

### ISSUE THREAD

**Issue by tradesouthwest** [soflyy/breakdance-bugs#120]
After installing and activating plugin everything looked fine and went through the settings. When attempting to edit a page post, I opened the page editor and see "Edit In BreakDance" which I click on then after clicking I see a completely blank page; with no dashboard bar or any elements on the page.

WordPress Version: 6.0.1 PHP Version: 7.4.29 MySQL Version: 10.3.31 WP_DEBUG: 1 
JQuery Version: 3.6.0
Server Software: LiteSpeed
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0
Session Save Path: /opt/alt/php74/var/lib/php/session
Session Save Path Exists: No
Session Save Path Writeable: No
Session Max Lifetime: 1440
WP Memory Limit: 40M

Currently Active Theme: ResuMe: 0.7

Parent Theme: resume

Currently Active Plugins:

    Breakdance: 1.0.0-beta.4
    Debug My Site: 1.0.2
    Hordes: 1.0.0
    Simple CSV/XLS Exporter: 1.5.8
    WordPress Importer: 0.7
    http://tswdev.com/news/?breakdance=builder&id=1828 example url that appears on edit page. (P.S. Seems like a security risk opening a query string without using a post request.

**Comment by louisreingold** [comment]
Email support@breakdance.com with your WP admin login details and we'll take a look.

> Seems like a security risk opening a query string without using a post request.

It isn't.
