### ISSUE TITLE
Video Background - mobile

### ISSUE THREAD

**Issue by fruitygod** [soflyy/breakdance-bugs#130]
Using a video as background for section desktop.
Choosing a fallback image for mobile and choose not to play on Mobile.

Videom still plays on mobile

BD Beta 4
[https://0fejlbd.us12.instawp.xyz/](url)

**Comment by louisreingold** [comment]
@fruitygod we made changes to this behavior in beta 5. Please upgrade to beta 5 and let me know if this still happens for you.
