### ISSUE TITLE
Header builder | Background shadow settings conflict

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#131]
My goal is to have a dropshadow in header. I first did that in border settings
![image](https://user-images.githubusercontent.com/51177627/181187404-a47e5662-51cd-4c54-a231-6b2523542321.png)

The problem is it's being ignored because the Overlay setting probably has a higher render priority
![image](https://user-images.githubusercontent.com/51177627/181187741-13e6c3a8-e142-4755-93be-ec62d58536e0.png)

![image](https://user-images.githubusercontent.com/51177627/181187166-2a7a9da6-ddbd-4275-81a0-0a8341d72dbc.png)

**Comment by louisreingold** [comment]
Does enabling the Keep Style option solve the problem?

**Comment by Dancerist** [comment]
It does. But. If I enable that, the overlay background is active too. And I want it to overlay to top without a background unless user starts scrolling.
![image](https://user-images.githubusercontent.com/51177627/181197844-e98a78d4-78d9-4243-9346-b7bd152a280d.png)

**Comment by louisreingold** [comment]
> It does. But. If I enable that, the overlay background is active too. And I want it to overlay to top without a background unless user starts scrolling.

Then set the main background to transparent and the sticky background to whatever you want, like this:

https://www.loom.com/share/577abffdb0ce4438944412120639c537

**Comment by Dancerist** [comment]
Thanks! I miss the part where I can add a background in sticky options.
