### ISSUE TITLE
Counter not working on safari 

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#132]
When using the Simpel Counter element it's not working on Safari.

<img width="428" alt="Simpel counter" src="https://user-images.githubusercontent.com/56388399/181191777-829a257a-bfcf-43e9-ae89-fa310b709885.png">

<img width="618" alt="error-js" src="https://user-images.githubusercontent.com/56388399/181197209-b22c84a5-7f9b-4b10-875b-df11186e6402.png">

**Comment by louisreingold** [comment]
Can confirm - using Safari on Mac OS Catalina

**Comment by louisreingold** [comment]
Thanks for the report. This will be fixed in beta 7.
