### ISSUE TITLE
Animations not working on iOS more than 2 years old (IOS 13.6.1)

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#133]
The animated elements won't load because the is-animated class is not added to the element. 

PS: Not sure what you guys want to achieve with the fallback for older browsers :). Will there be a list of supported browsers?

**Comment by louisreingold** [comment]
Breakdance uses GSAP for animations under the hood.

It's one of the most respected animation libraries around.

We support whatever they support.

You can expect Breakdance to have browser support similar to every other visual builder in existence. What this means is that all modern browsers can handle websites built with Breakdance. You can expect Breakdance to use CSS features that are used on other mainstream websites, such as CSS variables, flexbox, gap, etc.

I know the definition of "modern browser" is vague, and some of it depends on how you build the website (for example, how much are you relying on flex gap?). We support whatever we can reasonably support and deliberately avoid using features without wide browser support.
