### ISSUE TITLE
Global styles heading line height not working

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#134]
The line height of the headings are not working.

<img width="349" alt="line-height" src="https://user-images.githubusercontent.com/56388399/181237070-d964f9b0-ac8f-441e-99c6-2fee8b0f557b.png">

**Comment by louisreingold** [comment]
This should be solved in beta 5. 

In beta 5 we removed the default line height from our heading element which was overriding the global line height in many instances.
