### ISSUE TITLE
When trying to edit a header item, "Failed to load "" Error loading some of the dependencies, check your console"

### ISSUE THREAD

**Issue by Foolevil** [soflyy/breakdance-bugs#135]
console.error(
          `Couldn't load some of the inlineScript dependencies because one of more scripts failed to load:${dependency.scripts}`
        );
        NotificationLogger.log.message(
          "Error loading  some of the dependencies, check your console"
        );
        
          `Error when running 'builderCondition' for element '${element.data.type}': ${e}`

Seems like Breakdance is asking for a custom item I have deleted.

**Comment by neeckola** [comment]
> You can safely ignore this error - it won't affect anything. We'll have it solved in beta 5 or 6.

Source: https://www.facebook.com/groups/breakdanceofficial/posts/5267265846642001/?comment_id=5267998656568720

**Comment by louisreingold** [comment]
Thanks for the bug report. Unfortunately, I can't reproduce this.

If you email support@breakdance.com with your WP admin login details and exact steps we should take to see the bug, we'd love to take a closer look.
