### ISSUE TITLE
Image Element Error When Using a Custom Size and Width or Height are Blank

### ISSUE THREAD

**Issue by Kpudlo** [soflyy/breakdance-bugs#136]
When using an Image element, and you set the size to Custom, if the Width or Height boxes are blank, it produces an error

### Steps to Reproduce

- Add an Image element in Breakdance
- Select "Custom" Image Size
- Set the Width of the Image Size, leave the Height blank
- Click "Apply" and see the error

Video of the issue: https://www.loom.com/share/2ec05256d0f049f1ad1074a4d86917e1

**Comment by neeckola** [comment]
I guess there is a lot of issues with leaving values blank - something similar is https://github.com/soflyy/breakdance-bugs/issues/99

And my other guess is that will all be polished in future betas. Try to fill all values, for now, is my best advice.

**Comment by louisreingold** [comment]
The behavior should be to use the provided side and keep the aspect ratio.
