### ISSUE TITLE
IO-TS decoding failed when Co Authors Plus plugin is active

### ISSUE THREAD

**Issue by etjallings** [soflyy/breakdance-bugs#137]
Breakdance is not working when the plugin co-authors plus is active.

Loading the editor says Validation Error: IO-TS decoding failed

Check browser console for debug information.

To reproduce download  https://wordpress.org/plugins/co-authors-plus/ and activate. Go to headers or any other place that loads breakdance editor.

**Comment by neeckola** [comment]
![image](https://user-images.githubusercontent.com/83248721/181399318-4e163d74-6854-4872-8920-d6ce93a47f37.png)

Can confirm. 
WP: 6.0.1
BD: beta 4
nginx, php 7.4.1, local

**Comment by louisreingold** [comment]
Confirmed.

**Comment by louisreingold** [comment]
Solved in beta 7.
