### ISSUE TITLE
Color gradient option is unavailable in some elements

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#138]
Like how it is not available in column element
![image](https://user-images.githubusercontent.com/51177627/181391688-14bd8f4b-0e05-491b-aff4-cf5b777a7862.png)

But available in buttons custom settings
![image](https://user-images.githubusercontent.com/51177627/181391740-08052a9e-c19d-4d79-890c-0d593c8f2b4e.png)

But not really, if I go to buttons' advance settings, then background, the gradient option tool is not present
![image](https://user-images.githubusercontent.com/51177627/181391929-21557689-9897-41f4-a3d4-9a5daedae82e.png)

**Comment by louisreingold** [comment]
> Like how it is not available in column element
> But not really, if I go to buttons' advance settings, then background, the gradient option tool is not present

Those Background controls are meant to be a mirror of CSS's background properties. You can add a background gradient by adding a layer. This is by design.

Explanation: https://www.loom.com/share/5093fc1752624273a86702f700cfea4f
