### ISSUE TITLE
Menu Builder Wrapper Width Issue

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#139]
Menu builder wrapper width is not responsive to the number of items inside. But if I override the width (see screenshot) with "auto" it will perform as intended.

![image](https://user-images.githubusercontent.com/51177627/181402445-52d230a5-5c2e-43a0-8e02-f8ed2ac48bac.png)

Also I think it would be a good addition if there's also a setting to set the width of the menu builder wrapper equal to the header container width. see example

![image](https://user-images.githubusercontent.com/51177627/181402773-f8462c5f-0447-4a93-b93e-8f0ef49a59b2.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
