### ISSUE TITLE
Rich Text is Not Affected By Global Line Height

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#14]
When adding a **RICH TEXT** element and a **BASIC TEXT** element only the **BASIC TEXT** element is affected by **GLOBAL** Line Height. Not sure if this is as intended or a bug.

**Comment by louisreingold** [comment]
Thanks for the report.

In beta 4, Rich Text's line height will default to the line height set at Global Settings > Typography > Advanced > Body.
