### ISSUE TITLE
Register Form Button Styling not working

### ISSUE THREAD

**Issue by justingluska** [soflyy/breakdance-bugs#140]
No settings besides alignment works on the submission button on register forms

<img width="1048" alt="Screen Shot 2022-07-27 at 11 34 36 PM" src="https://user-images.githubusercontent.com/53244307/181421334-a5d92e42-f00d-411f-95b1-fd76958fd44f.png">

**Comment by louisreingold** [comment]
Confirmed: https://www.loom.com/share/29bd4a982d964d7f96bc5d2f6559bbc6

**Comment by louisreingold** [comment]
Thanks for the report. This will be fixed in beta 7.
