### ISSUE TITLE
Transition Duration problem with Custom Button with Gradient Background.

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#141]
The transition duration property is not working for the background transition when gradient is applied to a button background. 
Note that it is working for the icon movement.

**Comment by louisreingold** [comment]
Unfortunately, you can't use a CSS transition on a background gradient: https://stackoverflow.com/questions/6542212/use-css3-transitions-with-gradient-backgrounds

It's possible we could come up with a hacky workaround using some combination of ::before and ::after, so I'm leaving this open.
