### ISSUE TITLE
WooCommerce Image Aspect Ratio Controls

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#144]
Sorry I am late to respond. Github doesn't send me notifications. In other builders the options are available in the builder. I've never had to go into the customiser to edit anything to do with woocommerce unless the theme I am using has forced it like Blocksy.

_Originally posted by @misslaidlaw in https://github.com/soflyy/breakdance-bugs/issues/108#issuecomment-1200288434_

**Comment by salasmx** [comment]
Hey @louisreingold,

This will be added to the builder, right? As of now, there is no way to manipulate the aspect ratio or height of images. This could be useful for the product list element.

**Comment by louisreingold** [comment]
@salasmx you can change the image aspect ratio same way you always do in WooCommerce: https://www.loom.com/share/cd9e60ffdbcf4f18b62a8a490af2bc14

Adding a way to do it directly in Breakdance is under consideration.
