### ISSUE TITLE
WooCommerce Cart Page

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#146]
This is not really a problem but a feature. 

I don't want you guys to think for me and with some of the elements it feels like you are. I am a bit of a control freak so bare with me lol 

I think it's easier when you have the elements separated rather together. The cart and the total would be good if I can disable or enable them individually. That way if i wanted the cart in one column and the total in another column with a different background I could do that. The other page builders have separated elements for each of their woocommerce products

**Comment by louisreingold** [comment]
I created a feature request for this at https://breakdance.canny.io/element-requests/p/woocommerce-cart-page-elements
