### ISSUE TITLE
Many problems with the logo list element 

### ISSUE THREAD

**Issue by choegl** [soflyy/breakdance-bugs#147]
Animation doesn't work, logo size change does not work as expected, links are ignored and some more issues. See video.
 
https://www.loom.com/share/b97af1d8db0447bc8b9a68282e97f594

**Comment by louisreingold** [comment]
We fixed the primary issue with the logo list (broken CSS) that was likely causing all the other issues. It will be available in beta 6. Once you try beta 6, let us know if you encounter any further problems with the Logo List element.
