### ISSUE TITLE
Checkout page styles still not working correctly

### ISSUE THREAD

**Issue by silverlunace** [soflyy/breakdance-bugs#148]
The checkout page looks perfect in the Builder but doesn't reflect on the frontend. No matter what I do, it stays one column and won't apply any styles. Using Chrome on iMac and hosting on SiteGround.

Short video - https://share.vidyard.com/watch/BPuCwWP7Nj6uu77y8dCQ4W?

Let me know if you need any other details.

Was originally issue #52 and supposedly fixed in beta 5 but I'm still encountering the same issue. I tried trashing and recreating the checkout page and still no luck. 

Let me know if you need admin access to my test site for this issue. Thanks

**Comment by louisreingold** [comment]
> Let me know if you need admin access to my test site for this issue. Thanks

Yes please. Send WP admin login details and a link to this ticket to support@breakdance.com and we'll take a look.

**Comment by silverlunace** [comment]
Sending shortly. Thanks

**Comment by louisreingold** [comment]
Closing this issue and handling this in our support desk.
