### ISSUE TITLE
HTML Tag - Problem

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#149]
If you have since given users the freedom to tag sections with header, footer, article and section, something is missing, a global tag for the whole template. Indeed, for an article for example, if you would is correct semantically, you need :
A parent tag: article
and child tags: section
However, everything is done at the section level as far as tag settings are concerned, can you add a global setting to the template, so that you can then tag the sections present in the global tag as you wish.

**Comment by louisreingold** [comment]
This is a good idea. As this is a feature request and not a bug report, please post it at https://breakdance.canny.io/

**Comment by rodolphebertozzo** [comment]
@louisreingold This is not a feature like any other actually, we are talking in this case to be fair and accurate for our SEO and DOM of our pages, it should be held before the final release date, I put you the link: https://breakdance.canny.io/features/p/html-tag

**Comment by rodolphebertozzo** [comment]
@a-dubiel Where is this issue, because it creates a significant problem when designing parts of my theme, I am forced to go through div elements.
We should make it possible to globally tag our templates as soon as possible

**Comment by louisreingold** [comment]
As I stated previously:

> This is a good idea. As this is a feature request and not a bug report, please post it at https://breakdance.canny.io/
