### ISSUE TITLE
Formfield Checkbox not accepting html (a href Link)

### ISSUE THREAD

**Issue by marcel2008** [soflyy/breakdance-bugs#150]
When trying to add a Link inside a Checkboxfield it show some strage content including the ID before the actual Link and Text. See Screenshot attached. Other Form Plugins have either a field of the type "acceptance" or the checkboxfield supports some simple html.

![image](https://user-images.githubusercontent.com/58587248/182003137-800a5454-0965-4556-bdb0-316ea7c0f32b.png)

**Comment by louisreingold** [comment]
Post the exact HTML string you are trying to use at https://gist.github.com/, and then post the link here.

**Comment by marcel2008** [comment]
Hey Louis, to be honest Im not too familiar with github and gist. Hope this is what you need.

https://gist.github.com/marcel2008/ebe51806880b369b34218ebaa4d5f27a#file-gistfile1-txt

**Comment by louisreingold** [comment]
Perfect, thanks.

I've reproduced the bug. To workaround it for now, set your Option Value to anything - for example, "yes".

**Comment by louisreingold** [comment]
Fixed in beta 6.
