### ISSUE TITLE
Tabs Element - Beta 5

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#151]
After updating to beta 5, the tabs button are displayed in columns, and styles missing

![image](https://user-images.githubusercontent.com/51177627/182003187-0ddc0231-d463-4da2-b2b2-f46dbdc31a6c.png)

**Comment by Dancerist** [comment]
The same goes for Advance tabs

![image](https://user-images.githubusercontent.com/51177627/182003260-e35f2928-b447-445f-9f65-f00a1c4519bd.png)

**Comment by louisreingold** [comment]
Save and refresh the page.

If solved, let me know. If not, in the WP admin, go to Breakdance > Settings > Tools and click Regenerate Cache.

If solved, let me know. If not, save and refresh the page again.

If solved, let me know. If not, email your WP admin login details to support@breakdance.com and I'll take a look.

**Comment by Dancerist** [comment]
Solved! Here's what I did

**Step 1**
Breakdance > Settings > Tools and click Regenerate Cache. Save & Refresh Editor/Page - NOT WORKING

**Step 2**
Editor > Delete and add back the Element > Save > CTR F5 - SOLVED

**Comment by Dancerist** [comment]
Thanks!
