### ISSUE TITLE
FAQ Block - Element Enhancement

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#152]
-I increase the vertical padding now the tab is only clickable in the center. The green box means the area not clickable.
![image](https://user-images.githubusercontent.com/51177627/182005285-38bb989b-b0d7-4b02-ae07-2af062d51fed.png)

-No spacing option for tab item. I did it via custom CSS
![image](https://user-images.githubusercontent.com/51177627/182005299-c8efbb73-c9ea-4cc6-97f2-cfe1a3c06d38.png)

-No background option for tab item. I did it via custom CSS
-the tab animation feels snappy. hope there's an option to make it smooth. or make it smooth by default.
-cant close back to default the tab item if "Accordion" option is enabled.

![image](https://user-images.githubusercontent.com/51177627/182005316-131a12b5-14e4-45e5-bddc-0b11f7c6be78.png)

**Comment by Dancerist** [comment]
And I don't think the "Active Title" is working.

![image](https://user-images.githubusercontent.com/51177627/182005463-2cd14fb1-46a3-4560-8ff4-9893e0ec9b17.png)

**Comment by louisreingold** [comment]
We addressed everything except for the following in beta 8.

> -the tab animation feels snappy. hope there's an option to make it smooth. or make it smooth by default.
> -cant close back to default the tab item if "Accordion" option is enabled.
