### ISSUE TITLE
Dropdown box caret out of position on Chrome MacOS

### ISSUE THREAD

**Issue by tonylondon** [soflyy/breakdance-bugs#154]
Appears on breakdance.com and on own test site.
<img width="448" alt="Screenshot 2022-07-31 at 08 23 31" src="https://user-images.githubusercontent.com/110322370/182011739-02d7f9ca-61bd-4a67-8448-41a7cc0a7985.png">

**Comment by louisreingold** [comment]
I can get this to happen sometimes but not always. Do you have steps to reproduce reliably? 99.9% of the time, the caret appears correctly.

**Comment by tonylondon** [comment]
The common denominator is Chrome on MacOS Catalina.

I first noticed it on breakdance.com and momentarily thought it might be a new feature! 

Also appears on our test site since Beta 5.

Looks fine on Safari on the same platform, and on iOS 15 Chrome and Safari.

**Comment by louisreingold** [comment]
I'm on Catalina and using Chrome and can rarely get this to happen.

Does this happen to you every time you load the page, or just in a small percentage of the time?

**Comment by tonylondon** [comment]
The issue is constant. Should add that I'm running latest version of Chrome.

**Comment by tonylondon** [comment]
UPDATE: It appears that saving the header has fixed this. I'll keep an eye out to see if it appears again and will report anything back here.
