### ISSUE TITLE
Rich text element acting weird on Safari

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#155]
Rich text element in popup mode is acting weird: you don't see the cursor, it looks like you can't select anything, ...
I'm on latest stable version of Safari (15.6 (17613.3.9.1.5)) on latest version of Mac OS (Monterey 12.5).

Video: https://a.cl.ly/o0uGzbzn

**Comment by louisreingold** [comment]
Thanks for the report. This will be fixed in beta 7.
