### ISSUE TITLE
Connect Gallery element to ACF gallery field

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#157]
Allthough I have two ACF gallery fields active (one tied to the current page and one tied to a general ACF option page), I don't see them showing up in the dynamic data popup within the Gallery element settings.

**Comment by louisreingold** [comment]
We'll fix the issue with the Gallery element not being able to pull from an ACF gallery field.

Please open a request to support ACF options pages at https://breakdance.canny.io/

**Comment by louisreingold** [comment]
> We'll fix the issue with the Gallery element not being able to pull from an ACF gallery field.

Does this still happen for you in beta 7? I was not able to reproduce the issue. I'm able to link the Gallery element to an ACF Gallery field with no problems.
