### ISSUE TITLE
Custom image sizes (created in the BD UI) are stored in /uploads/ instead of the normal media folders

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#161]
Reported at https://www.facebook.com/groups/breakdanceofficial/posts/5270469469654972/

"Custom image sizes (created in the BD UI) are stored in /uploads/ instead of the normal media folders. Tools like Shortpixel don't pick them up for optimizing file size. I don't know if there's something that can be done about it and I'm not sure if putting them into the media folders would solve this."

**Comment by FelipeMarcos** [comment]
By default, images are stored in folders organized by date:
http://breakdance.local/wp-content/uploads/2022/07/image.jpeg

And we store the custom image sizes directly in the uploads folder.
http://breakdance.local/wp-content/uploads/image-100-100.jpeg

I'm assuming the user wants the custom image also organized by date.
