### ISSUE TITLE
[Element Studio] Missing "saving location"

### ISSUE THREAD

**Issue by salasmx** [soflyy/breakdance-bugs#164]
Missing "saving location" when trying to create a new element, macro, or preset.

Expectative: [https://share.getcloudapp.com/llu0p1Dl](https://share.getcloudapp.com/llu0p1Dl)

What I see: [https://share.getcloudapp.com/jkuXN1Qj](https://share.getcloudapp.com/jkuXN1Qj)

[https://www.loom.com/share/ed9c0233f22440fc977f4d94bb009f10](https://www.loom.com/share/ed9c0233f22440fc977f4d94bb009f10)

**Comment by louisreingold** [comment]
You need to setup a plugin to save your elements: https://breakdance.com/documentation/developers/element-studio/
