### ISSUE TITLE
Menu - No option to change --active link color AND Menu Button text color

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#170]
To change the the color for --active links. e.g. active link color indicator when the user is on that page, I end up using the CSS stylesheet to override the default link color.

![image](https://user-images.githubusercontent.com/51177627/182740222-ddbb2096-aa5e-446b-929b-634ea67790c2.png)

**Comment by dancerist** [comment]
@a-dubiel @louisreingold hope this is one of the priorities.

We are missing the ability to add style for active menu links.

I want to apply the same style if a menu link is hovered. see img attached
![image](https://user-images.githubusercontent.com/51177627/219544226-8af77583-58eb-4044-a2fb-79fff03b7016.png)

**Comment by louisreingold** [comment]
We recently added various styling options for active menu links to Breakdance. Thanks for the report!
