### ISSUE TITLE
Not possible to use "Current Date (WordPress)" condition twice to establish time window.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#171]
It would be great if we could choose "Current Date (WordPress) is after <date> AND Current Date (WordPress) is before <date>" to establish time windows for element visibility.

**Comment by AjmDigitalServices** [comment]
Agreed, currently can't select the date more than once and for the box to enter the date does not accept input.

**Comment by louisreingold** [comment]
@Spellhammer please repost this at https://breakdance.canny.io/
