### ISSUE TITLE
Form Fields - Fields Hidden By Condition Shouldn't Be Required

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#172]
I have created a form that has conditions. There are basically two branches with almost identical fields showing based on the firstly selected dropdown. 

The problem is that when I fill up one of the branches the form wants from me to input information also in the hidden ones, because they are as well required fields.

So I guess hidden fields should be transformed to a not required ones.

**Comment by louisreingold** [comment]
Thanks for the report. This will be fixed in beta 7/8.

**Comment by louisreingold** [comment]
Solved in beta 7.
