### ISSUE TITLE
Pop ups are opening on exit, even if not set up (They are set up to open only on click)

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#173]
I have created a Pop Up and set it up to open only when a button is clicked, but the popup opens also when I exit the viewport (Try to change Tab or Close the broweser).

**Comment by jijojosein** [comment]
I have the same issue. A pop set up to open on click started showing up on exit. It started happening after upgrading to beta 5.

**Comment by StefanPavlov23** [comment]
I believe this one is fixed in the Beta 6.

**Comment by louisreingold** [comment]
I'm not longer able to reproduce this. If this still happens, please open another issue.

In beta 6, we fixed some issues related to the popup that were probably causing this.
