### ISSUE TITLE
Mobile: Mini Cart Responsiveness 

### ISSUE THREAD

**Issue by jijojosein** [soflyy/breakdance-bugs#174]
Mini Cart goes out of the screen on mobile. 

![Screenshot_20220804-153516](https://user-images.githubusercontent.com/12230445/183246837-633040c6-01c1-4e8a-98a2-c270b264e795.jpeg)

Screenshot taken on: Pixel 4A, Chrome

**Comment by louisreingold** [comment]
Thanks for the report. Will be fixed in beta 7.
