### ISSUE TITLE
Adding a posts list element to a Menu Custom Dropdown (Menu Builder) gives all sorts of errors

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#175]
I'm using latest stable version of Safari on latest stable version of Mac OS.

short demo:
https://a.cl.ly/eDuXdBAj

**Comment by louisreingold** [comment]
@adkoen we tweaked the Posts List a bit recently. Does this still happen? If so, please make another demo and click Details & Troubleshooting and scroll through it so we can see the entire error message.

**Comment by adkoen** [comment]
No this seems fixed from my part (beta 8). No error messages anymore 👍
