### ISSUE TITLE
Automatic Update in WP Admin Failing with cURL Error

### ISSUE THREAD

**Issue by emyerfo** [soflyy/breakdance-bugs#178]
When trying to update to the latest version I receive this error: 
Update failed: Download failed. cURL error 18: transfer closed with 4725819 bytes remaining to read

![08a16](https://user-images.githubusercontent.com/108147547/183417420-d6638b6d-4f9d-4990-bac8-52ce25429c57.jpg)

**Comment by Anticosti** [comment]
Same here

**Comment by Anticosti** [comment]
Retried after deleting beta 6 and replaced by beta 5. Suddenly solved. It upgraded.

**Comment by louisreingold** [comment]
Closing as a duplicate.

**Comment by andrija-naglic** [comment]
This is the opened issue: [One click update not working #81](https://github.com/soflyy/breakdance-bugs/issues/81)
