### ISSUE TITLE
Post title element not working when ACF group assigned to the CPT

### ISSUE THREAD

**Issue by wpkorea** [soflyy/breakdance-bugs#179]
When I create single post template for CPT, post title (or Heading with dynamic data from post) NOT pull the post title data from the post if the ACF group assigned to this CPT. When I remove the assigned ACF group from the CPT, the post title is normally displayed back.
![스크린샷 2022-08-08 오후 11 06 48](https://user-images.githubusercontent.com/7345257/183440924-14b7a3fc-936c-4765-aad0-73a990414f60.png)
![스크린샷 2022-08-07 오후 5 43 39](https://user-images.githubusercontent.com/7345257/183440977-0497a22c-6ccc-4b6a-879d-c37be71cafd3.png)

**Comment by louisreingold** [comment]
Email support@breakdance.com with your WP admin login details and we'll take a look.

**Comment by louisreingold** [comment]
This was solved in a recent beta.
