### ISSUE TITLE
Form: required fields with conditionals misbehave

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#180]
If you create a field which is required and make this conditional when to show or hide. It always keeps saying the field is required. Also all the conditional fields are showing inside the mail.

**Comment by louisreingold** [comment]
Thanks for the report. I'm closing this since we already have a report of it at https://github.com/soflyy/breakdance-bugs/issues/172

> Also all the conditional fields are showing inside the mail

Please report this in a separate issue, and please describe the issue in more detail.
