### ISSUE TITLE
Unused Gravity Forms CSS Styles Present In Codebase

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#181]
From what I can tell, it looks like there is an attempt at styling Gravity Forms in the form.css file.  However, it looks like the targeting isn't quite right.  The CSS is looking for this for example...

`.breakdance-form .gform_wrapper.gravity-theme .gfield input, .breakdance-form .gform_wrapper.gravity-theme .gfield textarea, .breakdance-form .gform_wrapper.gravity-theme .gfield select, .breakdance-form .breakdance-form-field__input`

...but none of the Gravity Forms have the `breakdance-form` class on them.  I tried putting that class on the shortcode wrapper but it caused an issue with the grid layout.  Basically, it looks like the `.breakdance-form` part of the CSS targeting needs to be removed.

**Comment by louisreingold** [comment]
We considered building a gravity forms styler, and it may be available in the future, but it's not part of Breakdance currently.

We'll remove that code.

**Comment by thekendog** [comment]
Bummer, seems like the basic look and style and of the inputs and submit buttons could grab the styling somehow.  Imagine it's gotta be hard to style for all form plugins though.  Thanks for the response.

**Comment by louisreingold** [comment]
This will be cleaned up in the next beta.
