### ISSUE TITLE
Gallery Masonry with Tabs - images overlapping in preview

### ISSUE THREAD

**Issue by Bosssaa** [soflyy/breakdance-bugs#183]
In Library preview of Gallery "Masonry with Tabs", some images are overlapping. When I add the section to page it is ok.
![Gallery Masonry with Tabs](https://user-images.githubusercontent.com/110844935/183472037-9c3bde68-b4d3-4cb6-9bb7-26f650d03fb0.jpg)

**Comment by Bosssaa** [comment]
![Gallery Masonry with Tabs_2](https://user-images.githubusercontent.com/110844935/183472507-ed1f3da1-13f4-4eed-8989-2839c82d1abb.jpg)

**Comment by louisreingold** [comment]
I'm not able to reproduce this. We will probably add a "report" feature to the design library to report problems with design library elements to design library authors.
