### ISSUE TITLE
Product builder element shows JS error

### ISSUE THREAD

**Issue by antonijo01** [soflyy/breakdance-bugs#184]
If I try to add product builder element to a section, I get the error:

![image](https://user-images.githubusercontent.com/107608985/183513475-e7908968-f939-4370-87fc-1103c0e0974a.png)

Also, the product image is not visible.
Please check video:
https://www.loom.com/share/89e8be37d6ac4607a73fda63a376816e

I can provide temporary login if needed.

BD Version 1.0.0-beta.6
PHP version: 8.1.9

**Comment by louisreingold** [comment]
@antonijo01 please send your WP admin login details and name of the page/template you are editing in Breakdance when this error occurs to support@breakdance.com.

**Comment by antonijo01** [comment]
I close the problem - it is caused by custom code
