### ISSUE TITLE
Popups - open on selector click doesn't work

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#185]
Created an icon with the ID "search" 

![image](https://user-images.githubusercontent.com/7070435/183518340-332bd91f-fbce-44ef-96aa-90d03f9b8621.png)

Created a popup which opens when I click on icon

<img width="930" alt="image" src="https://user-images.githubusercontent.com/7070435/183518412-12cd7e48-81a4-4f52-831e-25e17c77e81e.png">

When I set up popup and go to click my icon Nothing happens.

**Comment by louisreingold** [comment]
In beta 7, we're gonna get rid of "Open On Selector Click" replace it with the following: https://www.loom.com/share/b1d0e9ecb0814dbb96a00eb5ff5a26b1

**Comment by louisreingold** [comment]
Maybe we'll leave the Click action. It might be nice to have both options.

**Comment by misslaidlaw** [comment]
I do like both .. but,.... your video is exactly how I envisioned using it. Very similar to how Elementor does it.

**Comment by louisreingold** [comment]
Solved in the latest beta.
