### ISSUE TITLE
Dynamic Data - Post Terms not working

### ISSUE THREAD

**Issue by justingluska** [soflyy/breakdance-bugs#189]
Trying to customize my blog template & display post terms -> category on my page. Changing to either category, post tag, or post format don't update and display the proper tag

<img width="1014" alt="Screen Shot 2022-08-08 at 7 23 58 PM" src="https://user-images.githubusercontent.com/53244307/183531195-67f4a845-6094-47db-9ba0-1b4704aa729c.png">

**Comment by obedparla** [comment]
Hey @justingluska, I wasn't able to reproduce the issue. Could you give more info to help me reproduce the bug? What type of template did you create, what element did you use? 

I created a *template* for both "Single Post" and "Post Archive", and I can see the correct post terms for my posts in both:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/10674462/184899641-779391cb-ee60-4b0a-ac1e-088eed70c3e9.png">

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/10674462/184899732-c4010871-36dd-442c-b10a-d9322e1471da.png">

**Comment by louisreingold** [comment]
@justingluska we fixed this in a recent beta.
