### ISSUE TITLE
Heading Element

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#190]
The **Heading Element** doesn't have the ability to link anywhere and the **Text Link** Element doesn't have the ability to choose a H1 element so unable to link any headers at the moment which I think is important. 

![image](https://user-images.githubusercontent.com/7070435/183546039-6545c3d1-9a3f-4465-9c2b-3221b92d3e98.png)

**Comment by louisreingold** [comment]
I added support for h1...h6 to the Text Link element. This will be available in beta 7.
