### ISSUE TITLE
Custom field of Image URL

### ISSUE THREAD

**Issue by jorodr** [soflyy/breakdance-bugs#193]
Hello,
I can add featured image as source of Image URL, but I need to use not only featured images, but custom field images too. Now there is no such possibility. I hope it will be improved.
Thanks in advance.

**Comment by wpkorea** [comment]
They have both featured image elements and just image element, and I found that featured image element doesn't have any dynamic options, but image element does. You may want to use image element for dynamic data from custom field data. But the image element doesn't support acf field or someting neither, for now. I also need this custom field data for image.

**Comment by louisreingold** [comment]
We added the ability to set an image to a Custom Field that stores the URL.
