### ISSUE TITLE
Text Element - cannot change the unit of the width to anything other than px

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#194]
See screensho
![CleanShot 2022-08-09 at 10 07 50](https://user-images.githubusercontent.com/7188497/183598207-c2749bd8-4f18-4a91-8cc5-9dc994eef500.png)
t

**Comment by Spellhammer** [comment]
The width field for Headings also does not have selectable units.

**Comment by louisreingold** [comment]
@adkoen @Spellhammer this will be fixed in the next beta. If you find any other elements with missing unit choices, please report them.
