### ISSUE TITLE
Post Loop element doesn't have the link to the post url.

### ISSUE THREAD

**Issue by wpkorea** [soflyy/breakdance-bugs#195]
I'm trying the Post Loop element and stuck at how I link the featured image to the post URL. And the heading(or the post title) are not linking to the post url.
![스크린샷 2022-08-09 오전 12 06 12](https://user-images.githubusercontent.com/7345257/183602944-6a427b48-3f33-4f72-82d9-e51a50082806.png)

**Comment by louisreingold** [comment]
This was solved in beta 7.
