### ISSUE TITLE
Column widths not taking affect in frontend

### ISSUE THREAD

**Issue by demonLaMagra** [soflyy/breakdance-bugs#197]
**Example Scenario.**

Building a header with 3 columns, set to 40%, 20%, 40%. They show fine in the builder and take up the entire width of the page. When saving this and loading it in the frontend, content is displayed but the column widths have disappeared and shrink to the size to fit the content only.
Seems also styling of the menu elements is wrong also, the arrows for the dropdowns have disappeared, and the spacing on the submenu elements is not there.

**Comment by louisreingold** [comment]
I can't reproduce this.

Email support@breakdance.com with your WP admin login details and we'll take a look.
