### ISSUE TITLE
Form Builder - Sub Labels - Line Height

### ISSUE THREAD

**Issue by dgz61** [soflyy/breakdance-bugs#198]
Please try to clearly describe the problem.
Line Height for Sub Labels in the form builder does not change when entering any values.
Including a screenshot of the problem is a good idea.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/110975554/183875160-1f734887-9d81-4c0a-a018-bd18781a274b.png">

(Or a screencast - https://www.loom.com/)

**Comment by louisreingold** [comment]
This will be solved in the next beta.
