### ISSUE TITLE
Post List default query skips the first post when used in a Post Archive template.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#199]
Steps to reproduce:

1. Add a 5 posts to your site
2. Add a Post Archive template
3. Inside the Post Archive template, add a Post List element
4. Note that on the front and back-end, the most recently published post is missing from the Post List

Screen recording: https://www.loom.com/share/02b01a22e4d644c28286738bb4c313da

**Comment by louisreingold** [comment]
This will be fixed in the next beta.
