### ISSUE TITLE
Animated Heading to GlobalBlock looses it's Texts

### ISSUE THREAD

**Issue by Anticosti** [soflyy/breakdance-bugs#200]
01. Create an Animated Heading;
02. Convert it to a GlobalBlock;
03. Place it in a new template using the associated shortcode [breakdance_block blockId=189];
04. Result: It looses it's associated Texts.
05. On Frontend is OK but not in template editing.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
