### ISSUE TITLE
Animated Heading - Can't change the background color of the highlighted texts

### ISSUE THREAD

**Issue by Anticosti** [soflyy/breakdance-bugs#201]
Animated Heading 
No option to change the background color of the highlighted texts (animated).
Also, there is a subtle vertical shift.
It has to be fixed with:
`.bde-section-xx-xxx .bde-animated-heading__text > span:nth-child(1){
	vertical-align: 1px;
}`

**Comment by louisreingold** [comment]
@Anticosti you can change the background color as follows:

<img width="285" alt="Screen Shot 2022-08-17 at 2 23 27 PM" src="https://user-images.githubusercontent.com/6425257/185245919-6072b26d-b082-43cd-bd17-904d0c29fc79.png">
<img width="286" alt="Screen Shot 2022-08-17 at 2 23 07 PM" src="https://user-images.githubusercontent.com/6425257/185245924-99615dcf-0d19-46cd-a0fb-6598d7cfe437.png">

**Comment by louisreingold** [comment]
@Anticosti please open a new issue with steps to reproduce the vertical shift issue. I can't reproduce it. 

Does it only happen when certain settings are used? If so, right click the element, hit copy, and then go to https://gist.github.com/ and click anywhere in the big box and hit paste. Then save the gist and post the URL to it here.

**Comment by Anticosti** [comment]
I have recreated an Animated Heading directly in the page where I want it. No more issue.
