### ISSUE TITLE
Invisible button to confirm a deletion

### ISSUE THREAD

**Issue by rbogdanowicz** [soflyy/breakdance-bugs#204]
When deleting a typography preset the confirm button has the bg and color blank, correct the css to make it visible.

Screenshot:
![image](https://user-images.githubusercontent.com/2027191/184019629-6ca014a5-5401-4604-a1ec-430e7b84d3fe.png)

**Comment by louisreingold** [comment]
@rbogdanowicz

What version? Beta 6?

**Comment by rbogdanowicz** [comment]
> @rbogdanowicz
> 
> What version? Beta 6?

Yep, beta 6

**Comment by louisreingold** [comment]
I wonder if toggling dark mode on and off would have an effect.

**Comment by louisreingold** [comment]
I can't reproduce this and neither can anyone else, but we've received more than one report of it.

**Comment by louisreingold** [comment]
@rbogdanowicz does this still happen for you with beta 9? If so, can you send your WP admin login details to support@breakdance.com so we can take a look?

**Comment by rbogdanowicz** [comment]
![image](https://user-images.githubusercontent.com/2027191/185809080-34144d09-12bd-4b5e-990b-66f0e06636df.png)

Hello @louisreingold 
I installed beta 9, cleared the cache, did all the procedures and I still have the "invisible" confirm delete button.
I will forward the login details to support@breakdance.com 👍

**Comment by louisreingold** [comment]
Thanks. Also... what browser / OS are you using?

**Comment by rbogdanowicz** [comment]
> Thanks. Also... what browser / OS are you using?

Windows 11
Chrome 104.0.5112.81

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
