### ISSUE TITLE
WooCommerce Product Gallery - display thumbnails as slider

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#205]
https://www.facebook.com/groups/5118076864894234?multi_permalinks=5306518362716749&hoisted_section_header_type=recently_seen

Does WooCommerce accommodate this by default and we just need to flip a flag somewhere?

**Comment by LiamX2** [comment]
Thumbnails slider at the bottom or left/right would be great and more flexible.

**Comment by louisreingold** [comment]
We're tracking this on the Canny board: https://breakdance.canny.io/search?search=thumbnail%2520slider
