### ISSUE TITLE
Desktop Dropdown Arrow

### ISSUE THREAD

**Issue by cleverlyincognito** [soflyy/breakdance-bugs#206]
There are two issues with the dropdown arrow in the menu builder. Only one issue is new in Version 1.0.0-beta.6.

1. New In Version 1.0.0-beta.6: The dropdown arrow appears as intended when the top link (the link that opens the dropdown when hovered or clicked) has no link/URL associated. The arrow disappears immediately upon hyperlinking the top link.
2. When using the Firefox browser, the dropdown arrow doesn't have a smooth transition period as it rotates. Instead, it rotates instantly without any animation.

**Comment by louisreingold** [comment]
> The arrow disappears immediately upon hyperlinking the top link.

This was done deliberately for UX purposes. What's the alternative? You click the link and the arrow animates and the dropdown but you also are navigated away from page?

> When using the Firefox browser, the dropdown arrow doesn't have a smooth transition period as it rotates. Instead, it rotates instantly without any animation.

Also deliberate until Firefox fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1671784

Here's what would happen in Firefox if we didn't disable the smooth transition: https://codepen.io/FelipeMarcos/pen/QWQYpbg

**Comment by louisreingold** [comment]
> The arrow disappears immediately upon hyperlinking the top link.

This is how Dribbble does it: https://dribbble.com/
