### ISSUE TITLE
Video Block Lazy Load Poster Image not working

### ISSUE THREAD

**Issue by justingluska** [soflyy/breakdance-bugs#208]
When adding a poster image for a lazy-loaded youtube video, the image doesn't show on the front end, only the icon does

<img width="1136" alt="Screen Shot 2022-08-11 at 9 54 31 AM" src="https://user-images.githubusercontent.com/53244307/184149899-5814d521-d633-4364-836c-721a7d201b62.png">
<img width="1204" alt="Screen Shot 2022-08-11 at 9 54 25 AM" src="https://user-images.githubusercontent.com/53244307/184149901-b3777eba-c0fa-4432-b998-8ba8fb2f5b33.png">

**Comment by louisreingold** [comment]
Fixed in beta 9.
