### ISSUE TITLE
UI: Global settings Height problem

### ISSUE THREAD

**Issue by krstivoja** [soflyy/breakdance-bugs#21]
<img width="346" alt="Screenshot 2022-06-25 at 08 20 46" src="https://user-images.githubusercontent.com/1234350/175762464-783d7c09-8f80-41c9-8035-6b0957ee3bfa.png">

This section is only 130px height.

**Comment by louisreingold** [comment]
What browser / OS?

**Comment by krstivoja** [comment]
Mac. Chrome. Local by Flyweel

<img width="558" alt="Screenshot 2022-06-25 at 11 59 31" src="https://user-images.githubusercontent.com/1234350/175768664-65a27403-e6a7-4aea-aa6e-232d0992c3c9.png">

**Comment by louisreingold** [comment]
@krstivoja I can't reproduce this on Chrome on a Mac. Are you still encountering this an alpha 2?

**Comment by krstivoja** [comment]
Fixed in Alpha 2
