### ISSUE TITLE
Conditions don't work when querying blog post

### ISSUE THREAD

**Issue by justingluska** [soflyy/breakdance-bugs#211]
trying to add a condition to a custom blog template (like only show if author is xyz, post category is xyz) and when I select the condit
<img width="625" alt="Screen Shot 2022-08-11 at 4 02 03 PM" src="https://user-images.githubusercontent.com/53244307/184229848-d0f941ff-ccff-4254-b8f0-7a1d96fc3dd9.png">
ion the condition box resets like I pressed nothing
<img width="1047" alt="Screen Shot 2022-08-11 at 4 00 16 PM" src="https://user-images.githubusercontent.com/53244307/184229318-f5c48934-b3a4-4678-ab54-9a389da0af82.png">

**Comment by louisreingold** [comment]
Solved in a recent beta. Thanks for the bug report.
