### ISSUE TITLE
Global settings you can't use CSS variables to set new colors in the palette

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#214]
Would be convenient as I'm running my own color system that is making shades on the fly (no it is NOT acss as I'm running my own stuff ;-) )
<img width="275" alt="CleanShot 2022-08-12 at 13 58 38@2x" src="https://user-images.githubusercontent.com/7188497/184349760-ff98c608-ec02-462b-8c49-d596f6a4fc06.png">

**Comment by louisreingold** [comment]
Does it not work at all or does the color just not show up in the UI?

**Comment by adkoen** [comment]
Just tried this again in Beta 8. It does not work in the palette. Here a screenshot of some colors I've added to the palette:
<img width="383" alt="CleanShot 2022-08-17 at 21 05 37@2x" src="https://user-images.githubusercontent.com/7188497/185222323-eda23761-5454-4987-b4ea-26dc731bd260.png">
Next, when trying to use those colors from the palette, only the one created without a CSS variable shows up:
![SCR-20220817-tbw](https://user-images.githubusercontent.com/7188497/185222469-c3c29a1e-519f-4b85-bf2c-c0100a566ce2.png)
And the color preview does not seem to work anywhere when using a CSS variable. But, that is polish, would be great, but can live without.

**Comment by louisreingold** [comment]
OK. This is a good idea, but not a bug per se, so please request this as a feature at https://breakdance.canny.io/

**Comment by adkoen** [comment]
OK done.
