### ISSUE TITLE
Wrapper link element - not possible to use ACF URL field

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#215]
The ACF URL field does not show up to pick as a dynamic url the wrapper link element.
![CleanShot 2022-08-12 at 20 39 22](https://user-images.githubusercontent.com/7188497/184423068-38343937-2101-478f-a9c3-8ba7041676ab.png)

**Comment by louisreingold** [comment]
This will be solved in beta 8.
