### ISSUE TITLE
No link to post url in post title, heading, text elements

### ISSUE THREAD

**Issue by wpkorea** [soflyy/breakdance-bugs#218]
There is no link property option to link post url at post title, heading, text elements in either post loop builder element or elsewhere.   Instead used text link element, but those element with link property would be better. 
![스크린샷 2022-08-13 오후 12 50 45](https://user-images.githubusercontent.com/7345257/184468158-9a53e0fb-d7d0-4360-b83b-d03cc3493f3a.png)
![스크린샷 2022-08-13 오후 12 36 29](https://user-images.githubusercontent.com/7345257/184468160-a31eedbf-db26-4c37-932d-714b23129b49.png)

**Comment by louisreingold** [comment]
Currently, you can use the Text Link element to achieve this. It has an option to use heading tags.
