### ISSUE TITLE
Post builder link (beta 7)

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#221]
In beta 7 you added the ability to link to (custom) post types using the post builder.
But it does not seem to work.

It links to https://www.domain.com/[breakdance_dynamic%20field='post_permalink'] instead.

![Screenshot (2)](https://user-images.githubusercontent.com/10600315/184474504-7bc06b0a-5b2c-47cd-9e20-736ce534a910.png)

**Comment by louisreingold** [comment]
This is happening for the button element.

**Comment by wpkorea** [comment]
There is no link property in both heading and post title element natively with no link working.

![스크린샷 2022-08-16 오전 8 04 37](https://user-images.githubusercontent.com/7345257/184735351-a9d347af-4cd1-4462-a460-c019667464e9.png)

**Comment by wpkorea** [comment]
It's working for text link element for FYI.

![스크린샷 2022-08-16 오전 8 12 26](https://user-images.githubusercontent.com/7345257/184736318-663edd4f-d179-4248-b704-c98109e429ac.png)

**Comment by louisreingold** [comment]
@mikehenze thanks for the report. I've fixed this and the fix will ship in beta 8.

@wpkorea I've created a new issue with your comment.
