### ISSUE TITLE
Overlay doesnt work on first try

### ISSUE THREAD

**Issue by Bonnie-Clyde** [soflyy/breakdance-bugs#222]
Using Win 11 and Firefox
Added overlay to background section and it doesnt show up. Works on the front end. 
![Screenshot 2022-08-13 at 18-27-18 Breakdance Single Post](https://user-images.githubusercontent.com/111174477/184475949-74260a6b-1225-48f2-81cb-161f6ad092f2.png)
Reloading the page fixes the problem.

**Comment by louisreingold** [comment]
I'm on a Mac. I can't reproduce this.

Can anyone else on Windows reproduce this?
