### ISSUE TITLE
Beta 7 - Using the 'post permalink' dynamic data on 'wrapper link' element does not work

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#223]
I'm in a global block that is used as an post item for the post loop builder.
When I set the link for the 'wrapper link' element to 'post permalink', this is what happens:
![CleanShot 2022-08-13 at 10 49 13](https://user-images.githubusercontent.com/7188497/184476480-639dbb56-8e9c-4099-898d-a616779bfccf.jpg)

**Comment by mikehenze** [comment]
Dupe of https://github.com/soflyy/breakdance-bugs/issues/221

**Comment by louisreingold** [comment]
Thanks for the report. I've fixed this and the fix will ship in beta 8.
