### ISSUE TITLE
Plugin Autoupdate

### ISSUE THREAD

**Issue by specdc** [soflyy/breakdance-bugs#224]
![Screen Shot 2022-08-13 at 9 35 39 AM](https://user-images.githubusercontent.com/9505276/184476813-cea70d91-1156-4d93-b783-6ce55eec644b.png)

Autoupdate for beta 7 fails with cURL error 18.  beta 6 failed autoupdate as well. Did not note beta 6 error.  Manual update for beta 6 worked fine.
Including a screenshot of the problem is a good idea.

(Or a screencast - https://www.loom.com/)

**Comment by louisreingold** [comment]
Thanks for the report. We have an open issue about this so I'm closing this one.

**Comment by andrija-naglic** [comment]
This is the opened issue: https://github.com/soflyy/breakdance-bugs/issues/81
