### ISSUE TITLE
Section background shows always the same featured image in loop builder

### ISSUE THREAD

**Issue by etjallings** [soflyy/breakdance-bugs#226]
![image](https://user-images.githubusercontent.com/110063773/184493274-ac6cd0a7-6d77-4c45-884d-e63801057610.png)
I build a new global block with a section that display the post featured image as background image. Want to create a sort of  hero. But when adding the block to page with loop builder, it shows the same image for every post.

In the css(chrome inspect element) is can see the other image is loaded. Because both posts have the same css class for the section, it is not working correctly. Think each section needs its own unique css class.  And then make sure the correct css is generated to attach the background image to the correct section.
![image](https://user-images.githubusercontent.com/110063773/184496327-df920ea1-27e9-428c-b64e-9e48a761ad01.png)

**Comment by louisreingold** [comment]
As a workaround for now, I would advise using an absolutely positioned Image element and z-index.

A fix for this is being investigated for 1.1, but it is unlikely to make it into 1.0.

**Comment by louisreingold** [comment]
Same problem: https://www.facebook.com/groups/breakdanceofficial/posts/5330178473684071/ - lightbox script doesn't work inside Loop Builder because class names are duplicated.

**Comment by louisreingold** [comment]
We actually solved this issue and the one mentioned on Facebook in beta 11, but I'm still leaving the "beta" warning label on Post Loop Builder. If you encounter further problems, please report them.
