### ISSUE TITLE
Can't Select Post Featured Image Size in Global Block

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#227]
In beta 7, I am inserting a post featured image element in a global block.  Upon doing so, the image size dropdown is disabled.

https://www.awesomescreenshot.com/image/31348371?key=ab1d41034d5f2008c1ede42a53e3e7ad

As a result, the image on the frontend is the full resolution image and also does not have the srcset attribute.

**Comment by louisreingold** [comment]
Fixed.
