### ISSUE TITLE
Builder doesn't work anymore after updating to 1.0.0-alpha.3

### ISSUE THREAD

**Issue by mirkoschubert** [soflyy/breakdance-bugs#23]
After updating the breakdance plugin from 1.0.0-alpha.1 to 1.0.0-alpha.3 the builder doesn't work anymore. If you open any page, template, header or footer you always get a blank page with a PHP error message (see screenshot).

I use WordPress 6.0 with PHP 8.0. It seems that you moved the loader directory to a new place and even though the relative path to the manifest.json looks correct to me the system doesn't recognize it.

**To Reproduce**
1. Update the breakdance plugin from 1.0.0-alpha.1 to 1.0.0-alpha.3
2. Open any page, template, header or footer in the breakdance builder
3. See error

**Screenshot**
<img width="1368" alt="screenshot 2022-06-25 at 10 20 22" src="https://user-images.githubusercontent.com/6443573/175765286-d5699aa6-7848-4967-8e9b-5d1b9ce7fd47.png">

**Comment by mirkoschubert** [comment]
**Update:**
I have tested it now for the alpha.2 and the builder is working there. So do not update to alpha.3 for now!

**Comment by louisreingold** [comment]
Alpha 3 was a mistake, it wasn't supposed to be released. Sorry!
