### ISSUE TITLE
Internal Server Error - ACF gallery

### ISSUE THREAD

**Issue by Kenneth-web-1** [soflyy/breakdance-bugs#231]
Gives an error when im trying to add ACF gallery

![Screenshot_1](https://user-images.githubusercontent.com/111271450/184594303-bcd437aa-bea9-44dd-8c7a-6e5b2feb97bb.jpg)

**Comment by louisreingold** [comment]
This will be solved in beta 8. Instead of choosing Custom Field you will choose the actual ACF gallery field in the dynamic data dialog box.
