### ISSUE TITLE
WP Menu element - can't change link color for dropdowns

### ISSUE THREAD

**Issue by AJJ444** [soflyy/breakdance-bugs#232]
Can not change link color in:
WP menu/ Desktop menu/ Dropdowns/ Links/ Title/ Color.

Nothing happens when I change the color.

Can only change this color in Gobal settings/ Color/ Brand or Link.

Best regards
Allan

**Comment by louisreingold** [comment]
Significant enhancements to the menu element shipped between the date this issue was originally reported and now. I'm not able to reproduce this with a current version of Breakdance.
