### ISSUE TITLE
Post permalink in dynamic link is not rendering correctly

### ISSUE THREAD

**Issue by gdewey** [soflyy/breakdance-bugs#233]
creating an archive loop and need a button to go to post detail (woo product)

adding a POST PERMALINK dynamic variable to button does not render right.  see

https://www.dropbox.com/s/7w7a9s7j8lrjeyh/2022-08-15_10-01-32.png?dl=0

this is my output on the rendered page
https://bd.ofik.com/product-category/sillas/[breakdance_dynamic%20field='post_permalink']

the shortcode does not render.

**Comment by louisreingold** [comment]
Thanks for the report. I've fixed this and the fix will ship in beta 8.
