### ISSUE TITLE
Header styling fails

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#236]
Hi, the styling of my header is wrong in the frontend and the backend in all pages except for in the header editor.

Please see
https://www.loom.com/share/bc6a21574ede4f24b90a5ef8889b27c9

Missing styling:
Margin-right: auto on logo
Search icon background
Account icon size
Cart amount should not be displayed.

Could be same issue as https://github.com/soflyy/breakdance-bugs/issues/197

**Comment by louisreingold** [comment]
I can't reproduce this. Please email support@breakdance.com with your WP admin login details.
