### ISSUE TITLE
woocommerce pagination not working

### ISSUE THREAD

**Issue by gdewey** [soflyy/breakdance-bugs#238]
pagination is returning a 404 .. see https://bd.ofik.com/categoria/mobiliario/

this is done making a loop over a global block on woo products.  btw, the query is missing "current taxonomy" on the query builder. there is no way to filter unless we make a mannual query. 

tks

**Comment by louisreingold** [comment]
We fixed pagination for the Post Loop Builder in beta 9.

We also removed the need to set a custom query in the query builder when the Post Loop Builder is used on any archive page. The correct query is now autodetected.
