### ISSUE TITLE
zlib.output_compression must be disabled to be able to edit template

### ISSUE THREAD

**Issue by Anticosti** [soflyy/breakdance-bugs#239]
Just noticed that **zlib.output_compression** must be **disabled** otherwise you get errors and locked out, when trying to edit a template.
Noticed this while I was trying to configure **Matomo Analytics** plugin which requires :
You need to set "zlib.output_compression" in your php.ini to "Off".

Does this makes sense?

**Comment by Anticosti** [comment]
![Screen Shot 2022-08-16 at 19 03 45](https://user-images.githubusercontent.com/5446224/185001186-a4b7a116-c187-4b2e-9927-044988e2c9f3.png)
![Screen Shot 2022-08-16 at 19 03 55](https://user-images.githubusercontent.com/5446224/185001202-8bbaf0a6-fd92-4cea-8df7-95159d1ffdea.png)

**Comment by Anticosti** [comment]
Finally deactivated Matomo and now I can edit my templates :)

**Comment by louisreingold** [comment]
Closing as this sounds like a server configuration error unrelated to Breakdance.

I would never use a plugin that requires me to edit my PHP configuration and I wouldn't recommend anyone else does either.
