### ISSUE TITLE
Safari Mac I don't see admin panel for templates

### ISSUE THREAD

**Issue by krstivoja** [soflyy/breakdance-bugs#24]
<img width="2491" alt="Screenshot 2022-06-25 at 12 00 09" src="https://user-images.githubusercontent.com/1234350/175768720-2f731227-2bf0-43ca-822d-0182febad6d5.png">

**Comment by daguob** [comment]
This is not just the Breakdance template. Except for the Breakdance Home tab, all BD plugin tabs and the BD editor are all white screens (inside WP) for Safari. But it displays on Firefox and Chrome in the same local environment.

**Comment by nick-s5** [comment]
Same here, nothing of Breakdance loads in Safari. All work on Chromium browsers though (I personally use Edge on my Mac when necessary).

**Comment by louisreingold** [comment]
This is solved.
