### ISSUE TITLE
Animated Heading > Unpredictable behavior

### ISSUE THREAD

**Issue by Anticosti** [soflyy/breakdance-bugs#241]
When creating an Animated Heading you never know if you will be able to edit again once you closed Breakdance editor.

 https://www.loom.com/share/ef25efb9048b466d82ca74ef27ee90da

**Comment by louisreingold** [comment]
Please email support@breakdance.com with your WP admin login details and we'll take a look.

**Comment by Anticosti** [comment]
Logins sent

**Comment by Anticosti** [comment]
Knowing that it works on your side.... My bad. I took a chance to try it with Google Chrome instead of Firefox and... it works. I then went back to Firefox and tried again suspecting it had something to do with my Security preferences/settings...
Swap the setting from **Strict** to **Standard** and then.. Boom! It works.
At least we got it elucidated.

**Comment by Anticosti** [comment]
![Screen Shot 2022-08-22 at 15 23 57](https://user-images.githubusercontent.com/5446224/186004662-2344670f-2bd1-4e52-9347-c6b67f1ef1c7.png)
