### ISSUE TITLE
Sticky Header overlays the content

### ISSUE THREAD

**Issue by marcel2008** [soflyy/breakdance-bugs#245]
When setting the header to sticky it overlays the content.

https://www.loom.com/share/1596a856d80a4d9cad1cf88395065eca

I guess thats what is supposed to happen when setting the header to overlay, not sticky.

**Comment by louisreingold** [comment]
That's what's supposed to happen for both, otherwise the page would jump when the sticky header moved in and out of view without hacky JavaScript that adds margin on the body tag (which is not desirable).

**Comment by marcel2008** [comment]
So how would you recomment to get the first section just below the header? What would be the right approach?

**Comment by louisreingold** [comment]
Add padding to the section.

**Comment by thekendog** [comment]
I too am having this issue.  I see that the sticky header has a position:fixed on it which is causing the issue.  Why not use position:sticky?  That seems to solve the issue.

**Comment by louisreingold** [comment]
Because that will cause countless other issues. We thoroughly considered all possible ways to build this and decided on the way we did because all the other ways were worse. When you try to build an element that can support nearly every possible use case, trade offs need to be made.

**Comment by thekendog** [comment]
@louisreingold makes sense.  I guess I can just put it in my stylesheet for my own personal use.
