### ISSUE TITLE
Learndash incompatibility

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#246]
1. Can't apply template for Focus Mode
2. Some Learndash shortcodes don't work, e.g. [ld_topic_list]. Error:
```
learndash_course_step_available_date(): Argument #2 ($course_id) must be of type int, string given, called in /www/htdocs/w00b969e/go.helmutberger.life/wp-content/plugins/sfwd-lms/themes/ld30/templates/topic/partials/row.php on line 59
```

Reported by user via ticket #195 in the support desk.

**Comment by louisreingold** [comment]
> Can't apply template for Focus Mode

Please elaborate.

**Comment by louisreingold** [comment]
Please open a new issue for Focus Mode.

The other error is coming from a LearnDash plugin file, not Breakdance.
