### ISSUE TITLE
Cannot Load Custom Stylesheet After Breakdance Styles

### ISSUE THREAD

**Issue by bmc38119** [soflyy/breakdance-bugs#247]
Referencing the following post on FB Group:
https://www.facebook.com/groups/breakdanceofficial/permalink/5327866970581888/

Please either correct the current hook functionality or add custom hook to allow custom stylesheet to be loaded following the Breakdance styles. 

**Preference would be use the native WP Hooks.  I use WP Codebox for SASS stylesheet generation and these use the standard WP hooks for loading (and real-time refresh during dev).**

**Comment by louisreingold** [comment]
I can't reproduce this. I checked our hook priority. Here's how Breakdance loads its styles:

```php
    add_action(
        'wp_head',
        function () {
            echo BREAKDANCE_HEADER_ASSETS_PLACEHOLDER;
        },
        1000000
    );

    add_action(
        'wp_footer',
        function () {
            echo BREAKDANCE_FOOTER_ASSETS_PLACEHOLDER;
        },
        1000000
    );
```

If you use a priority above `1000000` and still encounter problems, please paste the exact code you are using.

**Comment by bmc38119** [comment]
@louisreingold Thanks - I used a number higher than 1000000 and still no luck. I am using WPCodebox for my custom code and scripts (and I am sure many future BD users will be as well).  I will supply this to the developer to see if they can determine the issue.  Thanks for supplying the BD code.

**Comment by louisreingold** [comment]
Paste the exact code you are using here and I will test it.

**Comment by bmc38119** [comment]
I have reached out to the developer of WP Codebox.  For the SCSS compiler (and live reload) feature, you do not specify the hook and priority in the code - but enter the parameters into the UI - so I need to understand how they are enqueuing the script and priority.  I ran a manual test using the code you provided above and 1000001 priority - and my test script was placed below the BD script - so this does not appear to be an issue with BD.

**Comment by Hakira-Shymuy** [comment]
add_action( 'wp_enqueue_scripts', 'custom_enqueue_files' );

function custom_enqueue_files() {
    wp_enqueue_style( 'hakiracss', plugin_dir_url( __FILE__ ) . 'assets/style.css', '', '1.0.0', 'all', 1000010 );
}

does not work

 add_action( 'wp_enqueue_scripts', 'custom_enqueue_files' );

function custom_enqueue_files() {
    wp_enqueue_style( 'hakiracss', plugin_dir_url( __FILE__ ) . 'assets/style.css', '', '1.0.0', 'all', 999999999 );
}

does not work

from what i understand the issue remains????
