### ISSUE TITLE
Image box content position 

### ISSUE THREAD

**Issue by mohammadrony16** [soflyy/breakdance-bugs#251]
When I try to make the image box content position type middle - I select the middle option but it didn't work. 
![Screenshot (8)](https://user-images.githubusercontent.com/111675093/185777365-1d82d225-5ae7-48d8-840e-6ebcd8653fdd.png)

**Comment by louisreingold** [comment]
Will be fixed in beta 12. For now, just clear the Content Position field and set it again.
