### ISSUE TITLE
UI idea - auto focus text input when add list item

### ISSUE THREAD

**Issue by fadlee** [soflyy/breakdance-bugs#253]
Currently, when I click Add Item button on the List element (basic and checkmark), input text is not focused automatically.

I need to click text input manually before typing...

**Comment by fadlee** [comment]
When Add Item position is on the bottom of the screen, I need extra step to input the text, input text is not visible without scrolling

**Comment by louisreingold** [comment]
This may be addressed as part of a larger UX change initiative.
