### ISSUE TITLE
Conditions - Show hide element not working

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#255]
Please refer to this thread in FB group.
https://www.facebook.com/groups/breakdanceofficial/permalink/5327911107244141

I want to be able to hide my light logo on the home page. I use the "Home URL" condition, it does hide the logo but also for other pages. It's not showing.

None of these conditions worked
![image](https://user-images.githubusercontent.com/51177627/185781363-ce637f3a-8585-410e-9b26-4cc70424fb69.png)

**Comment by louisreingold** [comment]
Solved in a recent beta. You can now use "Page is / Page is not" (and all other conditions) in Headers, Footers, and Global Blocks.
