### ISSUE TITLE
ACF Repeater

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#257]
I have an itinerary ACF repeater field
![image](https://user-images.githubusercontent.com/51177627/185788734-efd9f7ab-02fc-417b-87ad-fb2de61cf34b.png)

But I'm not sure if the ACF repeater is supported or not yet. cause for the life of me I can't find it.

![image](https://user-images.githubusercontent.com/51177627/185788695-d139e0c8-cabb-40d3-9b88-5996d4026b0f.png)

**Comment by louisreingold** [comment]
Closing in favor of the feature request: https://breakdance.canny.io/features/p/custom-fields-plugins-repeater-support
