### ISSUE TITLE
Popups - entrance animation plays before popup is opened (resulting in overlay appearing when it shouldn't)

### ISSUE THREAD

**Issue by marcel2008** [soflyy/breakdance-bugs#259]
I have set up a popup thats triggered with a button in the header.
The popup has an overlay color wich is visible on page load for half a second or so. Also the entrance animation is not working in the frontend.

https://www.loom.com/share/a200e3e0f8b146b893bdfcd0844575fa

**Comment by louisreingold** [comment]
Can you email support@breakdance.com with your WP admin login details and we'll take a look? We tried to reproduce this locally but we couldn't do so.
