### ISSUE TITLE
Header Builder Flex controls not working

### ISSUE THREAD

**Issue by djrwp** [soflyy/breakdance-bugs#262]
Flex controls in Header Builder don't seem to have any effect. Whatever wrapper setting I use 'space-around', 'space-between' etc, nothing changes.

https://www.loom.com/share/57288bbb995e4c88bd46466a4348e687

**Comment by djrwp** [comment]
Upon further investigation maybe this isn't a bug but intended behaviour? I'm guessing flex is already built into the header builder by default? It seems I can control items by using the flex child controls. It would be good if this could be confirmed?

**Comment by louisreingold** [comment]
> I'm guessing flex is already built into the header builder by default? It would be good if this could be confirmed?

Yes. The inner wrapper is already `display: flex;` by default.

Header Builder contains two HTML elements - the outer wrapper (full width), and the inner wrapper (section width). The children of the header builder are in the inner wrapper.

For all elements, the Wrapper styles apply to the outermost HTML element.

I find the most efficient way to build headers that contain more elements than just a logo and a menu is to put the elements I want to group inside a div. Then I can use the layout controls on the div.

There will be a tutorial on our YouTube channel in the coming days that shows an example of this.
