### ISSUE TITLE
Form Builder -> Layout -> Vertical At - doesn't work properly

### ISSUE THREAD

**Issue by andrebeltrame** [soflyy/breakdance-bugs#263]
**Edit by Louis with repro: https://www.loom.com/share/2ff8375136624cad8a13749b7770f44c**

Original report:
Vertical / Horizontal and (vertical at ) is not workin as expected, it's always the same.

**Comment by joethseo** [comment]
I'm getting a related issue where changing the container width doesn't get saved for each breakpoint. Instead, all breakpoints are overwritten by your last change. See here:

https://www.loom.com/share/52260100ed4342ceace6e678e88b999f

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
