### ISSUE TITLE
Copy and Paste and Paste Design will not work on my install of Breakdance Beta 9 using Firefox on Mac

### ISSUE THREAD

**Issue by MickDJ** [soflyy/breakdance-bugs#264]
Screencast https://share.vidyard.com/watch/GJwqZZNvZcdB5FF3jmSN15 

Issue is when using Firefox 103.0.2 on Mac, issue does not happen when using Chrome where it works fine

**Comment by Spellhammer** [comment]
I was also able to reproduce this issue using Firefox on MacOS.

**Comment by louisreingold** [comment]
We think we solved this in beta 10. @Spellhammer please re-open if this still happens.

**Comment by MickDJ** [comment]
Hi, I can confirm this has been fixed, thank you 

 

From: Louis Reingold ***@***.***>
Reply to: soflyy/breakdance-bugs ***@***.***>
Date: Saturday 27 August 2022 at 22:44
To: soflyy/breakdance-bugs ***@***.***>
Cc: MickDJ ***@***.***>, Author ***@***.***>
Subject: Re: [soflyy/breakdance-bugs] Copy and Paste and Paste Design will not work on my install of Breakdance Beta 9 using Firefox on Mac (Issue #264)

 

We think we solved this in beta 10. @Spellhammer please re-open if this still happens.
