### ISSUE TITLE
Search returning incorrect query

### ISSUE THREAD

**Issue by justingluska** [soflyy/breakdance-bugs#266]
https://user-images.githubusercontent.com/53244307/186187538-5fefe25b-923e-4463-b885-557d0231106c.mov

**Comment by tommytompkins** [comment]
I think this might be related to this issue. What I found is that if I have a search results template with a custom query on the Post List, the custom query does not work after the search is submitted and it returns no results. If I remove the custom query, it works.

**Comment by rodolphebertozzo** [comment]
@louisreingold @a-dubiel Status ? It seems that the same of this : https://github.com/soflyy/breakdance-bugs/issues/779

**Comment by louisreingold** [comment]
Thanks for the report. This is addressed in Breakdance 1.6, along with many other search enhancements.

Set the post type you want to query on your search results form, leave the query as is on the search results page, and it'll work.

Demo: https://www.youtube.com/watch?v=NVbPxRuTxPY

> 
> Enhanced Search with WooCommerce & Custom Post Type Support
> In this update, we’ve supercharged the Breakdance’s Search Form element.
> 
> Search WooCommerce Products & Custom Post Types
> Now, you have the power to refine your search results even further. With the new update, you can add an option in the Search Form element to display results from a specific post type. This means if you want your users to only see blog posts or product listings or any other custom post type in their search results, you can easily set that up.
> 
> Combine search with Breakdance’s elements for WooCommerce filtering
> The Breakdance Search Form element seamlessly works hand-in-hand with our specialized elements for WooCommerce filtering. When users navigate through your WooCommerce store, they can effortlessly filter and refine their search results. Whether they’re looking for a particular product category, price range, or other attributes, our search functionality streamlines the shopping experience, guiding users to their desired products with ease.
> 
> In our recent update, we’ve bolstered the connection between the Breakdance Search Form element and our specialized elements for WooCommerce filtering. This enhancement ensures that when users browse your WooCommerce store, they can effortlessly filter and refine their search results. Be it a specific product category, price range, or other attributes, these filters can be integrated with the search results page users are taken to after searching with the upgraded Search Form Element. Our upgraded search functionality streamlines the shopping experience, making product discovery straightforward and efficient.
> 
> 
> 
> Smoothly integrate with third-party plugins like FacetWP and WP Grid Builder for added filtering capabilities
> The Breakdance Search Form element is designed to integrate with popular third-party plugins, specifically FacetWP and WP Grid Builder. This integration provides users with enriched filtering capabilities, ensuring that they can access more refined and precise search results.
> 
> Accessibility Improvements for the Search Form
> We believe in creating a web that’s accessible to all. To this end, we’ve addressed and fixed the A11Y issues related to the Search Form, ensuring no duplicate IDs and adding missing a aria-label. This not only enhances the user experience for those using screen readers but also makes it easier to ensure your website is compliant with accessibility standards.
>
