### ISSUE TITLE
Install in a /public_html/2022 subfolder (even with subdomain) causes directory creation issue

### ISSUE THREAD

**Issue by helpwise** [soflyy/breakdance-bugs#269]
I installed Breakdance Beta 2, then replaced it with Beta 9 Breakdance immediately.

The existing cpanel based website is in /public_html

I created a sub folder called /public_html/2022 and copied the site and its database to facilitate a rebuild in breakdance from Divi.

THere was an error that said that some folders were not created so I hit the "CREATE FOLDERS" button and it went away, however non of the templates are able to be created.

![image](https://user-images.githubusercontent.com/29443705/186364787-bb13aa19-a7ea-401f-8c40-1ac2f87cb829.png)

**Comment by helpwise** [comment]
I suspect Breakdance has this issue due to the subfolder - it works fine in a root folder on another account.

**Comment by louisreingold** [comment]
Breakdance works in subfolders. Email support@breakdance.com with your WP admin login details and we'll take a look.
