### ISSUE TITLE
Piricng Table (Text Alignemnt & Feature Added)

### ISSUE THREAD

**Issue by artur-burkalo** [soflyy/breakdance-bugs#270]
When the text expands to the second line in features, it centres, unless the layout is set to left or has no width set, then it expands.

<img width="677" alt="Screenshot 2022-08-24 at 10 03 07" src="https://user-images.githubusercontent.com/63022491/186377762-14053522-fa86-4ed3-b033-18e7920aa6f9.png">
The badge is also limited in styling and could have a border-radius. 

<img width="687" alt="Screenshot 2022-08-24 at 10 05 14" src="https://user-images.githubusercontent.com/63022491/186378104-4efb6e0a-6f97-4be1-983c-684dfa8e5e47.png">

**Comment by artur-burkalo** [comment]
Reviewed Beta 10, border radius to the badge is added. 

Text position to centre still happens, when the pricing table container can't expand.

**Comment by louisreingold** [comment]
Thanks for the report. I added `text-align: left;` to the default CSS for the feature list items. It'll be available in the next update.
