### ISSUE TITLE
Weglot translated pages have broken styling, console errors.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#271]
Reported by a user via support desk.

Visiting the /en/ version of the user's home page resulted in completely broken styling and the following console errors.

![image002](https://user-images.githubusercontent.com/8459002/186415161-56e6acfc-01e8-4a14-85c1-31dd4974a382.png)

**Comment by louisreingold** [comment]
@Spellhammer we need login details for the site or a sandbox reproduction.
