### ISSUE TITLE
Logo List

### ISSUE THREAD

**Issue by ReflectedReality648** [soflyy/breakdance-bugs#272]
Adding a link to a logo in the logo list does not seem to work. Also I can't find anywhere to make the link open in a new tab

**Comment by louisreingold** [comment]
We fixed the logo list in beta 10. 

<img width="123" alt="Screen Shot 2022-08-27 at 3 11 11 PM" src="https://user-images.githubusercontent.com/6425257/187049687-057d68f4-0a64-4f01-971b-2bfce23efe2e.png">

<img width="284" alt="Screen Shot 2022-08-27 at 3 11 07 PM" src="https://user-images.githubusercontent.com/6425257/187049686-00b6b828-982a-408a-ab29-b805eab06daf.png">

(Click the pencil icon to open the popout)
