### ISSUE TITLE
Learndash Focus Mode not working

### ISSUE THREAD

**Issue by gatti-dev** [soflyy/breakdance-bugs#274]
If you create a template for Learndash Modules the focus mode do not appear.
You only got a empty page and you only can add dynamic post data.

**Comment by wpkorea** [comment]
Same to me.

**Comment by parfilov** [comment]
At 1.1 Beta 1 focus mode works almost fine. Global Breakdance font settings (families etc) dob't inherit to LearnDash focus mode theme.

**Comment by a-dubiel** [comment]
Hey @parfilov I am closing this for now. Feel free to open another issue for the typography.
