### ISSUE TITLE
Forms Padding Not Wroking

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#276]
After the Beta 10 update, the form's field padding stopped working. Forms input fields won't change their size.

![image](https://user-images.githubusercontent.com/54561285/186650479-85db96eb-f5bf-4daa-8af2-dc63d289551d.png)

**Comment by StefanPavlov23** [comment]
+1 

I was just going to report this. I can confirm that its not working.
