### ISSUE TITLE
Global setting - brand color - not recognized/working

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#277]
all of my primary btns, backgrounds or any element with a brand background/color is now transparent.
![image](https://user-images.githubusercontent.com/51177627/186695151-0a319d7b-1b2d-49d7-add0-23469d1344ac.png)

again this issue appears in all element using a brand color/background.
So far I only did regenerate CSS. no luck

**Comment by crsmoore** [comment]
This is the same issue as this other report: 

https://github.com/soflyy/breakdance-bugs/issues/275

**Comment by louisreingold** [comment]
This is fixed in beta 11, but because we changed the name of the CSS variable to use the `bde` prefix you'll have to reset any color picks you've set to use your "Brand" color.
