### ISSUE TITLE
Post list - title and button - now have text decoration as default? 

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#278]
so far this only happens in post list element
![image](https://user-images.githubusercontent.com/51177627/186695845-c36d8a33-3b42-46a6-98b8-322fbc35ad60.png)

**Comment by louisreingold** [comment]
Thanks for the report. This will be fixed for the post title in the next update. You can control the text decoration on the Read More link at Post > Button > Text > Typography.
