### ISSUE TITLE
Breadance transition duration is too snappy!

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#279]
--bd-transition-duration from 300ms to 60ms? 
![image](https://user-images.githubusercontent.com/51177627/186718259-34a115f5-d64e-46fb-99c2-5ee2fdf3c8d8.png)

Please, I think 300ms is a standard. :) 

The issue is very noticeable when using the header shrink animation. It feels snappy and looks like jumping

**Comment by louisreingold** [comment]
I searched our entire codebase for "60ms". It's not present in anything related to CSS.
