### ISSUE TITLE
WooCommerce Feedback from Ferdinand Nyarko

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#28]
Reposted from:

[Official Breakdance User Group](https://www.facebook.com/groups/5118076864894234/?hoisted_section_header_type=recently_seen&multi_permalinks=5183471378354782&__cft__[0]=AZXjGn4W1AkWGNIK93X6bvCDWK_wF11EbEt-2yEk22SOJTXgZgqBNSL9yq-WhRjQJsMWjdX27sr5mYz-t15QHznHoD0ThrtpNPwKi8TLhtYFFPCFf1o9szNww4PUi0-_baxloHcsP0yin_EyL1GFORYikjVO4pVhcmEqCjvOFBRVEsM55fJHzREmmXQvTTsTmeA&__tn__=-UC%2CP-R)
[Ferdinand Nyarko](https://www.facebook.com/groups/5118076864894234/user/100004945891868/?__cft__[0]=AZXjGn4W1AkWGNIK93X6bvCDWK_wF11EbEt-2yEk22SOJTXgZgqBNSL9yq-WhRjQJsMWjdX27sr5mYz-t15QHznHoD0ThrtpNPwKi8TLhtYFFPCFf1o9szNww4PUi0-_baxloHcsP0yin_EyL1GFORYikjVO4pVhcmEqCjvOFBRVEsM55fJHzREmmXQvTTsTmeA&__tn__=%2CP-R)  · 

- [x] Dynamic Content: The dynamic content does not work when you want to pull, let's say, a product image or gallery. If you try to pull the content dynamically, it will only show for one product that you manually have assigned. **Will be fixed in beta 5 or beta 6**

- [x] Stock levels: There is customization for out-of-stock items, but not the normal stock level. It can only be changed by using the typography option in the wrapper module in the advanced section. Which is not streamlined at all. **Will be added in beta 5**

- [x] Breadcrumbs: The breadcrumbs customization has a sort of bug in which if the length of the text is too long, the text breaks to the next line but pushes the top text up, which makes the text look like it has been centered which shouldn't be the case. **will be fixed in beta 5**

- [x] Shop Products: Can products have an aligned feature so it does not have to be left-aligned all the time? **will be added in beta 5 / 6**

- [x] Product List: When I add a product list to a page, I get an error that disables the page completely. The page can not be viewed on the front end but can be edited. This is not the shop page. **I was not able to reproduce this.**

- [x] Checkout Coupon Notification: The background color's height doesn't fit on mobile devices when the background color is applied. It covers only half of it. **Will be fixed in beta 5 / 6**

- [x] Checkout Coupon Notification: Text on mobile has a padding that cannot be removed.  **I was not able to reproduce this.**

**Comment by louisreingold** [comment]
> Dynamic content

I did find a bug with WooCommerce Product Gallery dynamic data (nice catch, thank you), but I wasn't able to reproduce the other issues you describedhttps://www.loom.com/share/a702b6b317af4ddd977c044a309c8ec1

**Comment by louisreingold** [comment]
> Product List: When I add a product list to a page, I get an error that disables the page completely. The page can not be viewed on the front end but can be edited. This is not the shop page.

What error? Please provide a screenshot.

**Comment by louisreingold** [comment]
> As there are no loop builders or repeaters in BD, making columns clickable is a must.

Here's how to make anything inside of a Section (including a Column) a link: https://www.loom.com/share/d1b3eee02a3044d0b18e46315491b319

**Comment by louisreingold** [comment]
@onenyarko

> Product List: When I add a product list to a page, I get an error that disables the page completely. The page can not be viewed on the front end but can be edited. This is not the shop page.

What error? Please provide a screenshot.

> As there are no loop builders or repeaters in BD, making columns clickable is a must.

Here's how to make anything inside of a Section (including a Column) a link: https://www.loom.com/share/d1b3eee02a3044d0b18e46315491b319

**Comment by louisreingold** [comment]
@onenyarko

> Product List: When I add a product list to a page, I get an error that disables the page completely. The page can not be viewed on the front end but can be edited. This is not the shop page. 

I was not able to reproduce this. If this still happens for you, please email support@breakdance.com with the URL to the page with the problem and your WP admin login details.

**Comment by onenyarko** [comment]
Hey Louis, below is a screenshot.

![pdt](https://user-images.githubusercontent.com/10132543/181130137-639b449a-7776-4e98-a274-3f5e43290d1e.png)

**Comment by louisreingold** [comment]
@onenyarko can we please get admin access to the site? That error has been reported a couple of times but we can't reproduce it locally.

**Comment by louisreingold** [comment]
@onenyarko 

> Checkout Coupon Notification: Text on mobile has a padding that cannot be removed. 

Please elaborate. I'm not sure which text you're referring to. I was able to remove the padding around all the text in the coupon notification / form.

**Comment by louisreingold** [comment]
We solved the issues listed in the fist post in this thread in beta 5.
