### ISSUE TITLE
"Featured Image" option missing from Dynamic Data dialog for Column element.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#280]
1. Add a Columns element
2. Select one of the individual Columns
3. Go to Background > Add Item
4. Choose Type > Image
5. Click the Dynamic Data button for the Image field
6. Note that the "Featured Image" option is not available

This could effect other elements as well.

**Comment by parfilov** [comment]
Thank for the issue. Here is the screenshot. Maybe it will help
![ScreenShot 25-08-2022_15 31@2x](https://user-images.githubusercontent.com/12493645/186737378-4a60bdbd-2173-4819-a6c5-a48673563196.png)

**Comment by parfilov** [comment]
Same issue with ACF image field. Tried to do temporary solution with it, but it doesn't work too.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
