### ISSUE TITLE
Wrong JS URL on Countdown Timer

### ISSUE THREAD

**Issue by brandontan903** [soflyy/breakdance-bugs#281]
When using Countdown Timer, frontend doesn't render it's animation.

Apparently the HTML output of the page has wrong JS URL of the Countdown Timer. Between `countdown-timer.js` and `?`  has space:

`<script src="https://mysite.com/wp-content/plugins/breakdance/subplugins/breakdance-elements/elements/Countdown_Timer/assets/countdown-timer.js  ?bd_ver=1.0.0-beta.10"></script>
`

**Comment by louisreingold** [comment]
Nice catch, thanks. This will be fixed in beta 12.
