### ISSUE TITLE
BETA 10: Post Loop Builder not working with Global block image box in it

### ISSUE THREAD

**Issue by Foolevil** [soflyy/breakdance-bugs#282]
An error occurred while running an inline script from "onPropertyChange" for element with ID "101". Error:"TypeError: window.BreakdanceSwiper is not a function" 
I seem to get this error from some other reason too???

Anyway: I can use featured image and content text, but cant get Post Title into Image Box title

**Comment by louisreingold** [comment]
> An error occurred while running an inline script from "onPropertyChange" for element with ID "101". Error:"TypeError: window.BreakdanceSwiper is not a function" I seem to get this error from some other reason too???

I can't reproduce this. Email support@breakdance.com with your WP admin login details and we'll take a look.

> Anyway: I can use featured image and content text, but cant get Post Title into Image Box title

I was able to set an Image Box's title to the Post Title: https://www.loom.com/share/4bd04d9b57a04805a9817a8eecc5fb6c
