### ISSUE TITLE
Minicart on product pages - .breakdance-woocommerce class causing width: 100%

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#284]
In beta 10 the header gets misformed on the product page.

Its because the .breakdance-woocommerce class is added to .bde-mini-cart and on the product page it gets width=100%

**Comment by FelipeMarcos** [comment]
@mikehenze, I couldn't reproduce this. 

- Do you have a screenshot for us?
- Does it happen for the Single Product page or the Shop/Product Archive Page?
- Does it still happen on the recent beta 11?

**Comment by mikehenze** [comment]
- Please see https://www.internet360.nl/jilsen/product/melanie-suede/
- Single product page
- Yes beta 11 also

**Comment by FelipeMarcos** [comment]
Thanks, I've managed to reproduce the issue. This should be fixed in the next beta.

**Comment by mikehenze** [comment]
This seems fixed in beta 12, thanks
