### ISSUE TITLE
Loop builder Load more and Infinite scroll - ACF fields don't work

### ISSUE THREAD

**Issue by parfilov** [soflyy/breakdance-bugs#285]
ACF fields doesn't loads inside ajax loaded loop elements. The first "page" (Posts per page query option) elements works good, but the next "pages" elements loads without any data.

**Steps to reproduce:**

1. Create Global block for Loop Builder
2. Add some elements to show dynamic data from ACF fields
3. Put The Post Loop Builder in static page (not archive)
4. Set the Query:  Posts per page — 4;  Total posts — 30
5. Select pagination Infinite Scroll or Load more

**Comment by louisreingold** [comment]
We can't reproduce this. Can you email support@breakdance.com with your WP admin login details so we can take a closer look?
