### ISSUE TITLE
Upgrade Path

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#286]
Since testing breakdance I've never been able to upgrade straight from the WordPress dashboard . I have to delete the plugin and then reupload the new one. 

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/7070435/186924457-734894fd-c10e-4ae1-92b1-756b6fecef2b.png">

**Comment by louisreingold** [comment]
For now, download and install the beta manually. The problem is with our website breakdance.com, not the Breakdance plugin itself.
