### ISSUE TITLE
Popup Not Working on Mobile When Entrance Animation is Set

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#287]
Popups stop working (on click) on mobile after I set the entrance animation. When removed, popups work as they should.

**Comment by louisreingold** [comment]
We tried to reproduce this but weren't successful. Can you please email support@breakdance.com with your WP admin login details so we can take a closer look?

**Comment by NaoufelTarchoul** [comment]
> We tried to reproduce this but weren't successful. Can you please email [support@breakdance.com](mailto:support@breakdance.com) with your WP admin login details so we can take a closer look?

Sure I'll.
