### ISSUE TITLE
Menu Builder element default font size is hard-coded

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#288]
Hi, the default font size of the menu builder element has been hard-coded to 14px. The consequence is that changing the typography base size in the global settings does nothing to the font-size used in the menu builder element.

![CleanShot 2022-08-26 at 20 42 17@2x](https://user-images.githubusercontent.com/7188497/186971097-3309d725-c0a4-4f72-9bd2-153ce6b00015.png)

**Comment by louisreingold** [comment]
This will be solved in the next release.
