### ISSUE TITLE
When styling a button I am missing color options for the icon

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#290]
Is this a bug or not, I'm not sure, but I can't set a color for the icon on a button. Would be nice to have because you can achieve some nice graphic touches with it.

On a sidenote:
- In general, in the current implementation, if you go past the straightforward, simple primary/secondary buttons, you quickly end up in a cumbersome workflow. I go past this rather quick. Even the custom BD classes seem to target as much, so you end up having to write custom CSS real quick.
- I can set the text and URL for each button regardless if it is a primary button and so on, but I cannot pick another icon. IMHO the specific chosen icon is content just like the text/url and it would be nice if it were changeable, the rest is design and can stay global (color, size, padding, ...)
- I'm also missing a way to have multiple global styled buttons: inverted primary, button with only outline and no background, a less important one (usually in a neutral gray color), ...

**Comment by dancerist** [comment]
+1

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
