### ISSUE TITLE
Version Beta 11 just totaly broke the site (?):  Warning: Undefined array key "name" in renderer.php on line 863

### ISSUE THREAD

**Issue by Foolevil** [soflyy/breakdance-bugs#291]
SOLVED! I MySql version 8 did not do good!
Using 7.41 

Warning: Undefined array key "name" in /Users/kidthecat/Local Sites/breakdance-play-elements/app/public/wp-content/plugins/breakdance/plugin/render/renderer.php on line 86

![Screenshot 2022-08-27 at 13 54 35](https://user-images.githubusercontent.com/246077/187027090-e004f28b-b2c1-43fa-a3e5-adb8d2657f2a.png)
3

**Comment by louisreingold** [comment]
I can't reproduce this. It is very unlikely it has anything to do with your MySQL version. If it happens again, please email support@breakdance.com with your WP admin login details and we'll take a look.

**Comment by dgz61** [comment]
I got the same problem after migrating a site from wplocal to "real" hosting. Both, with all-in-one WP Migration and with Duplicator. The migrated site needs custom fonts to be freshly loaded. Then it looks ok in the back-end. But the front-end is a complete mess still. Will send you access info.
