### ISSUE TITLE
z-index issue Sale Badge on WooCommerce Product Image element overlaps Menu Builder dropdown (when displayed as off-canvas / flyout)

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#293]
The sale badge (and other elements such as slider) overlap the sidebar menu and cart as shown in the photo:

![IMG_20220827_152049](https://user-images.githubusercontent.com/54561285/187034474-d29ffa0c-df6f-4567-b71c-db832af25e03.jpg)

**Comment by NaoufelTarchoul** [comment]
Please note that it's not only the Sale badge, other elements are affected as well. The slider for example.

**Comment by FelipeMarcos** [comment]
@NaoufelTarchoul I couldn't reproduce this. 

1. Could you please share a link to your website?
2. DId you set the z-index manually by any chance?

<img width="403" alt="Screen Shot 2022-08-29 at 16 33 00" src="https://user-images.githubusercontent.com/3706755/187283272-28e3a68a-d5e4-45f6-a355-0062032fbac6.png">

**Comment by louisreingold** [comment]
@NaoufelTarchoul email support@breakdance.com with your WP admin login details and we'll take a look.

**Comment by NaoufelTarchoul** [comment]
@louisreingold 

Email sent with login credentials and a list of bugs to take a look at
