### ISSUE TITLE
Shape divider: "Display in front of content" affecting section content (in editor only)

### ISSUE THREAD

**Issue by brandontan903** [soflyy/breakdance-bugs#297]
_(Wordpress 6.0.1, Breakdance 1.0.0-beta.11)_

It happen only when editing in the BD editor. If turning-on the "Display in front of content", the content affected in some way.

When viewing on frontend, it just fine

https://www.loom.com/share/d76f0cd1801a4957a8a43fb52facf093

**Comment by louisreingold** [comment]
Reproduced: https://www.loom.com/share/7c4e3a7ea92540a9995b4cc75f64fbe1

**Comment by a-dubiel** [comment]
This has been fixed in the latest 1.1 Beta
