### ISSUE TITLE
Comment Form - Spacing & SSR

### ISSUE THREAD

**Issue by artur-burkalo** [soflyy/breakdance-bugs#298]
Comment form spacing margin top and bottom does not work.

Once it's dragged, the comment box disappears and %%SSR%% shows on the back end, works fine on the front end.

**Comment by louisreingold** [comment]
Thanks for the report. I've fixed the margin drag bar bug and it will be available in the next release.

I wasn't able to reproduce the %%SSR%% issue. Please let me know if this still happens for you in the next release.
