### ISSUE TITLE
Udating Plugin Issues

### ISSUE THREAD

**Issue by base-74** [soflyy/breakdance-bugs#299]
Hi,
I always have issues when updating Breakdance from WP Dashboard, as you can see in the image. I always need to upload files manually from File Manager or FTP.
This is a staging site without https (FYI).
Hosting is: Hostinger Cloud Plan

PS. Other plugins update with no problems.

Chris

![updateIssue](https://user-images.githubusercontent.com/112316868/187067425-2cee2ac1-8108-4d09-9eb0-63c23c3f55a4.jpg)

**Comment by louisreingold** [comment]
Thanks for the report. This is an issue with our website breakdance.com, and not the plugin. We are aware of it and will address it.
