### ISSUE TITLE
403 Foridden Error

### ISSUE THREAD

**Issue by alivemediadev** [soflyy/breakdance-bugs#3]
I am receiving a 403 forbidden error message for many of the left nav options. Here are the ones affected:
Templates, Headers, Footers, Global Blocks, and Popups. The others work fine. 

Reproduce:
After installing the plugin, I am unable to view any of the above listed pages. I am using SiteGround for web hosting. Running WordPress 6.0. 

<img width="1353" alt="Screen Shot 2022-06-22 at 4 43 32 PM" src="https://user-images.githubusercontent.com/2434787/175133100-7fbeb500-fe95-4eeb-b535-c438a24bba9f.png">

**Comment by alivemediadev** [comment]
I am also getting the same 403 error message when trying to open the Breakdance editor.

**Comment by Grezvany13** [comment]
Looks like it's related to #7, meaning your hosting prevents direct PHP execution from the wp-content directory (as it should).
