### ISSUE TITLE
Code Block element - error when typing if Code Block contains CSS selector with psuedo-element

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#301]
https://www.loom.com/share/af8cb8f53d1047e7924a40b6720054e3

The error shows up every time I type. This only happens if I add a pseudo-element to my class using a codeblock.
![image](https://user-images.githubusercontent.com/51177627/187125713-1fa54b1a-42d4-4931-af82-2cff5782d938.png)

**Comment by Dancerist** [comment]
but my styles seem to be working on the front end.

**Comment by louisreingold** [comment]
@Dancerist please post a screenshot of the entire UI here so I can see exactly what is happening.

**Comment by Dancerist** [comment]
@louisreingold   https://www.loom.com/share/af8cb8f53d1047e7924a40b6720054e3

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
