### ISSUE TITLE
Beta 11 - heading margin-block-start and margin-block-end

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#306]
I've upgraded my live site from beta 7 to beta 11 and now headings seems to have a default 1 em margin-block-start and end. This is not a heading used in a rich text element (where the margin-blocks need to be present), but just a regular h3 rendered from within a code block. IMHO this does not need any margin or padding applied by default. Isn't the gap meant for this functionality?
![CleanShot 2022-08-30 at 20 01 45](https://user-images.githubusercontent.com/7188497/187510975-65ae9e4b-ebc1-4fd8-b855-ffeac658ffeb.png)

BTW, how long does it take before beta 11 expires? It was only by accident that I found that the website was completely broken due to expiring of beta 7. Is it possible to prevent this expiration?

**Comment by a-dubiel** [comment]
This is the default browser CSS which affects spacing. You can address this using Global Settings.
