### ISSUE TITLE
Bug in Recaptcha

### ISSUE THREAD

**Issue by alemacielsilva** [soflyy/breakdance-bugs#308]
The Recaptcha feature is buggy and causes an error when trying to submit a form. Both in the API Keys screen and in the Custom function of the form, the Recaptcha does not work and causes an error in the submission. Error reported: '**[reCAPTCHA] Error retrieving token.**'

https://www.loom.com/share/cd719f6949694bda8f36b5dbd4d9db52

Message returned when entering Site Key and Secret Key in APIs screen:

![form 2 - Recaptcha não funciona 2](https://user-images.githubusercontent.com/21241956/187568226-4428c035-b190-4957-b7f3-e2ef88fff9e6.png)

**Comment by louisreingold** [comment]
This is fixed in beta 12.

**Comment by alemacielsilva** [comment]
Hi Louis. Are you sure? I did tests on two sites, with two different keys and the same problems reported above continue (using Beta 12). Prints taken today on one of the sites.

![rec 01](https://user-images.githubusercontent.com/21241956/187906920-4d57429c-e757-4a6e-988f-95c54fa26296.png)

![rec 02](https://user-images.githubusercontent.com/21241956/187906944-fd86327e-b47a-4737-98a5-c36ea39943d6.png)

**Comment by louisreingold** [comment]
Email support@breakdance.com and we'll take a look.

**Comment by Spellhammer** [comment]
@louisreingold Confirming I'm able to repro this issue on the RC in my local dev environment.

After adding recaptcha site/secret keys at Breakdance > Settings > API Keys, the "Default" recaptcha API key option results in the "[reCAPTCHA] Error retrieving token" error, but using the same exact site/secret keys via the "Custom" option works fine.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
