### ISSUE TITLE
Menu - Hiding by custom Breakpoint

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#311]
At the moment you can't choose your custom breakpoints inside the (advanced) menu builder to hide it (and make it a breadcrumb). 

The custom breakpoint.
<img width="316" alt="Schermafbeelding 2022-08-31 om 10 48 44" src="https://user-images.githubusercontent.com/56388399/187639241-8df9331e-0dd8-4e9e-b870-7dd145c7fc47.png">

The hide/show option.
<img width="270" alt="Schermafbeelding 2022-08-31 om 10 44 58" src="https://user-images.githubusercontent.com/56388399/187639381-b69a1cfa-5917-4d64-a6f5-857ca31e0aa6.png">

PS: don't know if it is a bug or a feature request, else I can place it at canny.

**Comment by JeusuDigital** [comment]
Also just noticed this, would make sense for them to be in there.
As a work around you can hide the elements using custom CSS for the particular breakpoint and display: none.

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been included in Breakdance 2.1 Beta 1.
