### ISSUE TITLE
Display flex wrap issue

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#314]
Hi,

Currently (beta 12) there is an issue with the display flex. The default now is flex-wrap: wrap. I believe before it was off or nowrap.

Divs stacking vertically
<img width="1501" alt="Schermafbeelding 2022-09-01 om 09 37 42" src="https://user-images.githubusercontent.com/56388399/187859148-aaf71996-e5f3-4da6-a9b3-45a9038a23bc.png">

CSS area
<img width="217" alt="Schermafbeelding 2022-09-01 om 09 37 59" src="https://user-images.githubusercontent.com/56388399/187859160-c88a2229-4348-498d-93d7-652a8e86b4a7.png">

**Comment by louisreingold** [comment]
Link to the page? We deliberately enabled flex-wrap by default for horizontal layouts, as this is the desired behavior for 99% of layouts.

Maybe we need to add a checkbox for "no wrap" if a horizontal layout is enabled.

**Comment by jeffreyvandervet** [comment]
The link is:
https://wizardly-satoshi.45-82-188-79.plesk.page/

But I fixed it with flex-wrap: no-wrap. Maybe my approach was bad. I think checkbox would help :).

**Comment by louisreingold** [comment]
This will be addressed as part of a larger layout preset overhaul that brings CSS grid support as well. Discussion and request is on Canny.
