### ISSUE TITLE
Issue with animations when page re-loaded below animated section

### ISSUE THREAD

**Issue by tonylondon** [soflyy/breakdance-bugs#315]
Hello, I've noticed that when a page is reloaded from below an area with animations, that yields unexpected results, and the animated text fails to appear. Please see screencast below.

https://www.dropbox.com/s/7dbvdgo1ts6s6po/website%20error.mov?dl=0

**Comment by tonylondon** [comment]
Any word on this?

**Comment by a-dubiel** [comment]
Hey @tonylondon thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
