### ISSUE TITLE
Javascript(?) error on changing post loop builder from grid to list

### ISSUE THREAD

**Issue by etjallings** [soflyy/breakdance-bugs#318]
Just a bug report to help, no big issue. The error pops up when changing from grid to list with the post loop builder, but maybe it also happens when its done at the normal post list builder? For so far i can see, the error has no effect on anything.  But for new users when going to prodution every error popup is one to much.

![image](https://user-images.githubusercontent.com/110063773/187984766-77f2d9e7-2c15-4550-8a75-f49938dadda9.png)
![image](https://user-images.githubusercontent.com/110063773/187983923-0c7358b7-06c9-40c7-87dd-7df0e505e7c9.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
