### ISSUE TITLE
I cannot change typography of a title in the Pricing table element

### ISSUE THREAD

**Issue by Timmotey** [soflyy/breakdance-bugs#320]
In Breakdance Beta 12, I cannot change typography of a title in the Pricing Table Element. It is not responding to any changes unfortunatelly.
The same with changing Global settings -> Typography -> Base size, the title is not responding to changes too...

![Title_issue](https://user-images.githubusercontent.com/112655984/187988196-931374e5-a3e8-4b40-908e-850c52631f84.jpg)

**Comment by a-dubiel** [comment]
This has been fixed in the latest 1.1 Beta
