### ISSUE TITLE
Mini Cart sidebar always comes from left on mobile.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#323]
Despite setting the Mini Cart Sidebar Position to Right: https://d.pr/i/2axFsT

It always comes from the left on mobile: https://d.pr/i/2UigWb.

This behavior begins at exactly 767px viewport width and below.

The issue is corrected if you select Full Screen At: Never and Full Screen Position: Right.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
