### ISSUE TITLE
Licence error prevents operation of builder

### ISSUE THREAD

**Issue by rodpascoe** [soflyy/breakdance-bugs#324]
Installed Breakdance, created new page, immediately got the error and nothing works.

Internal Server Error
Undefined array key "license_key"

Tried downloading plugin again and entering licence again - no difference.
<img width="1206" alt="Screenshot 2022-09-02 at 15 25 10" src="https://user-images.githubusercontent.com/56805772/188170724-826a9abe-f91b-426e-b23c-a71eac3bdaa4.png">
<img width="962" alt="Screenshot 2022-09-02 at 15 24 44" src="https://user-images.githubusercontent.com/56805772/188170728-a10b72d2-5169-4928-8989-032e1e239486.png">
<img width="2463" alt="Screenshot 2022-09-02 at 15 24 36" src="https://user-images.githubusercontent.com/56805772/188170730-d8013d39-17de-4520-bc3f-51d095556f76.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
