### ISSUE TITLE
There is a bug in writing from right to left in the Hebrew language from Israel

### ISSUE THREAD

**Issue by ilan31** [soflyy/breakdance-bugs#329]
![חסר אותיות ](https://user-images.githubusercontent.com/110189546/188273574-c1ea6cb3-a0a7-4530-bfaa-45b420351753.jpg)
![שמאל ימין לא עובד חלק 2](https://user-images.githubusercontent.com/110189546/188273577-d9505f55-2742-4044-99a2-2ccf9c6b5f43.jpg)
![שמאל לימין לא עובד](https://user-images.githubusercontent.com/110189546/188273580-1cf9902e-3e3e-4ef5-bfd1-0e620632a54f.jpg)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
