### ISSUE TITLE
Column Width still considered after Hide on Breakpoint

### ISSUE THREAD

**Issue by nick-s5** [soflyy/breakdance-bugs#330]
Add a columns element, set one of the columns to hide on a breakpoint. Go to that breakpoint. The column will be hidden, but its width is still taken into account if you adjust the remaining columns.

I.E. You have 3 columns of 20%, 60%, 20%. You hide the last column on mobile. You won't be able to set the other two columns to 50%/50%, the other will always adjust itself based on the hidden column. You have to go to the hidden column and set it to 0% first. Should be done automatically since the column is hidden.

**Comment by obedparla** [comment]
If the column width is set to 0%, then it'll be 0% on all breakpoints, not only in the breakpoint where it's hidden. This happens because Columns' size property isn't responsive. We have a few controls to change their size based on the breakpoint, but not to hide them.
