### ISSUE TITLE
Some Hosts Don't Allow Large Icon Sets

### ISSUE THREAD

**Issue by madzoni** [soflyy/breakdance-bugs#331]
This error happens on adding or editing an element that has an icon:

`Validation Error:
IO-TS decoding failed

Check browser console for debug information.`

**Comment by louisreingold** [comment]
What host are you on? We've seen this issue on WP Engine if you upload more than 4Mb of icons, and are planning to rework how we store the icons so we can support more than 4Mb of icons.

**Comment by madzoni** [comment]
Sorry, my bad, the problem was, I had no icons on BD, as soon I uploaded an iconmoon package the problem was gone.

**Comment by louisreingold** [comment]
Breakdance comes with some icons by default. The question is... what happened to them, and why were they removed in a way that caused an IO-TS error?

What web host are you on?

Knowing what host you are on will be very helpful to us.

**Comment by madzoni** [comment]
I also found it strange. 

I am on a cloud server, centos 7 PHP 8.0.22, Plesk Obsidian

I have this apache error:

`AH01071: Got error 'PHP message: WordPress database error Got a packet bigger than 'max_allowed_packet' bytes for query INSERT INTO `bCl2A3L_options` (`option_name`, `option_value`, `autoload`) VALUES ('breakdance_icons', '\\"[{\\\\\\"slug\\\\\\":\\\\\\"FontAwesome 5 Free - Brands\\\\\\",\\\\\\"name\\\\\\":\\\\\\"FontAwesome 5 Free - Brands\\\\\\",\\\\\\"icons\\\\\\":[{\\\\\\"slug\\\\\\":\\\\\\"icon-500px.\\\\\\",\\\\\\"name\\\\\\":\\\\\\"icon-500px.\\\\\\",\\\\\\"svgCode\\\\\\":\\\\\\"<svg xmlns=\\\\\\\\\\\\\\"http:\\\\/\\\\/www.w3.org\\\\/2000\\\\/svg\\\\\\\\\\\\\\" viewBox=\\\\\\\\\\\\\\"0 0 448 512\\\\\\\\\\\\\\"><!-- Font Awesome Free 5.15.1 by @fontawesome - https:\\\\/\\\\/fontawesome.com License - https:\\\\/\\\\/fontawesome.com\\\\/license\\\\/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d=\\\\\\\\\\\\\\"M103.3 344.3c-6.5-14.2-6.9-18.3 7.4-23.1 25.6-8 8 9.2 43.2 49.2h.3v-93.9c1.2-50.2 44-92.2 97.7-92.2 53.9 0 97.7 43.5 97.7 96.8 0 63.4-60.8 113.2-128.5 93.3-10.5-4.2-2.1-31.7 8.5-28.6 53 0 89.4-10.1 89.4-64.4 0-61-77.1-89.6-116.9-44.6-23.5 26.4-17.6 42.1-17.6 157.6 50.7 31 118.3 22 160.4-20.1 24.8-24.8 38.5...', `

Is appears only once, on the day I installed BD.

**Comment by louisreingold** [comment]
Perfect. Thank you! That error is helpful.

**Comment by salasmx** [comment]
Still happening on WP Engine + Breakdance 1.0.3. All icons disappeared. You have to upload them again to remove the super annoying error message. The worst part is you can't tell immediately what's causing the error.

**Comment by charisti** [comment]
On Plesk I don not have any Icons, and can't upload any.

**Comment by louisreingold** [comment]
We changed the way icons are stored and loaded in Breakdance some months ago to solve this. Since then, no reports of issues, although the UX of the icon picker is slightly worse. :(
