### ISSUE TITLE
Typography of some elements are not changing with modifying Global Settings

### ISSUE THREAD

**Issue by Timmotey** [soflyy/breakdance-bugs#333]
I noticed that typography of some elements are not changing with modifying Global Settings -> Typography -> Base size.
I have this issue with all text of Blockquote element, size of the price in Pricing table, size of Testimonial in Fancy Testimonial, size of a number in Simple Counter... 
I use Beta 12.

**Comment by louisreingold** [comment]
Thanks for the reports and specific elements.

Over the last year we polished many elements to make them better respect global styles. We used our judgement when to use global styles and when not to, as some elements wouldn't look as good if they did respect the base size exactly, but numerous elements were improved.

If you have any additional elements that you think don't follow the global styles as well as they should, please open a new issue for each element.
