### ISSUE TITLE
RC1: Linear gradient on text - Rotation value doesn't allow numeric input

### ISSUE THREAD

**Issue by jdub850000** [soflyy/breakdance-bugs#335]
When trying to change the rotation value on linear gradient with a text element, the field doesn't allow it.
The rotation dial to the left of the field does work, but it is low contrast (blue on black - I didn't initially see it) and low precision.

<img width="249" alt="Screenshot 2022-09-05 at 14 52 59" src="https://user-images.githubusercontent.com/58231590/188462334-6d75c11a-0f08-48d9-89ab-60f24ffbc67c.png">

**Comment by jdub850000** [comment]
Also tried gradient on an image overlay. The rotation dial (although still wrong colour) does work when scrubbing however (quite accurate after all - apologies), so the only real issues are:
1) Colour of the rotation dial
2) Enabling direct numeric field input

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
