### ISSUE TITLE
Error on page open

### ISSUE THREAD

**Issue by MediaGozo** [soflyy/breakdance-bugs#338]
When i open the home page in BD i getthis error:

'An error occurred while running an inline script from processAndAddInlineScriptsToHead. Error:"TypeError: n[p] is not a function"'

aswell as the second error:

'An error occurred while running an inline script from "onMountedElement" for element with ID "272". Error:"TypeError: n[p] is not a function" '

If you would like admin creds they are below:

Thank you

https://user-images.githubusercontent.com/108728775/188590284-2b0b3ba5-d4d9-4bb7-a16f-66655c5e2824.mp4

**Comment by jdub850000** [comment]
Just a thought - Have you tried disabling css-hero and some of the other plugins to see if there's a conflict? :)

**Comment by MediaGozo** [comment]
I have the same set up exactly on 11 other sites with no conflict... i use Gridpane to set up sites.. and have my 'Bundles' set up so i always start with the same plugins... i ddon't have this problem on any of the other sites running the same stack?

Ill try it by all means and thank you for the input,

**Comment by jdub850000** [comment]
Are you running Breakdance on the other 11 sites too?

**Comment by MediaGozo** [comment]
yes same stack on all of them

**Comment by MediaGozo** [comment]
same server types too ... aswell as same stack on same servers

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
