### ISSUE TITLE
RC1 - Permission denied error in php code block

### ISSUE THREAD

**Issue by markpinkster** [soflyy/breakdance-bugs#339]
When adding some php code into the PHP block in breakdance builder a permission denied error pops up.
E.g. when you put in something like this:

<?php echo 'some text for testing if php code runs'; ?> 

Saving and viewing the page on the frontend gives the desired result. And the text is displayed as intended.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
