### ISSUE TITLE
Section flexbox - Settings > Advanced > Layout doesn't work

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#34]
The settings are applied to the wrapper (well, the label really does say "Wrapper"), not the container.

Maybe we need to add an option to apply those styles to the Container? Just for sections? Hmmm. 

At that point it's confusing because we have both Wrapper, Wrapper Hover, Container, and Container Hover, but on the other hand, those options are highly advanced, and I'm sure someone will want to customize the Section's wrapper AND container at the same time.

At what point do we just tell people "write the CSS, you know how to do it" rather than polluting the UI with 2389348 options?

**Comment by mikeingz** [comment]
I think we should never 'touch' the main section element (apart from the background-color) and all the settings should be applied to this container only (.section-container).

**Comment by louisreingold** [comment]
> The settings are applied to the wrapper (well, the label really does say "Wrapper"), not the container.
> 
> Maybe we need to add an option to apply those styles to the Container? Just for sections? Hmmm.
> 
> At that point it's confusing because we have both Wrapper, Wrapper Hover, Container, and Container Hover, but on the other hand, those options are highly advanced, and I'm sure someone will want to customize the Section's wrapper AND container at the same time.
> 
> At what point do we just tell people "write the CSS, you know how to do it" rather than polluting the UI with 2389348 options?

Closing for this reason. Wrapper Styles means styles on the wrapper, not some element inside the wrapper.

If you want to set flexbox styles above and beyond what the Section's controls already provides and you want to do it inside the section's container, add a div or write the CSS.
