### ISSUE TITLE
Can't paste formatted text into Rich Text element

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#343]
![image](https://user-images.githubusercontent.com/6425257/188721754-8371ae91-b66b-447f-a059-24d3912343dd.png)

https://www.facebook.com/groups/breakdanceofficial/posts/5380740401961211/

**Comment by obedparla** [comment]
This is already solved, we have a "HTML" view. (although some tags are removed: https://github.com/soflyy/breakdance-bugs/issues/683)

<img width="460" alt="image" src="https://user-images.githubusercontent.com/10674462/222901070-6d1254cd-fb83-4718-a3eb-4ea3400c7de1.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
