### ISSUE TITLE
Can't set Featured Image as a background in Insert Dynamic Data. Requires String, needs Image URL.

### ISSUE THREAD

**Issue by nick-s5** [soflyy/breakdance-bugs#344]
- Create a new Global Block.
- Add a div.
- Insert Dynamic Data for the background image.
- **Only allows for string, not Image URL**
- If you change Type to Image URL it shows the Featured Image option, but you can't click it.

![CleanShot 2022-09-06 at 13 03 53](https://user-images.githubusercontent.com/99763054/188728542-5e645cf5-6d38-49f8-8289-78765c9a67cb.png)

**Comment by a-dubiel** [comment]
This has been fixed in the latest 1.1 Beta
