### ISSUE TITLE
RC 1 - Element Enhancement - Icon List vertical icon alignment.

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#345]
We should have a way to vertically align the Icon List icon for when there's lots of text in a list item.

https://d.pr/i/WNdQFQ

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
