### ISSUE TITLE
RC 1 - Products List - Default query shows draft products, and custom queries don't work

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#346]
https://www.loom.com/share/71df0bf8d1614104bb81d75662058fd8

Steps:

1. Set a Product to draft status
2. Add a Products List to a page
3. See that the Products List returns the draft Product
4. Try to use any custom query (e.g. ```post_type=product&post_status=publish```) and see that the Products List doesn't seem to use it at all

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
