### ISSUE TITLE
RC1 - Numeric value scrubbing?

### ISSUE THREAD

**Issue by jdub850000** [soflyy/breakdance-bugs#347]
Hopefully minor UI feature request: -

Would it possible to allow vertical mouse scrubbing on numeric values?

1. Select a numeric value
2. Click select with the mouse and move up and down to increase or decrease the numeric value.

<img width="319" alt="Screenshot 2022-09-07 at 15 48 10" src="https://user-images.githubusercontent.com/58231590/188895592-a1808a41-c244-4b41-aa7b-c11454f54287.png">

With the attached shot the font value slider doesn't really offer enough precision when adjusting.
This would solve that.

**Comment by a-dubiel** [comment]
You can achieve similar effect with keyboard using up and down. For now we are not planning to implement mouse scrubbing.
