### ISSUE TITLE
Permission Denied error is missing Details & Troubleshooting button

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#35]
![image](https://user-images.githubusercontent.com/6425257/175902822-27963b3d-5d98-4d39-9171-8fa74ced2d5a.png)

**Comment by krissborowy** [comment]
Welcome...

Changing the icon in **_Menu Builder > Style > Toogle > Custom Icons_** I can't save the settings I get the same error.

> Permission Denied
> Not enough permissions to perform the action.


Cheers, I hope this gets fixed

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
