### ISSUE TITLE
RC1: Including global breakdance block in Gutenberg editor broken

### ISSUE THREAD

**Issue by worldoptimizer** [soflyy/breakdance-bugs#350]
Please try to clearly describe the problem.

Using the latest WordPress (6.0.2) and latest Breakdance (RC1)

1. Create a global block
2. Create a post using Gutenberg
3. Add the global block using the Gutenberg Block

The problem, it includes the header and footer.

Including a screenshot of the problem is a good idea.

![CleanShot 2022-09-08 at 12 58 09@2x](https://user-images.githubusercontent.com/1752114/189106221-c1013140-60c4-4a3b-ba1b-c6f10b948d3a.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
