### ISSUE TITLE
Not enough room in fields with deg values

### ISSUE THREAD

**Issue by choegl** [soflyy/breakdance-bugs#352]
Ad a Div element.
Go to Advanced/Wrapper/Effects/Transform
Add a Skew transform
It's possible to move the slider and also to enter numbers, but only one digit visible
<img width="285" alt="image" src="https://user-images.githubusercontent.com/40766504/189114391-8bb638a7-68bb-47d1-aad9-2bed9f67bfbf.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
