### ISSUE TITLE
Global Blocks - post terms not working

### ISSUE THREAD

**Issue by gualhanone** [soflyy/breakdance-bugs#354]
When trying to add post terms on Global Block, taxonomy dropdown shows "no data available".

Post previewed has category, tag and custom taxonomies assigned.

![220908-SSBD](https://user-images.githubusercontent.com/60180554/189173428-674f7c83-4dbc-4c62-b66c-b156665f78ef.png)

**Comment by alemacielsilva** [comment]
I am also facing this problem.

**Comment by gualhanone** [comment]
As a workaround to retrieve post terms, using "insert dynamic data" > "shortcode" and pasting shotcode like: 

`[breakdance_dynamic field='post_terms' type='modified' taxonomy='post_tag' link='false' separator=', ' fallback='fallback text']`

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
