### ISSUE TITLE
Form builder text area rows not working

### ISSUE THREAD

**Issue by djrwp** [soflyy/breakdance-bugs#355]
Adjusting 'text area' row count has no affect. The field block remains the same size regardless. 
 
![A16CA753-49CF-4DE3-B81D-2C7183FF86FE](https://user-images.githubusercontent.com/84224815/189223557-5e14f833-86b9-4221-a992-c1d069fae8e3.jpeg)

**Comment by digitalsmithy** [comment]
No 'rows' tag is added to the form... so still broken.

**Comment by djrwp** [comment]
Seems to be fixed in 1.1
