### ISSUE TITLE
Icon Sets - can't use symbol-defs.svg

### ISSUE THREAD

**Issue by HenkDz** [soflyy/breakdance-bugs#36]
Please try to clearly describe the problem.
When you add an icon set, in my case "Box Icons symbol-defs.svg" it gets treated as a single icon and not a set.
Including a screenshot of the problem is a good idea.

(Or a screencast - https://www.loom.com/)
![image](https://user-images.githubusercontent.com/17301927/175904110-167dbfae-7e71-4248-a8ac-4ea855a96fe4.png)

**Comment by louisreingold** [comment]
You can add a feature request for this at https://breakdance.canny.io/
