### ISSUE TITLE
Element Studio Won't Create a New Element

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#365]
Element Studio won't create a new element. 

![Screen Shot 2022-09-11 at 14 16 16](https://user-images.githubusercontent.com/54561285/189529679-79925872-0b8b-4f9c-bacc-c73cfbb28f69.png)

**Comment by MrBushid0** [comment]
@NaoufelTarchoul 
 You need this plugin to create a save location, see https://www.youtube.com/watch?v=442oJQH2Mlk&t=184s
