### ISSUE TITLE
Section Text Color overrides shape divider color

### ISSUE THREAD

**Issue by tommytompkins** [soflyy/breakdance-bugs#366]
1) Create a section and change the background color
2) Create a shape divider for the section and change the color to a different color. Notice how the shape divider color is the same as the text color for the section instead of the color that you just selected.
3) Remove the text color for the section and notice how the shape divider color is correct now. 

![Screen Shot 2022-09-11 at 1 27 14 PM](https://user-images.githubusercontent.com/4631803/189543401-36bf4c6f-8416-40e4-86d6-b200fed4da07.png)

**Comment by a-dubiel** [comment]
@tommytompkins  we just release 1.1 Beta which addresses this issue. Feel free to test it out.
