### ISSUE TITLE
Woocommerce product page error

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#367]
When clicking a thumbnail for another product color for example the image flickers:
https://www.loom.com/share/588b1ddef5e04a7b9a48f1879adf9d99

**Comment by a-dubiel** [comment]
Hey @mikehenze can you provide me with the product images you are using?

**Comment by mikehenze** [comment]
Sure check here:
https://www.predatorgear.nl/product/gator-gum-9cm/

It happens when you select another color

**Comment by mikehenze** [comment]
Still exists in 1.1 beta

**Comment by a-dubiel** [comment]
@mikehenze we could not reproduce this error on our end. We copied your images, tested locally and found nothing wrong. 

Did you try disabling plugins one by one to narrow down the probable cause? Seems like a caching issue. Please email support@breakdance.com with your credentials and we will take a closer look.
