### ISSUE TITLE
Wrapper Link - contained Text Element displays as link

### ISSUE THREAD

**Issue by djrwp** [soflyy/breakdance-bugs#368]
When using 'text' element with dynamic custom field it displays as a link. If you use 'heading' element it doesn't. Only happens when text is set to dynamic.
![306138128_1201210953775049_1254718578847187553_n](https://user-images.githubusercontent.com/84224815/189631241-8c6686af-308f-4585-a180-0671ff536f8c.jpg)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
