### ISSUE TITLE
Breakdance 1.0 still has a Beta Message on Breakdance > Home

### ISSUE THREAD

**Issue by Kpudlo** [soflyy/breakdance-bugs#369]
Breakdance still has a Beta message when installing 1.0.

To see the issue, go to Breakdance > Home.
![image](https://user-images.githubusercontent.com/4432822/189692286-b5cb46ca-839c-47d9-82cd-58a3f67499fb.png)

**Comment by jdub850000** [comment]
This is shown if you are using the beta license code - it is removed if using a full license.
