### ISSUE TITLE
1.0 - Post Featured Image - Fallback image not shown when no featured image set on post

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#377]
Steps to reproduce:

1. Add a post with a featured image
2. Add another post without a featured image
3. Add a Single Post template
4. Add a Post Featured Image element with a fallback image

Note that while viewing a post with a featured image, it shows as expected. On a post with no featured image, the fallback image is not used as expected.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
