### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by bluefish1960** [soflyy/breakdance-bugs#38]
I first had loading time issues on a wp local test site but burned it as there were other issues.
I now have Breakdance installed on my cloud hosting and the admin pages load really fast as do the regualr wp pages and posts for editing etc.

The problem is that it takes 12 seconds from initial click to fully loaded to have a useable Breakdance editor screen. The initial screen appears after 5/6 seconds but is not ready to edit until another 6 seconds pass.

My server is Bunnyshell with DO droplet 2gb RAM and 2cpu - it works really well on Oxygen 4.0 websites.

Hope this is clear enough.
Thanks
Andy

**Comment by neeckola** [comment]
Experiencing the same issue on DO droplets. Hope this one gets solved as it is a dealbreaker for me.

**Comment by pmk885** [comment]
Same issue with Hetzner dedicated server. With FF and FF dev opening a page with no content at all, no header or footer, the editor loads in ~14 seconds, even with fresh profile. Chrome loads in ~9 seconds.

Hardware: 
CPU 4C/8T
RAM 64GB
NVMe SSD
1 Gbit/s bandwith.

Software and settings:
LiteSpeed Enterprise 6.0.12
PHP 8.1.7 (tried also with 7.4.30)
max_input_vars 3000
WP_MAX_MEMORY_LIMIT 512M
WP_MEMORY_LIMIT 512M

**Comment by louisreingold** [comment]
We dramatically improved load time in beta 1.
