### ISSUE TITLE
Unexpected gap between first and second post loop

### ISSUE THREAD

**Issue by LiamX2** [soflyy/breakdance-bugs#380]
I got unexpected gap between first and second post in a loop builder and error message, please refer to the image attached.
<img width="844" alt="Screen Shot 2022-09-15 at 12 04 44 pm" src="https://user-images.githubusercontent.com/74690623/190296645-159403f6-22e4-4814-92ca-7437b6191dc5.png">

**Comment by LiamX2** [comment]
This gap only happened on mobile.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
