### ISSUE TITLE
1.0 - Cannot link to a PDF using any type of link element

### ISSUE THREAD

**Issue by graemeoswaldrr** [soflyy/breakdance-bugs#381]
When adding a .PDF link to any of the link elements when using advanced tabs, the page cannot be saved and prompts the "Permission Denied" pop-up.

**Comment by a-dubiel** [comment]
Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
