### ISSUE TITLE
1.0 - Custom dynamic data not showing on header template

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#382]
Within the header template the custom created dynamic data shows as a shortcode.

<img width="406" alt="Schermafbeelding 2022-09-15 om 15 04 22" src="https://user-images.githubusercontent.com/56388399/190411010-4ad3c00f-3129-4a29-8ad1-8dabeed3ac27.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
