### ISSUE TITLE
1.0 - WP Nav Menu: Space between not editable within breakpoints

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#383]
The space between the menu items can't be edited per breakpoint.

<img width="259" alt="Schermafbeelding 2022-09-15 om 15 08 52" src="https://user-images.githubusercontent.com/56388399/190412032-fa9963f3-ddf6-4e72-a0d7-c2340a76ade2.png">

**Comment by louisreingold** [comment]
We made significant enhancements to the WP Menu and Menu Builder element in Breakdance 1.3 including making many controls that weren't previously responsive, responsive.
