### ISSUE TITLE
1.0 - WP Nav Menu: Can't change padding per breakpoint

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#384]
Can't change padding of link items per breakpoint.

<img width="286" alt="Schermafbeelding 2022-09-15 om 15 14 05" src="https://user-images.githubusercontent.com/56388399/190413230-0ca291c7-d14b-4357-8c91-f87d9b3390f8.png">

**Comment by louisreingold** [comment]
We made significant enhancements to the Menu Builder and WP Menu elements in 1.3, including making many more controls responsive.
