### ISSUE TITLE
Fragen zu Header Bulider Einstellung Overlay

### ISSUE THREAD

**Issue by 675056817** [soflyy/breakdance-bugs#386]
Please try to clearly describe the problem.
Problem: When the Overlay of Header Bulider is turned on, the default z-index of Header Bulider is 1; generally newcomers do not understand z-index:, so it is recommended that the default number apply for a higher 9999.

Including a screenshot of the problem is a good idea.

(Or a screencast - https://www.loom.com/)
https://www.loom.com/share/16d1b0d580da483188349be33eb91256

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
