### ISSUE TITLE
Menu builder - Top bar image - Can't change logo width in responsive mode

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#387]
![image](https://user-images.githubusercontent.com/51177627/190583613-912382b8-2d16-4fa2-805e-f18d8f711ed5.png)

**Comment by louisreingold** [comment]
Thanks for the report.

We added support for this in a previous version of Breakdance but overlooked updating this issue.

<img width="292" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/6425257/f4186825-8c4f-4b06-8712-fc7e7f830c8d">
