### ISSUE TITLE
Post Archive

### ISSUE THREAD

**Issue by ewamazed** [soflyy/breakdance-bugs#39]
Post archive template... when adding the first section and setting the image in the section with  'featured image' it shows fine in the backend but not on the front. I tried plain old image element and it works properly but can't set it to full width and some other things.

The post archive looks real good and **my only suggestion would be to set the button for 'read more' to have a left, right, and center positioning capability.**

I am liking this very much and thank you.

**Comment by ewamazed** [comment]
SOLVED... I used the overlay before and it didn't work, so I thought I would try again and this time it worked...whew!

So far everything I've tried works very well...sorry but I was  sure I had tried the overlay first at that made sense.

**Comment by louisreingold** [comment]
> my only suggestion would be to set the button for 'read more' to have a left, right, and center positioning capability.

You can already do this:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6425257/182064646-597ec483-d06b-44c6-98ba-1bc5362e5300.png">
