### ISSUE TITLE
1.0 Columns: Column count is 4 when choosing 50% width

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#391]
The column count is 4 when choosing 50% width in columns. This gives a gap on the right side of the second column. So the column count should be 2 instead of 4.

--columnCount: 4;

<img width="677" alt="Schermafbeelding 2022-09-16 om 11 19 56" src="https://user-images.githubusercontent.com/56388399/190604385-d2da98bb-4617-4aa0-a2a8-2ec19f4747be.png">
<img width="205" alt="Schermafbeelding 2022-09-16 om 11 20 06" src="https://user-images.githubusercontent.com/56388399/190604410-80384ccb-5d3c-419c-ac13-568028caeee4.png">

**Comment by udoro** [comment]
Actually, it should not be 2, it should be 4, that's correct. What you are seeing there is not a CSS property, but a variable used in calculating the width of each columns.

The solution is to set the .breakdance .bde-column to flex-grow: 1. 
This should be a default value for the columns element.
![image](https://user-images.githubusercontent.com/22454125/192120601-05f2f060-3d81-4b2b-b620-c3d88611a67e.png)
![image](https://user-images.githubusercontent.com/22454125/192120603-f1af2608-9008-477d-a82b-a09a54c04ecf.png)

**Comment by udoro** [comment]
This can also be solved by setting the .breakdance .bde-column flex-grow to 1.
![image](https://user-images.githubusercontent.com/22454125/192120880-24206de3-9e4d-410b-8fd2-999ae7bddf46.png)
