### ISSUE TITLE
1.0 Sliders: Custom height not working on other breakpoints

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#392]
The custom height can't be changed when using another breakpoint. 

<img width="277" alt="Schermafbeelding 2022-09-16 om 13 05 03" src="https://user-images.githubusercontent.com/56388399/190625425-a0806c6b-2f54-46b7-ba20-2082d19e1341.png">

**Comment by marcel2008** [comment]
Confirmed. Basic Slider the same. I tried both and cant change the height per breakpoint.

https://www.loom.com/share/705d42b99c614e889bf7a819658c3fc6

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
