### ISSUE TITLE
1.0 Sliders: Can't change slides per view per breakpoint

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#393]
You can't change slides per view per breakpoint. You can't do it inside the basic slider nor the advanced slider.

<img width="292" alt="Schermafbeelding 2022-09-16 om 14 15 45" src="https://user-images.githubusercontent.com/56388399/190637331-4dc50237-9f48-41f1-a156-8722454e13bd.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
