### ISSUE TITLE
Simple Counter Element - Error pops out once you start draging the element to inside a div

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#394]
![image](https://user-images.githubusercontent.com/51177627/190654815-79056aaf-5078-4e3f-9d56-dcfe2f1c4fa9.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
