### ISSUE TITLE
Problem with self closing tags in PHP code

### ISSUE THREAD

**Issue by choegl** [soflyy/breakdance-bugs#395]
Do these steps

1. Add a code element 
2. In the PHP section (without any <? or echo command) enter 
`<iframe parameters />`

3. Add another section or elements below

In the Breakdance editor everything looks fine, but on the front end all elements after the iframe are missing or garbled.

If you change the code from `<iframe parameters />` to `<iframe parameters></iframe>` everything works as it should.

Breakdance appears to choke on the self-closing tag.

(Parameters need to be real code, i.e. Google Maps embed. Omitted here for readability)

**Comment by louisreingold** [comment]
I wonder if this is a Breakdance bug or default behavior of PHP eval?

**Comment by louisreingold** [comment]
We apologize for incorrectly marking this as a bug.

There's no such thing as a self-closing iframe tag.

https://stackoverflow.com/questions/27545757/why-is-a-self-closing-iframe-tag-preventing-further-dom-elements-to-be-displayed

Close the iframe tag.

This has nothing to do with Breakdance or PHP eval.
