### ISSUE TITLE
1.0 - ACF Integration - Add better support for File field type

### ISSUE THREAD

**Issue by Spellhammer** [soflyy/breakdance-bugs#398]
Presently, the File field type does not show up as an option in the Dynamic Data dialog for any Breakdance fields that accept dynamic data.

Additionally, attempting to get this field using Post > Custom Field via the Dynamic Data dialog returns only the attachment's ID, despite the return value specified in ACF, making it unusable.

Use case: Providing a link to an attached file in a post template.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
