### ISSUE TITLE
1.0 <?php the_author(); ?>

### ISSUE THREAD

**Issue by Anticosti** [soflyy/breakdance-bugs#400]
1. Create a new CPT (in this case "information");
2. Make sure your CPT supports Author;
3. Create a custom template for your single CPT;
4. Create a new Code Block inside your custom template;
5. Paste this code in your Code Block (PHP Code):
```
<div>
    <img class='info-image' style="margin:0px 20px 2em 0px;border:1px solid black;display:inline-block;float:left;max-width:50%; src="<?php the_post_thumbnail('large'); ?>
     <p class='global'><h2 class='info-title' style=""><?php the_title(); ?></h2>
  	  <p class='author'><?php the_author(); ?></p><p class='date-published'><?php the_time(get_option('date_format')); ?></p>
      <div class='content'><?php the_content(); ?></div>
  	</p>
</div>
```
6. Add a snippet to support the CPT (information):
```
function add_author_support_to_information() {
add_post_type_support( 'information', 'author' );
}
add_action( 'init', 'add_author_support_to_information' );
```

**Issue:**
```<?php the_author(); ?>``` does not pull anything. It stays blank.

**Comment by Anticosti** [comment]
![Screen Shot 2022-09-19 at 15 29 33](https://user-images.githubusercontent.com/5446224/191099838-348fdeac-272a-4b13-ab68-640bb0f11c94.png)

**Comment by a-dubiel** [comment]
Hey, pretty sure the Post Meta + Post Content elements will achieve something similar. I think there is no need for custom code blocks. Closing this for now.
