### ISSUE TITLE
Section divider color is lost if the divider width is changed at a responsive breakpoint

### ISSUE THREAD

**Issue by tommytompkins** [soflyy/breakdance-bugs#403]
1) Add a section and a curvy divider at the top of the section with a light background color on Desktop
2) Select the Tablet Landscape breakpoint
3) Change the width of the divider and notice how the divider color goes dark even though the light color is still selected.

![Screen Shot 2022-09-18 at 4 50 43 PM](https://user-images.githubusercontent.com/4631803/190929540-abc51511-e9a4-4bd1-9c68-bc3f35722a5a.png)

![Screen Shot 2022-09-18 at 4 51 01 PM](https://user-images.githubusercontent.com/4631803/190929543-b1d2f8d6-e126-45d8-98e8-48318a2088f2.png)

![Screen Shot 2022-09-18 at 4 51 23 PM](https://user-images.githubusercontent.com/4631803/190929552-9624dd03-1c7d-4d6c-a01c-344349010a4c.png)

**Comment by a-dubiel** [comment]
This should be fixed in 1.1 Beta.
