### ISSUE TITLE
Global Settings: Buttons don't have Override Width and Full Width At

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#405]
When you are trying to adjust the button from the Global Settings those two settings are missing from the Size sub-menu when you've selected "Custom". 

Image of the Global Setting Menu:
![image](https://user-images.githubusercontent.com/110225636/191008377-635d780a-1451-4fc9-9f0b-3c833f70f7c9.png)

Image from the Custom Button Setting in the Button Element:

![image](https://user-images.githubusercontent.com/110225636/191008519-5d4f5f8a-ad54-458d-8936-9ba0b56a655f.png)

**Comment by a-dubiel** [comment]
This is done on purpose. For these two controls please use granular settings instead.
