### ISSUE TITLE
Section - Background Gradient - Tilt control stuck on click

### ISSUE THREAD

**Issue by Dancerist** [soflyy/breakdance-bugs#409]
When I click, it jumps to 179deg

![image](https://user-images.githubusercontent.com/51177627/191141876-d4d21888-ef48-428d-acb1-2d713dadff95.png)

**Comment by Dancerist** [comment]
SOLVED. I try logging out and logging in. It's now working.

Sorry, I don't know how to delete this.

Thanks.

**Comment by MrBushid0** [comment]
@Dancerist You have the Close Issue button next to the green Comment button
