### ISSUE TITLE
Form - Remove Field shadow on focus

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#411]
Please remove the default field shadow on focus. At first, I thought it was a border.

![image](https://user-images.githubusercontent.com/51177627/191190958-0ffc1a1c-88b4-4fe7-8f49-d2e822099e0a.png)

**Comment by a-dubiel** [comment]
Hey, feel free to use a design control for that. 

<img width="380" alt="Screenshot 2022-11-28 at 18 18 00" src="https://user-images.githubusercontent.com/669243/204340618-115a5620-69a2-4673-9392-ecc083c1df8a.png">
