### ISSUE TITLE
1.0 - Dynamic Data: ACF Checkbox Field Error

### ISSUE THREAD

**Issue by bmc38119** [soflyy/breakdance-bugs#413]
Receive the following error when adding a Text Element and populating with Dynamic Data: ACF Checkbox Field.  Confirmed that the ACF Field is set to output as String.  This is happening on Global Block - have not verified on normal page.  The error does not prevent saving - only displays after saving.  Front-end does display the field value correctly despite the Error Message.  

Error Message:
![image](https://user-images.githubusercontent.com/20451326/191305232-4c082133-5954-4e9f-9703-bc2fa92857b0.png)

ACF Field Setting:
![image](https://user-images.githubusercontent.com/20451326/191305377-70ad0e30-7c9e-4ecd-a45a-d532caa4dd32.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
