### ISSUE TITLE
Advanced slider pagination bullets space between

### ISSUE THREAD

**Issue by slawomiroruba** [soflyy/breakdance-bugs#414]
When changing from px to rem or em is not doing anything. It's always px. 

https://www.loom.com/share/1985354600284d04a35c45ef0961837c

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
