### ISSUE TITLE
Section padding not working if section inside Template Content Area

### ISSUE THREAD

**Issue by le-serg** [soflyy/breakdance-bugs#416]
Section padding not working if section inside Template Content Area, because the padding is overridden by the parent section.

How to reproduce the error:
1 Add page template
2 Add Section and Template Content Area
3 Edit page with this template and try change section padding

How to fix the error:
Change this .breakdance .bde-section-484-100 .section-container 
to this .breakdance .bde-section-484-100>.section-container

**Comment by a-dubiel** [comment]
This has been fixed in 1.1 Beta
