### ISSUE TITLE
Editor errors

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#419]
I have a header. I got to BD->Template-> and edit the header. I click COPY on a DIV inside the header and get this:

<img width="560" alt="Screenshot 2022-09-22 at 15 11 12" src="https://user-images.githubusercontent.com/17641345/191770447-b4464776-c2e8-4558-95a9-091f99c3177b.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
