### ISSUE TITLE
Mobile menu - Horizontal Center Links not working on level 2/3

### ISSUE THREAD

**Issue by djrwp** [soflyy/breakdance-bugs#420]
Horizontal Center Links has no effect on drop down level 2/3? Doesn't seem to be a sub setting so guessing a bug.

![308799245_1210300952866049_2527679212087522237_n](https://user-images.githubusercontent.com/84224815/191938082-84845319-5254-4639-b25e-2023f08a237e.jpg)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
