### ISSUE TITLE
WooCommerce Price needs center alignment

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#423]
The price element in the product list needs center alignment, otherwise, on variable products, the '-' separator appears more like an underscore:

![image](https://user-images.githubusercontent.com/112517932/192106426-6e478b97-f0b7-46d3-b28f-a889037678dc.png)

I'm adding to compensate right now:

.breakdance-woocommerce .entry-summary .price, .breakdance-woocommerce.bde-wooproductprice .price, .breakdance-woocommerce ul.products li.product .price {
	align-items: center;
}

**Comment by a-dubiel** [comment]
This has been fixed in 1.1 Beta
