### ISSUE TITLE
1.0.1 Background image: Can't set featured image

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#429]
You currently can't set featured image inside a background. The background image probably excepts strings instead of image url's. 

<img width="1722" alt="Schermafbeelding 2022-09-30 om 14 54 11" src="https://user-images.githubusercontent.com/56388399/193274162-e2ffc20a-f05b-4874-8a2d-4c66184cd47e.png">

**Comment by a-dubiel** [comment]
This has been fixed in 1.1 Beta
