### ISSUE TITLE
No Advanced Options for Meta Box Custom Fields

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#430]
As the attached screenshot shows, there is no **Advanced Options** for data from **Meta Box** custom fields. This is usually used to append/prepend currency in my case or add a Fallback sentence. 

![Screen Shot 2022-10-01 at 17 41 00](https://user-images.githubusercontent.com/54561285/193419687-6f9cb92e-4586-4012-b028-f52882961d19.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
