### ISSUE TITLE
Body tag - background image not showing in editor but working on front-end.

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#431]
![image](https://user-images.githubusercontent.com/51177627/193435885-81cb30bc-cf77-42ff-9149-298280073ecb.png)
![Uploading image.png…]()

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
