### ISSUE TITLE
Post slider - Space between bug

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#432]
Space between slides not showing in the editor but working on the front-end

![image](https://user-images.githubusercontent.com/51177627/193486789-d2734326-a10d-456c-acf8-350d63a94a38.png)

![image](https://user-images.githubusercontent.com/51177627/193486832-d4469f1b-e425-44de-b53f-cc37ccb6e955.png)

**Comment by a-dubiel** [comment]
Hey @dancerist there are times when content loaded through SSR (server side) does not update instantly. We are aware of that. For now I suggest hitting the "refresh" icon if you don't see the canvas being updated.

<img width="222" alt="Screenshot 2022-11-30 at 15 14 45" src="https://user-images.githubusercontent.com/669243/204818835-ee1d3e95-9931-4a8c-97b7-fe5b777e6f08.png">
