### ISSUE TITLE
Breakdance UI - Input Field Values Too Small

### ISSUE THREAD

**Issue by bigfattso** [soflyy/breakdance-bugs#436]
Please improve the UI overall where; there are many input fields for values you cannot see the whole value, the input fields are too small, the flyout panels are too small, crampt and busy. Sometimes I find myself 5 panels deep just to get to a fairly basic change I would expect to see on the first level.

I hate to say this but Elementor has this (UI) nailed, much more logical layout of values and a cleaner view/flow of styles and attributes per element.

![Screenshot 2022-10-06 at 14 45 45](https://user-images.githubusercontent.com/115084260/194330452-63da6613-3102-4795-860a-a36dcf19d2ea.jpg)
![Screenshot 2022-10-06 at 14 46 18](https://user-images.githubusercontent.com/115084260/194330458-8347446f-7ce7-4fe1-bda9-5c97700e48dc.jpg)

**Comment by a-dubiel** [comment]
Hey @bigfattso what browser and OS are you working on?

**Comment by bigfattso** [comment]
I’ll give it a try as soon as I can download a new copy although in Louis’ video I watched earlier i still saw a field masking some of the input.

I’ll check again later


Sent from mobile

On 31 Oct 2022, at 18:02, Andrzej Dubiel ***@***.***> wrote:

﻿

This should be fixed in the latest 1.1 Beta
