### ISSUE TITLE
Error When Using SVG as Logo

### ISSUE THREAD

**Issue by bigfattso** [soflyy/breakdance-bugs#437]
I'm seeing an error when using an SVG image as a logo in the header. Only happens with SVG, seems ok when using other image types PNG, JPG etc.

![Screenshot 2022-10-06 at 15 02 37](https://user-images.githubusercontent.com/115084260/194333783-b5afdd56-c98b-4416-9998-88d5af302ae5.jpg)

**Comment by bigfattso** [comment]
Here's what's happening when I insert a SVG image in the body of the page.
This is on a site originally built using Elementor, I am currently replicating the page using BD. ie. the same site, server, just a new page (/home2). 
The original page works fine.
Using BD - error.
Note Elementor/Elementor Pro is still active. Hello theme is installed but disabled in BD settings.
Hope this is enough info.

<img width="1918" alt="Screenshot 2022-10-06 at 20 37 05" src="https://user-images.githubusercontent.com/115084260/194404879-c4191f15-128a-42a0-b3ce-a96319983fba.png">
<img width="1918" alt="Screenshot 2022-10-06 at 20 37 15" src="https://user-images.githubusercontent.com/115084260/194404886-8b68f64d-57de-407c-bae8-900d0e77ca3c.png">

**Comment by a-dubiel** [comment]
We don't support SVG uploads yet. We are considering it. For now please use a separate plugin. Thanks.
