### ISSUE TITLE
Licence not recognised - or just a glitch

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#439]
Please try to clearly describe the problem.
Key valid - warning still shows. I'm very much hoping it doesn't kill my site when it think it's expired.
Including a screenshot of the problem is a good idea.
<img width="777" alt="bd-issue" src="https://user-images.githubusercontent.com/17641345/194345234-49931d56-6285-4b00-8cab-32a889dffd6e.png">

(Or a screencast - https://www.loom.com/)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
