### ISSUE TITLE
Sticky/Pinned Elements: Pin state doesn't update after a layout change in parent element

### ISSUE THREAD

**Issue by MrBushid0** [soflyy/breakdance-bugs#441]
**Problem:** 

When you have a sticky element in a section and then change the section layout ( say from align left to right ) , the element position will reflect the change but not the pin element of scrolltrigger.

The pin wrapper will update to reflect the new position once you click the element itself. 

This problem happens with any element that uses scrolltrigger to pin elements. I'm facing the same problem with a custom element as well. 

**Screencast of the issue:** 

https://www.loom.com/share/4adea26a72c444b0a3924a88dc96dc39  

**Possible solutions:** 

1. Automatically execute  the on property change action of child elements when the parent property changes. ( maybe too taxing in terms of re-rendering if too many child elements? ) 

2. Expose the parent on change property via a new action to child elements

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
