### ISSUE TITLE
No option to change "Share" button text

### ISSUE THREAD

**Issue by etjallings** [soflyy/breakdance-bugs#445]
There is no option to change the text for the mobile "Share" button of the scocial share buttons. I want to change the text to my website language.
![306088126_10159691303758591_4766752677543934057_n](https://user-images.githubusercontent.com/110063773/194832278-c6f997e2-733b-4da3-b8cc-956902ea3739.jpg)

**Comment by a-dubiel** [comment]
This has been fixed in the latest 1.1 Beta
