### ISSUE TITLE
Menu Builder - option to only have one column open at a time

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#45]
![image](https://user-images.githubusercontent.com/6425257/176086587-9868bd15-fe46-40b8-af7a-89e13a1d1883.png)

'when I open "TAB 2" named "Places"... "TAB 1" should auto close. or just 1 tab should be active at the same time. hope it make sense.'

**Comment by udoro** [comment]
I agree that auto closing other items will cause jumpiness. Maybe this should be an option in preferences

**Comment by louisreingold** [comment]
This is a feature request and not a bug report. It should be posted at https://breakdance.canny.io/.
