### ISSUE TITLE
Lightbox type links don't accept dynamic data sources for images/videos.

### ISSUE THREAD

**Issue by clockwood** [soflyy/breakdance-bugs#454]
Add a Wrapper Link, choose Type = Lightbox, select image or video - there's no option to add dynamic data.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
