### ISSUE TITLE
Icon list - icon size only in px

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#455]
Can we have rem, % etc. pse. Thanks.

**Comment by digitalsmithy** [comment]
Also in Icon-Box - these are silly little things, but you did ask if I could post them... so...

**Comment by adkoen** [comment]
Yep, the same goes for the normal icon element. You can only set the size in px, not in rem, em or whatever.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
