### ISSUE TITLE
No option to deselect or remove dropdown options in styling or Advance options

### ISSUE THREAD

**Issue by timolukayode** [soflyy/breakdance-bugs#456]
Once you select a drop down option, there is no way to deselect or remove it except you undo.
E.g.: 
Wavy Decoration to a button by going to the Styling option:
Typography > Advanced > Decoration > Style

Once you choose an option from the dropdown, there is no way to deselect/remove the option except you use the undo option.

This applies to almost all the dropdown options on Breakdance 

![Bug](https://user-images.githubusercontent.com/38001551/196048008-f83cb831-9f9b-4372-a745-aaf39f8c1b22.png)

**Comment by a-dubiel** [comment]
@timolukayode can't you use the indicator on the left side of the control label? https://www.loom.com/share/450a738e39e64d79aafe3e5ae97fbbfe?from_recorder=1&focus_title=1

**Comment by timolukayode** [comment]
> @timolukayode can't you use the indicator on the left side of the control label? https://www.loom.com/share/450a738e39e64d79aafe3e5ae97fbbfe?from_recorder=1&focus_title=1

Honestly, didn't know that was there. Maybe it can be more visible.

**Comment by timolukayode** [comment]
> @timolukayode can't you use the indicator on the left side of the control label? https://www.loom.com/share/450a738e39e64d79aafe3e5ae97fbbfe?from_recorder=1&focus_title=1

Honestly, didn't know that was there. Maybe it can be more visible.
