### ISSUE TITLE
No Standard Accordion element

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/breakdance-bugs#459]
Am I missing something or is there no standard Accordion element?
i.e to achieve something like this:
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_accordion

**Comment by a-dubiel** [comment]
Advanced Accordion is coming very soon. Stay tuned.

**Comment by JeusuDigital** [comment]
Ok thanks

**Comment by louisreingold** [comment]
Thanks for the suggestion. Advanced Accordion shipped in Breakdance 1.3: https://breakdance.com/breakdance-1-3/
