### ISSUE TITLE
Search Form & Mini Cart Bug

### ISSUE THREAD

**Issue by onenyarko** [soflyy/breakdance-bugs#46]
Hey @louisreingold, mini cart and search form bug

When a search form is changed from classic to full screen and it is paired with a mini cart element. The mini cart element breaks to the next line. This only happens when the cart is placed after the search form. If the search form is behind it, this bug doesn't happen.

To replicate it. 

Try creating a header.
Add search form as the first element.
Add a mini cart as the second element.
Make the section horizontal.
Preview the header on a page. 

![minicart](https://user-images.githubusercontent.com/10132543/176095900-2f10541f-5329-4ecb-aeac-a8cad0e52e9b.png)

**Comment by louisreingold** [comment]
Nice catch. There was an extra closing /div in the search form element. This will be solved in beta 4.
