### ISSUE TITLE
Blend mode for image element

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#460]
I'm not sure if this is a bug, but the image element could use a blend mode. You can set the opacity and add some effects, but blend mode is missing. And yet blend-mode 'multiply' for instance is something used regular is my guess, at least in my book.
thanks.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
