### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#461]
Site worked fine on MAMP. Moved to dev server - same as multiple websites... PHP 8.1 memory 384M, vars=6000... I've built full ecommerce on same without issue. But now when saving a page I regularly get a memory error (see image)

Including a screenshot of the problem is a good idea. (EDIT - Attached wrong screenshot...)

<img width="558" alt="Screenshot 2022-10-18 at 14 14 48" src="https://user-images.githubusercontent.com/17641345/196448209-f23bc413-a0c4-44ca-a0a6-e18caccb68fb.png">

(Or a screencast - https://www.loom.com/)

**Comment by Nicscott01** [comment]
Also had a memory issue running 1.3.0-alpha.1 on a site that I had pretty much completed. Breakdance editor wouldn't load for a footer or a page styles. Tried clearing the Breakdance cache, didn't work.

Then I got into the php memory settings for the instance and jacked it up to 256M. That allowed Breakdance to load.

Obviously it would be great to not have memory issues with 128M.

Thanks!

**Comment by louisreingold** [comment]
Numerous efficiency improvements have been made to Breakdance over the last year. We have more work to do with large WooCommerce stores - I've seen numerous issues with memory_limit on stores with 20,000+ products.

**Comment by louisreingold** [comment]
Closing this as non-specific, and we have an open issue about monster WooCommerce store memory issues. If you encounter a specific memory limit issue in a specific setting (i.e. you have 10k taxonomies and doing some specific thing generates a memory limit error), we're all ears.
