### ISSUE TITLE
Wrapper flex-child > align-self applies invalid properties

### ISSUE THREAD

**Issue by MrBushid0** [soflyy/breakdance-bugs#467]
Under Wrapper > Layout > Advanced > Flex Child

The Align Self applies invalid values for the left and right options. It should be flex-start and flex-end on the css but it adds left and right respectively.

![image](https://user-images.githubusercontent.com/3267657/197235843-b953a2e0-65c8-4df8-8492-66183d6d6af1.png)

**Comment by bhartlenn** [comment]
This bug still exists in all four versions released since this bug was reported.

Can we give it a bump?

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
