### ISSUE TITLE
Parent rows of columns automatically convert to columns when there is responsiveness

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#468]
There is a problem, when there is the presence of rows of columns on the page, systematically, when I switch to a breakpoint tablet, the parent column row converts itself into a column and is no longer a row as I want it to be, I tried to go through flexbox but there is nothing to do, see my capture
![bug flexbox](https://user-images.githubusercontent.com/56270626/197273925-0fc0fd15-0f90-498f-ae96-1ebc331ae7d8.png)

**Comment by a-dubiel** [comment]
Hey @rodolphebertozzo - you control this via `Stack Vertically` under Columns settings.

<img width="280" alt="Screenshot 2022-10-24 at 18 24 21" src="https://user-images.githubusercontent.com/669243/197576854-2da78d1f-2634-4cbd-908a-583f9e1c959f.png">
