### ISSUE TITLE
Woocommerce styles

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#469]
When changing icon color in notices... if color is blank the icon is fine. If I change to any color, it goes black - not the chosen color.

Also - WooC product table (basket). Gets text color from global WC text color. Can't change the headings text color. If I make table head background dark, the text is dark - so I have to have a light background. Be good if there was a 'table headings' color option.

**Comment by a-dubiel** [comment]
> When changing icon color in notices... if color is blank the icon is fine. If I change to any color, it goes black - not the chosen color.

I can't reproduce this. Can you be more specific? What type of notice are you trying to update?

> Be good if there was a 'table headings' color option.

Did you try Cart Page > Contents > Typography > Table Headings?

**Comment by digitalsmithy** [comment]
BD->Settings->Global Styles->Edit
Go to basket in left pane.
Right-bar: Wooc->other->Notices->Success (or any other)
![bd-not](https://user-images.githubusercontent.com/17641345/198249354-cace95fd-a7d3-4527-9aea-5681a0e4cf0d.jpg)
Note green (don't know why) tick icon by 'carrots' when color=blank. Black when color set White (or any).

You asked: Did you try Cart Page > Contents > Typography > Table Headings?
I can't find that option? I can edit the page 'my basket' but I use default Wooc so no content. There's no 'Cart Page' in global styles options. Where is it?
