### ISSUE TITLE
Dynamic URL bugs

### ISSUE THREAD

**Issue by wp-vaksin** [soflyy/breakdance-bugs#470]
The data always shown blank after the refreshing the page

Below is steps to reproduce this issue:
1. Add dynamic URL to button element
2. Save it
3. Refresh the page via browser
4. Check the dynamic URL

Please check screencast for the detail:
https://www.loom.com/share/fbe023e8417e41cd8d14d5140a3c8d02

This bugs is related with issue #464

**Comment by a-dubiel** [comment]
Hey @wp-vaksin thanks for your report and stellar first issue. This has been addressed in the latest beta which has been already released. We are going to release 1.1 RC very soon.
