### ISSUE TITLE
Icon Box Gradient Missing palette

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#473]
**EDIT** the gradient seemed messed up but it was my error. So reduced to the missing palette issue. Add icon-box. Select background. Doesn't show palette colors.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
