### ISSUE TITLE
BUG FORM ELEMENT

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#474]
It seems that there is a footer tag at the end of the form element generated in the DOM, but there is no header to the form, and from a semantic point of view, this is not right
![bugformulaire](https://user-images.githubusercontent.com/56270626/197627107-58080824-e010-4e41-9bdc-0fb168578368.png)

**Comment by louisreingold** [comment]
Thanks for the report. This is addressed in Breakdance 1.7.
