### ISSUE TITLE
Post Date on Loop builder

### ISSUE THREAD

**Issue by ReflectedReality648** [soflyy/breakdance-bugs#478]
When i use post date on the loop builder I can't change the published date. I update the published date in wordpress bu it remains the same in the post loop builder. The wordpress posts widget works as expected only the loop builder has the issue.

**Comment by a-dubiel** [comment]
I can't reproduce this. Are you sure the correct date type is selected?

<img width="286" alt="Screenshot 2022-10-26 at 19 03 59" src="https://user-images.githubusercontent.com/669243/198090680-1352b55b-3673-4b97-8160-9c7a77f4ea46.png">
