### ISSUE TITLE
Drop-down menu icons (e.g. chevron) don't seem to appear

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#479]
Kinda says it all...

**Comment by a-dubiel** [comment]
Hey @digitalsmithy see https://github.com/soflyy/breakdance-bugs/issues/480#issuecomment-1293234156

**Comment by sherissar** [comment]
Would be great if the drop-down arrow shows even where there is a link present in the top-level menu item. The drop-down arrow indicates there are sub-menu items. And the top-level menu can also be clicked.

**Comment by louisreingold** [comment]
Closing as duplicate of https://github.com/soflyy/breakdance-bugs/issues/480, leaving the duplicate open.
