### ISSUE TITLE
Element meta post template

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#481]
![space meta](https://user-images.githubusercontent.com/56270626/198708841-1388c5c0-c079-4885-a428-472afc5ebe76.png)
There is no possibility of spacing between the text that and the dynamically generated field. For example, published on => published on10/28/22

**Comment by a-dubiel** [comment]
Hey @rodolphebertozzo!

Perhaps you can just add an empty space after your prepended text?

<img width="855" alt="Screenshot 2022-10-30 at 18 17 36" src="https://user-images.githubusercontent.com/669243/198892143-f2909551-2c8c-4738-a504-33026887c015.png">

**Comment by rodolphebertozzo** [comment]
Hi, actually, this is how I do it, just, maybe adding an option could be something interesting (to avoid having to go through a space), I know I'm really going into details, but it's an idea
