### ISSUE TITLE
URL Parameter in form dynamic data not working with hidden fields

### ISSUE THREAD

**Issue by tommytompkins** [soflyy/breakdance-bugs#484]
1) Create a form inside a popup with a single hidden field
2) For the hidden field's value, go to dynamic data and select URL Parameter and enter the name of the parameter. In my case, I'm using "botid" in my URL like so ?botid=1234
4) Load the form on the front end with ?botid=1234 in the URL and Submit the form
5) Notice how it does not capture the URL parameter in the submission

![Screen Shot 2022-10-30 at 3 47 18 PM](https://user-images.githubusercontent.com/4631803/198901087-209f43ba-dece-4f34-9f57-2c8cbbe6c338.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
