### ISSUE TITLE
Column width bug

### ISSUE THREAD

**Issue by Bonnie-Clyde** [soflyy/breakdance-bugs#487]
Added three columns into a section. When trying to resize the column using the Size > Width percentage it brings up error message instead of adjusting other columns to fill 100%.
Unable to setup a 20-60-20 design.

**Comment by a-dubiel** [comment]
Hey @Bonnie-Clyde I can't reproduce this. Any chance for a screen recording?

**Comment by Bonnie-Clyde** [comment]
Moved to another computer and that 1st problem works, but another one started.


https://user-images.githubusercontent.com/111174477/199199671-98c1adeb-9fbd-4a01-b9da-474ec5abebc3.mp4

**Comment by Bonnie-Clyde** [comment]
Recorded on other computer the first problem.
If I move the mouse cursor away from the input value, then it works.

https://user-images.githubusercontent.com/111174477/199201847-30baadec-2ce0-41ce-a976-cf2fcfa21889.mp4
