### ISSUE TITLE
Registration Form not using standard WP hooks

### ISSUE THREAD

**Issue by matthewbacon** [soflyy/breakdance-bugs#488]
I have a plug-in (Restrict Email Domains by Mahmoud Kassab) that hooks into the registration process to only allow certain email addresses to register (blocks domains unless on a whitelist).  When I use the standard WP registration form the plug-in works as intended (only allowing emails with domains that appear on the whitelist to register and receive a password to activate their account), however, the Breakdance form seemingly bypasses these checks/hooks and allows any domain to register.

As a result I cannot use the Breakdance forms. Is Breakdance bypassing the standard WP code and writing directly to the database? Can Breakdance reference any hooks in the registration process to allow the use of this plug-in and others.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
