### ISSUE TITLE
Fancy Container 1.1 overlay bug

### ISSUE THREAD

**Issue by djrwp** [soflyy/breakdance-bugs#489]
When setting overlay it also overlays elements within the container (see attached with white heading) . I reported the same bug on wrapper link and that was fixed.

<img width="866" alt="Screenshot 2022-10-31 at 14 53 20" src="https://user-images.githubusercontent.com/84224815/199046108-8d7509c6-c1fb-499f-b7e8-4099d27fe315.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
