### ISSUE TITLE
UX improvement, make options more distinctive

### ISSUE THREAD

**Issue by udoro** [soflyy/breakdance-bugs#49]
The options in the panels are a bit indistinctive. Sometimes it's difficult to tell where one start and the other stops... 
so I decided to do a little CSS edit to reflect what I think would be more distinctive and reflect hierarchy within each option. 
The UI team has done a fantastic job, so this is just a suggestion based on my opinion
Please see the screenshots for the original and edited.

SCREENSHOT:
![image](https://user-images.githubusercontent.com/22454125/176311841-1e75ace5-4e8c-4af1-942b-1dd1472a227d.png)

**Comment by vmcosta** [comment]
@udoro Nicely done, I like it a lot.
