### ISSUE TITLE
Classes no longer function

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#490]
When you create a class and assign a CSS property, it works for the first element, but for the following elements, the CSS property of the class to which you assign the same element no longer works

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
