### ISSUE TITLE
Issue with the BETA Breadcrumb feature

### ISSUE THREAD

**Issue by buzzagencyco** [soflyy/breakdance-bugs#492]
When you have a FAQ Rankmath Breakcrumb and a FAQ element on same page, it breaks the design. Using a Global style somehow fixes it?

Loom: https://www.loom.com/share/4ddd87fa6a8544c7970c391d3423838b

**Comment by Spellhammer** [comment]
This is caused by an erroneous parenthesis in the default styles of the breadcrumb separator: https://www.loom.com/share/c447f22f64974184a09088069f9d751c

**Comment by a-dubiel** [comment]
Just FYI this will be addressed with the next release, most likely 1.1 Beta 2.
