### ISSUE TITLE
Youtube Lightweight Load Method not working with ACF oEmbed Content

### ISSUE THREAD

**Issue by vince-pat** [soflyy/breakdance-bugs#496]
Hi,

When using an ACF Field oEmbed Content for displaying a Youtube Video, the Youtube Lightweight Load Method is not working. It looks like the Full Embed is used by default.

Regards,

Vincent

**Comment by cmidgley** [comment]
I am also experiencing this behavior.  If I use ACF dynamic data for the link it video it uses full, but if I enter a URL (no dynamic data) it uses light.

**Comment by cornish-td** [comment]
Also getting this issue, but on a standard video element not using ACF dynamic data for the link. On v 1.1.

https://bfrv2.onyx-sites.io/

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
