### ISSUE TITLE
🔴 Compatibility problem 🔴

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#499]
Breakdance is not compatible with Happy Files.io, when I open the media library, the folders are not displayed, I just have the whole media

**Comment by TrustedSamurai** [comment]
This works fine for me with ver 1.0 of BD.

![image](https://user-images.githubusercontent.com/14268836/199859672-e56c6489-c9f0-417f-a298-3f3f0e1c7b21.png)

Perhaps check if you have any other plugins causing conflict?
