### ISSUE TITLE
Button Text Color Change Not Showing on Frontend

### ISSUE THREAD

**Issue by onenyarko** [soflyy/breakdance-bugs#5]
**CLEARLY and CONCISELY Describe the bug**

**To Reproduce**
1. Go to 'Add a button to a design'
2. Click on 'Change the text color to any color'
3. See error 'preview to frontend to see color doesn't change'

**Screencast**
If applicable, please include a [screencast](https://www.loom.com/) showing the issue.

**Comment by louisreingold** [comment]
We can't reproduce this using the steps provided. Can you provide a screencast showing this problem and open another issue? You can make one free and easily using Loom: https://loom.com.

**Comment by onenyarko** [comment]
Hey Louis, I had it on a local machine, I think that was where the issue was. I have moved my test to a live site and everything seems to work fine. I should close this case.
