### ISSUE TITLE
Sender From Email still "Wordpress" when using the "Forgot Password Form" element

### ISSUE THREAD

**Issue by tommytompkins** [soflyy/breakdance-bugs#500]
1) Add a forgot password form element to your page
2) Send the password reset email
3) check your inbox and notice how it's from the default "Wordpress" when all forms are sending from the correct name. There is no way to edit the from name from what I can see.

I also installed the Easy WP SMTP plugin and changed the name there which works with all other forms. But the password reset email still comes from "Wordpress". 

<img width="528" alt="Screen Shot 2022-11-02 at 8 43 45 PM" src="https://user-images.githubusercontent.com/4631803/199725281-2345f30a-87f1-4b1f-92c2-d2173d5811e0.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
