### ISSUE TITLE
ACF - Upload Field - Dynamic Data Problem

### ISSUE THREAD

**Issue by gatti-dev** [soflyy/breakdance-bugs#502]
ACF - Upload Field isn't working. I set the return value to data-url should i set it to data-array or data-id? Because if a user add a datasheet the link should be on the product detail site but i think there is a bug with ACF to Breakdance but only the ACF upload field. 

![313273572_6006346332718218_5620910226055712464_n](https://user-images.githubusercontent.com/112075216/199735917-327d0abc-200c-4247-b52d-ac3f5792e110.jpg)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
