### ISSUE TITLE
LMS - Templates not working without woocommerce plugin activated

### ISSUE THREAD

**Issue by gatti-dev** [soflyy/breakdance-bugs#503]
We tried Tutor LMS and Learndash. After install on a blank installation only the dashbord was visible.
But if you install Woocommerce and activate it all slugs(paths) are working. 
Same if you deactivate woocommerce its not working again.
So the LMS systems are only woring (templates) when Woocommerce is activated.
I think it has something with the plugin activate hook. Strange Problem, but it would be better not to activate woocommerce to get the LMS templates working.

**Comment by a-dubiel** [comment]
Hey @gatti-dev! Thanks for the report. Can you e-mail support@breakdance.com and we will take a closer look.
