### ISSUE TITLE
Content Toggle not Working 1.1 BETA-1

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#505]
The content Toggle is not working for me. It returns an error and I can't include any content inside it. It's basically just a button with Monthly/Yearly.
Tried clearing the cache, regenerating CSS, and clearing the server cache, but the issue persists. 

![Screen Shot 2022-11-01 at 21 07 52](https://user-images.githubusercontent.com/54561285/199806526-81453f57-b8d8-458b-9a37-71b7af8caca7.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
