### ISSUE TITLE
Overriding Global Styles Not Working in Cart Content - 1.1 BETA 1

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#506]
**_Override Global Styles_** is not working in Cart and Checkout granular elements. 

![Screen Shot 2022-11-03 at 22 16 02](https://user-images.githubusercontent.com/54561285/199836348-5a6b3a27-4ab9-4a70-ba7f-56499399b1b6.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
