### ISSUE TITLE
ACF options Page and new Element repeater field not working

### ISSUE THREAD

**Issue by marcel2008** [soflyy/breakdance-bugs#508]
![1D812A14-BB49-4DF0-9F42-5595C13794EE](https://user-images.githubusercontent.com/58587248/199859074-8f2e84d5-5c44-4b92-9423-6ec9eb9e6bc4.jpeg)
![A059B794-4B48-405C-9EE4-DBA7C0C5A322](https://user-images.githubusercontent.com/58587248/199859078-9e8dcaf8-95ee-488c-99d6-d443c9b5f88e.jpeg)
![6108459F-BDE1-4FE7-BA72-6BB89CD77B74](https://user-images.githubusercontent.com/58587248/199859079-23de790c-e6b6-4138-ba5f-22f0840f1535.jpeg)

I have added a script to load an ACF option page with subpages. I then added an ACF repeater to one of the subpages. Next I tried to build a global block with those repeater fields. Than can be chosen but don’t show any value in the builder. When trying to ad the new repeater element to a page and choosing the global block an repeater field nothing is shown. This can be seen in the provided screenshots.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
