### ISSUE TITLE
Can't align text in a Frequently Asked Questions block element

### ISSUE THREAD

**Issue by joethseo** [soflyy/breakdance-bugs#51]
I had a Frequently Asked Questions block element in a section and the section was set to align centrally.

This made the FAQ block text align centrally but I wanted it to align to the left.

I [posted on FB](https://www.facebook.com/groups/breakdanceofficial/posts/5187402914628295/) and a workaround is to put the FAQ block in a DIV but Louis suggested reporting it here as its missing controls, so a bug.

**Comment by louisreingold** [comment]
We've prevented the section alignment from affecting the FAQ in beta 3, and will ship typography alignment controls for the FAQ in beta 4.
