### ISSUE TITLE
Breakdance Beta v1.1 - Woocommerce "Cart Contents" block on cart page

### ISSUE THREAD

**Issue by bhartlenn** [soflyy/breakdance-bugs#510]
1) Add "Cart Contents" block(and any other of the new cart partial blocks) to cart page and save
2) Go to front end and add a product to cart and visit cart page
3) Try to remove product from cart contents with "X" button, or by changing quantity to 0
4) cart contents does the ajax refresh, but cart item stays in cart

If the cart empty message block is added to the cart page, it correctly says the cart is empty, mini cart count also updates

Console has warning about cookie shown in screenshot-2.

<img width="1186" alt="screenshot-1" src="https://user-images.githubusercontent.com/791598/200106115-cf7cc69a-7103-4ae5-a2de-36e5268273c6.png">
<img width="1278" alt="screenshot-2" src="https://user-images.githubusercontent.com/791598/200106118-8de0d0ea-677e-4347-b4c3-aa161b2cc645.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
