### ISSUE TITLE
1.1 beta 1 - Issues with connecting a BD Gallery element to a ACF gallery field

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#512]
There are all sorts of issues:

- using a gallery based on an ACF gallery field inside a section where the background slider is set to another ACF gallery field returns an empty gallery element on the frontend.
- on the same page using more than one BD gallery element connected to each another ACF Gallery field gives all sorts of weird problems.

**Comment by mikehenze** [comment]
Is there any news regarding the support for acf gallery?
Can we expect it in 1.1 for example?

**Comment by a-dubiel** [comment]
Hey @adkoen thank you for the feedback. Indeed this feature is much needed. Planning this for 1.2.

**Comment by a-dubiel** [comment]
>using a gallery based on an ACF gallery field inside a section where the background slider is set to another ACF gallery field returns an empty gallery element on the frontend.
> on the same page using more than one BD gallery element connected to each another ACF Gallery field gives all sorts of weird problems.

Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Comment by mikehenze** [comment]
I have sent you a mail.
Issue is not fixed.
