### ISSUE TITLE
1.1 Beta 1 - Cannot load Global Blocks, Templates when WP Debug is activated

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#513]
I made a small recording:
https://share.webmatic.be/geuyLZp8

**Comment by louisreingold** [comment]
Various errors that appears with WP_DEBUG enabled have been addressed over the last 7 months. If you encounter this issue or a similar one with WP_DEBUG enabled, please open a new issue and include the full text of the error that appears in the error log file.
