### ISSUE TITLE
popup builder z-index is 10000 when not open

### ISSUE THREAD

**Issue by bhartlenn** [soflyy/breakdance-bugs#514]
1) Create a new popup, and apply it to everywhere
2) Visit front end
3) .bde-popup element has default css that causes it to be on top of some other page content, and it gets in the way because it is hidden with visibility and opacity. I can't scroll the page when the mouse pointer is over the hidden popup, and can't click or hover over links that are behind the hidden popup element: .bde-popup
```
/* popups.css:5 */
.breakdance .bde-popup, .breakdance .bde-popup .breakdance-popup {
  opacity: 0;
  visibility: hidden;
}
```

```
/* post-400-defaults.css:1 <- post 400 is the popup I created */
.bde-popup {
  width: 100%;
  height: calc(100% - var(--wp-admin--admin-bar--height, 0px));
  position: fixed;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  top: var(--wp-admin--admin-bar--height,0px);
  left: 0;
  z-index: 10000; /* This line is the bug I think */
}
```

I temporarily fixed this by editing the popup, and going to Popup Settings >> Wrapper >> Layout >> Advanced, and setting the z-index to -1000(largely negative to be safe).

Then the popup was hidden, and behind everything else, but when it was opened it was layered behind the sticky header, and much of the page content I had in place. The following addition to the popup Settings >> Advanced >> Custom css fixed that:
```
%%SELECTOR%%.breakdance-popup-open {
  z-index: 120; 
}
```

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
