### ISSUE TITLE
When Mini Cart is used in the upper part; The H2 tag (Basket) breaks the Heading flow.

### ISSUE THREAD

**Issue by orhanbilikvar** [soflyy/breakdance-bugs#515]
![outline](https://user-images.githubusercontent.com/48365764/200270771-f7d2a67c-8ee9-45a9-bfb6-212171c62a1e.jpg)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
