### ISSUE TITLE
Editing .bde-heading selector

### ISSUE THREAD

**Issue by simonclay** [soflyy/breakdance-bugs#517]
Because Breakdance removes all margins from the header element (I don't know why), I would like to add top abd bottom margin globally. But when Editing Selector .bde-heading changing the margin has no effect. 

Here's a video explaining...

https://www.loom.com/share/87b673bd04f244078005dadb0b189242

**Comment by mikeingz** [comment]
if you want to change them globally, use h1,h2,h3... as a selector instead of using the class.

**Comment by simonclay** [comment]
Thanks @mikeingz I tried that first, but that has no effect. Is it the same for you?

**Comment by mikeingz** [comment]
You can use this full selector : .breakdance .bde-heading, h1,h2,h3

.breakdance .bde-heading will affect all the heading elements
h1,h2,h3 will affect the headings in the rich text and text elements
