### ISSUE TITLE
Gallery not pulling caption from Wordpress Caption

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#518]
I have hundreds of images in my media folder and they all have captions. Can we have the option to use these in the gallery rather than a seperate field in the builder?

I'd also appreciate it if the caption can allow for html code so that I can include a link in the caption for image credits.

Thanks.

**Comment by a-dubiel** [comment]
Hey @LambMediaGroup thanks for your report. This has been implemented in the latest release 1.1 Beta 2.
