### ISSUE TITLE
ACF missing from dynamic data selection screen

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#519]
I've seen videos of people selecting ACF content from the "Insert Dynamic Data" window but I don't have this at all despite having ACF pro installed and working.

**Comment by a-dubiel** [comment]
Hey @LambMediaGroup can you provide a screen recording or anything we can look at?

**Comment by a-dubiel** [comment]
When you want to attach dynamic data to image we only return dynamic data returning image URLs (ie. featured image). That's why the rest of the options that are not images are greyed out. Please watch [this video](https://www.youtube.com/watch?v=eYOu1TJcrSc) where we go over the dynamic data and how to reference ACF fields inside the builder.

**Comment by LambMediaGroup** [comment]
I get the same issue when I add a heading or text element and go to dynamic data there as you can see here. I started the screen recording by showing all the ACF fields associated with the page and then going into breakdance to try and add them but they don't show up.

[](https://www.staging6.whichgreekisland.co.uk/wp-content/uploads/2022/11/screen-capture-2.webm)

**Comment by LambMediaGroup** [comment]
I've updated to beta 2 and I now get the ACF section but it's still not picking up all the custom fields that are applied to a page, I suspect it's something to do with the fact that I have 2 different ACF field groups applied as it's picking up the fields from one but not the other.

**Comment by LambMediaGroup** [comment]
@a-dubiel 

I think I've got a bit of extra info on this one, if I edit the page directly I get all the correct ACF fields but if I edit the template that affects that same page then it doesn't bring up all the ACF fields.

With the point of templates being that I don't have to edit each page separately it would be handy if the templates would see the same ACF fields as the page that is being previewed.

**Comment by louisreingold** [comment]
Between this report and the latest release of Breakdance, numerous enhancements have been made to the ACF integration to support fields from options pages, term fields, and also fix bugs related to ACF fields not showing when they should.

If you encounter further issues with an ACF field not appearing in the dynamic data chooser, please open a bug report with exact steps to reproduce - include all the details of the field and associated field group (such as rules on where it is set to apply).
