### ISSUE TITLE
Image Comparison Shows error in Beta 1.1

### ISSUE THREAD

**Issue by marcel2008** [soflyy/breakdance-bugs#521]
![image](https://user-images.githubusercontent.com/58587248/200784044-8fe656ba-b8fc-4aa3-a01c-4e8f8b4c4056.png)

Once I select the images and save, this error pops up and I cant get rid of it.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
