### ISSUE TITLE
Mailerlite connection issue

### ISSUE THREAD

**Issue by jcwerb** [soflyy/breakdance-bugs#522]
Hi, I'm trying to connect a simple form to Mailerlite and upon testing get the following error:

[MailerLite]: Email address is required.

See attached as well. I've double-checked the form setup.

Thanks!

![screenshot-www orcadiadesign co uk-2022 11 09-11_02_58](https://user-images.githubusercontent.com/13662691/200814483-fd8a0186-4594-44a0-9fc7-ce254ac17bb4.png)

**Comment by louisreingold** [comment]
Mailerlite has two API versions - did you use the new version or the old version? You might need to use the old version.

**Comment by jcwerb** [comment]
Thanks! Will check and let you know if there are any further issues.

**Comment by louisreingold** [comment]
Closing as no response.
