### ISSUE TITLE
Dynamic Data for ACF Image not Available in Header Builder

### ISSUE THREAD

**Issue by cornish-td** [soflyy/breakdance-bugs#523]
I'm building a custom header to show on all location custom post type posts, so that the logo uploaded to the post appears in the header of the site next to the main site logo. Despite having the ACF field set and a logo uploaded, in the header builder when inserting the image field I can't find anywhere to pull that data from the ACF field. Please help!

Is this a bug? Will it be fixed in 1.1? 

Here's a video: https://www.loom.com/share/7950e89a426f4ef89c0ec3e8bb6ee49d

Thank you.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
