### ISSUE TITLE
iPad air 4 not getting tablet settings

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#524]
when looking at the site on an iPad air 4 it's getting the desktop options rather than tablet landscape which is a bit frustrating as it squashes the content up too much.

I've checked on an older ipad and it's picking up the correct tablet landscape settings so I think it's probably the higher resolution on the iPad air 4. 

Is there any way of fixing this?

**Comment by a-dubiel** [comment]
> Is there any way of fixing this?

Feel free to create a custom breakpoint. Looks like iPad 4 is at `1180px` and our tablet settings are at `1120px`.
