### ISSUE TITLE
Nofollow not working on Text Link

### ISSUE THREAD

**Issue by orhanbilikvar** [soflyy/breakdance-bugs#525]
![00](https://user-images.githubusercontent.com/48365764/201019202-38149c56-bfd0-41cc-93a9-f090c565f9de.jpg)
![01](https://user-images.githubusercontent.com/48365764/201019223-b2a32183-65a1-4c17-8e18-6a8ff0bf0605.jpg)

**Comment by a-dubiel** [comment]
Hey @orhanbilikvar are you using a plugin to support `rel` attributes?

**Comment by orhanbilikvar** [comment]
Rank Math exists but is turned off
![03](https://user-images.githubusercontent.com/48365764/201151839-87180d1f-74d2-495d-ac31-c69b72d9c1aa.jpg)

**Comment by a-dubiel** [comment]
Hey @orhanbilikvar it turns out you can already do that in Breakdance via Advanced tab.

<img width="280" alt="Screenshot 2022-11-11 at 08 46 17" src="https://user-images.githubusercontent.com/669243/201291724-04ac5878-f961-470a-bb9b-b55c526a3833.png">

**Comment by orhanbilikvar** [comment]
thx :)
