### ISSUE TITLE
Menu Builder - Link doesn't change color while hovering

### ISSUE THREAD

**Issue by bpbezerra** [soflyy/breakdance-bugs#53]
Even after setting link hover color, it won't change colors when hovered
https://postimg.cc/6789JRxL

**Comment by neeckola** [comment]
Live site here: https://breakdance.brunoswebstudio.com/evernote-mega-menu/

**Comment by louisreingold** [comment]
The Menu Link element isn't supposed to have design controls (will be fixed in the next update).

Set the color of the menu's top-level links at Desktop Menu > Links > Typography.
