### ISSUE TITLE
Empty categories are not listed in Condition

### ISSUE THREAD

**Issue by orhanbilikvar** [soflyy/breakdance-bugs#530]
I guess this is a choice, not a bug. But not so good for webmasters.
On the website I am currently making, I will wait for the editor to enter content. I'll check to see if he has added articles. If it is, I will add the categories to the condition. It's not a good work process.

*I'll solve it with php conditional.

![04](https://user-images.githubusercontent.com/48365764/201280656-bd3bfb66-75b6-45dc-a78a-8d47841d8b8f.jpg)
![05](https://user-images.githubusercontent.com/48365764/201280670-0c8891e7-6902-439a-89cc-61033484eb13.jpg)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
