### ISSUE TITLE
1.1 Beta Form input fields not same height

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#531]
Not all input fields has the same height.

<img width="1104" alt="input-fields-heights" src="https://user-images.githubusercontent.com/56388399/201340283-d774c1eb-d379-438e-bce1-7388b26df073.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
