### ISSUE TITLE
Advanced Slider - Full width not working

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#533]
I want my slider to be full width but setting it inside the styles option work
![image](https://user-images.githubusercontent.com/51177627/201519467-44db4001-b013-4f8c-9a07-f0ca111509ba.png)

But it works when applying the 100% via advanced setting.
![image](https://user-images.githubusercontent.com/51177627/201519493-72ca3cba-b093-432d-bf58-4bfb45804a4e.png)

**Comment by dancerist** [comment]
Just found that it works if using 100vw. Which also makes sense if I use vw value. but I thought 100% should also work the same,

**Comment by a-dubiel** [comment]
Hey @dancerist you probably do not need some of the settings. 

Here is how I would do it https://www.loom.com/share/428edb30bfc14d489cc24e5b2c70ff5f

**Comment by dancerist** [comment]
Thanks. I dont have this problem after update. Not sure how but it works now.
