### ISSUE TITLE
Can't Import Breakdance Settings

### ISSUE THREAD

**Issue by nerdtech** [soflyy/breakdance-bugs#536]
Hello,

I can't seem to import Breakdance settings on either the stable or beta 1.1 versions. I can export the JSON settings file but when importing it I get an error message. Please see screencast.

https://www.loom.com/share/a4fd2039d1e74999808fbdf35a7b0187

Thanks.

**Comment by a-dubiel** [comment]
This should be fixed in most recent release 1.1 Beta 2. Thanks for your reprot.
