### ISSUE TITLE
Section Background Overlay: Desktop overlay not applied/showing on smaller screen.

### ISSUE THREAD

**Issue by nicolaskid** [soflyy/breakdance-bugs#54]
In my section, I add a slideshow background and an image overlay. But the overlay is no longer showing starting at the second breakpoint "Tablet landscape" and below. So I ended up adding again the same image for each breakpoint resulting to this(see img attached). I'm concerned cause maybe I'm loading 5 images every time the page loads??

![image](https://user-images.githubusercontent.com/51177627/176798096-baf10852-926a-4a8d-81bb-74a6ff5e99a8.png)

**Comment by louisreingold** [comment]
This is solved in beta 4.
