### ISSUE TITLE
Editing Template Search Results Breaks When Setting Custom Permalinks

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/breakdance-bugs#541]
Wordpress Version: 6.1.1
Breakdance Version: 1.1-beta.1

If you set Wordpress to custom permalinks like this:
/%category%/%postname%/

Then it is no longer possible to edit the default search results template as it returns the 404 error

**Comment by JeusuDigital** [comment]
Issue still persists in breakdance-1.1-beta.2
Seems to be: /%category%/ that causes it to break

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
