### ISSUE TITLE
All page not showing on dropdown menu in pop up conditions

### ISSUE THREAD

**Issue by Pagemark-Solutions** [soflyy/breakdance-bugs#543]
When I try to choose my home page in pop up conditions, my page isn't showing on drop down..
![Screenshot 2022-11-17 134030](https://user-images.githubusercontent.com/118454444/202465182-f04e1025-3cff-4fed-a8cd-6e2dc9920470.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
