### ISSUE TITLE
Button Pop Up

### ISSUE THREAD

**Issue by Pagemark-Solutions** [soflyy/breakdance-bugs#544]
![Screenshot 2022-11-17 133825](https://user-images.githubusercontent.com/118454444/202466839-083939be-1663-46c3-b7e8-935ff2c34f60.png)

Trying to trigger my pop up to open when button is clicked but it's not working. Settings I used are in the screenshot, am I missing something or is this also a bug?

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
