### ISSUE TITLE
WP Menu Doesn't Respect Menu Structure 

### ISSUE THREAD

**Issue by nerdtech** [soflyy/breakdance-bugs#545]
hello,

If you create a menu that has a nested level and use the WP Menu element to display it it doesn't show it as nested. The nested items are displayed underneath instead of as a side dropdown.

As a side note there doesn't appear to be a way to create this kind of menu using the menu builder element either unless I'm missing something.

Please see loom recording for example...

https://www.loom.com/share/e2120139865340bf996dfc4f1044d14f

thanks

**Comment by nerdtech** [comment]
Apparently this is done by design because it's deemed "bad practice" so I'm closing the ticket.

**Comment by siparker** [comment]
i have just come across this issue. why is it bad practice?

**Comment by nerdtech** [comment]
> i have just come across this issue. why is it bad practice?

Because navigation menu's should aid in navigating around the site and if the navigation contains items nested multiple deep then users are likely to get confused. You should either try creating everything top level or if you need to categorise nav items then use something like a mega menu... that's not to say you can never nest nav items just limit the practise... here is a good article on it:  [The Rules For Modern Navigation](https://uxbooth.com/articles/the-rules-for-modern-navigation/)
