### ISSUE TITLE
Error with Animation on a Popup

### ISSUE THREAD

**Issue by vince-pat** [soflyy/breakdance-bugs#549]
After adding a link (action type) on an object (in my case an icon) with a Popup as a link, when I edit the Popup and try to apply an Entrance or Exit Animation, the following error appears (see the screen capture below) :

"An error occurred while running an inline script from "onPropertyChange" for element with ID "100". Error:"TypeError: Cannot read properties of undefined (reading 'progress')"

![screen-capture](https://user-images.githubusercontent.com/34057501/203110796-130900e9-7754-4ea6-8b04-27cacc5e6953.png)

(Error still here with BreakDance 1.1 Beta 2)

On the Front the popup does not even display.

**Comment by alextest107** [comment]
Its an error from 1.0 alfa version, its still there...

**Comment by alextest107** [comment]
PLEASE FIX IT I NEED ANIMATION

**Comment by alextest107** [comment]
Fixed??

**Comment by alextester1x** [comment]
**### still not fixed**

**Comment by alextester1x** [comment]
1. **Not fixed...**

**Comment by alextest107** [comment]
Not fixed

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Comment by entercash1** [comment]
![image](https://user-images.githubusercontent.com/48694545/211901487-30a73e2d-8e9a-4b88-8d95-02e6f181255c.png)
still cant make animation on popups. please fix it

**Comment by WpUser10** [comment]
> ✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail [support@breakdance.com](mailto:support@breakdance.com) and we will take a closer look. Make sure to provide working URL to your website and login credentials.

please have a look
https://github.com/soflyy/breakdance-bugs/issues/656

**Comment by WpUser10** [comment]
[a-dubiel](https://github.com/a-dubiel)

**Comment by WpUser10** [comment]
Author, [vince-pat](https://github.com/vince-pat) i have tested this solution and it works on backend and frontend also.
/wp-content/plugins/breakdance/subplugins/breakdance-elements/dependencies-files/popups@1/popup-animations.js
just add string this.tween = this.createTween();
to function
play() {
return this.tween.progress(0).play();
}

**and error will gone.**

**Comment by FelipeMarcos** [comment]
What's your browser and version?

**Comment by WpUser10** [comment]
> What's your browser and version?

the latest chrome and opera and firefox, all of them updated.

i dont know but for me tween was undefined

**Comment by FelipeMarcos** [comment]
> i dont know but for me tween was undefined

Do you have "prefer reduced motion" enabled by any chance? I managed to reproduce this error by enabling this option. 
This error will go away in the next major version, but animations in Breakdance are disabled if this option is on.

**Comment by WpUser10** [comment]
> > i dont know but for me tween was undefined
> 
> Do you have "prefer reduced motion" enabled by any chance? I managed to reproduce this error by enabling this option. This error will go away in the next major version, but animations in Breakdance are disabled if this option is on.

sorry did not understand where this "prefer reduced motion" option can be.
but i have disabled all animations in windows by default, i has that issue on all windows versions before (7,10,11)

**Comment by WpUser10** [comment]
**### ALLRIGHT! that error appears when you have DISABLED "animated elements control inside windows" in performance settings** of system settings of computer in windows!!!!!!
![image](https://user-images.githubusercontent.com/48694545/213814343-0b9a86f3-84ba-4acc-a3f6-1821480b4505.png)

### **PROBLEM SOLVED!**
