### ISSUE TITLE
Section - Background Image Effects Not Working (ie; Blur)

### ISSUE THREAD

**Issue by wpdv** [soflyy/breakdance-bugs#55]
Section > Background > Image (Full & Cover) > Overlay > Effects > Blur (4px). No blur effect

**Comment by louisreingold** [comment]
Overlay > Effects only affects the overlay. It does not affect the image.

Put your image in the Overlay section.

https://www.loom.com/share/d39e3b4f6c8648e2ae770bfb44449905

**Comment by wpdv** [comment]
Hi Louis, thank you for the video. I removed the image from the background and added it in the overlay, however the image will not display on the front side. It does display (and is blurred) correctly in the builder for desktop, however, all other viewports are blank. Thoughts?

**Comment by wpdv** [comment]
Screencast: https://www.dropbox.com/s/nw0bbm7mj1yanmm/Breakdance-overlay-issue.mov?dl=0

**Comment by louisreingold** [comment]
Solved in beta 4.
