### ISSUE TITLE
Custom Code - Conditions

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#551]
You can extend your condition manager to Custom Code, but to do so, you need to convert the current functionality screen into a template, so you can customize the presence of custom code where you want it

**Comment by louisreingold** [comment]
Please elaborate.

**Comment by louisreingold** [comment]
If this is a bug report, please open a new issue with exact steps to reproduce.

If this is a feature request, please post it at https://breakdance.canny.io/features with more details.
