### ISSUE TITLE
Footer and menus

### ISSUE THREAD

**Issue by StaggerLeee** [soflyy/breakdance-bugs#555]
Any menu inside footer make it impossible to stick footer to the bottom, due to the dropdowns in menu items and hight is then wrongly calculated. It is allways empty space under the footer, high about how high is longest menu dropdown.

- If you add one new option to show dropdowns above menu items I believe it would fix problem.
- Or solution is to use new custom menu without submenus, for footer only.

Now, maybe something to take a look at because footer is very often place with different menus.
(Lost about whole day on troubleshooting it, but now I know why.)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
