### ISSUE TITLE
Form Builder Conditions with Checkbox or Radio requires Label (empty label won't work with condition)

### ISSUE THREAD

**Issue by raabmar** [soflyy/breakdance-bugs#556]
Form Builder Conditions with Checkbox or Radio requires label

**Steps**
- Add checkbox field to Form Builder and add an option e.g. "Add different shipping address"
- Add another text field **without a label** for the address and add a dynamic condition (goal: show this field only when the checkbox of the other field was ticked)

**Expected result**
- I would expect to be able to set the condition based on the checkbox field

**Actual result**
- I cannot pick the checkbox field and use it for the condition

**Workaround**
- Add a label to the checkbox field (and perhaps hide it with CSS when it is not wanted to show)

Without adding the label the feature won't work. I cannot select the field. In the screenshot it's possible because there is a label for the checkbox field.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/15885290/203150828-7e6f67ed-1307-4e98-bd1f-c31c60a60ce0.png">

**Comment by a-dubiel** [comment]
Hey @raabmar what version are you on? I cannot reproduce this.

**Comment by raabmar** [comment]
@a-dubiel Version 1.0.3 - that's interesting that you cannot reproduce it, it looked so obvious as a bug or missing feature. Could we have a misunderstanding? What version are you on?

**Comment by a-dubiel** [comment]
This has been addressed in the latest 1.1 Beta. Feel free to update it or wait for 1.1 RC which will be released very soon.
