### ISSUE TITLE
Form Builder - allow usage of conditions also for HTML fields

### ISSUE THREAD

**Issue by raabmar** [soflyy/breakdance-bugs#557]
I noticed I am not able to set up conditions for HMTL fields.

**use case:**
Imagine I have an entire block with a few fields
This entire block should only shown when some conditions are fulfilled (e.g. checkbox ticked)
The block with the fields also comes with a heading (HTML field)

I would like to be able to also hide the HTML field when the condition is not met.

Right now, I can do this with most of the fields, but not with HTML fields

<img width="591" alt="image" src="https://user-images.githubusercontent.com/15885290/203161355-59854068-37c9-4ee2-abb1-c617a694f30f.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
