### ISSUE TITLE
Breakdance 1.1 Beta 2- Custom field (field type taxonomy)

### ISSUE THREAD

**Issue by ArseneNB** [soflyy/breakdance-bugs#559]
Dynamic content : Custom field (field type taxonomy) don't appear in the "insert Dynamic Data" popup no more.

**Comment by a-dubiel** [comment]
Can't reproduce. What you might be looking for is "Post Terms". 

<img width="899" alt="Screenshot 2022-12-06 at 13 56 19" src="https://user-images.githubusercontent.com/669243/205918662-67b8ba47-6055-4a34-a502-220f291e2362.png">
