### ISSUE TITLE
Breakdance 1.1 Beta 2-advanced tabs

### ISSUE THREAD

**Issue by ArseneNB** [soflyy/breakdance-bugs#560]
The advanced tabs do not work properly

**Comment by a-dubiel** [comment]
Hey @ArseneNB can you provide more details? Screenshot? Errors?

**Comment by ArseneNB** [comment]
Just create an advanced tab and try to navigate through the tabs.

Thanks

Le mar. 22 nov. 2022 à 12:54, Andrzej Dubiel ***@***.***> a
écrit :

**Comment by dancerist** [comment]
> 

The advanced tab is working as is on mine. You should provide more info as to what's not working properly.
