### ISSUE TITLE
Add support for conditions by month

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#561]
"Hi, I want to set a condition based on the current season of the year. However, I'm not sure if conditions by month are supported? I can't find it"

Please refer to the original post 
https://www.facebook.com/photo?fbid=5554834504613708&set=gm.5600894973279085&idorvanity=5118076864894234

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
