### ISSUE TITLE
Menu enhancement - auto close the nav canvas when clicking an on page link or anchor links

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#562]
Please refer to original FB post 

https://www.facebook.com/groups/breakdanceofficial/posts/5602957043072878/?comment_id=5603590199676229&reply_comment_id=5603894982979084&notif_id=1669098237533609&notif_t=group_comment&ref=notif

**Comment by geektrg** [comment]
https://www.facebook.com/groups/breakdanceofficial/permalink/5569217773113472/

Check-out the above as well...
