### ISSUE TITLE
Table of contents jumping from first to last item.

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#563]
Hi, when I use the table of contents it jumps from the first item to the last one as soon as I start scrolling the mouse. Clicking the items does make it jump to the correct place but it still doesn't highlight the correct item.

I think it was working at first but I then moved each heading and text section into a div (to give it the white background and shadow) and then this issue started.

I've added a video where you can see me scrolling and clicking around and what happens in the table of contents element.

[screen-capture-4[1].webm](https://user-images.githubusercontent.com/117674105/203513107-38371bcc-0446-4375-b227-3fc1b2f572aa.webm)

**Comment by a-dubiel** [comment]
Hey @LambMediaGroup thanks for your report. Can you try adding a custom class or ID to the content column and reference this column in "TOC / Advanced / Container Selector".  Let me know if this works.

**Comment by drewzb** [comment]
@a-dubiel Hi, I just tried it and it doesn't work. If I add a custom class to the content column, the TOC doesn't recognize items in a different (but same class) column.

**Comment by 00x1a** [comment]
I confirm this issue. Something is messing with the scrolltrigger for the table of contents element and also animation sticky offset Unfortunately I can not pinpoint the reason for this but I had it happen in multiple projekts now. Interestingly when setting up a new site and building this setup first and fresh everything works. Then when continuing to build the project somwhere along the way it breaks.

**Comment by louisreingold** [comment]
We significantly changed the JS and other logic for the TOC element in Breakdance 1.5 Beta 1. 

If you encounter further issues with the TOC, please open a new GitHub issue for each individual problem.

And if it's solved all of these, I'd love to hear back here as well!
