### ISSUE TITLE
Table of contents not sticking properly

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#564]
I've tried all the various sticky options for the table of contents and cannot get it to work. I want it to stick underneath my sticky header, I've found settings that work in the breakdance editor but when looking at it on the frontend I get different results.

I've created a video showing what settings I have and how it behaves on the front end vs the back end.

[screen-capture (7).webm](https://user-images.githubusercontent.com/117674105/203518711-79192897-0c12-4697-81c6-041fc9b0763b.webm)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
