### ISSUE TITLE
Feature request - Add offset to table of contents

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#565]
When you use the table of contents and click on one of the items it brings that item to the top of the page, if you're using a sticky header this then covers that item which means it's not really gone to the correct place.

Please add an offset option so that we can add the sticky elements height in and stop this from happening. This would also need to have responsive options as the header size may be responsive too.

Thanks.

**Comment by drewzb** [comment]
Yes I am having the same issue. TOC isn't usable when there is a sticky header. The target location gets buried under the header.

**Comment by marcel2008** [comment]
+1 on that. ToC not realy uaseble at this stage. An offset would help.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
