### ISSUE TITLE
Feature Request: Allow links in gallery captions

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#566]
I use the photo captions to give credit to the people who uploaded images to my site and link back to their image on Instagram, Flickr or wherever. It would be great if the caption would allow links, currently it gives the following error when you add an a href into the caption

![image](https://user-images.githubusercontent.com/117674105/203538280-af6e75f2-0f77-4a06-9109-8442b7e9a7e9.png)

**Comment by ajlcomputers** [comment]
Is this likely to be done? Im having this issue and can’t use breakdance until it’s fixed.

**Comment by a-dubiel** [comment]
Currently not planned. Feel free to suggest this in [Canny](https://breakdance.canny.io/element-requests?sort=top).
