### ISSUE TITLE
Repeater tab using repeater element

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#568]
Any chance we can do a tabs repeater? I tried making a global template - adding tab element - choose a repeater, and not working. But I am convinced my method won't work because of how the elements are structured. What ends up happening is it repeats the tab parent, not the items themselves. 
![image](https://user-images.githubusercontent.com/51177627/203772780-6d7ee92d-b025-45ba-95e8-81fdcdbd7cf7.png)

However, it somehow works using FAQ element but my 3rd repeater item is not showing? It should show day 1 day2 and day 3. But day 3 is empty
![image](https://user-images.githubusercontent.com/51177627/203776351-1fdd6f85-cf60-4e6b-b881-84b88e04636a.png)

**Comment by a-dubiel** [comment]
Hey @dancerist thanks for the suggestion. It's a quite complex one. Currently we are not planning on creating such an element but you can come really close using Advanced Tabs. We are also working on Advanced Accordion which might also satisfy your use case. Stay tuned for more updates.
