### ISSUE TITLE
Post Meta Error

### ISSUE THREAD

**Issue by onenyarko** [soflyy/breakdance-bugs#57]
When I add a comment divider this is the error I get.

{"type":"INTERNAL_SERVER_ERROR","errorDetails":{"type":"Error","message":"Undefined constant \"type\"","code":0,"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/subplugins/breakdance-elements/elements/Post_Meta/ssr.php","line":23,"trace":[{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/subplugins/breakdance-elements/elements/Post_Meta/ssr.php","line":23,"function":null,"class":"Error","args":["Undefined constant \"type\""],"snippet":{"18":"if ($nbmeta != 0) {\n","19":"\n","20":"for ($xm = 0; $xm <= $nbmeta; $xm++) {\n","21":"\n","22":"    // common datas\n","23":"    $datatype = (string) ($propertiesData['content']['content']['meta_data'][$xm][type] ?? '');\n","24":"    $databefore = (string) ($propertiesData['content']['content']['meta_data'][$xm][before_text] ?? '');\n","25":"    $dataicon = (string) ($propertiesData['content']['content']['meta_data'][$xm][icon]['svgCode'] ?? '');\n","26":"    $datalink = (bool) ($propertiesData['content']['content']['meta_data'][$xm][link] ?? false);\n","27":" \n"},"startingLine":18},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/plugin/elements/Element.class.php","line":243,"function":"include","class":null,"args":[],"snippet":{"238":"        if ($ssr_file_path) {\n","239":"            // Include the file if it exists without blowing up\n","240":"            /**\n","241":"             * @psalm-suppress UnresolvableInclude\n","242":"             */\n","243":"            if(!@include $ssr_file_path) {\n","244":"                ob_end_flush();\n","245":"                return getSsrErrorMessage(\"This element doesn't have a ssr.php file\");\n","246":"            }\n","247":"\n"},"startingLine":238},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/plugin/render/ajax-server-side-render.php","line":49,"function":"ssr","class":"Breakdance\\Elements\\Element","args":[],"snippet":{"44":"        /**\n","45":"         * @psalm-suppress MixedMethodCall\n","46":"         * @var \\Breakdance\\Elements\\Element\n","47":"         */\n","48":"        $element = new $elementSlug();\n","49":"        $ssrResult = $element::ssr($properties ?: [], $parentProperties ?: [], true);\n","50":"\n","51":"        return [\n","52":"            'html' => $ssrResult,\n","53":"            'postsGeneratedCssFilePaths' => (object) ScriptAndStyleHolder::getInstance()->getPostsGeneratedCssFilePaths()\n"},"startingLine":44},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/plugin/ajax/api.php","line":93,"function":"Breakdance\\Render\\serverSideRender","class":null,"args":[],"snippet":{"88":"            }\n","89":"\n","90":"            try {\n","91":"                /** @var mixed $return_value */\n","92":"                /** @psalm-suppress MixedAssignment */\n","93":"                $return_value = call_user_func_array($callback, array_values($callback_args));\n","94":"            } catch (Exception $callback_exec_exception) {\n","95":"                throw new Exception($callback_exec_exception->getMessage(), 500, $callback_exec_exception);\n","96":"            }\n","97":"\n"},"startingLine":88},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/plugin/ajax/api.php","line":93,"function":"call_user_func_array","class":null,"args":[],"snippet":{"88":"            }\n","89":"\n","90":"            try {\n","91":"                /** @var mixed $return_value */\n","92":"                /** @psalm-suppress MixedAssignment */\n","93":"                $return_value = call_user_func_array($callback, array_values($callback_args));\n","94":"            } catch (Exception $callback_exec_exception) {\n","95":"                throw new Exception($callback_exec_exception->getMessage(), 500, $callback_exec_exception);\n","96":"            }\n","97":"\n"},"startingLine":88},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-includes/class-wp-hook.php","line":307,"function":"Breakdance\\AJAX\\{closure}","class":null,"args":[],"snippet":{"302":"\n","303":"\t\t\t\t// Avoid the array_slice() if possible.\n","304":"\t\t\t\tif ( 0 == $the_['accepted_args'] ) {\n","305":"\t\t\t\t\t$value = call_user_func( $the_['function'] );\n","306":"\t\t\t\t} elseif ( $the_['accepted_args'] >= $num_args ) {\n","307":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], $args );\n","308":"\t\t\t\t} else {\n","309":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], array_slice( $args, 0, (int) $the_['accepted_args'] ) );\n","310":"\t\t\t\t}\n","311":"\t\t\t}\n"},"startingLine":302},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-includes/class-wp-hook.php","line":331,"function":"apply_filters","class":"WP_Hook","args":[],"snippet":{"326":"\t *\n","327":"\t * @param array $args Parameters to pass to the callback functions.\n","328":"\t */\n","329":"\tpublic function do_action( $args ) {\n","330":"\t\t$this->doing_action = true;\n","331":"\t\t$this->apply_filters( '', $args );\n","332":"\n","333":"\t\t// If there are recursive calls to the current action, we haven't finished it until we get to the last one.\n","334":"\t\tif ( ! $this->nesting_level ) {\n","335":"\t\t\t$this->doing_action = false;\n"},"startingLine":326},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-includes/plugin.php","line":476,"function":"do_action","class":"WP_Hook","args":[],"snippet":{"471":"\t} elseif ( is_array( $arg[0] ) && 1 === count( $arg[0] ) && isset( $arg[0][0] ) && is_object( $arg[0][0] ) ) {\n","472":"\t\t// Backward compatibility for PHP4-style passing of `array( &$this )` as action `$arg`.\n","473":"\t\t$arg[0] = $arg[0][0];\n","474":"\t}\n","475":"\n","476":"\t$wp_filter[ $hook_name ]->do_action( $arg );\n","477":"\n","478":"\tarray_pop( $wp_current_filter );\n","479":"}\n","480":"\n"},"startingLine":471},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/plugin/ajax/ajax_at_any_url.php","line":28,"function":"do_action","class":null,"args":[],"snippet":{"23":"    /** @var string|null|false $ajax_action */\n","24":"    $ajax_action = filter_input(INPUT_POST, 'action', FILTER_SANITIZE_STRING);\n","25":"\n","26":"    if (is_post_request() && isset($_POST['breakdance_ajax_at_any_url']) && $ajax_action) {\n","27":"        $custom_action = \"breakdance_ajax_{$ajax_action}\";\n","28":"        do_action($custom_action);\n","29":"        return true;\n","30":"    }\n","31":"\n","32":"    return false;\n"},"startingLine":23},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-content/plugins/breakdance/plugin/actions_filters/template_include.php","line":16,"function":"Breakdance\\AJAX\\see_if_this_is_an_ajax_at_any_url_request_and_if_so_fire_it","class":null,"args":[],"snippet":{"11":"function template_include($file_to_include)\n","12":"{\n","13":"\n","14":"    do_action('breakdance_register_template_types_and_conditions');\n","15":"\n","16":"    $didAjaxFire = \\Breakdance\\AJAX\\see_if_this_is_an_ajax_at_any_url_request_and_if_so_fire_it();\n","17":"\n","18":"    if ($didAjaxFire) {\n","19":"        return null;\n","20":"    }\n"},"startingLine":11},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-includes/class-wp-hook.php","line":307,"function":"Breakdance\\ActionsFilters\\template_include","class":null,"args":[],"snippet":{"302":"\n","303":"\t\t\t\t// Avoid the array_slice() if possible.\n","304":"\t\t\t\tif ( 0 == $the_['accepted_args'] ) {\n","305":"\t\t\t\t\t$value = call_user_func( $the_['function'] );\n","306":"\t\t\t\t} elseif ( $the_['accepted_args'] >= $num_args ) {\n","307":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], $args );\n","308":"\t\t\t\t} else {\n","309":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], array_slice( $args, 0, (int) $the_['accepted_args'] ) );\n","310":"\t\t\t\t}\n","311":"\t\t\t}\n"},"startingLine":302},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-includes/plugin.php","line":191,"function":"apply_filters","class":"WP_Hook","args":[],"snippet":{"186":"\t}\n","187":"\n","188":"\t// Pass the value to WP_Hook.\n","189":"\tarray_unshift( $args, $value );\n","190":"\n","191":"\t$filtered = $wp_filter[ $hook_name ]->apply_filters( $value, $args );\n","192":"\n","193":"\tarray_pop( $wp_current_filter );\n","194":"\n","195":"\treturn $filtered;\n"},"startingLine":186},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-includes/template-loader.php","line":104,"function":"apply_filters","class":null,"args":[],"snippet":{"99":"\t *\n","100":"\t * @since 3.0.0\n","101":"\t *\n","102":"\t * @param string $template The path of the template to include.\n","103":"\t */\n","104":"\t$template = apply_filters( 'template_include', $template );\n","105":"\tif ( $template ) {\n","106":"\t\tinclude $template;\n","107":"\t} elseif ( current_user_can( 'switch_themes' ) ) {\n","108":"\t\t$theme = wp_get_theme();\n"},"startingLine":99},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/wp-blog-header.php","line":19,"function":"require_once","class":null,"args":["/home/gojonanujogevire/webapps/breakdanceblog/wp-includes/template-loader.php"],"snippet":{"14":"\n","15":"\t// Set up the WordPress query.\n","16":"\twp();\n","17":"\n","18":"\t// Load the theme template.\n","19":"\trequire_once ABSPATH . WPINC . '/template-loader.php';\n","20":"\n","21":"}\n"},"startingLine":14},{"file":"/home/gojonanujogevire/webapps/breakdanceblog/index.php","line":17,"function":"require","class":null,"args":["/home/gojonanujogevire/webapps/breakdanceblog/wp-blog-header.php"],"snippet":{"12":" * @var bool\n","13":" */\n","14":"define( 'WP_USE_THEMES', true );\n","15":"\n","16":"/** Loads the WordPress Environment and Template */\n","17":"require __DIR__ . '/wp-blog-header.php';\n"},"startingLine":12}]},"requestDetails":{"friendlyName":"WordPress AJAX Request","responseCode":"500","requestUrl":"https://breakdanceblog.us5.instawp.xyz/index.php/2022/07/01/a-breakdance-creator/","requestMethod":"POST","body":{"action":"breakdance_server_side_render","properties":"{\"content\":{\"content\":{\"meta_data\":[{\"type\":\"author\",\"link\":null,\"taxonomy\":null,\"icon\":{\"slug\":\"icon-user-circle.\",\"name\":\"user circle\",\"svgCode\":\"<svg xmlns=\\\"http://www.w3.org/2000/svg\\\" viewBox=\\\"0 0 496 512\\\"><path d=\\\"M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 96c48.6 0 88 39.4 88 88s-39.4 88-88 88-88-39.4-88-88 39.4-88 88-88zm0 344c-58.7 0-111.3-26.6-146.5-68.2 18.8-35.4 55.6-59.8 98.5-59.8 2.4 0 4.8.4 7.1 1.1 13 4.2 26.6 6.9 40.9 6.9 14.3 0 28-2.7 40.9-6.9 2.3-.7 4.7-1.1 7.1-1.1 42.9 0 79.7 24.4 98.5 59.8C359.3 421.4 306.7 448 248 448z\\\"/></svg>\"},\"avatar\":false,\"before_text\":null},{\"type\":\"date\",\"icon\":{\"slug\":\"icon-calendar-alt.\",\"name\":\"calendar alt\",\"svgCode\":\"<svg xmlns=\\\"http://www.w3.org/2000/svg\\\" viewBox=\\\"0 0 448 512\\\"><path d=\\\"M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z\\\"/></svg>\"},\"before_text\":null,\"link\":false,\"date_format\":null},{\"type\":\"comments\",\"before_text\":null,\"icon\":{\"slug\":\"icon-comment-alt.\",\"name\":\"comment alt\",\"svgCode\":\"<svg xmlns=\\\"http://www.w3.org/2000/svg\\\" viewBox=\\\"0 0 512 512\\\"><path d=\\\"M448 0H64C28.7 0 0 28.7 0 64v288c0 35.3 28.7 64 64 64h96v84c0 7.1 5.8 12 12 12 2.4 0 4.9-.7 7.1-2.4L304 416h144c35.3 0 64-28.7 64-64V64c0-35.3-28.7-64-64-64zm16 352c0 8.8-7.2 16-16 16H288l-12.8 9.6L208 428v-60H64c-8.8 0-16-7.2-16-16V64c0-8.8 7.2-16 16-16h384c8.8 0 16 7.2 16 16v288z\\\"/></svg>\"}}],\"show_divider\":false}},\"design\":{\"spacing\":{\"between_items\":{\"breakpoint_phone_portrait\":{\"number\":10,\"unit\":\"px\",\"style\":\"10px\"},\"breakpoint_base\":{\"number\":25,\"unit\":\"px\",\"style\":\"25px\"}},\"after_graphics\":null},\"typography\":{\"text\":{\"typography\":{\"custom\":{\"customTypography\":{\"fontWeight\":null,\"fontSize\":null}}}}},\"icon\":{\"color\":\"#AF8D8DFF\",\"size\":{\"breakpoint_base\":{\"number\":33,\"unit\":\"px\",\"style\":\"33px\"}},\"color_hover\":\"#DA2E2EFF\"},\"icons\":null,\"avatar\":null,\"container\":null,\"divider\":null,\"layout\":{\"alignment\":null,\"stack_vertically_at\":\"breakpoint_phone_portrait\"},\"graphics\":{\"icons\":{\"color\":\"#551DD0FF\"}}}}","parentProperties":"{}","elementSlug":"EssentialElements\\PostMeta","triggeringDocument":179,"breakdance_ajax_at_any_url":"true"}}}

**Comment by louisreingold** [comment]
This should be fixed in beta 4, but if not, please open another issue.
