### ISSUE TITLE
Post builder - Add support to query on sale products

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#571]
Two reasons why I would like to build it using post loop builder
1.) I can freely design my card
2.) The images are not cropped

Here's the problem with the Product list elements
https://www.dropbox.com/s/8voahp92lfxky2f/Product%20thumbnails%20are%20cropped.MP4?dl=0

**Comment by louisreingold** [comment]
Thanks for the suggestion.

We added this and a ton more WooCo conditions to Breakdance 1.3.

<img width="721" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/6425257/a00901c3-0777-436f-b1a5-670348a2d25e">
