### ISSUE TITLE
Custom classes not working properly

### ISSUE THREAD

**Issue by xogabi** [soflyy/breakdance-bugs#573]
Steps to reproduce:
1. Blank clean page
2. Add a section
3. From the Advanced tab, under classes, create and assign a class
4. Change the background color of the class (from the selectors panel) or any other property but the background color is the most obvious one
5. Nothing happens to the section...

How to fix in current version:
1. create a random class name in the advanced tab, change some settings = nothing happens
2. create another random class name in the advanced tab, change settings = bingo, it works!

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
