### ISSUE TITLE
1.1 RC 1 - archive template issue 

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#574]
I have a CPT called products with custom taxonomy named "product_types" One of my product type has only 1 post tied to it. But after the update, it now renders all posts/products.

**Antibac product before update**
![antibac before update](https://user-images.githubusercontent.com/51177627/204092669-9d7a7933-8861-4508-ab1d-2a2f710c652d.png)

**After update**
![antibac after update](https://user-images.githubusercontent.com/51177627/204092699-7dadba45-e50b-4502-addd-9be3ea0cba88.png)

**Comment by louisreingold** [comment]
What element are you using to render the products? Posts List? Post Loop Builder? Are you trying to use a custom query? Did you enable pagination?

**Comment by dancerist** [comment]
@louisreingold 

I'm using a post loop builder and same issue with post list element

https://www.dropbox.com/s/rq4sl2jrezvt0mo/RC%201%20template%20issue.MP4?dl=0

**Comment by dancerist** [comment]
@louisreingold @a-dubiel 

Thanks for the RC 1&2 update. But I think I found another bug? 
👇👇
https://www.dropbox.com/s/k04du1wsgxyfrmz/Archive%20template%20issue.MP4?dl=0

**Comment by rizaardiyanto1412** [comment]
Hi @dancerist 

Did you still face this issue? I tried to check it and could not replicate it. Opening my custom taxonomy archive only shows the related posts. 

Maybe I'm missing something, however, the dropbox video is deleted. Could you please re-upload it?

I'm on Breakdance 1.2 RC 1

**Comment by dancerist** [comment]
The following bug is fixed in version 1.1
