### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Bebuk85** [soflyy/breakdance-bugs#575]
Hi,

I just updated the Breakdance plugin, to 1.1 RC1

But it’s showing this.

![image](https://user-images.githubusercontent.com/72046610/204095183-19cfd5a3-fa26-426b-bc3b-93c104e74c4a.png)

**Comment by hellokittychaos** [comment]
I just received this same error. Following.

**Comment by a-dubiel** [comment]
Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Comment by StaggerLeee** [comment]
I have the same error. Fixed it few days ago but forgott how. Have to write down everything important I do.

**Comment by StaggerLeee** [comment]
That was something wrong with paths and URLs in database. To much playing with converting.
If you did not play with database try to resave your permalinks in backend.

**Comment by Bebuk85** [comment]
> That was something wrong with paths and URLs in database. To much playing with converting. If you did not play with database try to resave your permalinks in backend. (Or check your .htaccess file)

Didn't work the permalinks resave.
