### ISSUE TITLE
1.1 RC1 - Post Archive Template issue with custom query postloop builder 

### ISSUE THREAD

**Issue by markpinkster** [soflyy/breakdance-bugs#578]
I have a custom post archive template with 2 post loop builder elements. This to be able to add a CTA after big top article and then continue with rest of articles.

When viewing this layout on a separate page it works.
When selecting this page as 'Posts Page' on Wordpress settings -> reading -> posts page
OR when viewing a post-category archive page
The paging fails to appear.
<img width="1158" alt="Scherm­afbeelding 2022-11-28 om 10 32 12" src="https://user-images.githubusercontent.com/66789995/204245605-44188b41-f7f7-4899-a32a-91b6ddc02ffe.png">
<img width="1164" alt="Scherm­afbeelding 2022-11-28 om 10 32 41" src="https://user-images.githubusercontent.com/66789995/204245626-6d7f7478-ed67-416a-9606-1f46d8d8b093.png">

**Comment by a-dubiel** [comment]
Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
