### ISSUE TITLE
Blog Elements Issues

### ISSUE THREAD

**Issue by onenyarko** [soflyy/breakdance-bugs#58]
**Post Filtering or sidebar:** There's no native sidebar or filtering for blogs. Probably pop-ups builder (which is yet to arrive) will fix this. But a native sidebar will be the best.  ---- **belongs on feature requests board: https://breakdance.canny.io/**

- [x] **Post Meta:** This block creates an error for the site, posts can't be viewed when it is added to the template builder.
https://github.com/soflyy/breakdance-bugs/issues/57. ----  **This should be fixed in beta 4, but if not, please report a new issue.**

**Comment by louisreingold** [comment]
FB thread that contains link to site demoing the elements: https://www.facebook.com/groups/breakdanceofficial/posts/5197210366980883/

**Comment by louisreingold** [comment]
> Post Filtering or sidebar: There's no native sidebar or filtering for blogs. Probably pop-ups builder (which is yet to arrive) will fix this. But a native sidebar will be the best.

We've shipped Popup Builder. You're welcome to post this as a suggestion / feature request at https://breakdance.canny.io/

**Comment by louisreingold** [comment]
I've created dedicated issues for the other items in this thread:

#125

#126

#127

#128

#129

Closing, and tracking in the above issues.
