### ISSUE TITLE
Stable version 1.03 gets 1.1-rc1 and 1.1-rc2 update, beta features not ticked on

### ISSUE THREAD

**Issue by mirzahodzic89** [soflyy/breakdance-bugs#580]
![316820351_10158949647562765_4659384318967506830_n](https://user-images.githubusercontent.com/56724924/204269724-b5c09cf0-40b4-4790-8029-af3ed21ca92d.jpg)

**Comment by louisreingold** [comment]
We're not able to reproduce, but it's not the only report we've got. If this happens to anyone, please don't update, and instead email our support team at support@breakdance.com so we can login and see why this is happening. We'd love to take a look.
