### ISSUE TITLE
Slider and Advanced Slider Slides Per View Needs Responsive Controls

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/breakdance-bugs#583]
To create a carousel type slider where for instance you have 6 images at full desktop you would not want 6 to display on all breakpoints.
Need a responsive control on the Settings / Advanced / Slides per view setting on the standard slider and the advanced slider, or at least on the advanced one.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
