### ISSUE TITLE
WooCommerce Product Images element is not working properly

### ISSUE THREAD

**Issue by varunalex** [soflyy/breakdance-bugs#585]
I'm using Woo Product images element on the Single product template. 
Product gallery images thumbnails are not switching, and images are stacked vertically with a bullet point. 

* BD version:  1.0.3 (tested with 1.1-RC.2. Still same)
* No themes
*  No errors on the browser console

**Expected**
Show the main product image and gallery image thumbnails underneath as a row. When clicking on a gallery image thumbnail, it should show the full image.

https://komododecks.com/recordings/U6RKXS4yiNdueCqbeLpg

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
