### ISSUE TITLE
Text doesn't show in Advanced options Prepend and Append fields when re-editing them

### ISSUE THREAD

**Issue by vince-pat** [soflyy/breakdance-bugs#586]
Hi,

(BD 1.1 RC2)
When adding text in Prepend and Append fields inside the Advanced options in a text Block, the content appear correctly (on the Front and the Back).
But when re-editing the Advanced options, the texts Prepend and Append previously typed don't show anymore in the fields.

I hope I'm clear ;-)

Regards.

**Comment by a-dubiel** [comment]
@vince-pat I need more info. Are you using dynamic data? ACF? Metabox? If you need help, you need to provide exact steps to reproduce.

**Comment by vince-pat** [comment]
Hi,

I'm using in it in a Single post Template.
It is a Text field with ACF dynamic content.

And I discover an other bug that only one of the two is displayed at a time as you can see the screen captures below.

**Screen-01.png**:
For exemple purpose : "- Test Prepend -" has been inserted in the Prepend field
and "- Test Append -" in the Append field.
but only the Append is shown on the Front. Only one of the two item is displayed.
![Screen-02](https://user-images.githubusercontent.com/34057501/204784918-51777e46-c02c-457f-89c1-8e0b48494f34.png)

**Screen-02.png**:
When re-editing Both Prepend and Append fields are empty even if one is displayed.
![Screen-02](https://user-images.githubusercontent.com/34057501/204784965-8579d02d-0042-4902-b22d-e9a0eb4636af.png)

**Comment by jman1076** [comment]
I have an open support request for this that Elijah Mills has been working with me on.  Per the new RC1 download, this is mostly fixed. There is still a bug where when you type in html code, like <strong>Test</strong>, you will get some HTML errors upon saving, but once you clear the errors, everything still works. If you type your HTML in a text editor and copy it to the Append or Prepend fields, you won't get the error. 

Per Elijiah, they are still working on this, but have made progress. I can confirm the Append/Prepend text is still present in the field after saving. It was not there before this fix.

**Comment by a-dubiel** [comment]
>  I can confirm the Append/Prepend text is still present in the field after saving. It was not there before this fix.

Awesome. 

> There is still a bug where when you type in html code...

Control inputs accept plain text only. You should style your input using design controls. 

Closing this one. If you have further requests or feature suggestions please open another report. Thanks.
