### ISSUE TITLE
WordPress AJAX Request failed when Global Block with Form is present

### ISSUE THREAD

**Issue by marcel2008** [soflyy/breakdance-bugs#589]
Once the Form ist setup and saved as a globla block, when trying to edit the page with BD it shows "WordPress AJAX Request failed" Unrecoverable Error

![image](https://user-images.githubusercontent.com/58587248/204766880-9c0205bb-dc15-4298-9184-d8289626a12e.png)

I guess this short video should contain evry info you need.

https://www.loom.com/share/95d32c7ba064403e9b31db185bcf5f1f

**Comment by marcel2008** [comment]
As this site should go live on December 1st this is pretty urgent to me.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
