### ISSUE TITLE
Video Lazy Load - Poster Image Size

### ISSUE THREAD

**Issue by aadlung** [soflyy/breakdance-bugs#590]
The video element has a "lazy load" feature, which allows to select a poster image which has to be clicked to load the embed code (e.g. for Vimeo).

But this only adds an image tag (no responsive source set) which always takes the original URL of the image.

I would like to see an option to select the image size there as well (either in the media library modal window or in the Breakdance element like for normal images)

**Comment by obedparla** [comment]
The custom image is added as a background image directly on top of the Custom Element. We can't use a source set in that case. 

Doing this would require a significant refactor of the library enabling the lightweight embed which isn't worth it

**Comment by aadlung** [comment]
Hi, it seems the poster feature has been removed completely, or do I just miss it somewhere? Suddenly with an update maybe all our videos are just showing the ugly preview...
