### ISSUE TITLE
Rank Math archive disable causes Breakdance errors

### ISSUE THREAD

**Issue by cmidgley** [soflyy/breakdance-bugs#593]
**Problem summary:**

Rank Math has a feature to disable archives (date and author).  When disabled, these generate a redirect.  When editing an archive, if the preview dropdown selects a disabled archive Breakdance will display an AJAX failure (since it got a redirected `text/html` instead of the expected `application/json`) and not allow any editing.  Date archive is often the first archive in the preview list, so if it is disabled the error is generated anytime the archive template is opened. 

**Steps to reproduce**

1. Install Rank Math
2. Disable date archives:
![disable-date-archive](https://user-images.githubusercontent.com/8160316/205047046-af4dd78c-b24f-4175-9c4c-628ab240fb70.png)
3. Create / edit a post archive template
4. Assuming the preview selects a disabled archive, the following should appear:
![rank-error](https://user-images.githubusercontent.com/8160316/205047019-f9518200-a37d-4467-b1aa-3987a854166c.png)

**Work around**

Either of the following works:
1) Don't disable archives with Rank Math (primarily the date archive, as it is the default one)
2) With archives disabled and an error appearing, select a different non-disabled archive.  Editing will work again.

(May be what #62 was unable to reproduce?)

**Comment by obedparla** [comment]
This is impossible to fix from our end since RankMath doesn't provide a filter/hook. 

We have an issue asking them to add it: https://github.com/rankmath/seo-by-rank-math/issues/127

**Comment by obedparla** [comment]
Opened a PR in the RankMath GitHub. Once they merge it, we'll be able to fix this within Breakdance: https://github.com/rankmath/seo-by-rank-math/pull/143

**Comment by louisreingold** [comment]
RankMath has left our pull request ignored for over six months.

:(

**Comment by louisreingold** [comment]
> @louisreingold closed this as not planned 

We are unable to fix this if RankMath refuses to cooperate. Our engineers wrote the code and gave it to them.
