### ISSUE TITLE
ACF text area line breaks removed

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#595]
When I add content to the page from an ACF text area all the line breaks are removed so the text gets bunched up into one long string.

**Comment by LambMediaGroup** [comment]
I've also found that HTML is stripped too so any links that were in there are not shown on the page.

**Comment by a-dubiel** [comment]
Hey I cannot reproduce this. Make sure ACF Text Area is outputted using Rich Text only. 

If the problem persists feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
