### ISSUE TITLE
Undefined array key "background"

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#598]
Please try to clearly describe the problem.

Upgrading from 1.1 beta 2 to 1.1 GA, get Internal Server Error "undefined array key "background"" on editing a template for a CPT of 'recipe'. (update, also appears on the standard single post template as well). I can provide login details if needed.

Including a screenshot of the problem is a good idea.

![image](https://user-images.githubusercontent.com/112517932/205434580-467dc3c8-988c-43f2-893b-f6c8233bf3dd.png)

(Or a screencast - https://www.loom.com/)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Comment by Spellhammer** [comment]
Caused by conflict with "Enable Media Replace" plugin.
