### ISSUE TITLE
The templates for the headers do not work on the blog page

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#606]
Just create a different header applied only to the blog page (of the latest articles), and the template doesn't work, I tried everything, played with priorities, but nothing to do.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
