### ISSUE TITLE
Form Builder: width does not always get applied to form field (grid-column-start)

### ISSUE THREAD

**Issue by raabmar** [soflyy/breakdance-bugs#607]
The screenshot should explain everything. For some reason, the width does not get applied. I can set whatever I want, but it won't show in the frontend (won't show in the backend either). The code simply does not get applied, as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/15885290/206268056-caf71244-12f3-4e25-9a8e-bbd388aa8b65.png)

Using forms with the new multi step function introduced with BD1.1

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
