### ISSUE TITLE
Acf field for image not working in category

### ISSUE THREAD

**Issue by orhanbilikvar** [soflyy/breakdance-bugs#613]
How the ACF field is defined (Array, url or id) does not change the problem.
Could "$term" be missing?

![01](https://user-images.githubusercontent.com/48365764/207133549-990cf6e7-1ab0-4ae5-b04d-445441dc0e22.png)
![02](https://user-images.githubusercontent.com/48365764/207133579-1bc76922-00e0-4bcd-91b5-6dff5416034b.png)
![03](https://user-images.githubusercontent.com/48365764/207133604-57ee5b9d-019b-4ba3-8921-150cfcefd0fc.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
