### ISSUE TITLE
Video Background for Fancy Container doesn't work on Front End

### ISSUE THREAD

**Issue by maxproway** [soflyy/breakdance-bugs#614]
Works on Backend but not showing on Frontend:

https://vimeo.com/780762279/9022d21b77

**Comment by maxproway** [comment]
Update2:
Actually any video does not work on Frontend in Advanced Slider, starting on second and all further slides.

I have tried just to put stand alone video element, as well as manually added iFrame:


![image](https://user-images.githubusercontent.com/98363451/207626277-c2463d28-4aee-4195-a288-a33b29f10cd0.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
