### ISSUE TITLE
[Suggestion] when using Custom Fonts

### ISSUE THREAD

**Issue by theperfectwill** [soflyy/breakdance-bugs#616]
## Please try to clearly describe the problem.

When uploading a custom font the css generates the full site's domain in the font `src: url()`. 

Maybe relative urls can be used here instead? Because when migrating a site, these urls immediately throw off the site's font styles from what is expected.

**Comment by obedparla** [comment]
We automatically regenerate font files when you run the "replace url" tool, which is expected when you're migrating the site. This isn't needed

**Comment by obedparla** [comment]
> Maybe it would be better for Breakdance to detect if the urls in some places match the site's url, and if not, then generate a notice/link to to the site admin to update the urls in Breakdance Settings > Tools.

We already do this. The push/pull solutions may be messing up with our logic since they try to replace everything in the db, so it's not triggered. That'd be a bug.(@a-dubiel)

**Comment by louisreingold** [comment]
This is now handled when the CSS cache is regenerated.
