### ISSUE TITLE
Product Builder and Product elements showing errors

### ISSUE THREAD

**Issue by salasmx** [soflyy/breakdance-bugs#617]
Images and swatches are not showing on the builder or the live page, but they are showing on the PDP.

[VIDEO HERE](https://www.loom.com/share/fcd70de3cabe4e45a1a33c460deb4759)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
