### ISSUE TITLE
Icon in the search form is not visible on iOS

### ISSUE THREAD

**Issue by salvatoredefazio** [soflyy/breakdance-bugs#618]
I noticed that the icon in the Search Form is regularly visible on the desktop (and in the builder), but not on iOS.
I've tried both Safari and Chrome on iOS, but the result is always the same...

![320052050_689034999343017_6776195401357039346_n](https://user-images.githubusercontent.com/120631099/207809889-68c9d7a8-681c-4848-b14b-2a3cdf3604c0.jpg)

**Comment by lockedm** [comment]
I've noticed this with the icons on the social share buttons element as well.

**Comment by a-dubiel** [comment]
@salvatoredefazio @lockedm I have trouble reproducing this. What iOS are you guys on?

![IMG_5263](https://user-images.githubusercontent.com/669243/208755188-8ca2e189-63bc-4907-85f3-685b03c49ee8.PNG)
![IMG_5262](https://user-images.githubusercontent.com/669243/208755200-436b8ca6-b851-4c72-b0e3-a77c2cb7120d.PNG)

**Comment by lockedm** [comment]
I was on an iPad with ios 14.8.1. I've upgraded to 15.7.2 just now, and the social share icons show in that release.

**Comment by salvatoredefazio** [comment]
I noticed that the problem is the height set for the search form element. If you use the default form, the icon is also visible on iOS. If you set the height lower than 40px, the icon shrinks until it becomes invisible on iOS. In any case I'm on iOS and iPadOS 16.2

**Comment by louisreingold** [comment]
We've addressed this in a recent update to Breakdance. Thanks for the reports!
