### ISSUE TITLE
On my test server enabling Rank Math breaks the editor on Breakdance

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#62]
https://www.facebook.com/groups/breakdanceofficial/posts/5187116404656946/

**Comment by neeckola** [comment]
Couldn't reproduce. 
WP 6.0.1
Rank Math 1.0.93.1 (default settings)

**Comment by louisreingold** [comment]
I can't reproduce this. I installed Rank Math and was able to use it with no problems.
