### ISSUE TITLE
Table of Content not respecting parent when set to sticky.

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#621]
Hello I noticed that the Table of Content element is not respecting my parent height when set to sticky. Here you can see a video about it: https://www.loom.com/share/57cc278443c547958c5ea754517f54b1

**Comment by a-dubiel** [comment]
Hey @StefanPavlov23, thanks for your report. I was unable to reproduce this, but you should try wrapping Table Of Contents with a Div. After that, apply sticky animations to Div, instead of Table of Contents.

**Comment by StefanPavlov23** [comment]
The solution you provided does not work as well. The workaround was to use the css properties "sticky" on the div I added thanks to your suggestion.
