### ISSUE TITLE
1.2 beta 1 - header / footer conditions not working

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#622]
Upgraded from 1.1 to 1.2 beta 1 and header and footer conditions have stopped working. Under development site has a coming soon page where the header and footer were excluded from being shown on. The exclude works fine on 1.1. Upgrading to 1.2b1 and the header and footer conditions do not take effect:

https://komododecks.com/recordings/CIOqMeP7IrHnmgYsZx0q 

Downgrading back to 1.1 has the conditions working again.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
