### ISSUE TITLE
1.2 beta 1. Design library for 'this website' does not show the sites pages

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#623]
Prior to 1.2 beta 1, the design library for 'this website' showed all of the sites pages. In 1.2 beta 1. none of the sites pages are shown:

https://komododecks.com/recordings/uXWYjmjf0GbLMg1T9E89

**Comment by obedparla** [comment]
Hey @lockedm I tested this on 1.2 beta 1 and it works for me. Could you please contact our support with login details to your site so we can look into it?

https://breakdance.com/support/

**Comment by lockedm** [comment]
you fixed this in 1.1 beta 2. closing
