### ISSUE TITLE
Post featured image too small on mobile

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#625]
![Capture d’écran 2022-12-23 192516](https://user-images.githubusercontent.com/56270626/209391724-15c98e2c-d124-42f8-90c6-5be3f2ea2506.png)
padding: 0px;
On the breakpoint, mobile portrait, the post featured image element is too small

**Comment by a-dubiel** [comment]
Hey @rodolphebertozzo, first of all thank you so much for contributing to Breakdance. You have been really helpful and we really appreciate your feedback.

However, most of your issues do not include exact steps to reproduce or anything that would help us triage the issue. For example, in this issue it would be nice if to see what image are you trying to upload. With that in mind when think about CSS, the 100% width does not always mean image will stretch full width. You need to account other factors like parent width or original image dimensions.

Going forward, please include as much details as you can. Exact steps to reproduce, what structure your elements are using or a screen recording (even with no audio) - this will help us a lot. Thanks.
