### ISSUE TITLE
DOM overloaded

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#627]
Since version 1.2-beta, Gmetrix and Google Page speed tell me that the DOM of my site is overloaded, yet it is optimized to the maximum. Is this a common problem for all sites since the beta version, or is there something I didn't do correctly? Because the generated DOM is correct, maybe it is a default behavior of Google Page Speed that indicates a de facto overload, for sites where all the content is on one page

**Comment by a-dubiel** [comment]
See my comments in https://github.com/soflyy/breakdance-bugs/issues/625. Please provide a screenshot of report and URL to the page you were testing. Details, details, details. We can't help you, unless you provide more data.
