### ISSUE TITLE
Sticky menu problem

### ISSUE THREAD

**Issue by choegl** [soflyy/breakdance-bugs#630]
If you place two sticky header builder elements in the header, one with overlay enabled and set to fade out after scrolling 200 px and the other with solid background to fade in after 300 px you won't be able to click any links or see hover events on the first because the second one is actually placed above it (opacity:0) and blocking out all mouse events.

Luckily there is an easy solution. Add this to the css

```
.bde-header-builder--sticky-scroll-hide {
    pointer-events: none;
}
```

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
