### ISSUE TITLE
Safari Mini cart issue - Add to cart button falling of if to much products

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#631]
If you are using Safari you can't us the checkout button if opening the minicart (with a lot of products).

<img width="354" alt="Schermafbeelding 2022-12-30 om 14 24 21" src="https://user-images.githubusercontent.com/56388399/210074972-1b20e936-ff57-488e-a001-a0e1f7d604e9.png">

This part is missing / pushed down the screen.
<img width="359" alt="Schermafbeelding 2022-12-30 om 14 24 44" src="https://user-images.githubusercontent.com/56388399/210074982-b72457f7-1679-45d5-929a-0ae6637ca00c.png">

**Comment by a-dubiel** [comment]
@jeffreyvandervet any chance you can provide working URL? What version of Breakdance are you on?

**Comment by lockedm** [comment]
@a-dubiel I have this issue on 3 sites. It's not safari specifc, but iOS (at least Chrome on my iPad suffers from it as well). Here's 3 sites all suffering the same issue:

- https://abb.webxdesign.studio/shop
- https://butler-country-estates.co.uk/shop
- https://thehampshireshepherd.com/shop

**Comment by lockedm** [comment]
As per https://www.facebook.com/groups/breakdanceofficial/?multi_permalinks=5828527953849118&notif_id=1675408454804808&notif_t=feedback_reaction_generic&ref=notif a workaround has been provided:

The widget uses overflow-y:clip which is a relatively new CSS value, and the support for IOS only came out in version 16.
Try adding this to the CSS
.bde-mini-cart-offcanvas .widget_shopping_cart_content {
overflow-y: scroll !important;
}

**Comment by a-dubiel** [comment]
@lockedm thanks a lot for debugging this. I will pass it internally to see if we can address older iOS versions.

**Comment by louisreingold** [comment]
We did the best we could to support iOS down to v13 in March, but forgot to close the issue.
