### ISSUE TITLE
Stop push update 29 december ! AutoUpdate to last RC disable Breakdance, 2 websites break !!!!

### ISSUE THREAD

**Issue by nestarian** [soflyy/breakdance-bugs#632]
Please try to clearly describe the problem.

2 websites break after an auto update with your last RC
Breakdance is auto disabled in Wordpress by your update !!!!

Including a screenshot of the problem is a good idea.

(Or a screencast - https://www.loom.com/)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
