### ISSUE TITLE
ACF email and number field link support

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#634]
Hi, I wanted my email and number field to be clickable. It seems impossible atm cause when linking an email we need to add "mailto:" and the dynamic link in BD only supports URL field. Or am I missing something? 

TIA

**Comment by rizaardiyanto1412** [comment]
What element are you using in BD @dancerist ?

I tried adding it using text link element and it automatically add "mailto:" in my email ACF field
![image](https://user-images.githubusercontent.com/83811723/211179593-d5abfc8b-4b49-4d18-9c61-dd0b157adc74.png)

**Comment by dancerist** [comment]
Thanks for looking. Indeed it is working. I can't remember how it didn't work for me. I'm using the email field. I tried the same method and had no luck so I ended up writing a custom solution.

```
<?php
if( get_field('email') ):

  $email = get_field('email');
  echo '<a href="mailto:'.$email.'">'.$email.'</a>';

endif;
?>
```
However, it seems to be working for me now.
Thanks
