### ISSUE TITLE
Slider - allow to set slides per view on every breakpoints

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#635]
e.g. I want it to display 5 items on the desktop and 3 on tablet

![image](https://user-images.githubusercontent.com/51177627/210187448-1ed66470-c315-4c7e-bf45-4c95e9e5d93f.png)

**Comment by dancerist** [comment]
Sorry, I forgot to search first. Looks like there are existing post already
https://github.com/soflyy/breakdance-bugs/issues/583
https://github.com/soflyy/breakdance-bugs/issues/393

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
