### ISSUE TITLE
Link wrapper text color not working

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#636]
Currently the text color inside the link wrapper is not being detected.

<img width="283" alt="Schermafbeelding 2023-01-02 om 13 59 53" src="https://user-images.githubusercontent.com/56388399/210235005-23fdb5ba-3d83-4fca-893c-ad7d81793e86.png">

<img width="135" alt="Schermafbeelding 2023-01-02 om 13 59 59" src="https://user-images.githubusercontent.com/56388399/210235009-d1fff61b-58a7-4d58-8266-9d28202e4a00.png">

**Comment by louisreingold** [comment]
Thanks for the report. We've deprecated the Text Colors controls on wrapper elements, so this won't be an issue going forward.
