### ISSUE TITLE
V 1.2-rc.1 | Element Studio | Condition | Removing condition hides field

### ISSUE THREAD

**Issue by bootstrapio** [soflyy/breakdance-bugs#637]
Issue:
If you remove an existing condition from a field, the field will no longer display on the Builder Panel.

Steps to Reproduce:
1) Open Element Studio
2) Delete existing condition for Field
3) Save Item
4) Field is missing from Builder Panel
4) Refresh/Reload to confirm

Potential Solution:
**When deleting condition, remove the `'condition' => []` object from the .php field, as it's just leaving a blank condition object**

When Condition Exists (Correctly displays the condition)
`['type' => 'toggle', 'layout' => 'inline', 'condition' => ['path' => 'design.subsection.layout_style', 'operand' => 'not equals', 'value' => 'layout-style-two']],`

When Condition is Deleted (Hides the Field from the Builder Panel)
`['type' => 'toggle', 'layout' => 'inline', 'condition' => []],`

What fixes the issue (Field Displays Correctly, since condition does not exist)
`['type' => 'toggle', 'layout' => 'inline'],`
_Removing `'condition' => []` from the .php file fixes the issue._

**Condition Exists**
<img width="2056" alt="Screen Shot 2023-01-02 at 9 53 57 AM" src="https://user-images.githubusercontent.com/46854406/210252145-7ca09500-f536-4d3d-b6ba-e2168828546a.png">

**Condition Deleted** 
<img width="2056" alt="Screen Shot 2023-01-02 at 9 54 44 AM" src="https://user-images.githubusercontent.com/46854406/210252133-d3e3fefc-353e-4ef9-9d87-c95407f8bfd7.png">

.php leaves a `'condition' => []` object, that hides the Field from the Builder Panel
<img width="2056" alt="Screen Shot 2023-01-02 at 10 39 22 AM" src="https://user-images.githubusercontent.com/46854406/210252940-035ab962-92e4-4a93-8524-5a3cac955ef6.png">

_Removing `'condition' => []` from the .php file fixes the issue._
<img width="2056" alt="Screen Shot 2023-01-02 at 10 38 36 AM" src="https://user-images.githubusercontent.com/46854406/210252958-addd2b5b-d9c3-4780-80c2-c80fb9849493.png">

**Comment by a-dubiel** [comment]
@bootstrapio doing god's work. Thank you.

**Comment by louisreingold** [comment]
This was addressed in Breakdance 1.2. Thanks for the report.
