### ISSUE TITLE
License Key visible

### ISSUE THREAD

**Issue by Bonnie-Clyde** [soflyy/breakdance-bugs#638]
After entering the license key, it is still visible on Firefox(108.0.1).

When using the Inspect feature of Firefox it shows an error releating to -webkit-text-security: disc; - Invalid property name

![Untitled](https://user-images.githubusercontent.com/111174477/210471895-db5d49ad-8287-4469-82f0-f5b1704fb518.png)

![Screenshot 2023-01-04 at 11-45-21 Settings ‹ Development Site — WordPress](https://user-images.githubusercontent.com/111174477/210472115-d1e9963b-4a02-4f8b-bd1a-48d2e4c30c54.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
