### ISSUE TITLE
ACF URL fields containing &amp are decoded to & on the frontend

### ISSUE THREAD

**Issue by Brentnauer** [soflyy/breakdance-bugs#639]
If you have an ACF field which contains "&amp", it is forced to display as "&" when connecting that field on the frontend.

As an example, if I have an ACF URL field which contains the following:
https://web.archive.org/web/20050511225221/http://timetravelportal.com/viewtopic.php?p=2447&amp

That URL is changed on the frontend to:
https://web.archive.org/web/20050511225221/http://timetravelportal.com/viewtopic.php?p=2447& <== ('amp' is truncated)

From what I can tell, this behavior is something within ACF or WordPress to sanitize content before it's displayed. However, in the case above, the &amp is required for that URL to work at all. I was able to get around this using a code block with the following:

```
<?php

$link = get_field('thread_archiveUrl');

if( $link ): ?>

<a class="button" href="<?php echo esc_url( $link ); ?>">Continue Reading</a>

<?php endif; ?>
```
...Where thread_archiveUrl is my ACF field.

It would be nice if Breakdance provided an option to use esc_url (or whatever the equivalent might be) to use the literal field content rather than letting ACF/Wordpress sanitize it beforehand.

**Comment by a-dubiel** [comment]
Hey sorry, forgot to update. So it turns out `&amp` is a valid entity, and it's actually the browser that is doing this. Using it in an attribute (e.g href) will still work correctly.
