### ISSUE TITLE
SVG Image Error

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#641]
Adding or clicking an svg generates error.

![image](https://user-images.githubusercontent.com/51177627/210707354-687e1a30-3e96-4eff-8d21-6e161029eb47.png)

**Comment by rizaardiyanto1412** [comment]
@dancerist I'm not able to replicate it. Could you provide more information? PHP version or how you enable svg? Did you try with another images?

![image](https://user-images.githubusercontent.com/83811723/211179432-41302e09-90de-46d0-ba50-6e0cbd888939.png)
![image](https://user-images.githubusercontent.com/83811723/211179439-95988d49-339a-488b-b797-0d1e4393cc40.png)

**Comment by dancerist** [comment]
Thanks for checking. When you ask "how you enable svg", I look at happyfiles which is what I use for SVG support. I had it deactivated and use Safe SVG plugin. The error is gone now.

**Comment by dancerist** [comment]
cool
