### ISSUE TITLE
Menu builder error

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#642]
When hiding a menu item returns an error. Tho it still works on the front end
Note that the error only shows up when setting it to hide in builder preview.

![image](https://user-images.githubusercontent.com/51177627/210708218-79803bd5-07e9-4395-b4d0-be7b6317dc14.png)

**Comment by rizaardiyanto1412** [comment]
I'm able to replicate it @a-dubiel but with different error 
![image](https://user-images.githubusercontent.com/83811723/211179345-7f29c5bb-f4c3-49af-b9c1-4e91ba8f4bd8.png)

The moment I choose In Builder Preview "Hidden" the error shows up

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
