### ISSUE TITLE
Global block - Product previews not working

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#643]
When creating a global block and using a product in the preview it will give error (see image).

<img width="2549" alt="Schermafbeelding 2023-01-05 om 09 47 29" src="https://user-images.githubusercontent.com/56388399/210738976-4c02d302-bd5e-4f1e-9b18-e25b7d7115f8.png">

**Comment by rizaardiyanto1412** [comment]
I'm not able to replicate this issue @jeffreyvandervet 

Please provide more details like PHP version, step to replicate and others info that might be useful.

You can also try again on other environment, whether you still able to replicate it or only on that instance you face the issue?

**Comment by jeffreyvandervet** [comment]
PHP 8.1

Step 1: create a product in Woocommerce
Step 2: create global block
Step 3: go to a page and create a loop builder
Step 4: select the global block
Step 5: set the query to products
Step 6: click on edit global block
Step 7: check if the product is selected in the preview in the top
Step 8: do anything like placing a code block with echo "test"; or place a title and get the dynamic post title of the product.

Let me know if you still dont get it.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
