### ISSUE TITLE
Hide on Breakpoint 1px issue

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/breakdance-bugs#644]
Version: Breakdance 1.2 RC 1

When you set elements to hide on breakpoints there seems to be a pixel discrepancy between them actually hiding.

As an example if I set an element to hide on phone portrait which is 479px and below then the desired behaviour is that is it hidden at under 480px. When testing in Chrome dev tools and setting width to 479px it still shows and does not hide until setting width to 478px. The same applies when hiding on other breakpoints as well. 

I can see that when you apply hide on breakpoint it outputs code similar to this:

`
@media (max-width: 479px)
.breakdance .bde-text-102-101 {
    display: none;
}
`

A potential fix to make it actually hide at 479px could be to add in .98 on the 479px similar to what Bootstrap does:

`
@media (max-width: 479.98px)
.breakdance .bde-text-102-101 {
    display: none;
}
`

**Comment by rizaardiyanto1412** [comment]
@JeusuDigital 
I seems not able to replicate it. I try hide it on mobile portrait and it hides on 479 px. Am I missing something?

![image](https://user-images.githubusercontent.com/83811723/211178416-edf9b7d3-36a2-44f8-b351-9719fde0f865.png)
![image](https://user-images.githubusercontent.com/83811723/211178422-dd94d51d-ddd7-417f-8e62-ffb58302879b.png)
![image](https://user-images.githubusercontent.com/83811723/211178429-d4a23f4f-75af-46f3-93d3-c289f726e801.png)

**Comment by JeusuDigital** [comment]
Just checked it again on the same site and you are correct @rizaardiyanto1412 now seems to be working, very odd, must have been a cache issue as I tested in Chrome and Firefox, thanks for confirming, closing issue.
