### ISSUE TITLE
insert/edit link search is not working

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#645]
1.2 RC1. When using the insert/edit link box to link a page to a button (for example), the link search is not working. See video:

https://komododecks.com/recordings/VG2kJnV7PSEnzQu1uxQn

**Comment by rizaardiyanto1412** [comment]
Hi @lockedm 
I'm not able to replicate this behaviour on my end. Also the link option is provided by WordPress, not Breakdance. 

Other plugins might affecting the search result. Maybe you can try test it by deactivate all other plugins and see if the issue persists

**Comment by lockedm** [comment]
Thanks @rizaardiyanto1412 . This is indeed a user error. I had a code snippet running everywhere, instead of just on the frontend which was causing this. Thanks for pointing me in the right direction, and happy to close this as not a bug.
