### ISSUE TITLE
Add custom breakpoint support for elements with breakpoint dropdown

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#646]
Saw a post and thought this feature is actually useful? what do you think?
Post link
https://web.facebook.com/photo?fbid=962023671447415&set=gm.5742529585782289&idorvanity=5118076864894234

**Comment by jeffreyvandervet** [comment]
Also mentioned (a part) here [311](https://github.com/soflyy/breakdance-bugs/issues/311)

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been included in Breakdance 2.1 Beta 1.
