### ISSUE TITLE
repeater field + acf repeater with image fails to change number of items

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#647]
I've created an ACF repeater with 2 fields, an image and a block of text. I then use this with the breakdance repeater field to create an image gallery with the text below each image. This works as expected and I set it to have 3 images on desktop and then 2 on tablet portrait and 1 on mobile but this doesn't work. It stays at 3 wide.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/117674105/211099870-f7b68a35-d7cd-42eb-a94b-ef7a6f0ff1ec.png">

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/117674105/211100731-b9b6cea5-01de-4c67-ad1c-ab3b25ec73f3.png">

**Comment by rizaardiyanto1412** [comment]
I confirmed this as well @a-dubiel 

It stays 3 items on desktop, tablet, and mobile

The steps to reproduce is quite clear. But let me know if you need help to replicate it.

**Comment by a-dubiel** [comment]
Thanks for the feedback everyone. I confirmed this bug and we already have a fixed in place. This will be released with the next release which is happening very, very soon. Thanks for your patience.

**Comment by LambMediaGroup** [comment]
@a-dubiel This hasn't been resolved in 1.3 Alpha. Now it only shows 1 image per row instead of 3 no matter how many items per row I select.

**Comment by a-dubiel** [comment]
We have hit a regression in 1.3 Alpha. Sorry for that. Stay tuned for the next release.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
