### ISSUE TITLE
Gutenberg gallery block not rendering properly

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#648]
Hi, I'm not sure if this has to do with breakdance but I see it working for others.

This is my gallery layout in Gutenberg
![image](https://user-images.githubusercontent.com/51177627/211103236-d544b5a7-f206-4385-8c00-ab40d3ff0dd5.png)

and this is how it looks on the frontend

![image](https://user-images.githubusercontent.com/51177627/211103339-386450ff-15e0-44ed-8636-69135a1b3aba.png)

**Comment by orhanbilikvar** [comment]
Maybe you removed the Gutenberg Css?
BD>Setting>Performance

**Comment by dancerist** [comment]
I have learned that this has to do with BD's performance setting. If you tick "remove Gutenberg CSS", that's what gonna happen. make sense.

not a bug
