### ISSUE TITLE
ACF repeater images not opening in lightbox

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#649]
I've used an ACF repeater to create a gallery and when I click on the image 1 in the gallery it opens the lightbox but when clicking on images 2, 3, 4, 5 etc it loads the image in the browser window rather than in the light box.

**Comment by rizaardiyanto1412** [comment]
@a-dubiel I confirmed this

Step to replicate:
1. Create new repeater on ACF contain of image
2. Create global blocks contain image from ACF repeater
3. Set the link to lightbox
4. Create new post, add few images to repeater
5. Edit with breakdance
6. Add Repeater element
7. Choose the block
8. Save and view page
9. Observe issue, first image will open light box, the rest will not, and open the URL in browser instead
