### ISSUE TITLE
Video keeps playing on pop up

### ISSUE THREAD

**Issue by rizaardiyanto1412** [soflyy/breakdance-bugs#650]
Steps to reproduce the issue:

1. Create a pop up 
2. You can set the pop up to show when page load
3. Add youtube inside the popup
4. Save and view page
5. When the pop up is showing, try play the video on that popup
6. Close the pop up, the video will still playing

Expected behavior: Video stop playing on closing popup

![image](https://user-images.githubusercontent.com/83811723/211177208-f1ab86bc-870a-4455-bb28-5ee4f3e6bee8.png)

**Comment by dancerist** [comment]
I agree.
Please make this enhancement.

**Comment by jdweb86** [comment]
Hi there, I need to make quite a few popups and am having this same issue. Is there a way to fix it or will a fix be released relatively soon or should I look at using an alternative?

Thanks, really enjoying using breakdance!

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.4.
