### ISSUE TITLE
Vimeo Video element JS error subplugins/breakdance-elements/elements/Video/element.php

### ISSUE THREAD

**Issue by aadlung** [soflyy/breakdance-bugs#651]
When using the video element to embed a Vimeo video (observed after upgrading to 1.2, not sure if it was there before), I see JS error in console telling me that "observer is already defined".
The "observer" constant is defined in `subplugins/breakdance-elements/elements/Video/element.php` in line 538, and as "observer" is a very generic name, maybe it is used by any other plugin, I couldn't identify why it did not work.

Renaming the "observer" constant to "bdobserver" solved the issue.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
