### ISSUE TITLE
MiniCart Sidebar display issue when in sticky section

### ISSUE THREAD

**Issue by reactwoo** [soflyy/breakdance-bugs#653]
The MiniCart(Sidebar), when added to a sticky header section, maintains the height of the sticky section - not displaying the full sidebar as per the images attached - one image displays with the section (Non-sticky- displays sidebar correctly) however, when sticky selected (Top) the sidebar does not display correctly and maintains the height of the section

<img width="882" alt="MiniCart - no sticky section" src="https://user-images.githubusercontent.com/74898356/211472168-a04a03c4-6d47-4726-a003-d07042055333.png">
![MiniCart - In sticky section](https://user-images.githubusercontent.com/74898356/211472171-d8e9ee91-27e4-4b40-9e56-43adaafc982b.png)

![MiniCart - In sticky section](https://user-images.githubusercontent.com/74898356/211472396-5f1d3089-f966-4e59-8b29-626d694817f0.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
