### ISSUE TITLE
⚠️ Error with Animation on a Popup №2 [easy to reproduce] ⚠️

### ISSUE THREAD

**Issue by WpUser10** [soflyy/breakdance-bugs#656]
still cant make animations on popups.

![image](https://user-images.githubusercontent.com/48694545/211901862-203ede8a-9e3c-42d3-b583-62b63efc6a83.png)

**Comment by WpUser10** [comment]
![image](https://user-images.githubusercontent.com/48694545/211902402-b41eb1fe-3487-4cff-94ac-d569452b3cee.png)

**Comment by WpUser10** [comment]
i dont know what u cant to reproduce, its easy as 1,2,3:
1. create popup
2. make animation
3. profit.

here is url from YOUR website with that error included:
https://oxygen-qj92958r3cpql.oxygen-demo.qsandbox.org/?breakdance=builder&id=27

**Comment by WpUser10** [comment]
![image](https://user-images.githubusercontent.com/48694545/211905674-c5c14902-e9f8-458a-b748-b03f9a887641.png)

**Comment by WpUser10** [comment]
**COME ON!**

**Comment by WpUser10** [comment]
PLEASE

**Comment by WpUser10** [comment]
[a-dubiel](https://github.com/a-dubiel)

**Comment by a-dubiel** [comment]
https://www.loom.com/share/327bf77e3ee146bf95e5d488d74fc66f

I cannot reproduce this. Make sure you are using the latest version of Breakdance. Thanks.

**Comment by WpUser10** [comment]
i used your breakdance for that
https://breakdance.com/try/
https://oxygen-qj92958r3cpql.oxygen-demo.qsandbox.org/?breakdance=builder&id=27

**Comment by a-dubiel** [comment]
> i used your breakdance for that

I believe the live demo runs on 1.0 so it might be buggy. Please use the latest version and get back to me if this issue still persists. Thanks.

**Comment by WpUser10** [comment]
we have that error on 1.2.1 and have it from version 1.1

**Comment by a-dubiel** [comment]
1. Provide screen recording (not screenshot) of this error.
2. Provide exacts steps needed to recreate this error. This includes creating elements related to popups (like buttons triggering popups, forms etc.)

**Comment by WpUser10** [comment]
step 2:
1. open https://breakdance.com/try/
2. goto /wp-admin
3. click breakdance-popups
4. add popup "test1", (everywhere, page load=1s), SAVE
5. edit in breakdance
6. add section, add heading
7. add animation slide up - get error.

**Comment by a-dubiel** [comment]
> open https://breakdance.com/try/

In my previous message I informed you the website demo has not been updated to latest version (it runs on 1.0).

- If you want this solved, please recreate this error in 1.2.
- Provide provide the screen recording and exact steps to reproduce this.

I will not be able to help you unless those two requests are provided. Thanks.

**Comment by WpUser10** [comment]
step 1:

https://user-images.githubusercontent.com/48694545/212887989-83966284-f8ca-47b3-9ec4-5d71b8b2b641.mp4

i was recording that on 1.0 online demo because dont have 1.2 version right now on my pc
but error is the same!! swear of god

**Comment by a-dubiel** [comment]
> i was recording that on 1.0 online demo because dont have 1.2 version right now on my pc

Thanks. Like I said, I cannot reproduce this in 1.2. Make sure you update to 1.2. If the problem still persists please get back to me or e-mail support. Make sure to provide working URL to your website and admin credentials. This way we can help you quickly.

**Comment by WpUser10** [comment]
can u reproduce this on 1.2.1-beta.1 ?
it has the same error also

**Comment by WpUser10** [comment]
![image](https://user-images.githubusercontent.com/48694545/212889759-6ab9327e-2f7d-4d68-83d3-38d9650413ac.png)

**Comment by WpUser10** [comment]
not only me has that error.
but i cant to convince my co-workers to buy breakdance because they want popups and popups not working :(

**Comment by a-dubiel** [comment]
> can u reproduce this on 1.2.1-beta.1 ?

It is working fine in the newest beta. See below.

https://www.loom.com/share/2c9494fc35164afd877f484453b9c86d
