### ISSUE TITLE
Action name appears when custom acction triggers an error

### ISSUE THREAD

**Issue by slawomiroruba** [soflyy/breakdance-bugs#658]
It's enough to delete line 195 and 196 in file ```plugins/breakdance/plugin/forms/custom/custom.php```
But every time breakdance is updating this is overwriting. Can you please make an option to choose if action name should or not appear?

![image](https://user-images.githubusercontent.com/54029806/212037855-19581c05-d1f8-4b92-b443-e55c99cd237d.png)

![image](https://user-images.githubusercontent.com/54029806/212038258-91ba6684-0d5d-440a-ac79-3b0543775c14.png)

**Comment by a-dubiel** [comment]
This is needed for debugging purposes. Please elaborate what you are trying to achieve. Perhaps there is another way.

**Comment by louisreingold** [comment]
Closing as OP didn't respond to "Please elaborate what you are trying to achieve" for six months.
