### ISSUE TITLE
1.2 Column & Div 'Text Colours' broken

### ISSUE THREAD

**Issue by djrwp** [soflyy/breakdance-bugs#660]
Was working in 1.1, after update text colours within Divs and Columns is not respected. 
<img width="823" alt="Screenshot 2023-01-15 at 12 07 50" src="https://user-images.githubusercontent.com/84224815/212540039-aa040080-4778-41ac-8d81-71f3f0b7e3e8.png">

**Comment by djrwp** [comment]
I think this issue is fixed now??

**Comment by louisreingold** [comment]
Thanks for the report. We've deprecated the Text Colors controls on wrapper elements, so this won't be an issue going forward.
