### ISSUE TITLE
Videos: ACF link doesn't apply "Lightweight" mode

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#661]
In version 1.1 you present a new mode called "Lightweight" for videos, but it only works if it is a local video file. If I work with a link by ACF, it doesn't.

Lightweight mode:
https://youtu.be/H-paz3l6FR0?t=1619

When it's by ACF:
![breakdance_video](https://user-images.githubusercontent.com/122744933/212557940-3251b09d-b8c8-4021-a0d8-96c4789333b5.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
