### ISSUE TITLE
Star rating - add option to set the element vertical to never

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#662]
I'd like the element to stay horizontal or direction to row

I fixed it temporarily with custom CSS
%%SELECTOR%%.bde-star-rating {
  flex-direction: row !important;
}

![image](https://user-images.githubusercontent.com/51177627/212596226-025fa8f3-8348-48fb-baa4-5ce9b421e8d5.png)

**Comment by LambMediaGroup** [comment]
This should be an option on all elements really
