### ISSUE TITLE
Error with Popup animation on windows macbook

### ISSUE THREAD

**Issue by WpUser10** [soflyy/breakdance-bugs#664]
**Hello, this is a third thread, that is impossible to reproduce.**

I have tried all of these configurations:
macbook (main hardware)
windows 7,10,11 (the only one main system)
chrome/opera (latest version) with and without incognito

on all of these i got error with popup animation.
on all other devices it works very well, even on my smartphone.

**What could be the reason? at least theoretically**

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
