### ISSUE TITLE
Menu builder - desktop link - typhography - font resize not working on breakpoints.

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#665]
you can resize the text on desktop but can no longer do it from tablet down to mobile.

please refer to this FB post 
https://web.facebook.com/bertusdeleeuw/videos/1190199431871972?idorvanity=5118076864894234

**Comment by louisreingold** [comment]
As of Breakdance 1.3, many more controls in the Menu Builder are responsive, including these. Thanks for the suggestion!
