### ISSUE TITLE
Background overlay not working

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#666]
I'm using a section on this example
![image](https://user-images.githubusercontent.com/51177627/213327771-d0b8bd7f-0da2-4694-b47a-1e6919fc8f8d.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
