### ISSUE TITLE
The gallery element linked to an ACF gallery field within a ACF repeater element does not work as expected

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#668]
Here a small vid explaining the issue:
https://share.webmatic.be/nOu1QjGJ

So on load it only shows one image, when sizing the browser window all images are shown.

If you want me to prepare a staging site with the issue for this, let me know.

**Comment by a-dubiel** [comment]
Hey @adkoen thanks for your report. From the video I see this structure.

Advanced Tabs (vertical) > Tab Content > ACF Repeater > Gallery

Is this correct?

**Comment by adkoen** [comment]
Yes, this is correct. Here is a screenshot of the structure panel:
<img width="1496" alt="SCR-20230123-qo8" src="https://user-images.githubusercontent.com/7188497/214117343-01d111b9-b29b-4551-9502-1d9aa6e2d6ee.png">

**Comment by a-dubiel** [comment]
Alright. Thanks. We are aware of this bug and will ship the fix with the next release. Will update this thread when it happens.

**Comment by adkoen** [comment]
OK, looking forward. Thanks.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
