### ISSUE TITLE
Validation Error: IO-TS decoding failed

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#669]
Hi, I was only editing the site and suddenly errors just came out after saving it. I refresh the editor, I can save and continue working but the error are still there and looks like my dynamic data sections are not rendering in the editor but everything seems to be working well on the front-end

![image](https://user-images.githubusercontent.com/51177627/213866452-5e88065d-7c8b-4f3c-8e90-94a8f8ef80bf.png)

![image](https://user-images.githubusercontent.com/51177627/213866483-3e0b3b74-4a09-403f-98b2-b10d4372e8a4.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this without context. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
