### ISSUE TITLE
media Folder not working

### ISSUE THREAD

**Issue by MediaGozo** [soflyy/breakdance-bugs#67]
I'm using Gridpane. to manage my sites... as a norm i usually take their guidance and protect my sites using their site hardening and caching services.

When i do this... the media folder doesn't open.

![git1](https://user-images.githubusercontent.com/108728775/177301874-cc2153f9-9701-4720-bf56-2e7e1736e1b1.jpg)
![git2](https://user-images.githubusercontent.com/108728775/177301879-a6b99a69-cef5-4818-b80a-af5ff0a2a1a8.jpg)

These are the settings i normally enable to protect my site, i normally check them all... however when i do the media folder just hangs like in this users loom video:

https://www.loom.com/share/b9131532b5304fc9b8eff8ec06f02312

IF i can be of any further help please ask.
Thank you.

**Comment by louisreingold** [comment]
@MediaGozo we changed how the media library opens in beta 1. Does this still happen?

**Comment by MediaGozo** [comment]
@louisreingold Thank you I can confirm I have re-enabled all the Gridpane security settings and the Media library now appears without issue.

Thank you

![gp-wood](https://user-images.githubusercontent.com/108728775/179687464-7726eed2-9c4e-4821-84e0-1d89f43a5712.jpg)

**Comment by louisreingold** [comment]
Thank you!
