### ISSUE TITLE
Edit Content access allows customizing breakdance global styles?

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#674]
Please try to clearly describe the problem.
Set access for role (in my case Shop Manager) to edit only. Login as role. Go to theme->customiser->Breakdance Global styles.

You can access the global styles and so change all the site colours etc. This should not be possible with 'edit only' access.

**Comment by louisreingold** [comment]
This is solved in Breakdance 1.6.
