### ISSUE TITLE
Style dynamic Text Link or Text

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#676]
I'm trying to apply a color in a dynamic link. It doesn't apply on "a" selector, but in the parent div. See prints below.

In BD editor (it's green as it should):

<img width="606" alt="Screenshot 2023-01-24 at 00 58 41" src="https://user-images.githubusercontent.com/122744933/214191559-3054d10c-4b7f-459a-a609-2f930736773f.png">

In front-end (it's black):
<img width="164" alt="Screenshot 2023-01-24 at 00 58 57" src="https://user-images.githubusercontent.com/122744933/214191603-f5e958d9-b791-474e-ac3b-a11d1ca8e782.png">

Why, because it creates a second selector "a" that is black:
<img width="1706" alt="Screenshot 2023-01-24 at 00 59 31" src="https://user-images.githubusercontent.com/122744933/214191642-8a0a8721-b8cb-44a5-8407-463265450ea7.png">

And the first "a" get's the green in code but it's not the one showing in front-end:
<img width="1718" alt="Screenshot 2023-01-24 at 00 59 46" src="https://user-images.githubusercontent.com/122744933/214191719-e880be51-b045-41c3-82b0-71ac4fd6f551.png">

ALSO

Even using the basic text element, in the BD editor it doesn't apply the color.
It doesn't create a second "a", it creates a div and apply the color to it, not to the "a" selector.

<img width="624" alt="Screenshot 2023-01-24 at 01 06 05" src="https://user-images.githubusercontent.com/122744933/214192528-389b43ba-7787-48a0-a9f4-0fcdef49fa79.png">
<img width="291" alt="Screenshot 2023-01-24 at 01 06 09" src="https://user-images.githubusercontent.com/122744933/214192572-5387ee4b-e0f5-4218-9d31-c60a825c47dc.png">
<img width="587" alt="Screenshot 2023-01-24 at 01 11 43" src="https://user-images.githubusercontent.com/122744933/214192714-7edb22c3-9a68-4d08-a319-7aebde9e06c2.png">
<img width="298" alt="Screenshot 2023-01-24 at 01 11 48" src="https://user-images.githubusercontent.com/122744933/214192724-903d01a8-bd58-46cd-a193-ad9f9fb6f54f.png">

Hope I didn't confuse you. lol

**Comment by a-dubiel** [comment]
You should use the Rich Text element to style links individually using the appropriate typography controls.
