### ISSUE TITLE
Gallery slider in a repeater not working/broken

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#680]
**What version of Breakdance are you using?**
v1.2

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows

**Reproduction  Steps**
Step 1: Create a CPT with a repeater field. inside the repeater add a gallery field
Step 2: Add global block with slider gallery init.
Step 3: Add the CPT single template.
Step 4: Add the repeater element and choose the global block (step 2)

**Reproduction Video**
https://www.dropbox.com/s/euzs92ah8vg7qbe/Gallery%20slider%20in%20a%20repeater%20not%20working.MP4?dl=0

**Comment by a-dubiel** [comment]
Hey @dancerist thanks for your report. We are aware of this bug. This will be addressed in the next release. Stay tuned, will update you directly when this happens (very soon).

**Comment by louisreingold** [comment]
Sorry for not updating this issue. This has been addressed in a previous release of Breakdance.

**Comment by louisreingold** [comment]
Actually wait, has it? Or did we address a similar issue but not this one?

**Comment by louisreingold** [comment]
Thanks for the report. This was addressed recently.
