### ISSUE TITLE
Design Set invalid

### ISSUE THREAD

**Issue by Hakira-Shymuy** [soflyy/breakdance-bugs#681]
**What version of Breakdance are you using?**
1.2 / 1.2.1-beta.1

**What browser are you using?**
firefox, chrome

**What operating system are you using?**
Windows 11

**Reproduction  Steps**
Turn the website into a design set, go on another website, paste the domain, click save

This bug was present in prior to 1.2, when Louis made a video about the design library i though this was fixed
actually i asked on facebook about that and the answer was "yes"

looks like the bug "returned?"
when we set a website as a design set, save, and try to add that domain on another website as a design set, it gives the following error
The following URLs are invalid design sets and have been removed:

Have a client that wants to have the main elements, blocks, sections and so on, in a subdomain because the marketing team will be working closely with built elements as they wish to populate page content.
However, we cant really use the main domain as a design set because on the frontend everything appear as a section to copy, even incognito or logged out users

is there any future sight to fix this issue?

**Comment by a-dubiel** [comment]
Thanks for your report. We are aware of this issue. Planning on addressing this in the next release (very soon).

**Comment by obedparla** [comment]
@Hakira-Shymuy could you share the link to your design site website so I can test it? Or if you could contact our support team with details to your wordpress site we can confirm this is gonna be fixed.

https://breakdance.com/support

**Comment by obedparla** [comment]
Also, are both of your sites on the latest version? Mismatching versions could cause this issue.

**Comment by Hakira-Shymuy** [comment]
> Also, are both of your sites on the latest version? Mismatching versions could cause this issue.

both websites are on the same version, when i mention 1,2 / 1.2.1 i mean i tried both versions
i will reach out to support because i cant share the website due to NDA

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
