### ISSUE TITLE
Options for Design Set

### ISSUE THREAD

**Issue by Hakira-Shymuy** [soflyy/breakdance-bugs#682]
**Is your feature request related to a problem? Please describe.**
Yes, this feature is related to a problem with Design Set feature.
Mostly, i have a client who have a marketing team that will be working closely in page building with saved blocks / sections, we turn the website into a design set, not logged in or incognito users are still able to see the (copy) icon, as well the necessary z-index properties while hover a section

We are aware of a feature to disable design set per page, however, is not working. the page still have the copy feature.
Also, if we disable design set per page, then they will not be able to import sections

**Describe the solution you'd like**
An option to disable the copy sections feature on the frontend for not logged in users or users role = X

**Describe alternatives you've considered**
Change all the mockups, templates, blocks to a subdomain and use the design library feature, which is bugged also. "The following URLs are invalid design sets and have been removed:"

**Comment by louisreingold** [comment]
> An option to disable the copy sections feature on the frontend for not logged in users or users role = X

This is done in Breakdance 1.7. The copy button is can be hidden for users without a password. Thanks for the suggestion!
