### ISSUE TITLE
Rich text element filters out <table> and <figure> 

### ISSUE THREAD

**Issue by choegl** [soflyy/breakdance-bugs#683]
v1.2.1 - beta 1 (on macOS, Edge browser)

Add a Rich text element, select the HTML tab and enter html code, e.g. `<table><tr><td>Example</td></tr></table>` or `<figure>Text</figure>.` It will display correctly if you close the editor modal dialog with the HTML tab active.

All the mentioned tags will be gone when you re-open it or switch to the Visual tab. Just opening it will be enough to clear out the tags because the rich text element always opens with the Visual tab active. 

I guess the editor deliberately filters out all "bad" tags, but it would be nice if <table> (and related tags) and <figure> were added to the allowed tags.

**Comment by obedparla** [comment]
Same happens for <img> tag. Probably happens to many other tags too.

**Comment by Kpudlo** [comment]
https://secure.helpscout.net/conversation/2305307087/5904

**Comment by louisreingold** [comment]
Use a Code Block element to use any HTML tag. Could our Rich Text field support tables? Tracking at https://breakdance.canny.io/element-requests/p/full-rich-text-wysiwyg-element-like-tinymce
