### ISSUE TITLE
Structure node SVG-icons not visible in Safari

### ISSUE THREAD

**Issue by medianotions** [soflyy/breakdance-bugs#684]
**What version of Breakdance are you using?**
v1.2.1

**What browser are you using?**
Safari 16.2

**What operating system are you using?**
For example: macOS

**Reproduction  Steps**
Open the Breakdance editor in Safari and open the structure panel

**Reproduction Video**
Here is a screenshot: https://share.medianotions.de/j/0AtIsWoiQgSElYGCSFNi

**Suggested solution**
Safari seems to need explicit dimension settings for the  SVG-icons. I was able to solve the problem by adding this CSS:

`.structure-node-action__icon.breakdance-icon > svg { width: inherit; }`

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
