### ISSUE TITLE
Problem with icon-color info notice in Global Styles Woocommerce

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#686]
**What version of Breakdance are you using?**

1.2.1

**What browser are you using?**

Chrome latest

**What operating system are you using?**

macOS latest

**Reproduction  Steps**

Global Styles > WooCommerce > Other > Notices > Info > Icon
Setting the color through a variable or direct name doesn't work. It does work when using the color picker.

**Reproduction Video**
![SCR-20230205-gjw](https://user-images.githubusercontent.com/7188497/216815005-1b4b841e-f7d9-47a4-b168-0a6203d95fb2.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
