### ISSUE TITLE
Custom svg icon color

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#688]
BD 1.2.1

When using a custom svg icon in the icon element the selected color is not used.
Instead the brand color is always used.

**Comment by a-dubiel** [comment]
Hey @mikehenze can you share the SVG you are trying to use?

**Comment by mikehenze** [comment]
![Arrow circle-01](https://user-images.githubusercontent.com/10600315/217795260-cac366c0-47ab-4357-8c43-60b5429993d5.svg)

**Comment by a-dubiel** [comment]
<img width="516" alt="Screenshot 2023-02-09 at 12 07 11" src="https://user-images.githubusercontent.com/669243/217796073-2360416b-6ea7-4bb5-af41-824a2bd0ba32.png">

Looks like this SVG has inline styling (notice the `<style>` tag). Make sure your SVGs are exported with out it or try running it through tools like this https://jakearchibald.github.io/svgomg/
