### ISSUE TITLE
Shape divider does not work properly.

### ISSUE THREAD

**Issue by bombaka90** [soflyy/breakdance-bugs#69]
In section that have double shape divider, bottom shape appears upside down, i try to clear cache and change section and shape tipo.
Does anyone know how to fix this?
Link: [](https://iperform.training/iperform/)
TY
Please try to clearly describe the problem.

Including a screenshot of the problem is a good idea.

(Or a screencast - https://www.loom.c
![shape doesnt work](https://user-images.githubusercontent.com/83416939/177429072-cc956f1c-fd24-4d61-8f35-f9a51e65108a.JPG)
om/)

**Comment by louisreingold** [comment]
I'm not able to reproduce this in beta 3: https://www.loom.com/share/ec488ade8ab14d33aaf642406688725f

If this still happens for you, please contact support@breakdance.com.
