### ISSUE TITLE
Menu - Add option for vertical menus

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#691]
**Is your feature request related to a problem? Please describe.**
My projects have required vertical menus recently. Not to mention the footer where I use wp menus every build. And i kept adding this line of code to make my menus vertical:

%%SELECTOR%% .breakdance-menu-list{
  flex-direction: column;
  align-items: flex-end;
}

**Describe the solution you'd like**
Add an option to display it vertical

**Describe alternatives you've considered**
only custom CSS atm or basic list element

**Comment by a-dubiel** [comment]
Feel free to test this in 1.3 Alpha.
