### ISSUE TITLE
Menu builder - Menu Dropdown - link - add the gear icon or option to "open new tab"

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#693]
**Is your feature request related to a problem? Please describe.**
The menu dropdown link doesn't have the option to open a new tab, or the gear icon in general (see img attached).
![image](https://user-images.githubusercontent.com/51177627/218617821-4bd0fc41-55dc-4611-8ad2-67bec6f46233.png)

**Describe the solution you'd like**
Maybe add the same feature for all links?

**Describe alternatives you've considered**
For now, we can use the custom dropdown menu and manually add buttons or links that support "open new tab"

**Additional context**

### **MENU LINK**
![image](https://user-images.githubusercontent.com/51177627/218617821-4bd0fc41-55dc-4611-8ad2-67bec6f46233.png)

### **MENU DROPDOWN LINK**
![image](https://user-images.githubusercontent.com/51177627/218618490-d393cc7e-7ca5-4a8a-8541-8015c1517f64.png)

**Comment by breakdancemoderator** [comment]
Thanks for the report. This option has been available since Breakdance 1.6.
