### ISSUE TITLE
Form conditions for number values fail

### ISSUE THREAD

**Issue by choegl** [soflyy/breakdance-bugs#697]
Most current version of Breakdance (1.2.1), browser independent.

Conditions are ignored, see this example:
[https://sandbox.creativbox.at/no-number-condition-in-breakdance-form/](url)

**Comment by choegl** [comment]
additionally there is another bug. Follow these steps:

1. create a number field q
2. create a text field with the condition to show if q = 1
3. duplicate that conditional field
4. switch the condition toggle to on in this text field
5. now the conditions "greater than" and "less than" are not visible. only selecting any other condition first will make them appear, too.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
