### ISSUE TITLE
Import page global block not added

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#698]
**What version of Breakdance are you using?**
v1.2.1

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction  Steps**
When adding a whole page from the library (this website), global blocks won't be imported but instead it places the structured elements.

**Comment by louisreingold** [comment]
Tracking at https://breakdance.canny.io/features/p/design-library-save-import-and-export-template-parts
