### ISSUE TITLE
Shadow Not Working on Hover in Forms Buttons

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#699]
As mentioned in the title, when adding a hovering shadow to a form button, it doesn't work. No matter the settings, x, y, blur, or spread, nothing works when hovering.

The same style works just fine on normal buttons.

I'm using **Version 1.2.1** on a **CloudWays** server.

![Screen Shot 2023-02-21 at 17 30 10](https://user-images.githubusercontent.com/54561285/220410281-575e4f9a-e7ce-4cee-b707-31fdc5fb613f.png)

**Comment by a-dubiel** [comment]
@NaoufelTarchoul weird. I cannot reproduce this. Any chance you can share a URL to look at?
