### ISSUE TITLE
Pricing Table Suggestions

### ISSUE THREAD

**Issue by onenyarko** [soflyy/breakdance-bugs#70]
**Pricing Table Width:** Width has only px with no other unit of measurement. Can %, VW be added to it? The width is also not responsive. 

**Pricing Table Feature List:** There’s a center styling on the Feature Tab under the pricing. When it is checked, the feature list only centers itself according to a predefined width. The width is not a styling option that can be changed. You can only change it via custom CSS. 

CSS code: .essential-elements-pricing-table__features {
  width: 100%;
}

**Pricing Table Dividers:** Can there be an option to add dividers between sections of the pricing table.  For example, a divider between the features and the pricing section.

**Lottie Files:** It seems you can only have Lottie via a link, can there be support for it to be uploaded via the media library.

**SVG Files:** SVG files can not be uploaded natively via the media library. If you want to use an SVG it is only via the icon element. Can we have support for SVG files via media library upload?

Link to the page: https://breakdanceblog.us5.instawp.xyz/pricing/

**Comment by louisreingold** [comment]
Width:
 - added responsive support in beta 3
 - added units in beta 4 (coming soon)
 
 Feature List centering: please elaborate on what the purpose of this control would be - i.e. what layout does it allow you to create
 
 Dividers, Lottie upload, SVG upload - suggest this at https://breakdance.canny.io/

**Comment by louisreingold** [comment]
@onenyarko 

Width:
 - added responsive support in beta 3
 - added units in beta 4
 
 Feature List centering: please elaborate on what the purpose of this control would be - i.e. what layout does it allow you to create
 
 Dividers, Lottie upload, SVG upload - suggest this at https://breakdance.canny.io/
