### ISSUE TITLE
BUG FRONTEND

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#701]
On the following site: [https://locationduplexprazsurarly.fr/](https://locationduplexprazsurarly.fr/?fbclid=IwAR26gGV1bDq0BxAJlV_f7BwMjKk62OTQ_DMxaIMNlK9dis5tbmSPrDxTBaM), in the editor everything appears as it should, but on the rendering, all styles crash and malfunction, Breakdance is the only extension installed yet, can you tell me where it comes from?

**Comment by a-dubiel** [comment]
It would be useful to show what the builder view look like.

**Comment by rodolphebertozzo** [comment]
![image](https://user-images.githubusercontent.com/56270626/220742011-00e4db10-14cf-497b-ac3a-faa075301911.png)
