### ISSUE TITLE
Popup that's configured to open on selector click not working

### ISSUE THREAD

**Issue by tommytompkins** [soflyy/breakdance-bugs#702]
**What version of Breakdance are you using?**

v1.2.1

**What browser are you using?**

Chrome

**What operating system are you using?**

OSX

**Reproduction  Steps**

1) Create a new popup
2) Configure the popup to open when an element with a selector class .popup-bug-test is clicked (the actual class name doesn't matter)
3) Add a basic wrapper link element to your page
4) Add a basic text link element to your page
5) Add the .popup-bug-test class to both the wrapper link element as well as the text link element
6) Refresh the page and click both. Notice how the text link opens the popup but the wrapper link does not.

![Screen Shot 2023-02-22 at 4 24 06 PM](https://user-images.githubusercontent.com/4631803/220775795-75f688e6-4510-47dc-848a-023bd665ffce.png)

**Comment by a-dubiel** [comment]
https://www.loom.com/share/d3976ad5cae64788bf9f37d77d4558f3

Hey @tommytompkins sorry I can't reproduce it. See my Loom above.

Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
