### ISSUE TITLE
Google Search Console - Critical Error - Missing "position" field (in "itemListElement")

### ISSUE THREAD

**Issue by slawomiroruba** [soflyy/breakdance-bugs#708]
Many clients have been contacting our agency via email, reporting that they have received critical error messages from Google Search Console regarding their website, which is preventing it from being indexed. After investigating the issue, we have determined that it is due to an incorrect structure in the navigation menu. I am providing a link to a Google guide on how it should be done. Is there a chance that you will address this in the near future, or should we take steps to fix it ourselves?

![image](https://user-images.githubusercontent.com/54029806/223083282-14f64bf7-6374-4185-8960-c26482a525db.png)
https://developers.google.com/search/docs/appearance/structured-data/breadcrumb#html

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
