### ISSUE TITLE
Shop Filter (woo) 

### ISSUE THREAD

**Issue by Gille666** [soflyy/breakdance-bugs#709]
Latest bd version: Version 1.2.1
Tested in Chrome, Firefox, Safari
Theme: Zero theme Breakdance

When make a template for the main shop page: 2 column with left the filtering and right the shop page

-> I use the Shop filters module and choose attribute filter with the right attribute and display list and query "or".
It will not filter when clicked on a filter link. It goes directly to a product.

-> When I use the display dropdown option it will work like it should.

Looks like a bug. 

Thanks
Gille

https://user-images.githubusercontent.com/127147141/223219500-e6ec6e71-952e-4877-93fb-e001b7969e2d.mp4

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
