### ISSUE TITLE
Section Slideshow Background - BETA 1

### ISSUE THREAD

**Issue by nicolaskid** [soflyy/breakdance-bugs#71]
section slideshow background is not showing/working on the front-end but works fine in the editor after updating to beta 1 update.

I did regenerate CSS and clear cache.
Link - https://searchmaasin.online/ 

![image](https://user-images.githubusercontent.com/51177627/179466473-b8e9b133-7cd5-4f1a-a5c4-8256a1faa515.png)

![image](https://user-images.githubusercontent.com/51177627/179466529-80036807-a0de-4006-a133-7a2f0dfb959b.png)

**Comment by louisreingold** [comment]
https://www.loom.com/share/6bb0025ac7d74299ba5d4a409e49f00c

Try upgrading to beta 3. If that doesn't help, please submit a support ticket to support@breakdance.com.

**Comment by nicolaskid** [comment]
Good to know it’s working on your end. I’m updated to beta 3 and still facing same trouble. I already sent a ticket. Thanks! From: Louis ReingoldSent: Saturday, July 23, 2022 2:15 PMTo: soflyy/breakdance-bugsCc: BD Builder Lover; AuthorSubject: Re: [soflyy/breakdance-bugs] Section Slideshow Background - BETA 1 (Issue #71) https://www.loom.com/share/6bb0025ac7d74299ba5d4a409e49f00cTry upgrading to beta 3. If that doesn't help, please submit a support ticket to ***@***.***—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
