### ISSUE TITLE
WooCommerce: Available on back-order notice not displaying

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#711]
**What version of Breakdance are you using?**

v1.2.1

**What browser are you using?**

Edge

**What operating system are you using?**

Windows

**Reproduction  Steps**

- enable WooCommerce inventory management
- create a product with inventory of 0
- allow back-orders and set to 'allow backorder, notify customer'

available on back-order notice should show, but it is set to display:none

**Reproduction Video**

https://komododecks.com/recordings/pnuBjYdVbh53XNBybjLv

Adding this code to the product cart button works around the problem:

%%SELECTOR%% p.available-on-backorder {
    display: block;
}

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
