### ISSUE TITLE
Shadows and boders doesen't work properly in breakpoints

### ISSUE THREAD

**Issue by Kartoon160272** [soflyy/breakdance-bugs#712]
**What version of Breakdance are you using?**

I'm using version 1.2 (The last available now.

**What browser are you using?**

I'm using Safari

**What operating system are you using?**

MacOs

**Reproduction  Steps**

**Reproduction Video**
I'm using a border with radius 8px, light grey and 1px solid. Also use a shadow (values 0-20-32-0)
This works great. But I don't ant these borders and shadows in mobile view. So I change the breakpoint to Phone landscape and also phone portrait, and remove the border and shadow there.
Both also disappear in desktop view then. Disappears in every breakpoint really

**Comment by a-dubiel** [comment]
You need to set these borders explicitly for each breakpoint. If you don't want borders on mobile you need to set the shadow values to 0. "Clearing" control will remove it for all breakpoints.
