### ISSUE TITLE
Shortcode to build the text string of a menu link inside a menu builder only runs on save

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#713]
**What version of Breakdance are you using?**

latest

**What browser are you using?**

Arc, Chrome, it doesn't matter for this bug

**What operating system are you using?**
mac OS

**Reproduction  Steps**
So I use a shortcode to dynamically render the text of a menu inside a menu buillder. This only runs on save. It never runs again and the same text that was rendered on save is showed on the frontend.
See the video below, on the right side I have added a code block with the same logic and this updates every time.

![SCR-20230308-etj-2](https://user-images.githubusercontent.com/7188497/223678563-6f8634ee-6dac-4155-b6c2-a40d0b9a6771.png)

**Reproduction Video**
https://share.webmatic.be/BlubpvOg

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
