### ISSUE TITLE
Radio fields missing from CSV export of Stored Submissions in Form Builder

### ISSUE THREAD

**Issue by TheWebSmiths** [soflyy/breakdance-bugs#715]
**What version of Breakdance are you using?**

1.2.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction  Steps**

When using a form with text and radio fields, the submissions are stored correctly under 'Form Submissions' BUT, when exporting the entries to a CSV file the radio fields are missing.

I've also been able to reproduce this issue at the Try Breakdance demo site.

**Reproduction Video**

**Comment by choegl** [comment]
I can confirm that error. Also true for checkbox fields. Their contents is shown in the confirmation emails and when you access the entry on the website, but get lost on csv export.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
