### ISSUE TITLE
Attributes: Invalid Character

### ISSUE THREAD

**Issue by salasmx** [soflyy/breakdance-bugs#716]
**What version of Breakdance are you using?**

v1.2.1

**What browser are you using?**

Tested on Chrome, Safari, Mozilla, and Edge

**What operating system are you using?**

macOS

**Reproduction  Steps**

Here is a screenshot of the error I'm getting.
[https://share.getcloudapp.com/12u7EBe8](https://share.getcloudapp.com/12u7EBe8)

I've tested this on Elementor and Webflow and both worked.

**Comment by obedparla** [comment]
@salasmx what do you need to have a column in the html attribute for? Could you give me an example? Is there a library that uses them or something?

**Comment by salasmx** [comment]
@obedparla I'm using memberstack.com and they provide a lot of attributes [https://share.getcloudapp.com/E0uXEnGB](https://share.getcloudapp.com/E0uXEnGB) the thing is the attributes that end with ":update", ":add", or ":remove" does not work in the breakdance attributes panel. Also, I've been looking and it seems there is no option to add attributes to form fields.

**Comment by obedparla** [comment]
> the attributes that end with ":update", ":add", or ":remove" 

Makes sense

> Also, I've been looking and it seems there is no option to add attributes to form fields.

Not at the moment, but noted.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
