### ISSUE TITLE
CSV form submission download results in TMP files in wp-admin folder

### ISSUE THREAD

**Issue by TheWebSmiths** [soflyy/breakdance-bugs#717]
**What version of Breakdance are you using?**

v1.2.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction  Steps**

When downloading form submissions as CSV files, Breakdance is creating and retaining TMP files directly into the wp-admin folder.

WordFence is detecting these files and sending 'High Severity Problems' warnings out. Should these files either be removed following download or be saved somewhere other than the wp-admin folder?

High Severity Problems:
Unknown file in WordPress core: wp-admin/breakdance-submission-export-csvtmp-3XU0ec.tmp
Unknown file in WordPress core: wp-admin/breakdance-submission-export-csvtmp-mlqkJf.tmp
Unknown file in WordPress core: wp-admin/breakdance-submission-export-ziptmp-XMb4FT.tmp

**Reproduction Video**

**Comment by a-dubiel** [comment]
Thanks for your report. This will be addressed in the next release.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
