### ISSUE TITLE
Important request regarding custom CSS

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#719]
When adding custom CSS and forgetting to close the quotation mark, the site styles crash, which is normal, since the rules are added at the end of the existing rules. Can you add a tooltip to warn the user if he forgets to close a quote in a custom CSS that the style may crash

**Comment by rodolphebertozzo** [comment]
@a-dubiel

**Comment by a-dubiel** [comment]
> Can you add a tooltip to warn the user if he forgets to close a quote in a custom CSS that the style may crash

Users should be responsible for writing valid CSS. Not the builder. We are working on some safe guards that might prevent invalid CSS from being saved but at the end of the day it is the users responsibility. If you are not sure if you your CSS is valid there are [CSS validators online ](https://jigsaw.w3.org/css-validator/validator) you can use.

**Comment by rodolphebertozzo** [comment]
Yes. I see
