### ISSUE TITLE
Global block error & ACF repeater field returns error - Undefined array key "is_sub_field"

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#720]
**What version of Breakdance are you using?**
1.3 alpha

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows

**Reproduction  Steps**
1.) Create ACF repeater
2.) Connect the data dynamically when building the global block

![image](https://user-images.githubusercontent.com/51177627/225704222-d0984c62-bd39-43e6-8c5a-d86fbbaa8e59.png)

**Comment by dancerist** [comment]
@a-dubiel @louisreingold

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.

**Comment by StaggerLeee** [comment]
Adding ACF PHP code in Code Block, inside Global Blocks, make some strange loop despite PHP code is 100% perfect.
I had to restart Apache server and delete Code Block to make it OK again.
