### ISSUE TITLE
Product list - Slider infinite not working properly

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#721]
**What version of Breakdance are you using?**
1.3alpha

**What browser are you using?**
chrome

**What operating system are you using?**
Windows

**Reproduction  Steps**
1.) Use the product list element and into a slider
2.) set slide to infinite
3.) on the front-end sliding to left works but not to right

![product slider issue](https://user-images.githubusercontent.com/51177627/225705540-50963118-8049-4aa5-8480-6e6834dc39c9.gif)

**Comment by a-dubiel** [comment]
@dancerist thanks so much for the report. Bugs you reported will be addressed most likely tomorrow.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
