### ISSUE TITLE
Advanced Accordion Icons Disappear on Mobile

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#722]
The Advanced accordion icons disappear on mobile as the photo displays.

**Version**

Version 1.3.0-alpha.1

**What browser are you using?**

All main mobile browsers

**What operating system are you using?**

iOS and Android.

**Reproduction  Steps**

Add an Advanced accordion to any page. Make sure the icons are set. Access the page from mobile.

![Advanced Accordion icons on mobile](https://user-images.githubusercontent.com/54561285/225728397-d6365fd2-28b7-42e7-afb8-b5dd4e38e5d6.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
