### ISSUE TITLE
Advanced slider width collapses

### ISSUE THREAD

**Issue by NietAkkoord** [soflyy/breakdance-bugs#723]
**What version of Breakdance are you using?**
Version 1.2.1

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows

**Reproduction  Steps**

I tried to add an advanced slider in a section - should be full width.
Section has been set to 100%, all paddings 0.
Advanced slider has been put in the section, set to 100%. Removing all example slides, except from the one width the header.
Adjusting slider settings, such as the arrows in overlap. Suddenly the slider collapses and it's impossible to set back at 100%.
Putting a div below 100% > works perfect.
Tried it several times, collapses every time but not necessarilly when adjusting the arrows. It just happens.
[video.webm](https://user-images.githubusercontent.com/128130598/225849889-0fe738c9-ae6b-47e9-a2c0-26b815f7ea4f.webm)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
