### ISSUE TITLE
Open image lightbox triggered by button on mobile not working

### ISSUE THREAD

**Issue by slawomiroruba** [soflyy/breakdance-bugs#724]
When I want when I click on the button is to open the lightbox with a photo everything works ok on computers and on mobile devices it flashes for a second and shuts down. Please help.

https://www.loom.com/share/62877cdcb6b44fe1bce2fb84117a6b01

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
