### ISSUE TITLE
Fatal Error after update to version 1.3.0-alpha.1

### ISSUE THREAD

**Issue by wp-vaksin** [soflyy/breakdance-bugs#725]
**What version of Breakdance are you using?**

For example: v1.3.0-alpha.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction  Steps**

Just click update and go to dahasboard

Error Message (Debug Mode):
Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/tmp/breakdance/twig-auto-generated-cache/4d). in /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Cache/FilesystemCache.php:53 Stack trace: #0 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php(352): Breakdance\Lib\Vendor\Twig\Cache\FilesystemCache->write() #1 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php(312): Breakdance\Lib\Vendor\Twig\Environment->loadTemplate() #2 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php(280): Breakdance\Lib\Vendor\Twig\Environment->load() #3 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/render/twig.php(219): Breakdance\Lib\Vendor\Twig\Environment->render() #4 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(336): Breakdance\Render\Twig->runTwig() #5 [internal function]: Breakdance\Render\{closure}() #6 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(342): array_reduce() #7 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/render/cache.php(218): Breakdance\Render\cssForGlobalStyles() #8 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/setup/clean-cache.php(22): Breakdance\Render\generateCacheForGlobalSettings() #9 /home/rentugo-demo.eweb.id/public_html/wp-includes/class-wp-hook.php(308): Breakdance\Setup\cleanCacheWhenCacheCountChanges() #10 /home/rentugo-demo.eweb.id/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #11 /home/rentugo-demo.eweb.id/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #12 /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin.php(39): do_action() #13 /home/rentugo-demo.eweb.id/public_html/wp-includes/class-wp-hook.php(308): {closure}() #14 /home/rentugo-demo.eweb.id/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #15 /home/rentugo-demo.eweb.id/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #16 /home/rentugo-demo.eweb.id/public_html/wp-settings.php(480): do_action() #17 /home/rentugo-demo.eweb.id/public_html/wp-config.php(108): require_once('...') #18 /home/rentugo-demo.eweb.id/public_html/wp-load.php(50): require_once('...') #19 /home/rentugo-demo.eweb.id/public_html/wp-admin/admin.php(34): require_once('...') #20 /home/rentugo-demo.eweb.id/public_html/wp-admin/index.php(10): require_once('...') #21 {main} thrown in /home/rentugo-demo.eweb.id/public_html/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Cache/FilesystemCache.php on line 53

**Comment by wp-vaksin** [comment]
it seem bugs, i did var_dump on your twig.php file and below is the result:

Debug script:
$cache = $this->twig->getCache();
var_dump($cache); exit;

Result:
v2.1
string(94) "/home/rentugo-demo.eweb.id/public_html/wp-content/uploads/breakdance/twig-auto-generated-cache"

v1.3.0-alpha.1
string(41) "/tmp/breakdance/twig-auto-generated-cache"

**Comment by wp-vaksin** [comment]
After I read comment from Louis on FB, it seems intentional. Please rollback it to the previous version, this will be a problem if the directory is used by many users that using breakdance, the 2nd user cannot access the directory that was created by the previous user (because of same folder name).

**Comment by tonylondon** [comment]
Same issue here, also on Plesk.

**Comment by a-dubiel** [comment]
Thanks everyone. This will be fixed in the next alpha.

**Comment by Nicscott01** [comment]
Hey everyone, 

There's a quick fix to this that worked for me, if you want to continue to use 1.3.0-alpha.1:

`define( 'WP_TEMP_DIR', 'custom_directory_for_website_user' );`

Just define WP_TEMP_DIR to whatever you like. I set it to a path only accessible by the user account running my website. 

I'm not sure if there are other consequeces to this, but WP defaults to the root directory /tmp on the server. Seem like every site on a server should have its own tmp directory.
