### ISSUE TITLE
Repeater field query broken in 1.3

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#727]
I had a repeater field that used a basic query to select certain pages. That no longer works and just shows all pages. As you can see in the image below. It should just be showing the pages in the list but there's loads more showing as you can see in the background.

![image](https://user-images.githubusercontent.com/117674105/226061571-995904a5-1035-496a-b9bc-74c9e329c39e.png)

**Comment by RoninReilly** [comment]
Same. If we pick one category of post - result is good. If we pick multiple categories - result only latest category in list. Same situation in other query variants - text, array

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
