### ISSUE TITLE
Modulo by zero error when opening the product query

### ISSUE THREAD

**Issue by antonijo01** [soflyy/breakdance-bugs#73]
I added the product list to the empty section and when I click on the products query I get an error. Check image below.
 ![image](https://user-images.githubusercontent.com/107608985/179627420-91df0d00-2558-46fb-85fd-a10f48597815.png)

I am using the latest version - Beta version
PHP: 8.1.8

**Comment by louisreingold** [comment]
@Rados51 @antonijo01 I'm having trouble reproducing this locally but multiple people have reported it.

Can you please send your WP admin login details to support@breakdance.com so we can take a look?

**Comment by louisreingold** [comment]
This is solved in beta 5.
