### ISSUE TITLE
Icon List color setting not working if parent section has Text Colors >> Text setting set

### ISSUE THREAD

**Issue by bhartlenn** [soflyy/breakdance-bugs#732]
**What version of Breakdance are you using?**

v1.2.1

**What browser are you using?**

Firefox, Chrome, Safari

**What operating system are you using?**

macOS

**Reproduction  Steps**

1. Open a page in the Breakdance Editor, and add a section, then inside of that section, add an icon list element.
2. For the section set Design Tab >> Text Colors >> Text to some blue(whatever you like) color
3. For the child Icon list element set the Design Tab >> Icon >> Color to some red(different than before, but whatever you like) color.
4. The icon list icon color will stay the same as the text color setting for the section, instead of over riding it

Also when inspecting the svg element in the icon list icon you can see the color css from the section elements text color setting is inherited there on the svg element: but, the icon list color setting is applied to its parent span element. I wasn't able to over ride the styling from the section text color setting manually, but the css color for the icon list icon color needs to over ride the inherited styling from the section basically.
<img width="1501" alt="parent-span-styling" src="https://user-images.githubusercontent.com/791598/226751562-c829c089-9c7a-4319-a97e-381f47f0c5f9.png">
<img width="1499" alt="svg-styling" src="https://user-images.githubusercontent.com/791598/226751595-4afc46cc-dce2-4851-80ce-b1ba2046d388.png">

**Comment by louisreingold** [comment]
Thanks for the report. We've deprecated setting text colors on a wrapper, so this won't be an issue going forward.
