### ISSUE TITLE
Adding gradient colours to a circle counter makes it go "crazy"

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#734]
**What version of Breakdance are you using?**

v1.2.1

**What browser are you using?**

Edge

**What operating system are you using?**

Windows 11

**Reproduction  Steps**

- add a circle counter element
- choose 'bar style' of 'gradient'
- set a gradient start value using one of the global colours
- counter forever increments and the circle does not show

Picking colours explicitly (i.e. not global colours) allows correct behaviour.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
