### ISSUE TITLE
Hover over dropdown menu not working in Safari (macOS Ventura 13.2.1)

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#738]
**What version of Breakdance are you using?**
v1.2.1

**What browser are you using?**
Safari

**What operating system are you using?**
macOS Ventura 13.2.1

**Reproduction  Steps**
When hovering over the menu you can't select the menu item.

**Reproduction Video**
https://user-images.githubusercontent.com/56388399/227470737-9ed8a5c7-97be-4803-99ec-299516f220f2.mov

**Comment by jeffreyvandervet** [comment]
I think it's the z-index of the .breakdance-dropdown-floater. It needs to be 0 or just don't set it :). I don't know if it breaks anything else though.

**Comment by a-dubiel** [comment]
@jeffreyvandervet can you provide a working URL?

**Comment by jeffreyvandervet** [comment]
Sure, here you go:

https://callgranny.com/

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials. 

Also, feel free to try 1.3 Alpha. We made significant improvements to Menu Builder. This might fix it as well.
