### ISSUE TITLE
Mobile menu top level items, with submenu, do not link to page (only toggles sub-menu)

### ISSUE THREAD

**Issue by joerimarquerinck** [soflyy/breakdance-bugs#739]
V 1.2.1
Brave (chrome)
MacOS

With the mobile menu the top level menu item doesn't link to the page. It only toggles the submenu. It would be better if the icon (chevron) only toggles the submenu but you can still visit the page when clicking the top level menu name.

For example visit this site and check the mobile menu: https://www.furfreealliance.com/

**Comment by a-dubiel** [comment]
See #206
