### ISSUE TITLE
Internal Server Error: Trying to access array offset on value of type bool.

### ISSUE THREAD

**Issue by salasmx** [soflyy/breakdance-bugs#740]
**What version of Breakdance are you using?**

v1.3.0-alfa.1

**What browser are you using?**

Chrome, Safari, Microsoft Edge

**What operating system are you using?**

macOS Monterey

**Reproduction  Steps**

This warning occurs on "published" posts/pages/cpt when hitting the "save" button. Nothing happens when the posts/pages/cpt are in "draft" mode. I have to mention that despite the warning, the "save" button works. It saves the changes.

<img width="564" alt="Screen Shot 2023-03-26 at 22 35 13" src="https://user-images.githubusercontent.com/15803964/227842692-e9678096-dd2d-4994-9c2d-07df5dbac2a8.png">

<img width="923" alt="Screen Shot 2023-03-26 at 22 35 45" src="https://user-images.githubusercontent.com/15803964/227842714-e73b094f-7902-4a8a-a928-31667df1681a.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Comment by gruntek** [comment]
I have the same problem, did you solve it?
