### ISSUE TITLE
Icon and Button Element - Hover

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#742]
In the Icon Element, we have the option to change the color of the border on hovering, but is not working.

In the Button element, we don't have either of the option of changing the color or width of the border (outline) on hover. It has to be by code.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
