### ISSUE TITLE
Duplicate OR Unneeded Css when using [breakdance_block blockid="$post_id"] OR \Breakdance\Render\render($post_id)

### ISSUE THREAD

**Issue by theperfectwill** [soflyy/breakdance-bugs#743]
**What version of Breakdance are you using?**

 v1.2.1 and 1.3 alpha 1

**What browser are you using?**

Brave (Chromium)

**What operating system are you using?**

macOS

**Reproduction  Steps**

_Just let me know if there is something I should test/or change._

When having multiple instances of the shortcode `[breakdance_block blockid="$post_id"]` OR when `echo \Breakdance\Render\render($post_id);` is called for Breakdance content outside of the currently displayed post.

There are multiple instances of unneeded (duplicate) css generated where used, OR css that should have an ID prefixed to it, so it only applied to content generated from that post, and not global applied to the page where the shortcode or global element is inserted. I hope that makes sense, because then it becomes complicated to overwrite the css.

You can view the screenshots below of what I mean. Correct me if I am wrong, but all these styles seem to be styles that should be explicitly part of the "Global Styles" file. Which brings me to also mention a feature suggestion.

That suggestion is a "Global Elements" 

<img width="158" alt="About Us – Site_Title-03282023-090629About Us – Site_Title-03282023-090629" src="https://user-images.githubusercontent.com/6123260/228248226-5919d293-b3be-4e3a-ac27-23ee17645d40.png">

<img width="157" alt="About Us – Site_Title-03282023-092829About Us – Site_Title-03282023-092829" src="https://user-images.githubusercontent.com/6123260/228252418-c8c0058a-2699-4670-906b-9f40e1e7bd39.png">

**A Proposed (brainstorm) Solution**

The screenshot below is what I mean about having a specific section to style global elements of Breakdance, which then would be generated into a "global-elements.css" file, to avoid the issue above, while creating a specific section for users to customize the default style of certain elements.

<img width="185" alt="Breakdance | About Us-03282023-093120Breakdance | About Us-03282023-093120" src="https://user-images.githubusercontent.com/6123260/228253483-e5a755e7-3b84-4bed-9e08-edd57358431a.png">

Facebook Post Reference: https://www.facebook.com/groups/breakdanceofficial/posts/5999883150046930/

**Comment by louisreingold** [comment]
The reason we don't do this is because most sites don't use anywhere close to all the elements so we'd be loading a lot of stuff that is never used, so the performance for 99% of users is far better with our approach, even though it means a tiny amount of CSS is duplicated.
