### ISSUE TITLE
Enhancements to search bar for element fields

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#744]
1. Move the search option that is at the bottom the field settings sidebar to the top of that sidebar. I use this a lot and I have to go all the way down to the screen every time I need to search something.
2. If I click on the modify icon to show only the modified fields, keep it on modify when click next element until I turn it off.
3. Keep advanced search in elements enabled by default. Option to always enable the advanced icon in global preferences for the element search bar. I always have to click this icon before I start searching for a field.
4. Lock search value when you click a next element. Example: I want to change margin-top of 10 elements. Would be nice to have some sort of lock icon in the search field of elements where the search value is locked / saved no matter what element you click.

**Comment by louisreingold** [comment]
https://breakdance.canny.io/
