### ISSUE TITLE
Responsive placeholders of element fields

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#747]
Responsive placeholders in fields like padding. If you switch from tablet landscape to tablet portrait or phone, I have to get back every time to know which values I have in certain fields on different breakpoints. These inherit field values could be placeholders in the fields of lower breakpoints.

**Comment by louisreingold** [comment]
We did this in Oxygen and I personally hate it. It's not coming to Breakdance.

**Comment by louisreingold** [comment]
The problem with this approach is there are a million instances where the UI would detect a placeholder value and show it but it won't be the actual value the browser computes after reading the CSS. It would result in the UI simply being wrong in many instances.
