### ISSUE TITLE
Hide in builder preview not working in global blocks

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#751]
1.2.1
If set an element to hide in builder preview in a global block and load that global block on a page, the element is not hidden in the builder preview of the page.

**Comment by louisreingold** [comment]
In-builder preview only applies when you are actually editing the block.

Rendering the block while editing a page doesn't count.

This is by design.

When the global block is loaded, the conditions actually run - just as if you are on the frontend of the site.
