### ISSUE TITLE
Add more classes to UI

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#755]
Difficult to hide elements with CSS for certain users or other UI elements because many don't have a class or some unique attribute. It's difficult to hide advanced elements tab for example.

**Comment by louisreingold** [comment]
This is too vague to be actionable. Please request what specifically you want.

**Comment by Bobolinos** [comment]
@louisreingold, you are right, sorry. Here are some screenshots of what I mean. The purpose of this is to target more elements in the UI with CSS. I would use it to hide some fields / sections for clients who can edit their website and where I cannot give them less permissions because they cannot change a background image of a div for example. 

<img src="https://paste.pics/f8c9ca8f5372540335f7073d46007139" />

<img src="https://paste.pics/7cff5e42923ae215ac69df83f92a97ef" />

<img src="https://paste.pics/55503b5aa451fc58c5ef1331e701812a" />
