### ISSUE TITLE
FacetWP Not Working Properly With Products List

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#759]
I've created a template being used in the Woocommerce shop.  The template has a Products List element in it with the FacetWP toggle turned on.  I have added a Facet to the page that is a product category dropdown.  When I change the dropdown, the Facet itself refreshes and the checkboxes go from 2 options down to 1.  However, the Products List element does not change at all.

**What version of Breakdance are you using?**

1.3 Alpha 1

**Comment by RoninReilly** [comment]
@thekendog not worked for me(
