### ISSUE TITLE
Error when adding product to empty section

### ISSUE THREAD

**Issue by antonijo01** [soflyy/breakdance-bugs#77]
I got the error shown below after selecting a product from the list.

![image](https://user-images.githubusercontent.com/107608985/179851157-c459fbd7-97d1-4d7a-b1dd-c1dda7d3fd07.png)

The console on frontend:
![image](https://user-images.githubusercontent.com/107608985/179854777-2f26ee0f-5b3b-4b15-a258-99a1a618dae7.png)

BB version 1.0.0-beta.2
Woocommerce version: 6.7.0
PHP version: 8.1.8
Litespeed server

**Comment by antonijo01** [comment]
I get an error regardless of which woo element I insert into the page.
![image](https://user-images.githubusercontent.com/107608985/180240767-c5643b46-3e9c-4caf-9676-93ed0a8e5537.png)

Check video:
https://www.loom.com/share/b2f13a1fc6f34cd2b841b0284d2b5bd5

**Comment by louisreingold** [comment]
This will be fixed in the next beta.

**Comment by louisreingold** [comment]
Solved in beta 5.
