### ISSUE TITLE
Bug + video: Moving gallery element to different section makes it dissapear

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#772]
BD 1.2.1
If I move the gallery element (when in slider mode in my case) to a different section, the height of it becomes 1px. Can you please fix this bug? If a client moves it it disappears. If I change the settings of the element if appears again.

https://www.loom.com/share/f314b415f14348b9b7e06dfdd760428f

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.4. Thanks for the report.
