### ISSUE TITLE
Gradient slider crash 

### ISSUE THREAD

**Issue by matlitel** [soflyy/breakdance-bugs#773]
Windows 11
Chrome
Breakdance Alpha 1.3

Gradient slider crashes when trying to align 2 slides. It is also difficult and fiddly trying to align 2 sliders at the same point. When this happens only a page refresh resolved the issue. 

It would be better if we had a number box from 0 to 100 for more precise control.

I've attached a video and I'm posting this on a mobile so I'm not sure if you will be able to see it.

Thanks
Mat

**Comment by matlitel** [comment]
https://photos.app.goo.gl/uUXDMAP8dgrr9vmT6

Link to video

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
