### ISSUE TITLE
Cart doesn't accept decimal quantities when updating quantities in cart

### ISSUE THREAD

**Issue by markpinkster** [soflyy/breakdance-bugs#774]
**What version of Breakdance are you using?**
Breakdance 1.3 alpha 1

**What browser are you using?**
N/A

**What operating system are you using?**
N/A

**Reproduction  Steps**
For product I have set they can use decimal quantities with step size 0.1 as my client has products ordered by weight.
By using the following action and filter in functions.php it worked before migration to Breakdance:

```
add_action( 'init', 'mym_float_stock_amount', PHP_INT_MAX );
if ( ! function_exists( 'mym_float_stock_amount' ) ) {
	function wpcb_float_stock_amount() {
		remove_filter( 'woocommerce_stock_amount', 'intval' );
		add_filter(    'woocommerce_stock_amount', 'floatval' );
	}
}
add_filter( 'woocommerce_quantity_input_step', 'mymn_set_quantity_input_step', PHP_INT_MAX, 2 );
if ( ! function_exists( 'mymn_set_quantity_input_step' ) ) {
	function wpcb_set_quantity_input_step( $qty, $product ) {
		return 0.1;
	}
}
```

All is working right but when updating quantities in the cart page the decimal gets stripped out of the value.
So 1.2 becomes 12, 4.7 becomes 47, etc.

When looking into the cart code in subplugins/breakdance-woocommerce/mods/cart.php is see the function ajaxQtyCart().
There the qauantity is sanitized by the line:
`    $newQty = filter_var(filter_input(INPUT_POST, 'quantity'), FILTER_SANITIZE_NUMBER_INT);`

There FILTER_SANITIZE_NUMBER_INT causes the issue. When changing this to FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION it all works as it should.

` $newQty = filter_var(filter_input(INPUT_POST, 'quantity'), FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);`

In my opinion the sanitize part should be updated to listen to the filter on 
`add_filter(    'woocommerce_stock_amount', 'floatval' );`

After this change it's all working well when using default cart page without breakdance editor.
When using the cart builder or cart page the steps value is not respected and the values get rounded. Not stripped from the decimal but just rounded.

**Comment by a-dubiel** [comment]
Hey @markpinkster looks like we added this feature in 1.3 Alpha 1. Feel free to test.
