### ISSUE TITLE
Element Studio not saving

### ISSUE THREAD

**Issue by creator-spec** [soflyy/breakdance-bugs#780]
**What version of Breakdance are you using?**

Tested issue on both latest stable and latest beta. 

**What browser are you using?**
Chrome, latest version

**What operating system are you using?**
Windows 11, latest updates

**Reproduction  Steps**

- Setup blank instance of wordpress
- Upload breakdance plugin
- Activate license
- Create a new page
- Edit with breakdance
- Click on ... (top right menu)
- Element studio
- + new element
- popup to create new element is missing save location so unable to create the element.

**Reproduction Video**
https://www.loom.com/share/fd9c23bcea40499a8d2d44b5ad76de8b

**Comment by obedparla** [comment]
Hmm. I thought we showed a message explaining this. Maybe not in this particular modal

You need to install this plugin and you'll be able to save: https://github.com/soflyy/breakdance-custom-elements

**Comment by louisreingold** [comment]
We recently added a message to direct users to the docs as per the above comment. Thanks for the report.
