### ISSUE TITLE
Builder should show not logged in error if you try to open it when you aren't logged in

### ISSUE THREAD

**Issue by Bonnie-Clyde** [soflyy/breakdance-bugs#783]
When NOT logged in.
After your server url add ?breakdance=builder&id=x where x is your page id. It doesnt go to the login screen, it shows the builder with a AJAX popup window. If your try to edit a page using the default wordpress editor, your shown a login page.

![Screenshot 2023-04-15 at 19-20-15 Breakdance](https://user-images.githubusercontent.com/111174477/232205436-ec6c0a2b-594c-4817-a436-85f77eb636bb.png)

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0. The Design Library modal window is not shown to logged-out users.
