### ISSUE TITLE
ios 13.7 compatability

### ISSUE THREAD

**Issue by thesuss** [soflyy/breakdance-bugs#785]
**What version of Breakdance are you using?**

v1.2.1

**What browser are you using?**

Safari

**What operating system are you using?**

ios

**Reproduction  Steps**
The menu does not work in ios 13.7 
Not the one on gooddog.no and not the one on hundtrick.se 

**Reproduction Video**

https://vimeo.com/819138850/ff36e0faf5

**Comment by louisreingold** [comment]
iOS 13.7 marketshare isn't even displayed on any charts I could find, and they even showed versions with 0.2% of the total iOS market.
