### ISSUE TITLE
Image Hover Card Overlay

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#787]
The overlay setting is showing in the preview correctly but not in front-end.

<img width="910" alt="Screenshot 2023-04-24 at 12 01 27" src="https://user-images.githubusercontent.com/122744933/233978074-3c36a682-c85c-4936-b66f-aa7d246d0ac6.png">
<img width="351" alt="Screenshot 2023-04-24 at 12 01 34" src="https://user-images.githubusercontent.com/122744933/233978087-8837ff59-84e4-4c1d-b556-05fb27a07b11.png">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
