### ISSUE TITLE
License Key Not Working

### ISSUE THREAD

**Issue by misslaidlaw** [soflyy/breakdance-bugs#789]
**What version of Breakdance are you using?** 
1.3.0 - Beta 1

**What browser are you using?**
Chrome

**What operating system are you using?**

Mac

**Reproduction  Steps**

Added my license key and got this error message . Then went onto the Breakdance Website and added my URL directly and it still didn't work, or register my license key. 

![image](https://user-images.githubusercontent.com/7070435/234255057-3900edf1-d6be-4417-ab98-078fddbc1460.png)

![image](https://user-images.githubusercontent.com/7070435/234255550-aab57973-de7e-4df9-82cf-22922c88a660.png)

**Comment by Hakira-Shymuy** [comment]
I confirm, tried to update 2 websites 1 Local 1 Staging on the web from alpha to beta and the same happened to me
deleting and installing does not work, setting the key on phpmyadmin does not work
setting the domain on breakdance website also does not work

**Comment by fabrizim** [comment]
I can confirm this is happening with me as well - breakdance-v1.3.0-beta.1-2.zip

**Comment by a-dubiel** [comment]
https://www.loom.com/share/5be7cfbffeda4b158fc6cecc756592a1

Can you try this? ☝🏼

**Comment by Hakira-Shymuy** [comment]
> https://www.loom.com/share/5be7cfbffeda4b158fc6cecc756592a1
> 
> Can you try this? ☝🏼

@a-dubiel we tried, the problem that some users reported on Louis post on facebook, is that we do not have that button availbale

im wondering if that is because we are using the License from Oxygen free 1 year??

**Comment by a-dubiel** [comment]
Interesting. I will report this internally. Thanks for your patience.

**Comment by fabrizim** [comment]
@a-dubiel - I can confirm that I don't see the button either.

**Comment by a-dubiel** [comment]
Thanks everyone. I just want to confirm that we are working on fixing this. Thanks for your patience. Will update this thread as soon as we release the fix.

**Comment by misslaidlaw** [comment]
Hopefully it will be released quick so we can help test as the block is preventing me from using Breakdance to full capacity.

**Comment by Hakira-Shymuy** [comment]
@a-dubiel any luck to get a fix before a new beta update??

**Comment by a-dubiel** [comment]
Just a quick update. We already have a fix in place and 1.3 RC is coming very soon.

**Comment by Hakira-Shymuy** [comment]
> Just a quick update. We already have a fix in place and 1.3 RC is coming very soon.

@a-dubiel any chance we get a release candidate on the License Issue before day 20?
Have a website scheduled for day 20 and don't want to launch it with alpha version -.-''
