### ISSUE TITLE
Not fixed bug from alpha 1

### ISSUE THREAD

**Issue by slawomiroruba** [soflyy/breakdance-bugs#790]
Version of Breakdance : v1.3 Beta.1
Browser: Chrome
Operating system: Windows

After updating Breakdance to v1.3  Beta 1 I still have an issue with "Fix Twig cache directory for multiple WP installations on a same server". 
![image](https://user-images.githubusercontent.com/54029806/234346990-2cc46084-decf-4b02-b8d3-64c2e48dd682.png)
 
I found for me temporary solution but I think you need fix it somehow.

```php
/**
 * Mapping of bucket IDs to their uploads directory subpaths, or to their absolute paths
 */
$upload_dir = wp_upload_dir();
define("Breakdance\Filesystem\BREAKDANCE_FS_BUCKETS", [
    Consts::BREAKDANCE_FS_BUCKET_CSS => 'css',
    Consts::BREAKDANCE_FS_BUCKET_DESIGN_SETS => 'design_sets',
    Consts::BREAKDANCE_FS_BUCKET_FONT_FAMILIES => 'font_styles',
    Consts::BREAKDANCE_FS_BUCKET_FONTS => 'fonts',
    Consts::BREAKDANCE_FS_BUCKET_TWIG_CACHE => $upload_dir['basedir'] . '/breakdance/twig-auto-generated-cache',
]);
```

**Comment by misslaidlaw** [comment]
Just out of curiosity, how did you update? Did you upload a fresh install or replace the current plugin which was there. I was having this trouble with Alpha 1 but it seems to work for me now wth Beta 1 with a Fresh install.

**Comment by slawomiroruba** [comment]
I had Breakdance version 1.3 alpha 1 installed in the project. I downloaded the package from the official site and uploaded it in the "Plugins" section. In alpha 1 I also had to make a workaround for cache using upload_dir.

**Comment by louisreingold** [comment]
Click the `Create Directories` button.

**Comment by a-dubiel** [comment]
> Click the Create Directories button.

@slawomiroruba did this fix your problem?

**Comment by slawomiroruba** [comment]
> > Click the Create Directories button.
> 
> @slawomiroruba did this fix your problem?

Sorry, I didn't have time to test it. I'll give you know tomorrow.

**Comment by slawomiroruba** [comment]
@a-dubiel I created a new site and uploaded the plugin directly from your official site and it works. During the update I had some problem. It seems to be ok now.
