### ISSUE TITLE
ACF Field not showing on the frontend if page is an Archive

### ISSUE THREAD

**Issue by dancerist** [soflyy/breakdance-bugs#791]
**What version of Breakdance are you using?**

For example: v1.3 beta and alpha

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: Windows

**Reproduction  Steps**

CPT with ACF field, then global block

**Reproduction Video**

here
https://www.loom.com/share/1929b62d1d434eaa8f0b77c77a9c9fbb

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
