### ISSUE TITLE
Specific Styling for Form Step Submit Button

### ISSUE THREAD

**Issue by theperfectwill** [soflyy/breakdance-bugs#792]
**Is your feature request related to a problem? Please describe.**

The step form has no option to edit the Submit button for it. 
The step form renders the Submit button classes and styles from a normal form.
The problem is when styling the next and previous step form buttons, they will not look consistent with the submit button that renders in the last step for the step form. 

Example: I wanted my step form buttons to have a smaller font because there are 2 buttons there, and I don't want those buttons to be as large as a normal form, which only shows the one submit button. So after decreasing the font size for the next and previous step form buttons, I found that final submit button is larger than my next and previous buttons-- but I can't change it with custom css, because then it changes the style for the normal form submit button.-- and I can't change it through the step form settings, because there is no option to style the submit button in the step form.

And there is no unique parent class for the step form, so that I can target the step form submit button only. 

**Describe the solution you'd like**

Ideally, an option to edit the Submit button in Step Form settings, just like the Next and Previous buttons in Step Form have. This I submit to have all those options, like Icon, as well. For my Next and Previous buttons I have added arrow icons, but the Step Form Submit cannot have an icon explicitly. :( 

**Describe alternatives you've considered**

Custom Css to no avail! :)

**Screenshot:**

<img width="600" alt="Palette 1 – Contact Forms – Site_Title-05022023-063433Palette 1 – Contact Forms – Site_Title-05022023-063433" src="https://user-images.githubusercontent.com/6123260/235644654-6daf0808-4a9f-4695-88ee-9c76925ba917.png">

I had to add a Custom Class (which I'd rather not do), which only served for me to write custom css anyway.

**Screenshot:**

<img width="556" alt="Palette 1 – Contact Forms – Site_Title-05022023-064219Palette 1 – Contact Forms – Site_Title-05022023-064219" src="https://user-images.githubusercontent.com/6123260/235645649-8cf21ebf-9f3a-4cb3-ba19-b07b98852d80.png">

**Comment by breakdancemoderator** [comment]
You can go to the Form Builder element > Design > Form > Submit Button > Styles to style the Submit button and set a custom icon in the Design > Form > Submit Button > Styles > Icon.
