### ISSUE TITLE
Menu Builder - Full width no calculating the width correctly, leading to horizontal scrollbar.

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#793]
After testing the 1.3 alpha / beta there is a bug with the full width mega menu. It is not calculating right the viewport width and is making it wider, which leads to horizontal scrollbar. I cannot 

**What version of Breakdance are you using?**
: v1.3

**What browser are you using?**

Brave, Chrome

**What operating system are you using?**

Windows 10

**Reproduction  Steps**

![image](https://user-images.githubusercontent.com/110225636/235969810-b3218627-d695-49f1-9f21-baa5e1c6116c.png)

**Reproduction Video**

https://www.loom.com/share/2d3b8ef4d95c4f70ab48f8dbcf88b0c3

**Comment by a-dubiel** [comment]
Hey @StefanPavlov23 thanks for your report. I cannot reproduce this but this is definitely a bug. Any chance you can share a URL so we can test this on our end? Feel free to e-mail support@breakdance.com or just respond in this thread.

**Comment by louisreingold** [comment]
The only way we've been able to reproduce this (requires Firefox) is:

"Set a Menu Builder element to have full width dropdowns, open the inspector on Firefox, and refresh the page. It happens sometimes doesn't happen."

If anyone has more information or reliable steps to reproduce, we'd appreciate it!

**Comment by louisreingold** [comment]
Is anyone able to reproduce this without opening the inspector in Firefox and then refreshing the page?

**Comment by louisreingold** [comment]
I will re-open this if we receive reproduction steps that don't involve opening the Firefox dev tools.
