### ISSUE TITLE
Padding generated in Post Loop Builder with Slider Style presentation

### ISSUE THREAD

**Issue by vince-pat** [soflyy/breakdance-bugs#796]
Breakdance 1.3 Beta 1

Multiple browsers/OS

A 20px padding is automatically generated in the Slider presentation inside Post Loop Builder.
Check the selector => .breakdance .bde-post-loop .ee-posts

**Comment by louisreingold** [comment]
Is this a bug, and if so, why? Please elaborate.

**Comment by louisreingold** [comment]
Are you simply saying you don't like the default styles? Or am I misunderstanding?
