### ISSUE TITLE
Element Studio: Access fields with dynamic data in JS

### ISSUE THREAD

**Issue by MrBushid0** [soflyy/breakdance-bugs#797]
Breakdance 1.2.1

**Issue:** 

when reading a field that has dynamic data in it in the JS of a custom element ( inline scripts or action handlers ) we only get the shortcode ( ex: [breakdance_dynamic field='acf_image_field_6459378934671'] ) 

Accessing the same field in HTML or CSS works fine.

_Is there a helper function or a way to handle the shortcode in the JS?_ 

**Steps to reproduce:**

1. Add dynamic data to a field 
2. Console log the field content < console.log({{content.content.my_image_field|json_encode()}}) >

Expected results: The field content should be logged

Actual Result: Nothing is logged

The same is true with any field type including image galleries, looping the field in html works, in js there is only the shortcode so it never loops. 

**Work around:** 

Include the data in the dom and grab it via js

**Comment by obedparla** [comment]
We don't support accessing the dynamic data via an element's JS in the builder, but it works as expected in the frontend if you use Dependencies > InlineScripts

<img width="568" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/10674462/3f152208-c5f5-45eb-aaed-ae9257e650d1">

**Comment by MrBushid0** [comment]
Yeah, I saw it works on the frontend but not in the builder.

Got it, Thanks for the confirmation.
