### ISSUE TITLE
Element Studio: Breakpoints do not work for dropdown field

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#798]
V1.3 beta 2
Breakpoints do not work for dropdown field, if I add a dropdown field, it does not show any icon to change the value on a different breakpoint.

**Comment by a-dubiel** [comment]
<img width="581" alt="Screenshot 2023-05-11 at 12 16 59" src="https://github.com/soflyy/breakdance-bugs/assets/669243/89c8151f-c7c8-43bb-9a3f-276f170b0bf8">

Are you using this dropdown?

**Comment by Bobolinos** [comment]
@a-dubiel, thanks for getting back to me. No I use the normal dropdown field, but I want it to be responsive, but it does not work.

<img src="https://i2.paste.pics/NW8X0.png" width="1186" height="1148" alt="Screenshot">

<img src="https://i2.paste.pics/NW8X5.png" width="568" height="518" alt="Screenshot">

**Comment by a-dubiel** [comment]
What are you trying to accomplish?

**Comment by a-dubiel** [comment]
Show your code how you get the value from the dropdown.

**Comment by Bobolinos** [comment]
Ok the "Standaard" label has this value: var(--px-module-distance-default)
I simply want to do something like this:

@media (min-width: 768px) {
%%SELECTOR%% .test {
margin-bottom: var(--px-module-distance-default);
}
}

@media (max-width: 768px) {
%%SELECTOR%% .test {
margin-bottom: var(--px-module-distance-small); // This is the value of de mobile value of the dropdown
}
}

If only the desktop version of the dropdown is set, all breakpoints ouput var(--px-module-distance-default).

Does this answer your question?

**Comment by a-dubiel** [comment]
I assume you want to have different spacing based on the breakpoint? 

You don't to write media queries. Breakdance does it for you. Go like this

- Uncheck "Make this control value available..." 
- Check "Enable media queries" 

default.css
```
.selector {
  --px-module-distance: 30px;
}

.selector .test {
 margin-bottom: var(--px-module-distance);
}
```

css.twig
```
%%SELECTOR%% {
   --px-module-distance: {{ path.to.control }};
}

```
