### ISSUE TITLE
Element Studio: Typography preset field not working

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#799]
v1.3 beta 2
The typography preset field does not do anything, it's a text field and does not load the global presets. I need this field in my custom module to apply a typography preset and not have all the other typography settings.

**Comment by Bobolinos** [comment]
@a-dubiel I'm using this one:
<img src="https://i2.paste.pics/NW8GJ.png" width="1192" height="228" alt="Screenshot">
It does not work. I only want to select a preset and don't want to show all typography settings.

**Comment by a-dubiel** [comment]
>  I only want to select a preset and don't want to show all typography settings.

Element Studio is still in beta. There are things, like this one, that do not work as intended. For now, I suggest using typography presets from `EssentialElements\typography_*`

What you are trying to accomplish is not possible yet but this is a good suggestion. I will pass this internally.

**Comment by Bobolinos** [comment]
Ok great! 
I am trying to accomplish that clients who work with my custom module can only change the typography by selecting presets and not mess up the layout by setting all kinds of custom typography settings. 

This issue is still closed, should it be reopend since it's tagged an enhancement?

**Comment by Bobolinos** [comment]
@a-dubiel, do you think we can reopen this ticket? See my previous comment.
