### ISSUE TITLE
Search button overlapping the classes and selectors section.

### ISSUE THREAD

**Issue by hello-aravinda** [soflyy/breakdance-bugs#8]
Classes and Selectors are not visible and can't be scrolled properly. The search button is overlapping the selectors. 

**To Reproduce**
1.  Open the builder
2. Click on  the three dots (...) beside the SAVE button.
See that the search button is taking around 80% of the height overlapping the selectors. Thus making it impossible to select the classes.

![image](https://user-images.githubusercontent.com/85765711/175245145-d2d1ba66-28bb-48f2-9358-efba8f6d2335.png)

**Comment by louisreingold** [comment]
Fixed in alpha 2: https://breakdance.com/breakdance-alpha-2/
