### ISSUE TITLE
Section padding, Access to the container wrapper, DIV without it wrapped into a section (forced)?

### ISSUE THREAD

**Issue by ImKareem** [soflyy/breakdance-bugs#803]
Breakdance v1.2

**To BD Team,**

- Section padding is applied to the container wrapper inside the section. It should be applied to the section. Is there anything about this coming?
- Access to the container wrapper? Are you willing to add the container element?
- Will be a time that I can add a DIV without it wrapped into a section (forced)?

Regards
Kareem

**Comment by MichalisDBA** [comment]
+1 to have access to section-container

**Comment by louisreingold** [comment]
We have a product for you: https://oxygenbuilder.com/

Will any of this come to Breakdance? Maybe.

> Section padding is applied to the container wrapper inside the section. It should be applied to the section. Is there anything about this coming?

Definitely not planned.

> It should be applied to the section

False.
