### ISSUE TITLE
The animated heading element generates an error when saving the web page

### ISSUE THREAD

**Issue by braeu71** [soflyy/breakdance-bugs#805]
**What version of Breakdance are you using?**
BD 1.3 Beta 2

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows

**Reproduction  Steps**

The animated heading element generates an error when saving the web page. 
Everything works fine so far. But as soon as you enter a duration time and then want to save, the following error occurs:

Internal Server Error
An exception has been thrown during the rendering of a template ("Array to string conversion") in "ec10b002c35cf3dc9b90926cba0bf136ebfdf353" at line 20.

**Reproduction Video**
https://www.loom.com/share/1533ab3008e14161a288b94e604d179e

**Comment by snmme** [comment]
Also wanted to note the type delay doesn't work in both the existing version and beta.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Comment by a-dubiel** [comment]
<img width="292" alt="Screenshot 2023-05-17 at 17 44 20" src="https://github.com/soflyy/breakdance-bugs/assets/669243/1a8fab71-c71d-40c4-b857-b9426b77dff6">

Just tested 1.3 Beta 2 and these options and it works as expected.

**Comment by snmme** [comment]
Thanks for fixing it, thats correct it works in beta 2.
