### ISSUE TITLE
PHP 8.2.x: Call to a member function setTemplate() on null

### ISSUE THREAD

**Issue by forus-tulika** [soflyy/breakdance-bugs#807]
**What version of Breakdance are you using?**

1.2.1 and 1.3.0-beta.2

**What operating system are you using?**

Linux, PHP version 8.2.5

**Reproduction  Steps**

After activating Breakdance plugin, Wordpress doesn't work anymore. In server logs we see:
```
PHP Fatal error:  Uncaught Error: Call to a member function setTemplate() on null in /var/www/html/wp-content/plugins/breakdance/plugin/render/twig.php:204
Stack trace:
#0 /var/www/html/wp-content/plugins/breakdance/plugin/render/renderer.php(338): Breakdance\Render\Twig->runTwig()
#1 [internal function]: Breakdance\Render\{closure}()
#2 /var/www/html/wp-content/plugins/breakdance/plugin/render/renderer.php(315): array_reduce()
#3 /var/www/html/wp-content/plugins/breakdance/plugin/render/cache.php(215): Breakdance\Render\cssForGlobalStyles()
#4 /var/www/html/wp-content/plugins/breakdance/plugin/setup/clean-cache.php(69): Breakdance\Render\generateCacheForGlobalSettings()
#5 /var/www/html/wp-includes/class-wp-hook.php(308): Breakdance\Setup\cleanCacheWhenCacheCountChanges()
#6 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/html/wp-content/plugins/breakdance/plugin.php(39): do_acti
```

Looking at the source code, this is the offending line in `twig.php`:
```php
$this->loader->setTemplate($templateHash, $template);
```

It seems like `$this->loader` is null. Only way to make Wordpress work again is to disable Breakdance plugin via database.

Any ideas what's wrong and how to solve this problem?

**Comment by forus-tulika** [comment]
Same problem also with PHP 8.2.6, but downgrading to 8.1.19 solves this issue for us.

**Comment by a-dubiel** [comment]
Thanks for catching this. I will pass this internally.

**Comment by louisreingold** [comment]
I'm not able to reproduce this with PHP 8.2.x on various testing environments.

WordPress now says PHP 8.2 support is currently in beta.

We'll be taking time now to ensure Breakdance also works with PHP 8.2, with plans to officially support PHP 8.2 shortly after WordPress officially supports PHP 8.2 support.

If you have an environment where this can be reproduced, please email support@breakdance.com with login credentials.
