### ISSUE TITLE
Loop Builder in Slider mode

### ISSUE THREAD

**Issue by claudia-valle** [soflyy/breakdance-bugs#808]
Section containing the Loop Builder has Post > Padding > set to 0 (see image on the left).

When the Loop Builder is in Slider mode, the values in Post > Padding are not handled correctly, creating a hard coded margin.

When the Loop Builder is in Grid (or List) mode, the values in Post > Padding are handled correctly, with no margin.

Check that the Heading in both sections align correctly with no margin. Only the Loop Builder in Slider mode has this issue.

Happens in version 1.3 Beta 3, does not happen in version 1.2.1

See issue in the following page: https://apptimo.com/loop-builder-margins-issue/

![Breakdance - Loop Builder margins issue](https://github.com/soflyy/breakdance-bugs/assets/133992940/3725a365-0f59-4a0e-9348-ae32d372076b)

**Comment by claudia-valle** [comment]
Added the unconfirmed label by mistake.

**Comment by a-dubiel** [comment]
@claudia-valle thanks for your report. I was able to reproduce it and passed this to our internal team. I will update you in this thread once this is fixed.

**Comment by claudia-valle** [comment]
Hi Andrzej, I see it was fixed in version 1.3 Beta 4. One caveat: it does not fix until you edit the page and Save.

Thanks for this fix. We have many sites that use full screen Loop Builder in slider mode.

**Comment by claudia-valle** [comment]
I updated on another site and it did fixed the issue right away, without re-saving the page. Probably a cache issue. Thanks again.

**Comment by a-dubiel** [comment]
Awesome. Thanks for confirming.
