### ISSUE TITLE
One click update not working

### ISSUE THREAD

**Issue by pmk885** [soflyy/breakdance-bugs#81]
**Describe the bug**
Getting the error below when trying to update
Update failed: Download failed. cURL error 18: transfer closed with 4596303 bytes remaining to read

**To Reproduce**

    Go to 'Installed plugins'
    Click on 'update now'
    See error

**Expected behavior**
Plugin should be updated

**Screenshots**
![image](https://user-images.githubusercontent.com/74741763/180168334-cb9b284f-e80d-4f51-9161-aa345565e9e2.png)

**Additional context**
Tried updating from alpha2 and beta1
Happens with live server and LocalWP

**Comment by neeckola** [comment]
What version of WP are you using? This is most likely related to the host/ports and not plugin at all.

**Comment by pmk885** [comment]
I am not the only one, there are few other people who posted about this in beta 3 announcement post in Facebook:

https://www.facebook.com/groups/breakdanceofficial/permalink/5255559271145992/

I'm using latest version of WP. All other plugins update fine. ​

27. heinäk. 2022 klo 6.08, 6.08, neeckola ***@***.***> kirjoitti:

**Comment by andrija-naglic** [comment]
I had the same problem through beta 6-9 but now I've started getting error "-1".
I actually got the same error when I tried to update WooCommerce as well.

**Solution:** My issue has gone away once I've turned off the maintenance mode.

@pmk885 Is your site in maintenance mode as well?

**Comment by pmk885** [comment]
> I had the same problem through beta 6-9 but now I've started getting error "-1". I actually got the same error when I tried to update WooCommerce as well.
> 
> **Solution:** My issue has gone away once I've turned off the maintenance mode.
> 
> @pmk885 Is your site in maintenance mode as well?

None of the sites were in maintenance mode.
