### ISSUE TITLE
PHP 8.1: Broken install / Warning: Cannot modify header information

### ISSUE THREAD

**Issue by tc-tmmlt** [soflyy/breakdance-bugs#812]
I'm bumping into some issues with Breakdance on a brand new WP installation that I can't fix.  

Environment is road-tested on a dozen sites: dockerized WP + MariaDB + Redis
- Ubuntu 20.04 /  wordpress:6.2-php8.1-apache / mariadb:10.11.2-jammy / Redis 7.0.11
- Breakdance 1.2
- No other plug-ins except Redis Object Cache
- 8GB RAM, 4 cores, PHP = 256M of memory

Problem: Breakdance installation throws a ton of errors and won't let me add pages following along in "Get Started" video -- times out on "Add"

Steps to reproduce:
Step 1:  Install free version of BreakDance plugin on entirely new site.  Activate and...

```
The plugin generated 734 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Deprecated: Return type of Breakdance\Data\RecursiveTreeNodeIterator::hasChildren() should either be compatible with RecursiveArrayIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/wp-content/plugins/breakdance/plugin/data/recursive-tree-node-iterator.php on line 7
Deprecated: Return type of Breakdance\Data\RecursiveTreeNodeIterator::getChildren() should either be compatible with RecursiveArrayIterator::getChildren(): ?RecursiveArrayIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/wp-content/plugins/breakdance/plugin/data/recursive-tree-node-iterator.php on line 15
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/html/wp-content/plugins/breakdance/plugin/design-library/rest.php on line 193
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/wp-includes/functions.php on line 7053
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/wp-includes/functions.php on line 2165
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/breakdance/plugin/data/recursive-tree-node-iterator.php:0) in /var/www/html/wp-admin/includes/misc.php on line 1431
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/breakdance/plugin/data/recursive-tree-node-iterator.php:0) in /var/www/html/wp-includes/functions.php on line 6896
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/breakdance/plugin/data/recursive-tree-node-iterator.php:0) in /var/www/html/wp-admin/admin-header.php on line 9
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/html/wp-content/plugins/breakdance/plugin/subscription/wp-admin-warnings.php on line 41
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/html/wp-content/plugins/breakdance/plugin/subscription/wp-admin-warnings.php on line 47`
```

**Comment by tc-tmmlt** [comment]
I tried installing the "Breakdance Zero Theme" just to see if that cleared anything out (It had previously been using whatever theme WP 6.2 uses these days -- didn't look, but likely 2023.  Zero posts / Zero pages - fresh install).   That zero theme didn't stop the errors.  Tried reboots / de-activating / re-activating.

**Comment by a-dubiel** [comment]
What version of PHP are you using?

**Comment by tc-tmmlt** [comment]
8.1 (it is in the docker package name above — one of the official packages). 

Nothing but bog standard setup here. No other plugins besides ROC.  We have same dockerized environment running GeneratePress on one server, Elementor on another, and Sensei LMS / woo commerce on a third, so it has been robust under different setups.  Happy to help test.

**Comment by a-dubiel** [comment]
Thanks @tc-tmmlt 🙏🏼  I will pass this to our team and will get back to you in this thread.

**Comment by louisreingold** [comment]
I was not able to reproduce this with Breakdance 1.5 on various environments running PHP 8.1 & PHP 8.2. 

Does this still happen for you with Breakdance 1.5? If so, please email support@breakdance.com so we can login and take a look.

**Comment by tc60045** [comment]
Feel free to close this, as I moved on so long ago that I can scarce recall the blocking issue
