### ISSUE TITLE
Can't upload images with the new version of metabox (v5.7.1)

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#813]
**What version of Breakdance are you using?**

v1.3b4

**Reproduction  Steps**

- install breakdance
- install metabox v5.7.1
- edit a page in BD and add an image
- error is returned

I'm not sure if this is a BD or an MB issue. Downgrading to MB 5.6.18 overcomes the issue for now.

**Reproduction Video**

https://recordings.webxdesign.studio/recordings/wl6UOauxdjWPisQrr4am

**debug info**

{"type":"INTERNAL_SERVER_ERROR","errorDetails":{"type":"Breakdance\\AJAX\\BreakdanceAjaxHandlerException","message":"Attempt to read property \"id\" on null","code":500,"file":"/home/sowcroft/public_html/wp-content/plugins/breakdance/plugin/ajax/api.php","line":113,"trace":[{"file":"/home/sowcroft/public_html/wp-content/plugins/breakdance/plugin/ajax/api.php","line":113,"function":null,"class":"Breakdance\\AJAX\\BreakdanceAjaxHandlerException","args":["Attempt to read property \"id\" on null"],"snippet":{"108":"            try {\n","109":"                /** @var mixed $return_value */\n","110":"                /** @psalm-suppress MixedAssignment */\n","111":"                $return_value = call_user_func_array($callback, array_values($callback_args));\n","112":"            } catch (Exception $callback_exec_exception) {\n","113":"                throw new BreakdanceAjaxHandlerException($callback_exec_exception->getMessage(), 500, $callback_exec_exception);\n","114":"            }\n","115":"\n","116":"            if (is_array($return_value) && array_key_exists('error', $return_value)) {\n","117":"                throw new BreakdanceAjaxHandlerException((string) $return_value['error'], 500);\n"},"startingLine":108},{"file":"/home/sowcroft/public_html/wp-content/plugins/meta-box/inc/media-modal.php","line":102,"function":null,"class":"Breakdance\\Lib\\Vendor\\Whoops\\Exception\\ErrorException","args":["Attempt to read property \"id\" on null"],"snippet":{"97":"\tprivate function is_in_modal( array $meta_box ): bool {\n","98":"\t\treturn in_array( 'attachment', $meta_box['post_types'], true ) && ! empty( $meta_box['media_modal'] );\n","99":"\t}\n","100":"\n","101":"\tprivate function is_attachment_edit_screen(): bool {\n","102":"\t\treturn get_current_screen()->id === 'attachment';\n","103":"\t}\n","104":"}\n"},"startingLine":97},{"file":"/home/sowcroft/public_html/wp-content/plugins/meta-box/inc/media-modal.php","line":102,"function":"handleError","class":"Breakdance\\Lib\\Vendor\\Whoops\\Run","args":[],"snippet":{"97":"\tprivate function is_in_modal( array $meta_box ): bool {\n","98":"\t\treturn in_array( 'attachment', $meta_box['post_types'], true ) && ! empty( $meta_box['media_modal'] );\n","99":"\t}\n","100":"\n","101":"\tprivate function is_attachment_edit_screen(): bool {\n","102":"\t\treturn get_current_screen()->id === 'attachment';\n","103":"\t}\n","104":"}\n"},"startingLine":97},{"file":"/home/sowcroft/public_html/wp-content/plugins/meta-box/inc/media-modal.php","line":39,"function":"is_attachment_edit_screen","class":"RWMB_Media_Modal","args":[],"snippet":{"34":"\t * @param WP_Post $post The WP_Post attachment object.\n","35":"\t *\n","36":"\t * @return mixed\n","37":"\t */\n","38":"\tpublic function add_fields( $form_fields, WP_Post $post ) {\n","39":"\t\tif ( $this->is_attachment_edit_screen() ) {\n","40":"\t\t\treturn $form_fields;\n","41":"\t\t}\n","42":"\n","43":"\t\tforeach ( $this->fields as $field ) {\n"},"startingLine":34},{"file":"/home/sowcroft/public_html/wp-includes/class-wp-hook.php","line":308,"function":"add_fields","class":"RWMB_Media_Modal","args":[],"snippet":{"303":"\n","304":"\t\t\t\t// Avoid the array_slice() if possible.\n","305":"\t\t\t\tif ( 0 == $the_['accepted_args'] ) {\n","306":"\t\t\t\t\t$value = call_user_func( $the_['function'] );\n","307":"\t\t\t\t} elseif ( $the_['accepted_args'] >= $num_args ) {\n","308":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], $args );\n","309":"\t\t\t\t} else {\n","310":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], array_slice( $args, 0, (int) $the_['accepted_args'] ) );\n","311":"\t\t\t\t}\n","312":"\t\t\t}\n"},"startingLine":303},{"file":"/home/sowcroft/public_html/wp-includes/plugin.php","line":205,"function":"apply_filters","class":"WP_Hook","args":[],"snippet":{"200":"\t}\n","201":"\n","202":"\t// Pass the value to WP_Hook.\n","203":"\tarray_unshift( $args, $value );\n","204":"\n","205":"\t$filtered = $wp_filter[ $hook_name ]->apply_filters( $value, $args );\n","206":"\n","207":"\tarray_pop( $wp_current_filter );\n","208":"\n","209":"\treturn $filtered;\n"},"startingLine":200},{"file":"/home/sowcroft/public_html/wp-admin/includes/media.php","line":1925,"function":"apply_filters","class":null,"args":[],"snippet":{"1920":"\t * foreach ( (array) $things as $thing )\n","1921":"\t */\n","1922":"\t$form_fields = array_merge_recursive( $form_fields, (array) $args['errors'] );\n","1923":"\n","1924":"\t/** This filter is documented in wp-admin/includes/media.php */\n","1925":"\t$form_fields = apply_filters( 'attachment_fields_to_edit', $form_fields, $post );\n","1926":"\n","1927":"\tunset(\n","1928":"\t\t$form_fields['image-size'],\n","1929":"\t\t$form_fields['align'],\n"},"startingLine":1920},{"file":"/home/sowcroft/public_html/wp-includes/media.php","line":4334,"function":"get_compat_media_markup","class":null,"args":[],"snippet":{"4329":"\t\t\t$response['thumb'] = compact( 'src', 'width', 'height' );\n","4330":"\t\t}\n","4331":"\t}\n","4332":"\n","4333":"\tif ( function_exists( 'get_compat_media_markup' ) ) {\n","4334":"\t\t$response['compat'] = get_compat_media_markup( $attachment->ID, array( 'in_modal' => true ) );\n","4335":"\t}\n","4336":"\n","4337":"\tif ( function_exists( 'get_media_states' ) ) {\n","4338":"\t\t$media_states = get_media_states( $attachment );\n"},"startingLine":4329},{"file":"/home/sowcroft/public_html/wp-content/plugins/breakdance/plugin/media/metadata.php","line":34,"function":"wp_prepare_attachment_for_js","class":null,"args":[],"snippet":{"29":" * @param int $id\n","30":" * @return array|null\n","31":" */\n","32":"function prepareMedia($id)\n","33":"{\n","34":"    $attachment = wp_prepare_attachment_for_js($id);\n","35":"    if (!$attachment) return null;\n","36":"\n","37":"    $fieldsToKeep = ['id', 'filename', 'alt', 'caption', 'url', 'type', 'mime', 'sizes'];\n","38":"\n"},"startingLine":29},{"file":"[internal]","line":0,"function":"Breakdance\\Media\\Metadata\\prepareMedia","class":null,"args":[],"snippet":false,"startingLine":1},{"file":"/home/sowcroft/public_html/wp-content/plugins/breakdance/plugin/media/metadata.php","line":62,"function":"array_map","class":null,"args":[],"snippet":{"57":" * @param int[] $ids\n","58":" * @return array{data: array}\n","59":" */\n","60":"function endpoint($ids)\n","61":"{\n","62":"    $metadata = array_map('Breakdance\\Media\\Metadata\\prepareMedia', $ids);\n","63":"\n","64":"    return ['data' => $metadata];\n","65":"}\n"},"startingLine":57},{"file":"/home/sowcroft/public_html/wp-content/plugins/breakdance/plugin/ajax/api.php","line":111,"function":"Breakdance\\Media\\Metadata\\endpoint","class":null,"args":[],"snippet":{"106":"            }\n","107":"\n","108":"            try {\n","109":"                /** @var mixed $return_value */\n","110":"                /** @psalm-suppress MixedAssignment */\n","111":"                $return_value = call_user_func_array($callback, array_values($callback_args));\n","112":"            } catch (Exception $callback_exec_exception) {\n","113":"                throw new BreakdanceAjaxHandlerException($callback_exec_exception->getMessage(), 500, $callback_exec_exception);\n","114":"            }\n","115":"\n"},"startingLine":106},{"file":"/home/sowcroft/public_html/wp-content/plugins/breakdance/plugin/ajax/api.php","line":111,"function":"call_user_func_array","class":null,"args":[],"snippet":{"106":"            }\n","107":"\n","108":"            try {\n","109":"                /** @var mixed $return_value */\n","110":"                /** @psalm-suppress MixedAssignment */\n","111":"                $return_value = call_user_func_array($callback, array_values($callback_args));\n","112":"            } catch (Exception $callback_exec_exception) {\n","113":"                throw new BreakdanceAjaxHandlerException($callback_exec_exception->getMessage(), 500, $callback_exec_exception);\n","114":"            }\n","115":"\n"},"startingLine":106},{"file":"/home/sowcroft/public_html/wp-includes/class-wp-hook.php","line":308,"function":"Breakdance\\AJAX\\{closure}","class":null,"args":[],"snippet":{"303":"\n","304":"\t\t\t\t// Avoid the array_slice() if possible.\n","305":"\t\t\t\tif ( 0 == $the_['accepted_args'] ) {\n","306":"\t\t\t\t\t$value = call_user_func( $the_['function'] );\n","307":"\t\t\t\t} elseif ( $the_['accepted_args'] >= $num_args ) {\n","308":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], $args );\n","309":"\t\t\t\t} else {\n","310":"\t\t\t\t\t$value = call_user_func_array( $the_['function'], array_slice( $args, 0, (int) $the_['accepted_args'] ) );\n","311":"\t\t\t\t}\n","312":"\t\t\t}\n"},"startingLine":303},{"file":"/home/sowcroft/public_html/wp-includes/class-wp-hook.php","line":332,"function":"apply_filters","class":"WP_Hook","args":[],"snippet":{"327":"\t *\n","328":"\t * @param array $args Parameters to pass to the callback functions.\n","329":"\t */\n","330":"\tpublic function do_action( $args ) {\n","331":"\t\t$this->doing_action = true;\n","332":"\t\t$this->apply_filters( '', $args );\n","333":"\n","334":"\t\t// If there are recursive calls to the current action, we haven't finished it until we get to the last one.\n","335":"\t\tif ( ! $this->nesting_level ) {\n","336":"\t\t\t$this->doing_action = false;\n"},"startingLine":327},{"file":"/home/sowcroft/public_html/wp-includes/plugin.php","line":517,"function":"do_action","class":"WP_Hook","args":[],"snippet":{"512":"\t} elseif ( is_array( $arg[0] ) && 1 === count( $arg[0] ) && isset( $arg[0][0] ) && is_object( $arg[0][0] ) ) {\n","513":"\t\t// Backward compatibility for PHP4-style passing of `array( &$this )` as action `$arg`.\n","514":"\t\t$arg[0] = $arg[0][0];\n","515":"\t}\n","516":"\n","517":"\t$wp_filter[ $hook_name ]->do_action( $arg );\n","518":"\n","519":"\tarray_pop( $wp_current_filter );\n","520":"}\n","521":"\n"},"startingLine":512},{"file":"/home/sowcroft/public_html/wp-admin/admin-ajax.php","line":188,"function":"do_action","class":null,"args":[],"snippet":{"183":"\t * The dynamic portion of the hook name, `$action`, refers\n","184":"\t * to the name of the Ajax action callback being fired.\n","185":"\t *\n","186":"\t * @since 2.1.0\n","187":"\t */\n","188":"\tdo_action( \"wp_ajax_{$action}\" );\n","189":"} else {\n","190":"\t// If no action is registered, return a Bad Request response.\n","191":"\tif ( ! has_action( \"wp_ajax_nopriv_{$action}\" ) ) {\n","192":"\t\twp_die( '0', 400 );\n"},"startingLine":183}]},"requestDetails":{"friendlyName":"Get image metadata","responseCode":"500","requestUrl":"https://thesowcroftcentre.org/wp-admin/admin-ajax.php?_ajax_nonce=9cc7e38023","requestMethod":"POST","body":{"action":"breakdance_image_metadata","ids":[19]}}}

**Comment by a-dubiel** [comment]
Stellar job on the report @lockedm thank you. I will pass this to our internal team and will update you on this soon.

**Comment by slawomiroruba** [comment]
I am very much asking you to solve this bug as soon as possible. We use Metabox in almost every project and I mega want to solve this problem quickly.

**Comment by a-dubiel** [comment]
For the time being please downgrade the Metabox.

**Comment by slawomiroruba** [comment]
Ok, thanks for the information. What version of metabox do you recommend ?

**Comment by lockedm** [comment]
Yes, the latest versions of Metabox are working OK now. This can be closed. 
      
        
        
          On Jul 10 2023, at 8:36 am, Louis Reingold ***@***.***> wrote:
          
        
        
          
Has Metabox addressed this yet?

**Comment by louisreingold** [comment]
❤️
