### ISSUE TITLE
Validation of the completion of checkbox fields.

### ISSUE THREAD

**Issue by slawomiroruba** [soflyy/breakdance-bugs#814]
If we have, for example, a simple newsletter signup form that only consists of 2 fields: email and a checkbox for data processing consent, and we want to mark the marketing consent as "required", if the box is not checked, the message displays "is required.".

Errors to be fixed:

"is required." is not possible to change. First of all, it would be good to put this in a __('is required.', 'breakdance') to allow for translations, and secondly, to be able to write our own text.
The name of the field is only taken from the "label" and if I use a "placeholder" as in the example below, the "label" does not exist. Please add a condition that if the "label" does not exist, then it should take the "name".

![image (8)](https://github.com/soflyy/breakdance-bugs/assets/54029806/c5bbe9ad-d3c6-4c47-996b-e883f74e7142)

**Comment by a-dubiel** [comment]
> "is required." is not possible to change. 

This defaults to user/browser locale language. We are using  [client-side validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation) so all messaging comes from the browser.

> as in the example below, the "label" does not exist. 

You can hide labels using advanced settings and use placeholders instead.

<img width="871" alt="Screenshot 2023-05-26 at 15 40 30" src="https://github.com/soflyy/breakdance-bugs/assets/669243/ac5e74d2-87a4-4c5d-8f11-7a3b37be8161">

**Comment by louisreingold** [comment]
We're open to addressing this but only if the above solution isn't appropriate. If it isn't, please open a new issue with details.
