### ISSUE TITLE
SVG without width and height attribute

### ISSUE THREAD

**Issue by krissborowy** [soflyy/breakdance-bugs#816]
Hello, I found a bug when adding an image block. when selecting SVG in code the width and height attribute is empty.

Breakdance version: 1.3 RC1

Browser: Chrome/Safari
System: macOS

I have activated SVG support in the latest version.

I add an image block and from the media I select the SVG logo.!

In the code, the width and height attribute is empty.

[image](https://github.com/soflyy/breakdance-bugs/assets/81860559/90d9c1fd-9840-431b-b43c-44ebfee852b9)

I checked the options on several installations. I thought when I set the values ​​in the settings it would populate the attributes. However, they only give a new class. 

Regerds 
Kriss

**Comment by a-dubiel** [comment]
@krissborowy what is the bug exactly? Does the SVG not display correctly?

**Comment by krissborowy** [comment]
The svg image/graphic is displayed normally, but its parameters (width and height) are not specified (empty).

It's not a problem with the SVG file, because I downloaded the breakdance logo from your site and uploaded it to the media library and the parameters are not completed either. But on your site it works fine.

![image](https://github.com/soflyy/breakdance-bugs/assets/81860559/b2e09a4a-93eb-4e27-b6b7-dcc3ab587f95)

**Comment by a-dubiel** [comment]
> But on your site it works fine.

We set image height using Image settings. 

> But its parameters (width and height) are not specified (empty).

We just launched supporting SVG uploads and we are working on improving SVG sizing. Having empty attriburtes in SVG image is not a cirtical bug. If you need to set specific image height/width just use image design settings. For now, we make all SVGs to be 100% width by default. If you really really want to see these attributes feel free to disable SVG uploads in Breakdance and use a plugin like Safe SVG. 

> The svg image/graphic is displayed normally

Looks like there is no bug so unless there is something broken I am closing this.
