### ISSUE TITLE
Animated gifs not playing

### ISSUE THREAD

**Issue by DevineJasper** [soflyy/breakdance-bugs#820]
**What version of Breakdance are you using?**

For example: v1.3

**What browser are you using?**

Chrome & Safari

**What operating system are you using?**

macOS

**Reproduction  Steps**

I add an animated .gif file in an image element and set the Image Size to 'Full'.
Expected behaviour: gif automatically plays.
However, I didn't find a way yet to make it work.

**Reproduction Video**

https://github.com/soflyy/breakdance-bugs/assets/44393498/9459ec1e-e108-4d5d-986f-76c9b56a2f9f

**Comment by louisreingold** [comment]
Unable to reproduce. I tested with multiple GIFs and they work fine.
