### ISSUE TITLE
Product image hover/zoom shows original image and zoomed image if transparent product images are used

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#821]
**What version of Breakdance are you using?**

1.3

**Reproduction  Steps**

- create a single product template
- add product images
- add a product which has transparent background images

When the product image is hovered, the image is zoomed, but the original image is on display as well. A background color needs to be added to the zoomed image to hide the background image. I'm using this code as a workaround:

%%SELECTOR%% img.zoomImg {
    background: var(--bde-background-color);
}

**Reproduction Video**

https://recordings.webxdesign.studio/recordings/kjZE9ZQeEFFfOAjZLZ5y

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
