### ISSUE TITLE
Text presets do not work in the product list

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#822]
**What version of Breakdance are you using?**

1.3

**Reproduction  Steps**

- create a global text preset
- have a shop page with a products list
- try to apply the text preset to one of the elements such as the title

Preset does not work. If you switch back from preset to custom, the font-size from the present is copied in to the custom field.

**Reproduction Video**

https://recordings.webxdesign.studio/recordings/Pr7N7wf23iOszAzCKaa4

**Comment by louisreingold** [comment]
This is addressed in 1.5 Beta 1. Thanks for the report.
