### ISSUE TITLE
Simple Counter letter spacing not inheriting input value

### ISSUE THREAD

**Issue by kjb777** [soflyy/breakdance-bugs#823]
Hi there, I've run into a bug when using the Simple Counter element. It appears that the letter-spacing input doesn't inherit the input value. Someone on the FB group has confirmed it's a bug and posted a workaround involving forcing the selector to inherit the change via CSS.

I'm using BD v1.3, Chrome browser and Windows 11.

Steps to reproduce the problem is simple, just try adjusting the letter spacing for the "number" part of the counter. Here's a screenshot:

![image](https://github.com/soflyy/breakdance-bugs/assets/135413673/7f7091d4-9aa6-4e5e-9a8e-baabe26ea978)

**Comment by louisreingold** [comment]
Thanks for the report. This is addressed in Breakdance 1.7.
