### ISSUE TITLE
Border settings not visible on UI for a Column

### ISSUE THREAD

**Issue by kjb777** [soflyy/breakdance-bugs#825]
**What version of Breakdance are you using?**

v1.2

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

Windows 11

**Reproduction  Steps:**

1. Select a Column element.
2. Go to Borders setting.
3. Change border style, any width, any color, any side.
4. Save changes.
5. Close builder UI.
6. Reopen builder UI.
7. Go to border settings and inspect changes and you will find that they don't show on the UI, but the styling is still being applied to the element in preview mode and frontend.

**Comment by louisreingold** [comment]
I'm not able to reproduce this using the provided steps. 

After setting border and re-opening UI:
<img width="1016" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/6425257/b1022f5c-1ed4-4232-9e84-6be15b2b6542">

Individual side:
<img width="1006" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/6425257/b89b40d4-2b0b-429d-bd0e-5d39a8633067">

**Comment by kjb777** [comment]
Thanks Louis. I'll have a look at that using the latest version. If I come across the problem again I'll try screen recording it.
