### ISSUE TITLE
Html Img element seriously lacking

### ISSUE THREAD

**Issue by stavo34** [soflyy/breakdance-bugs#828]
The html Img Component should allow for selection of image through media library, it should pull in wp src set, it should allow media image size to be set, it should have a dynamic option. This would make it useful.

**Comment by a-dubiel** [comment]
Use Image element instead.

**Comment by stavo34** [comment]
I am unsure what purpose the HTML Img Element can perform without these options. AND Image element has very large number of html elements so it's a very poor choice for custom development - see below:

<div class="bde-image-7-344 bde-image">
<figure class="breakdance-image breakdance-image--">
	<div class="breakdance-image-container">
		<div class="breakdance-image-clip">
      <img class="breakdance-image-object" src="data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' width='540' height='540' viewBox='0 0 140 140'%3e%3cpath d='M0 0h140v140H0z' fill='%23e5e7eb'/%3e%3cpath d='M88 82.46H51.8v-4.52l6.74-6.74a1.13 1.13 0 011.6 0l5.23 5.23 12.76-12.77a1.13 1.13 0 011.6 0L88 71.91z' fill='%23e5e7eb'/%3e%3cpath d='M89.48 52.32H50.29a4.52 4.52 0 00-4.52 4.52V84a4.53 4.53 0 004.52 4.52h39.19A4.52 4.52 0 0094 84V56.84a4.52 4.52 0 00-4.52-4.52zm-33.16 5.27a5.28 5.28 0 11-5.27 5.28 5.27 5.27 0 015.27-5.28zM88 82.46H51.8v-4.52l6.74-6.74a1.13 1.13 0 011.6 0l5.23 5.23 12.76-12.77a1.13 1.13 0 011.6 0L88 71.91z' fill='%23d1d5db'/%3e%3c/svg%3e" width="540" height="540">
</div>
	</div>
	</figure>
</div>
