### ISSUE TITLE
Star Ratings inaccurate on the front end

### ISSUE THREAD

**Issue by joethseo** [soflyy/breakdance-bugs#83]
Star ratings work fine on the back end but not on the front end. See here:

https://www.loom.com/share/51e8098b938d41ffaebd507307491807

**Comment by louisreingold** [comment]
Unable to reproduce: https://www.loom.com/share/7fd57339ab004b0b834f72134e2c22b6

Please submit a support ticket and we'll take a look: support@breakdance.com.

**Comment by louisreingold** [comment]
We tried to solve this in beta 5 but people are still encountering problems with it.

**Comment by louisreingold** [comment]
Turns out this was a caching issue.

**Comment by louisreingold** [comment]
If anyone is reading and I'm wrong and it isn't a caching issue, please open in a new issue.
