### ISSUE TITLE
Mobile Menu (Menu Builder) did not work on Desktop

### ISSUE THREAD

**Issue by braeu71** [soflyy/breakdance-bugs#833]
In the beta, the mobile view of the menu builder no longer works for me? More precisely, it only does not work if I want to display the mobile menu in the desktop view as well.

**What version of Breakdance are you using?**

1.4 Beta 1

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

Windows

**Reproduction Video**

https://watch.screencastify.com/v/HvclbWCB77GzlGneBPbM

**Comment by Nicscott01** [comment]
I'm also having the exact same issue. Sorry I opened another item.

What version of Breakdance are you using?
1.4.0-beta.1

What browser are you using?
Safari Version 15.6.1 (17613.3.9.1.16)
Chrome Version 114.0.5735.106 (Official Build) (arm64)

What operating system are you using?
macOS 12.6.2

Reproduction Steps
Create a Breakdance Header, then create a Header Builder. Put a Breakdance Menu Builder in there. In the design panel, go to "Mobile Menu" and choose "Show At > Desktop." It spaces out all weird and doesn't show the hamburger. Works if you show at other breakpoints.

This just broke...it works in 1.3.0.

**Comment by krissborowy** [comment]
I'm having the same problem. after installing version 1.4 Beta 1.
