### ISSUE TITLE
Image Gallery Not Working

### ISSUE THREAD

**Issue by NaoufelTarchoul** [soflyy/breakdance-bugs#834]
The image Gallery is not working. The Slider is totally responsive. 

**What version of Breakdance are you using?**
1.4.0-beta.1

**What browser are you using?**

Chrome, Safari, and others

**What operating system are you using?**

macOS, Android

**Reproduction  Steps**

Just use the image gallery for a WooCommerce product. Try to use the slider.

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.4. Thanks for the report.

**Comment by lordloadalot** [comment]
thank you !!
