### ISSUE TITLE
Menu Builder "Show Mobile on Desktop" Breaks in 1.4.0-beta.1

### ISSUE THREAD

**Issue by Nicscott01** [soflyy/breakdance-bugs#835]
**What version of Breakdance are you using?**
1.4.0-beta.1 

**What browser are you using?**
Safari Version 15.6.1 (17613.3.9.1.16)
Chrome Version 114.0.5735.106 (Official Build) (arm64)

**What operating system are you using?**
macOS 12.6.2

**Reproduction  Steps**
Create a Breakdance Header, then create a Header Builder. Put a Breakdance Menu Builder in there. In the design panel, go to "Mobile Menu" and choose "Show At > Desktop." It spaces out all weird and doesn't show the hamburger. Works if you show at other breakpoints.

This just broke...it works in 1.3.0.

**Comment by Nicscott01** [comment]
Same as https://github.com/soflyy/breakdance-bugs/issues/833

**Comment by krissborowy** [comment]
Hi

I'm having the same problem. after installing version 1.4 Beta 1.

Thanks in advance for solving the problem

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.4. Thanks for the report.
