### ISSUE TITLE
Post list taxonomies query doesn't work, if infinity scroll / load more -button is being used

### ISSUE THREAD

**Issue by tommicappel** [soflyy/breakdance-bugs#837]
BD version 1.3.1
Chrome / Vivaldi
Windows 11

Workflow:

Add a Post list element on a normal page
Add Custom Query "Post type" --> "Posts" --> "Has Taxonomy" --> "Is one/all of" --> "choosen category" --> "Apply query"
Choose "Infinity scroll" or "Load more button" from the pagination selection

The result is, that the chosen categorys posts show on the list first and posts from all the other categories follow after that.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.4. Thank you for helping us improve Breakdance.
