### ISSUE TITLE
Breakdance 1.4 Beta 1 - Popup Issue / Concern with Caching Plugins

### ISSUE THREAD

**Issue by theperfectwill** [soflyy/breakdance-bugs#838]
**Is your feature request related to a problem? Please describe.**

The problem is that some caching plugins need to exclude the script from being compiled and cached, but the `<script id=` is only a `md5($)`. 

**Describe the solution you'd like**

I request that a standard prefix be applied to the script id, such as `<script id="bde-popup-"`. 

So to confirm, the output would then be...

```html
<script id="bde-popup-94cfaa8b58e2fe0158fad764d0e9fc92"></script>
```

So then a frag of the script id, like `*bde-popup*`, can be entered into a cache plugin, so that it will skip caching any script with that frag in the script id.

I confirmed this works in local testing without any issues...

<img width="260" alt="Site_Title - Site_Description-06102023-055335Site_Title - Site_Description-06102023-055335" src="https://github.com/soflyy/breakdance-bugs/assets/6123260/b031acaf-1937-4cab-8af3-98a5ffe9e244">

**Describe alternatives you've considered**
None are available.

In `wp-content/plugins/breakdance/plugin/themeless/popups.php`

I changed: `<script id="' . md5($inlineScript) . '">`

To: `<script id="bde-popup-' . md5($inlineScript) . '">`

**Additional context**

Canny Feature Request: https://breakdance.canny.io/features/p/breakdance-14-beta-1-detectable-script-id-missing-for-caching-plugins

**Comment by a-dubiel** [comment]
Currently we are not planning on integrating any caching plugin integrations. We are doing our best to optimise Breakdance out of the box so you don't need to use any third party plugins for additional optimisation. The fastest way to resolve this would be reaching out to plugin developer to integrate Breakdance.
