### ISSUE TITLE
Images on rich editor disappears

### ISSUE THREAD

**Issue by joohub** [soflyy/breakdance-bugs#840]
Hi,
the rich editor is buggy and loosing images if i add them on html and switching back to visual.
Also there should be an option to add images on visual. 

1.4.0 beta

best regards

**Comment by a-dubiel** [comment]
Hey @joohub thanks for the report. Images will be supported soon. I would say 1.5.

**Comment by louisreingold** [comment]
After further review, this is under consideration but not necessarily planned.

**Comment by louisreingold** [comment]
I wonder if we should just swap out the rich text editor for TinyMCE (WordPress Classic Editor)

I always thought TinyMCE was kind of a piece of trash but the reality is that it's battle-tested and proven and supports every use case everyone asked for.

**Comment by joohub** [comment]
Yes, probaply the right way. But please make the tinymce editor layout a little more beautiful ^^
b regards

**Comment by louisreingold** [comment]
Tracking at https://breakdance.canny.io/admin/feedback/element-requests/p/full-rich-text-wysiwyg-element-like-tinymce?boards=element-requests&sort=top
