### ISSUE TITLE
Validation Error: IO-TS decoding failed

### ISSUE THREAD

**Issue by salasmx** [soflyy/breakdance-bugs#842]
This has been happening quite a lot when creating new elements.

[Here is a loom video](https://www.loom.com/share/cfb99a44a9254c75aa694b5136530189)

**Comment by louisreingold** [comment]
> it seems it only happens when custom elements + GitHub are synced.

I suspect it's a real bug and is not related to GitHub. If it happens again please open a new issue send us the element in question.

Closing as there is no reproduction here.
