### ISSUE TITLE
Vertical Menu - switch from horizontal to vertical on mobile

### ISSUE THREAD

**Issue by joohub** [soflyy/breakdance-bugs#843]
Hi,
i just have the problem, that i want to create a submenu below the header hero image. So this nav menu is horizontal on desktop, but on mobile small resolution it should be vertical. At the moment i need to create 2 menu and hide one on desktop and make the vertical visible on smartphone 320px...

Please add a switch

best regards

**Comment by louisreingold** [comment]
If you don't want to use the built-in mobile menu toggle that opens a vertical collapsible menu, but instead want to use the desktop-style vertical menu functionality on a mobile device, two menus is the correct solution.
