### ISSUE TITLE
Respect excerpt_more filter instead of hard-coding ...

### ISSUE THREAD

**Issue by aadlung** [soflyy/breakdance-bugs#848]
**What version of Breakdance are you using?**
v1.2

When using exerpts, usually the filter `excerpt_more` can be used to add the "three dots" or other signs.

In the file `subplugins/breakdance-elements/elements/PostsList/ssr.php` in line 191, it's using e fixed string of "[...]" in combination with an excerpt length.
`echo wp_trim_words($content, $excerptLength, ' [...]');`

I would suggest to keep it with the default and remove the "[...]" string.

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
