### ISSUE TITLE
Menu broken when upgrading to v1.3 on mobile

### ISSUE THREAD

**Issue by devdream123** [soflyy/breakdance-bugs#849]
**What version of Breakdance are you using?**

v1.3

**What browser are you using?**

Chrome and Safari on mobile phone

**What operating system are you using?**

iOS

**Reproduction  Steps**

1. Upgrade to version 1.3
2. Check the menu header on the phone
3. Menu is broken on the phone

**Reproduction Video**

![IMG_5842](https://github.com/soflyy/breakdance-bugs/assets/17215327/0d426fe2-3f46-4431-a1e1-d19bb548d81d)

**Comment by a-dubiel** [comment]
Please try regenerating cache.

**Comment by live2evolve** [comment]
I'm also experiencing the same issue. Regenerating the cache doesn't fix the issue. Deleting and rebuilding the header and menu doesn't fix the issue. 

I'm on Breakdance 1.3
OS: IOS 16.5 iPHone 14 Prom Max (can replicate the issue on multiple phones)
Browser: Safari or Chrome

Screenshot of behavior of mobile selector not displaying correctly followed by the click state. 
![IMG_1790](https://github.com/soflyy/breakdance-bugs/assets/13304873/54b1c846-4d11-47d4-a270-a6624b560fa1)
![IMG_1789](https://github.com/soflyy/breakdance-bugs/assets/13304873/52af020e-4c17-46e3-b74e-a26c4eabde17)

**Comment by live2evolve** [comment]
I was able to find the issue. There is a conflict with the SiteGround Optimizer plugin. Disabling that plugin fixed the issue on my 1.3 site. 

I found the specific setting in the SiteGround Optimizer is in Front End Optimization > Combine CSS Files (Combine multiple CSS files into one to lower the number of requests your site generates.) 

Disabling this setting fixes the issue.

**Comment by a-dubiel** [comment]
> Front End Optimization > Combine CSS Files

This might break Breakdance. We do our best to optimise CSS on our end so any additional mechanisms outside Breakdance might break builder functionality. @devdream123 are you using any optimisers?

**Comment by devdream123** [comment]
@a-dubiel yep Im also using Siteground Optimiser. 
But why combining multiple css files into one breaks BD? BD doesnt combine CSS files right?

**Comment by louisreingold** [comment]
> BD doesnt combine CSS files right?

Breakdance doesn't combine the CSS files because it's counterproductive, bad for performance, and breaks browser-side caching.

It's a fake optimization technique designed to game tools that look at the number of requests (no longer applicable with HTTP2... it's been irrelevant for YEARS now), not designed to make your pages load faster.

Don't do it. It's a mistake.

As far as SG not combining the files correctly? If you say the styles are broken, then yes, it did something wrong in it's attempt to "optimize".
