### ISSUE TITLE
Product Tabs content not displayed

### ISSUE THREAD

**Issue by jijojosein** [soflyy/breakdance-bugs#85]
When adding the "Product Tabs" element, the content inside the tab is not displayed properly. Please check the screenshot. 

This is a local WP installation with no plugins other than BD Beta 2. 

![Screenshot 2022-07-21 at 6 41 41 PM](https://user-images.githubusercontent.com/12230445/180222355-eedeafdd-63f5-4c5e-b551-8108634a68ac.png)

![Screenshot 2022-07-21 at 6 41 58 PM](https://user-images.githubusercontent.com/12230445/180222328-0a4f40eb-0d54-4499-8c9d-ef5bfe202945.png)

**Comment by louisreingold** [comment]
Solved in beta 5.
