### ISSUE TITLE
Global Settings > Buttons > Effects > Scale On Hover won't accept decimal value if first digit is 0 after the decimal

### ISSUE THREAD

**Issue by d19dotca** [soflyy/breakdance-bugs#850]
When typing out a value of "1.05" for example in the Scale On Hover property for the Global Settings of a Button, it will make it "15" instead of "1.05". It only seems to affect numbers with a 0 after the decimal. If I take the value it converts to of "15" and make it "105" and then add a decimal between the "1" and "0", then it accepts the number.

**What version of Breakdance are you using?**

v1.4 beta 1

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction  Steps**

1. Go to Global Settings > Buttons > Primary > Effects
2. Enter a value of "1.05" by typing it in the Scale On Hover property
3. Notice the value is then "15" instead of "1.05" when entered.

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
