### ISSUE TITLE
Confirm Notice before deleting Stylesheets

### ISSUE THREAD

**Issue by lordloadalot** [soflyy/breakdance-bugs#853]
**Is your feature request related to a problem? Please describe.**

>> So yes - I am always frustrated when I inadvertently have deleted a CSS stylesheet without really noticing. 

**Describe the solution you'd like**

>> Please add one step of confirm like a popup "do you really ... ?"

thx. :)

**Describe alternatives you've considered**

**Additional context**

**Comment by a-dubiel** [comment]
> CSS stylesheet 

Can you be more specific? Global CSS?

**Comment by lordloadalot** [comment]
Hi a-dubiel!

Global Stylesheets under
GLOBAL SETTINGS >> CODE >> CSS > STYLESHEET

Best Martin.
![Bildschirmfoto 2023-06-14 um 14 19 50](https://github.com/soflyy/breakdance-bugs/assets/29510055/65a2863c-9209-4b05-8e5a-c7b9092eacf6)

**Comment by lordloadalot** [comment]
Hello! Any News here ??

...

**Comment by louisreingold** [comment]
We have undo and a revisions system for your global settings. 

If you delete a stylesheet and didn't mean to, just click undo or hit command-z.

If you save your global settings, leave the page, and come back in a week and decide you want the stylesheet back? Restore the revision from the history tab of the global settings panel.

**Comment by lordloadalot** [comment]
ok. thanks. did not see revisions in global settings.
