### ISSUE TITLE
Form attachments do not work unless you enable "Store uploaded files"

### ISSUE THREAD

**Issue by philc100** [soflyy/breakdance-bugs#854]
Images files are corrupt/missing data when sending via form builder element with "Attach uploaded files" enabled. 

The attachments work fine if you enable "Store uploaded files", alongside "Attach uploaded files"

Tried 2 different SMTP providers. (Postmark and Gmail API)
This was sending to a business gmail account

Using v 1.3.1

**Comment by breakdancemoderator** [comment]
Thanks for the report. This is addressed in Breakdance 2.0 beta 1.
