### ISSUE TITLE
Conditions >  Dynamic Data not working with ajax pagination in Post Loop Builder

### ISSUE THREAD

**Issue by MrBushid0** [soflyy/breakdance-bugs#856]
Breakdance 1.3.1

Can't see an existing issue for this but it seems like conditions when using dynamic data doesn't get applied inside a Post loop when using ajax ( load more or infinite scroll ). It works fine with the standard pagination though. 

 You can see the setup of the global block and behaviour for the different paginations here 
https://tinyurl.com/27fvwmt2

**Comment by a-dubiel** [comment]
Hey @MrBushid0 I was able to reproduce this. We have fix in place so this will be addressed soon. Thanks for your report.

**Comment by MrBushid0** [comment]
> Hey @MrBushid0 I was able to reproduce this. We have fix in place so this will be addressed soon. Thanks for your report.

Sounds good. Thanks for update!

**Comment by louisreingold** [comment]
This was addressed in Breakdance 1.5 Beta 1.

**Comment by MrBushid0** [comment]
> This was addressed in Breakdance 1.5 Beta 1.

Thank you!
