### ISSUE TITLE
Gallery Slider 

### ISSUE THREAD

**Issue by GinaOrlando** [soflyy/breakdance-bugs#857]
I am having issues with the Gallery control, it starts giving errors on the screen once you set the 'Type' to Slider:

![error2](https://github.com/soflyy/breakdance-bugs/assets/11299468/9fe8ad8b-1729-4297-b40c-ca839cf280a1)

When I went and viewed the page it's giving me this console error:

![error](https://github.com/soflyy/breakdance-bugs/assets/11299468/0fe01084-1fa4-4179-942c-be9ec670379c)

I also disabled my caching plugin (SG Optimizer) but that doesn't seem to change anything. I had another site build on Breakdance that is using the gallery slider. I just tested it out on there. Once I updated Breakdance to the most updated version the gallery slider on that site started throwing these errors as well.

I am currently using Version 1.4.0-beta.1 on PC with Windows operating system and Chrome as my browser.  What version do you recommend using? This is a client website build so I want to make sure we're using the most stable version!!

**Comment by a-dubiel** [comment]
Thanks for the report @GinaOrlando - we are working on getting this fixed.

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.4. Thanks for the report.
