### ISSUE TITLE
Taxonomy doesn't work in querybuilder

### ISSUE THREAD

**Issue by brandforwardnl** [soflyy/breakdance-bugs#858]
**What version of Breakdance are you using?**

v1.3.1

**What browser are you using?**

Safari (Latest)

**What operating system are you using?**

MacOS (Latest)

**Reproduction  Steps**

- Create a custom post type
- Add a post in that post type and select category (or a custom taxonomy)
- Create a listing that displays these kind of posts
- Add a loopbuilder widget to a page
- Select the correct listing
- Under query click 'edit query'
- Under condistions selecty 'Has taxonomy' and select the category / tax.

As you can see: nothing happens and the entered values are gone. The selected tax is empty. (see video below)

**Reproduction Video**

https://share.cleanshot.com/KGKlsGHq

**Comment by a-dubiel** [comment]
Thanks @brandforwardnl for the report. We are aware of this bug and currently working on the fix.

**Comment by brandforwardnl** [comment]
Great! Thanks 🤓

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.4. Thanks for the report.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.4. Thank you for helping us improve Breakdance.
