### ISSUE TITLE
ACF Repeater outside the loop

### ISSUE THREAD

**Issue by StaggerLeee** [soflyy/breakdance-bugs#859]
How to show ACF Repeater outside the loop ?
Say for example:

- I have a Page with ACF repeater
- I would like to show repeater values at the front page (homepage).

**Comment by StaggerLeee** [comment]
I mean I know how to show it with PHP code. Just, is it an way to make it with Breakdance to style it with builder ?

**Comment by louisreingold** [comment]
Put the repeater field on the page you want it to appear on... don't put fill out a repeater field on Page A and then try to show the contents of the repeater on page B.

You could do it using the Post Loop Builder and setting the query to only show one post... but that's kinda weird.
