### ISSUE TITLE
IO-TS decoding failed

### ISSUE THREAD

**Issue by phil-sola** [soflyy/breakdance-bugs#86]
I have just downloaded the beta 2 version to try it out for the first time and not a great start, I can't seem to get it working at all so far due to an IO-TS decoding failed error when trying to open the global styles. 

Below is a copy and paste of the errors I am seeing in the browser console:

io-ts-errors-to-_error.ts:194 IO-TS validation failed, see the details below
y @ io-ts-errors-to-_error.ts:194
io-ts-errors-to-_error.ts:86 Type `{"environment":"production"...` (Object) is not assignable to type `{ environment: ("local" | "...` (e)
io-ts-errors-to-_error.ts:90 Property `.builderElements` is missing in type `{"environment":"production"...` (Object), but is required in type `{ environment: ("local" | "...` (e)

I am using a clean local by flywheel WP environment on Linux Ubuntu 22.04 LTS 64-bit with Chrome. I have tried both normal and incognito browsing with the same results. 

No other plugins installed.

I have attached a screenshot of the white screen I get every time. 

![screenshot](https://user-images.githubusercontent.com/40669220/180287563-042f1a6d-d87b-4009-884c-346be34d2e65.png)

**Comment by Hanael** [comment]
Same issue for me. Even with a fresh WP install, zero plugins installed.

Server: Classic mutualized hosting with Apache
PHP: tested with 7.4 to 8.1
Browser: Chrome (what else ^^)

<img width="1175" alt="Capture d’écran 2022-07-22 à 13 01 06" src="https://user-images.githubusercontent.com/3649378/180425990-d556c19d-ccb3-4715-a742-7e2400bf8d29.png">

**Comment by Hanael** [comment]
Also tested with Kinsta (Nginx): same issue.

**Comment by Foolevil** [comment]
I too have this with Local (Nginx/Apache).

**Comment by mdomedia** [comment]
![image](https://user-images.githubusercontent.com/108284698/180491756-4dfc0c5a-7b98-4dbc-b31e-5620a0b3484a.png)

My error preventing me from using Local WP
