### ISSUE TITLE
Heading Element -  add div and span on selecting which h1-h6

### ISSUE THREAD

**Issue by joohub** [soflyy/breakdance-bugs#862]
Hi,
The heading element need am addional div or span for the tag selection. This is sometimes needed in the workflow if you write a headline and want to add something above or below. It is faster to duplicate the heading element to add an above heading. But it is too spammy to make many h2-h6 on a page, so i want to have an span for that.

best regards

**Comment by joohub** [comment]
Elementor have this option on the heading element. So it is needed even for the logic of new Breakdancer from Elementor.

**Comment by louisreingold** [comment]
We have that. It's called the Text element. The option is in the settings tab (cog icon), at Advanced > Tag.

> It is faster to duplicate the heading element to add an above heading

Type Command+A, type T, hit enter. 

https://www.youtube.com/watch?v=0AqKGn0lOHE

**Comment by joohub** [comment]
Hi, its about speed and easyness on building. Going to advanced - tag is  1-2 step more everytime. 
Its not logical to see the div option on an heading element, yeah - but in thinking about speed it's an good improvement in usability. You could add an advanced option on the Builder panel, to activate it.

Just a thought from my perspective. If it's not added, no problem.
