### ISSUE TITLE
Global Settings - Import Export settings

### ISSUE THREAD

**Issue by joohub** [soflyy/breakdance-bugs#866]
Hello,
could you please add an import export for global settings. Looks like an small feature to fast implement. This will optimize the workflow rapidly. It is anoying everytime to setup everything with clamp / full responsive.

https://breakdance.canny.io/element-requests/p/export-or-import-global-settings
https://breakdance.canny.io/features/p/export-global-settings

best regards

**Comment by joohub** [comment]
You could also create a default blank preset and a responsive starter preset with this to select.
https://www.youtube.com/watch?v=sWz1SpSWBOw

**Comment by breakdancemoderator** [comment]
Thanks for this request. This has been added in Breakdance 2.0.
