### ISSUE TITLE
Animations in advanced slider should be re-run when slide appears on screen

### ISSUE THREAD

**Issue by windkracht20-nl** [soflyy/breakdance-bugs#867]
**What version of Breakdance are you using?**
For example: v1.3, v1.3 and 1.4 beta 2

**What browser are you using?**
For example: Firefox

**What operating system are you using?**
macOS

**Reproduction  Steps**
- Add advance slider. 
- Delete all slides and add a new slide
- Select heading element and add entrance animation slide up for example 
- Duplicate the slide
- That's it. Now when show on front-end the text animation is only working properly the first time on the first slide. After that the text animation is not working properly.

**Reproduction Video**
https://www.loom.com/share/2786237fa84346e1b13a5c9c78711250?sid=18dbaeed-56b7-476b-a5eb-7e19ade5bf28

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
