### ISSUE TITLE
Better Facebook Ads

### ISSUE THREAD

**Issue by joohub** [soflyy/breakdance-bugs#869]
Hi, 
just view the 12 reasons why breakdance rocks. Theses ads need to be optimized. @louisreingold
You're loosing big money, because the ads are not the best...
Loosing money on Facebook and new Breakdance subscriptions. 

1. It is very dark, make it on the day with full light. 
2. An short intro is missing on the beginning. Like the first image on Youtube you need an good image and a short intro about the builder. Show them the epic megamenu builder and other things which are epic compare to other builder. Put it in the intro and first Image. There is an conversionrate on Youtube first image pictures, so on your FB Ads of course too. After the first image there is also an conversion how long peolpe watch a video. 

4. You dont write what is Breakdance in the title, so people dont understand it and you missing the main keyword. Breakdance Wordpress Page Builder is a keyword which people can read if the scan very fast a website. Breakdance is associated with the Sport so you have to write page builder.

https://fb.watch/llClHQ6GJU/

(I did not read the text, before i wrote this, but i see your marketing team is writing in the beginning "This one is from Louis, not the marketing department..." I can truly understand it, why they wrote that.)

Like you are doing research for Breakdance to create the best builder, buy books and courses for marketing on facebook and how to present best your page builder. Google for studies, whats going best. 

best regards

**Comment by joohub** [comment]
Look how this Seo Guy does good Videos:
https://www.youtube.com/results?search_query=backlinco

here: https://www.youtube.com/watch?v=1rzPLVJMSkQ

**Comment by a-dubiel** [comment]
Thanks for the suggestion @joohub. We use this space for specific Breakdance bugs. If you have other non-software suggestions feel free to use the Facebook group.

**Comment by joohub** [comment]
Yeah, so github is not everyone reading, i don't want it that everyone can see it... You can delete it.
