### ISSUE TITLE
Bug - Inserting columns in a div

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#87]
I'm having a lot of problems when I want to drag columns into a div, the elements don't nest properly, and my section ends up spitting

**Comment by louisreingold** [comment]
Our support team would be happy to take a look: email support@breakdance.com.

I'm not able to reproduce this based on the description provided. I can drag a Columns element into a Div: https://www.loom.com/share/facb6ad0c9a645c9ac890918fd9eeb7f
