### ISSUE TITLE
Error with Animation on a Popup

### ISSUE THREAD

**Issue by codingharz** [soflyy/breakdance-bugs#870]
![230621_breakdance_error_popup](https://github.com/soflyy/breakdance-bugs/assets/133856828/63f099eb-3e4c-4455-9d43-d23db232de12)

**What version of Breakdance are you using?**
BD 1.4.0-beta.2 (The error does not occur in version 1.3.0)

**What browser are you using?**
Chrome, Firefox

**What operating system are you using?**
Windows

**Reproduction Steps**
The error can be easily reproduced:

1. create a new popup
2. edit with breakdance
3. popup > animation > select any > error message

[Here was already this error #656 ](https://github.com/soflyy/breakdance-bugs/issues/656)

**In the short video, you can see the error**

[https://www.loom.com/share/2fa04a4030af414aa5f23e042b4e6028](url)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.4. Thank you for helping us improve Breakdance.
