### ISSUE TITLE
Comment Form Element - Respect WP Admin -> Settings - >Discussion -> Show comments cookies opt-in checkbox

### ISSUE THREAD

**Issue by StaggerLeee** [soflyy/breakdance-bugs#871]
Your code, seems as, does not respect setting in Settings - Discussion =  Show comments cookies opt-in checkbox, allowing comment author cookies to be set.

Checkbox is visible regardless of this setting.

**Comment by louisreingold** [comment]
@StaggerLeee - this issue has a strange title. To be clear, you're talking about the Comment Form element, yes?

**Comment by StaggerLeee** [comment]
Yes, comments form.

**Comment by breakdancemoderator** [comment]
Thanks for the report. We've addressed this in Breakdance 2.0 Beta 1.
