### ISSUE TITLE
Bug in query editor since 1.3

### ISSUE THREAD

**Issue by etjallings** [soflyy/breakdance-bugs#872]
The sorting/order by/has taxonomys option is not working correctly when selecting more than one taxonomy. So i select conditions, has taxonomys, is one of: then choose 2 taxonomy's.
Then i only get oosts from the second taxonomy.  

Tested in an older version of breakdance, then its working fine. Expected behaviour is show post from all selected taxonomys and order by date.
<img width="608" alt="Scherm­afbeelding 2023-06-24 om 11 41 34" src="https://github.com/soflyy/breakdance-bugs/assets/110063773/4b51ec9e-bc9e-4b7f-ab4c-21c76abc4c1a">

**Comment by a-dubiel** [comment]
What 1.3 version are you on?

**Comment by etjallings** [comment]
version 1.3.1

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.4. Thanks for the report.
