### ISSUE TITLE
Breakpoint conditions on popups do not work

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#874]
**What version of Breakdance are you using?**

Tested on 1.21 and 1.31

**What browser are you using?**

Edge, Opera, Mobile Edge

**What operating system are you using?**

Windows, Android

**Reproduction  Steps**

- create a popup
- add a condition to only display at certain breakpoints as per the image
- condition is not respected and popup displays at all breakpoints

![image](https://github.com/soflyy/breakdance-bugs/assets/112517932/a2605c27-b3e0-48ce-9ede-057251698532)

**Comment by a-dubiel** [comment]
https://www.loom.com/share/77f5d741ad154b9383ee4958bbf633a9

I just tested 1.4 RC and cannot reproduce this.

**Comment by lockedm** [comment]
@a-dubiel I'm seeing this as still broken in 1.4RC1, can reproduce on multiple systems:

https://recordings.webxdesign.studio/recordings/zluiuwUo5JAr8xD7e8wa

You can look at page: https://dev.webxdesign.studio/test-popup/

I can give you access if you need it

**Comment by a-dubiel** [comment]
Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.

**Comment by lockedm** [comment]
sent.
