### ISSUE TITLE
Woocommerce Cart adding amount error

### ISSUE THREAD

**Issue by Gille666** [soflyy/breakdance-bugs#875]
Breakdance 1.3.1
Woocommerce 7.8.1

When adding a product and raising the amount (for example from 1 to 2) -> the cart has a spinning ball.

It only happens in the open cart module, not in the full page cart overview (page).

I've made 2 woo sites, it had it on both of them.

Thanks for the fix.

**Comment by a-dubiel** [comment]
Hey, this is related to newest WooCommerce update. We already have this fixed and will be released with 1.4 very soon.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.4. Thank you for helping us improve Breakdance.
