### ISSUE TITLE
Feature Request: To Make "This Website" the default selection when the Design Library loads

### ISSUE THREAD

**Issue by theperfectwill** [soflyy/breakdance-bugs#876]
**Is your feature request related to a problem? Please describe.**

Yes, I feel it is delay to always have to click into "This Website" to get designs from the current website, over designs that are not of the current website. 

**Describe the solution you'd like**

I would like for "This Website" to be the default selected option.

With this in mind, it would be good to have an option to disable the Design Library, in the plugin settings, or by filter hook, but still allow the current website as the only Design Library option, as when handing the site over to a client, or when having created designs already in the current site for them; and so that potential Design Library designs are not used in a way not consistent with the current's sites design, by another user or current client.

**Describe alternatives you've considered**

N/A

**Additional context**

The designs are good for when starting a site from scratch, with no design already in mind, or needing to grab a certain design to start from, but once the current website design has its own momentum within the site, the other designs are less needed, but grabbing other designs of the current site are still commonly needed/useful (such as sections, buttons, woo product style pages, membership layouts, post list layouts, etc.)

Screenshot:

![image](https://github.com/soflyy/breakdance-bugs/assets/6123260/9946c4e4-5660-4f64-ad4a-eb07ecaba999)

**Comment by louisreingold** [comment]
This is done in Breakdance 1.7. "This Website" is now the default. The dialog also remembers the last-used provider, so it will only fall back to "This Website" if another provider wasn't used last.
