### ISSUE TITLE
Design library buttons visible for non-logged in users

### ISSUE THREAD

**Issue by brandforwardnl** [soflyy/breakdance-bugs#877]
**What version of Breakdance are you using?**

v1.3.1

**What browser are you using?**

Safari (latest)

**What operating system are you using?**

MacOS (latest)

**Reproduction  Steps**

I don't know if this a bug or intended use but if you turn a website into a design library non-logged in users can see the yellow copy buttons on the whole website (see video below). Wouldn't it be better to make this optional: show copy buttons for logged in users (admins) or non logged-in users?

In my case: sometimes you want to copy sections from client sites that I want to recycle but I don't want regular visitors see this.

Thanks!

**Reproduction Video**

https://share.cleanshot.com/M0TMSMVn

**Comment by louisreingold** [comment]
Intended behavior, but we have an internal issue to provide an option for this, and we'll likely add it.

**Comment by brandforwardnl** [comment]
Ok, let's hope it gets added in a future release. Thanks.

**Comment by louisreingold** [comment]
Thanks for your report!

As of Breakdance 1.7, you can now hide the copy button can now be hidden from the frontend even if the design library is enabled.

We've significantly enhanced the design library functionality for creators. You can now password-protect your design library sources.

https://breakdance.com/new-features-in-breakdance-1-7/
