### ISSUE TITLE
HEADER TEMPLATES: Canoot assign multiple Locations

### ISSUE THREAD

**Issue by lordloadalot** [soflyy/breakdance-bugs#879]
**What version of Breakdance are you using?**

1.4.0-beta.3

**What browser are you using?**

Chrome, Safari, FF, FF klar, Oopera, Blisk

**What operating system are you using?**

macOS 12.6

**Reproduction  Steps**

 I cannot add multiple locations to a header template – just multiple conditions.

I need to use a second header on
-- one specific "Page"
-- one specific "Specific Product Archive"
-- one specific "Product" Template

Please Help!
Best – da lord.

**Comment by louisreingold** [comment]
A Header can have one location and multiple conditions to narrow down where it appears. That's how it's supposed to work. Our existing settings allow you to put a header anywhere you want, with unlimited flexibility.

If you describe exactly what you'd like to do to our support team (i.e. where exactly you want your alternate header to show up), they'd be happy to show you how to do it with Breakdance. Email them at support@breakdance.com.
