### ISSUE TITLE
Template [Breakdance] No Header / Footer still shows FOOTER

### ISSUE THREAD

**Issue by plittlefield** [soflyy/breakdance-bugs#881]
I have a holding page with just a logo in the middle, while I work on the main site behind the scenes.

For this holding page I have selected Template: [Breakdance] No Header / Footer - in the Pages in the Dashboard (shown below):-

![image](https://github.com/soflyy/breakdance-bugs/assets/8265704/218d7b3b-fdb9-40e1-b7cd-d75d17dd3d73)

However, when viewing this page it still shows the Footer from the main site.

**Comment by louisreingold** [comment]
I'm not able to reproduce this. Our support team is happy to help you if you email support@breakdance.com.

**Comment by plittlefield** [comment]
My bad, I found the cause.

I had set the viewport size of the section to 90% of VH, so it was showing the default light grey background on 10% of the screen below the white background of the section above!
