### ISSUE TITLE
Beta 3 Bug | Repeater with ACF Gallery Slider

### ISSUE THREAD

**Issue by NietAkkoord** [soflyy/breakdance-bugs#882]
Breakdance Beta 3
ACF Version 6.1.7 

Current Version BD 1.3.1
I included a Gallery slider in a repeater. The gallery had images coming from ACF Gallery.
All duplicated blocks showing this slider were ok. Next / previous buttons worked.

I had this automatic update active and since the latest update to Beta 3, some issues occured.
Only the final block of the repeater showed my design and next/previous buttons worked.
All blocks lost their design and the slider buttons (prev/next) stopped working, except for the final block of the repeater. There all was ok. So when adding a new block, that one was ok again and the "previous final block" became wrong too.

When downgrading again to BD 1.3.1 all was good again.

Here's an example of the page:
https://tank-service.previewyoursite3.be/buitengebruikstellen-brandstoftanks/bovengrondse-tanks-verwijderen/

- "Werkwijze van het afbreken en verwijderen van een tank" is repeatable block 1
- "Enkele referenties" repeatable block 2
_Both showing good at this moment._

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
