### ISSUE TITLE
Global font-size Mobile not working

### ISSUE THREAD

**Issue by joaogatodebigode** [soflyy/breakdance-bugs#883]
I'm using Global fonts and i'm trying to change font-size when i'm in phone landscape. It doesnt change in the builder, but not in front-end.

<img width="311" alt="Screenshot 2023-07-04 at 15 06 52" src="https://github.com/soflyy/breakdance-bugs/assets/138598558/fcd372a9-bd43-43d1-9035-2aed4868aa25">
<img width="373" alt="Screenshot 2023-07-04 at 15 07 50" src="https://github.com/soflyy/breakdance-bugs/assets/138598558/e2037e62-6aac-45ed-8614-77d3afe8f40a">
<img width="356" alt="Screenshot 2023-07-04 at 15 07 29" src="https://github.com/soflyy/breakdance-bugs/assets/138598558/6a02c9b4-493b-4cbf-87fc-e6facc6912d9">

Im using 1.4 Beta 3.

**Comment by louisreingold** [comment]
I'm not able to reproduce this. Our support team is happy to help with technical support questions. Email us at support@breakdance.com.
