### ISSUE TITLE
Level 3 Styling ist Level 2 (1.4 Beta 3)

### ISSUE THREAD

**Issue by aportmann** [soflyy/breakdance-bugs#884]
**What version of Breakdance are you using?**

For example: v1.4 Beta 3

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction  Steps**

Menubuilder Mobile Dropdown Links --> Typography --> Level 2 affect nothing, Level 3 ist for Level 2 styling.

**Reproduction Video**

https://d.pr/v/ZJTBSc

**Comment by louisreingold** [comment]
You don't have any level 2 links in your menu.

https://www.loom.com/share/9b0874cd4ede4ca687d77f860b148ef1
