### ISSUE TITLE
Unable to close a popup if 'do not show this popup if an other popup has already shown'

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#887]
**What version of Breakdance are you using?**

For example: v1.4RC1

For example: macOS, Windows

- create a popup
- set do not show this popup if an other popup has already shown' to true
- popup cannot be closed with the close button or by clicking off the popup

**Comment by lockedm** [comment]
Sorry, this looks to be an impatibiity with something within perfmatters. disabling perfmatters and all is good.

**Comment by lockedm** [comment]
Actually, perfmatters is a red herring. can reproduce when perfmatters is disabled. It appears to be related to the number of triggers, or when using the trigger - page scroll - and then to a percentage. As you can see from this video, sometimes it works, but on the second time I'm clicking on the button and the background and it is not closing.

https://recordings.webxdesign.studio/recordings/Z8q2ABNPJ7FAtlqSGtDG

You should definitely be able to reproduce if you use these type of popup settings:

![image](https://github.com/soflyy/breakdance-bugs/assets/112517932/76992d8d-f50b-43ee-b73f-a2dc949ca5c9)

**Comment by a-dubiel** [comment]
Can you help me with triaging this? You have 5+ conditions on this popup. Which exact condition breaks the functionality?

**Comment by lockedm** [comment]
@a-dubiel if you look at the video, I've shown it with just 2 conditions like:

![image](https://github.com/soflyy/breakdance-bugs/assets/112517932/c8117379-2c2b-4b43-af0e-e70564e51cf5)

Refresh the page a couple of times with this in place and you can't close the popup. You can login to the same system as I've just emailed you for the breakpoint popup issue

**Comment by lockedm** [comment]
I can repro this with just a single trigger of 'page scroll' using percent

**Comment by a-dubiel** [comment]
Awesome. I suspected these two triggers (scroll and exit) in conjunction cause errors. Thanks for the details. We are working on a fixing this soon.

**Comment by lockedm** [comment]
That's great. Hope you've been able to repro it, otherwise log in to the site I emailed details for, and you'll see it. 
      
        
        
          On Jul 12 2023, at 10:46 am, Andrzej Dubiel ***@***.***> wrote:
          
        
        
          
Awesome. I suspected these two triggers (scroll and exit) in conjunction cause errors. Thanks for the details. We are working on a fixing this soon.

**Comment by lockedm** [comment]
This is fixed in 1.4.1 RC2. THanks.
