### ISSUE TITLE
Background videos don't play in advanced slider

### ISSUE THREAD

**Issue by winkcreative** [soflyy/breakdance-bugs#888]
**What version of Breakdance are you using?**

v1.3.1

**What browser are you using?**

Mac Firefox

**What operating system are you using?**

macOS

**Reproduction  Steps**

I currently have 2 global blocks. These both include a section which has a hosted vimeo video set as the background (videos are 15 seconds) and a div that contains some styling, a title and button.

The advanced slider on the homepage contains 2 slides which each contain one of the global blocks. When viewed on the front end only one of the background videos play and it does load the other elements in the global block. - see the video where the first 15 seconds only show the elements and no video playing in the background.

**Reproduction Video**

[](https://vimeo.com/843486919/1f21d80394?share=copy)

**Comment by winkcreative** [comment]
in additional when the slider then loops none of the background videos play

**Comment by a-dubiel** [comment]
Can you link the reproduction video?

**Comment by winkcreative** [comment]
https://vimeo.com/843486919/1f21d80394?share=copy

Many thanks... Will
[A pink and grey logo  Description automatically generated]<https://winkcreative.co.uk/>
Will Patterson | Creator
Wink Creative
[signature_2980068613] 07812 063 285<tel:07812%20063%20285>
***@***.******@***.***>
[signature_323976437] www.winkcreative.co.uk<http://www.winkcreative.co.uk>
[LinkedIn]<https://www.linkedin.com/in/will-patterson/> [Facebook] <https://www.facebook.com/winkCreative>  [Instagram] <https://www.instagram.com/justthinkwink/>  [Twitter] <https://twitter.com/wink_creative/>
Web Design | Photography | Video | Logo Design | Graphic Design | Social Media


From: Andrzej Dubiel ***@***.***>
Date: Tuesday, 11 July 2023 at 2:11 pm
To: soflyy/breakdance-bugs ***@***.***>
Cc: Will Patterson ***@***.***>, Author ***@***.***>
Subject: Re: [soflyy/breakdance-bugs] Background videos don't play in advanced slider (Issue #888)

Can you link the reproduction video?

**Comment by winkcreative** [comment]
Sure ill do that today, seems like if you have more than one slider on a page they go a bit haywire, as I also have other image sliders and fancybox sliders on the one page and only one seems to work at a time

Many thanks... Will
[A pink and grey logo  Description automatically generated]<https://winkcreative.co.uk/>
Will Patterson | Creator
Wink Creative
[signature_2099497327] 07812 063 285<tel:07812%20063%20285>
***@***.******@***.***>
[signature_1013411078] www.winkcreative.co.uk<http://www.winkcreative.co.uk>
[LinkedIn]<https://www.linkedin.com/in/will-patterson/> [Facebook] <https://www.facebook.com/winkCreative>  [Instagram] <https://www.instagram.com/justthinkwink/>  [Twitter] <https://twitter.com/wink_creative/>
Web Design | Photography | Video | Logo Design | Graphic Design | Social Media


From: Andrzej Dubiel ***@***.***>
Date: Tuesday, 11 July 2023 at 3:03 pm
To: soflyy/breakdance-bugs ***@***.***>
Cc: Will Patterson ***@***.***>, Author ***@***.***>
Subject: Re: [soflyy/breakdance-bugs] Background videos don't play in advanced slider (Issue #888)

Can you link the reproduction video?

I meant record yourself in Breakdance doing this...

I currently have 2 global blocks. These both include a section which has a hosted vimeo video set as the background (videos are 15 seconds) and a div that contains some styling, a title and button.

The advanced slider on the homepage contains 2 slides which each contain one of the global blocks. When viewed on the front end only one of the background videos play and it does load the other elements in the global block. - see the video where the first 15 seconds only show the elements and no video playing in the background.

I cannot reproduce this on my end and a video showing me what you are trying to do would be super helpful.

**Comment by winkcreative** [comment]
https://vimeo.com/844590076/47db4c2c53?share=copy
