### ISSUE TITLE
Gallery loads full size images regardless of Image Size settings

### ISSUE THREAD

**Issue by djrwp** [soflyy/breakdance-bugs#889]
1.3.1
Chrome, Safari,
macOS

I reported this bug via support last month but no sign of it here and not fixed in 1.4 rc.

Image Size settings are not respected in front end, the only one that works is thumbnail, all the others have no effect. This leads to a huge page size as full size images are loaded for every gallery image.

<img width="1278" alt="Screenshot 2023-07-09 at 08 53 49" src="https://github.com/soflyy/breakdance-bugs/assets/84224815/6dbb9a00-2170-4466-917e-8da2bf848cc1">

**Comment by louisreingold** [comment]
> I reported this bug via support last month

@djrwp what's the ticket ID?

**Comment by louisreingold** [comment]
Is there more to the issue than what I described above? If so, can you provide steps to reproduce? As you can see in my video, choosing a different size from the dropdown affects the image src attribute in the HTML, which is the correct behavior. 

Is something different happening for you?

**Comment by djrwp** [comment]
> Same thing happens with the Image element, yeah?

No, image element respects the chosen image size.

**Comment by djrwp** [comment]
> > I reported this bug via support last month
> 
> @djrwp what's the ticket ID? I want to see if there's more info in the ticket.

No ticket ID, but email was sent to support on 5th June, Subject - Gallery bug - loading full size images

**Comment by djrwp** [comment]
> Here's what's actually happening: https://www.loom.com/share/4cb9b0de9a8b486bb8267a2c7f346356

that all makes sense, but in my browser it's loading full size 2560 width images which makes the initial page huge and slow to load even with lazy load. I take GTmetrix with a pinch of salt but the gallery page comes in at 27mb.

**Comment by djrwp** [comment]
> Removing the `bug` tag but leaving open as we might ship the option I proposed in the Loom.
> 
> But do you actually want this option?

I think the option would be handy to override browser choice as regardless of users connection I wouldn't want to load full size images.

**Comment by djrwp** [comment]
> Is there more to the issue than what I described above? If so, can you provide steps to reproduce? As you can see in my video, choosing a different size from the dropdown affects the image src attribute in the HTML, which is the correct behavior.
> 
> Is something different happening for you?

Pretty much as you describe, but this only happens with Gallery widget. In other widgets - image, loop builder, post loop the chosen image size is loaded.
