### ISSUE TITLE
Sidebar cart does not work with sticky header

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#89]
Hi, when making the header sticky the mini cart can not be set to the sidebar cart.
It will contained to the header.
Please check.

![Screenshot (37)](https://user-images.githubusercontent.com/10600315/180415391-ee30dade-66d8-4ece-935e-7ff7fecdfb28.png)

**Comment by louisreingold** [comment]
I'm not able to reproduce this: https://www.loom.com/share/585e09ae6c394ea2a7c1b1f1745d1e17

Have you manually set z-index on anything? Can you provide more exact steps to reproduce? If you email support@breakdance.com we can take a look.
