### ISSUE TITLE
Updating breakdance from 1.2.1 to latest stable 1.3.1 breaks designs/template

### ISSUE THREAD

**Issue by ivansrbic** [soflyy/breakdance-bugs#890]
**What version of Breakdance are you using?**

For example: v1.2.1 -->1.3.1

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: Windows

**Reproduction  Steps**

1) Create design using 1.2.1 version of Breakdance (no other plugins were used)
2) Update the Breakdance to 1.3.1
3) The design gets broken
4) Revert back to old version the design is fixed

**Reproduction Video**

This  breaks more than just header as shown in this clip I have websites where whole website designs gets completely broken. Again no other plugins but breakdance being used.

https://github.com/soflyy/breakdance-bugs/assets/39265418/ef6d0eb2-9a3c-44b6-aba9-1d3d93b33f55

https://github.com/soflyy/breakdance-bugs/assets/39265418/aa509ef1-f01f-4cbf-a05b-a1b30203391a

https://github.com/soflyy/breakdance-bugs/assets/39265418/22a38282-5a59-43cc-ac61-a7ad34508f60

I have split problem video in 2 parts because it would not fit in a single video since it was over 10Mb.

**Comment by louisreingold** [comment]
1.4 will automatically clear the CSS cache.

**Comment by ivansrbic** [comment]
But that has nothing with the fact that if you update your breakdance to never version your design will break?
I just cleared cache to show that's not the problem but the upgrade from older to newer version.

**Comment by louisreingold** [comment]
Am I missing something in the video?

The design appeared in correctly and after you cleared the CSS cache it appeared correctly? Or did I miss something?

**Comment by ivansrbic** [comment]
Apologies if the video was confusing.

Its like this.

On 1.2.1 is the version that was originaly used to create a design.

If that version got updated to 1.3.1 the design broke. Nothing fixed it, not even clearing the cache.

If I then DOWNGRADED back to 1.2.1 the design was once again working as it should.

Best regards.

**Comment by louisreingold** [comment]
Email support@breakdance.com with login details for a site that looks right on 1.2.1 but not 1.3.1 and we'll take a look.

**Comment by ivansrbic** [comment]
Done.
