### ISSUE TITLE
BasicSlider - Needs to be logged as admin

### ISSUE THREAD

**Issue by Anticosti** [soflyy/breakdance-bugs#892]
**What version of Breakdance are you using?**

Version 1.4.0-rc.1

**What browser are you using?**

Firefox

**What operating system are you using?**

macOS

**Reproduction  Steps**

01. Create a BasicSlider (3 images)
In my case I use it for my Home Page.

02. Visit your HomePage as admin (first two images): You will have your BasicSlider working fine.

03. Visit your HomePage as a visitor (last image): The navigation(s) arrows will display but won't work at frontend. The Autoplay settings is not working. The Pagination Type is not showing at frontend.

![Screen Shot 2023-07-11 at 01 30 21](https://github.com/soflyy/breakdance-bugs/assets/5446224/06ba2426-94fb-4ec1-9894-4d19fb346ab4)
![Screen Shot 2023-07-11 at 01 31 14](https://github.com/soflyy/breakdance-bugs/assets/5446224/a293c338-fcdb-4564-9650-d7bec286255a)
![Screen Shot 2023-07-11 at 01 31 34](https://github.com/soflyy/breakdance-bugs/assets/5446224/9ca0dec9-573a-4edc-8f97-3195d8d5d357)

**Comment by a-dubiel** [comment]
Are you using any third party plugins? If so, try to disabling them and test again.

**Comment by Anticosti** [comment]
Just found out that I have a snippet conflicting with Motion.Page plugin.

The snippet:
`add_action("breakdance_register_template_types_and_conditions", function () {
    if (function_exists("wpm_get_installed_languages")) {
        $lang_list = wpm_get_installed_languages();
        \Breakdance\ConditionsAPI\register([
            "supports" => ["element_display", "templating"],
            "slug" => "WPMultilang-condition", // MUST BE UNIQUE
            "label" => "Locale",
            "category" => "WPMultilang",
            "operands" => ["equals", "not equals"],
 
            "values" => function () use ($lang_list) {
                return [
                    [
                        "label" => "Language",
                        "items" => array_map(function ($lang_list) {
                            return [
                                "text" => $lang_list,
                                "value" => $lang_list,
                            ];
                        }, $lang_list),
                    ],
                ];
            },
 
            "allowMultiselect" => false,
 
            "callback" => function (string $operand, $value) {
                $myVal = get_locale();
 
                if ($operand === "equals") {
                    return $myVal === $value;
                }
 
                if ($operand === "not equals") {
                    return $myVal !== $value;
                }
 
                return false;
            },
        ]);
    }
});`

If I desactivate this snippet and Motion.Page, then the BasicSlider works as expected.

**Comment by louisreingold** [comment]
I recommend contacting the motion.page team.
