### ISSUE TITLE
Using an SVG image in an image element causes an error

### ISSUE THREAD

**Issue by winkcreative** [soflyy/breakdance-bugs#894]
**What version of Breakdance are you using?**

1.3.1

**What browser are you using?**

Firefox

**What operating system are you using?**

macOS

**Reproduction  Steps**
Placing an svg file in an image element causes an "internal server error" - Undefined array key "sizes". I use svg files for the site logo as they can be scaled  easily.

**Reproduction Video**

<img width="1480" alt="Screenshot 2023-07-12 at 4 02 27 pm" src="https://github.com/soflyy/breakdance-bugs/assets/63597000/a064a1fc-b9b6-4cb0-b07c-45d53c7bcc35">

**Comment by a-dubiel** [comment]
Did you set SVG support on in admin Settings?

**Comment by winkcreative** [comment]
Yes I did thanks


From: Andrzej Dubiel ***@***.***>
Date: Wednesday, 12 July 2023 at 4:43 pm
To: soflyy/breakdance-bugs ***@***.***>
Cc: Will Patterson ***@***.***>, Author ***@***.***>
Subject: Re: [soflyy/breakdance-bugs] Using an SVG image in an image element causes an error (Issue #894)

Did you set SVG support on in admin Settings?

**Comment by a-dubiel** [comment]
So it did
