### ISSUE TITLE
Honey Pot cancels out the page from loading content

### ISSUE THREAD

**Issue by theperfectwill** [soflyy/breakdance-bugs#897]
**What version of Breakdance are you using?**

Breakdance 1.4.1 RC 1

**What browser are you using?**

Brave

**What operating system are you using?**

Mac

**Reproduction  Steps**

Screencast: https://take.ms/FHcez

Install a form, enable Honey Pot, save, then load the page on the frontend.

It took me awhile to find this out, which I only noticed in the latest BETA. 

So I ask you to try and see. My page was blank for awhile and I had been troubleshooting to see what the issue was. But now I've found that when Honey Pot is enable the frontend of the page doesn't render anything in that section or page.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
