### ISSUE TITLE
WP GridBuilder facets inserted in popups can no longer be clicked

### ISSUE THREAD

**Issue by lalucioledigitale** [soflyy/breakdance-bugs#899]
Version of Breakdance: v1.4 and 1.4.1 RC1
Browsers: Chrome, Safari, Firefox
Operating system: MacOS

Version 1.4.1 RC1 fixed the animation problem on popups, but WP GriBuilder facets inserted in popups no longer work with version 1.4 and 1.4.1 RC1. They are displayed but can no longer be clicked.

**Comment by a-dubiel** [comment]
What kind of trigger events do you have on your popups?

**Comment by lalucioledigitale** [comment]
Thanks for your answer. I have one trigger, it's a button for open the popup with an animation slideup.

**Comment by a-dubiel** [comment]
I was able to reproduce this. We are working on fixing this. Thanks so much for your report.

**Comment by lalucioledigitale** [comment]
Thank-you for your prompt response ! 😊

**Comment by louisreingold** [comment]
Thanks for the report. We've addressed this in Breakdance 1.4.2 RC 1. The same fixes are also available in Breakdance 1.5 Beta 1.
