### ISSUE TITLE
Column width not updating on responsive mode

### ISSUE THREAD

**Issue by jackstracey** [soflyy/breakdance-bugs#9]
**CLEARLY and CONCISELY Describe the bug**
When adding columns to a section to create a header, on mobile I want to have the logo and menu icon to be inline with each other. Using responsive view, and selecting the column, I set size to 50%, it doesn't change. 
In the CSS Editor I can set:
width: 50%important;
and it does change. I feel as though theres something else controlling the 100% width. 
**To Reproduce**
1. Create a new header template
2. Add a 2 wide column
![Screenshot 2022-06-23 at 10 45 49](https://user-images.githubusercontent.com/9158589/175270162-e9ea0732-f34a-4cac-be2c-a6d145ff38c1.png)
4. add elements that you need to use
5. Enter responsive mode for tablet landscape
![Screenshot 2022-06-23 at 10 46 53](https://user-images.githubusercontent.com/9158589/175270381-0aee5aea-0530-4eef-a7c1-8a659484074e.png)
7. select a column, size and set width to 50%
8. Nothing happens.

**Comment by louisreingold** [comment]
Column widths on mobile are controlled at Columns > Layout.

Here's a quick video explaining how to do it: https://www.loom.com/share/bc22142e261547f9aa4fb607a27d26f5
