### ISSUE TITLE
Header search form

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#90]
Hi, it seems impossible to remove the .screen-reader-text label from the search form in the header in the settings.

![Screenshot (38)](https://user-images.githubusercontent.com/10600315/180417364-52c3580b-30ab-4172-b378-3c905c5e4f04.png)

**Comment by louisreingold** [comment]
I can't reproduce this. Do you have any browser-specific settings or extensions enabled that would make .screen-reader-text always appear? If you email support@breakdance.com with the page this takes place on, we'll take a look.
