### ISSUE TITLE
Nested Repeater

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#900]
Hello!

I'm trying to create a nested repeater field.

So I have this structure:
- ACF Group
  -  ACF Repeater 1
      -  ACF Repeater 2

In my template I create a repeater block and inside of the global I put another repeater block. And puff. Breakdance keeps loading 4ever and ever and nothing works.

Is this a bug or maybe a missing feature?

What i'm trying to archive:
<img width="1198" alt="Screenshot 2023-07-15 at 15 32 40" src="https://github.com/soflyy/breakdance-bugs/assets/122744933/e715ff70-646b-43ad-94d3-6ab1809761f4">

My ACF structure:
<img width="1120" alt="Screenshot 2023-07-15 at 15 34 47" src="https://github.com/soflyy/breakdance-bugs/assets/122744933/74146c1b-7cd5-4f58-ba58-f6a40d117691">

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
