### ISSUE TITLE
Images not appearing on ACF Repeater

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#902]
I build a repeater where the block is a dynamic image by ACF Repeater field. It appears in the Breakdance interface, but not on the front-end.

Breakdance Interface:
<img width="288" alt="Screenshot 2023-07-17 at 00 30 35" src="https://github.com/soflyy/breakdance-bugs/assets/122744933/ed5e185b-177c-4f16-815f-3ed3c7ad4899">

Front-end:
<img width="382" alt="Screenshot 2023-07-17 at 00 30 38" src="https://github.com/soflyy/breakdance-bugs/assets/122744933/7bc3e09b-8e75-48af-b823-a83fbb459088">

I'm using 1.4 Beta 3.

**Comment by a-dubiel** [comment]
Can you show me the structure of your ACF repeater?

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. Unfortunately, I cannot reproduce this. Feel free to e-mail support@breakdance.com and we will take a closer look. Make sure to provide working URL to your website and login credentials.
