### ISSUE TITLE
Custom links/buttons for navigating a slider is not working as indented.

### ISSUE THREAD

**Issue by StefanPavlov23** [soflyy/breakdance-bugs#903]
When you try to control the slider movement with a custom button outside of the slider/post loop looper it's not working as expected. It's just scrolling back to the top as the link is pointing to "#"

**What version of Breakdance are you using?**

v1.4

**What browser are you using?**

Brave

**What operating system are you using?**

Windows

**Reproduction  Steps**

Create a slider. Add two buttons or icons or element that has the option to become a link. Set it up to control the slider/post loop. Try to change the slides with the custom buttoms.

**Reproduction Video**

 Here is a video about the problem: https://www.loom.com/share/296d1f58af8d4ad5afc4f51136986637

PS: I had a website that is on 1.2.1 beta and that functionality is working without a problem.

**Comment by a-dubiel** [comment]
Hey @StefanPavlov23 thanks for your report. I was able to reproduce this and passed this to our internal team.

**Comment by a-dubiel** [comment]
Hey @StefanPavlov23 I cannot reproduce this. I thought I could but it works as expected in 1.4.1. See https://www.loom.com/share/e8c10205fadc4fe59322ab34f4bb6812

Please email support@breakdance.com and we will take a look.
