### ISSUE TITLE
Popup wont close in mobile view

### ISSUE THREAD

**Issue by winkcreative** [soflyy/breakdance-bugs#904]
**What version of Breakdance are you using?**

1.4

**What browser are you using?**

Firefox

**What operating system are you using?**

macOS

**Reproduction  Steps**

I have a popup that is triggered on a page by a button. It works fine on desktop but in mobile view the close "X" doesnt close the popup and you have to reload the page to get rid of the popup. I've tried it in and out of wrapper but it still doesnt close.

**Reproduction Video**

**Comment by a-dubiel** [comment]
Hey @winkcreative 1.4 introduced bunch of bugs related to popups. We are working on addressing these bugs.

**Comment by DeivisPau** [comment]
This is not just Firefox and not just mobile. There is a serious issue with the popups not closing randomly.

**Comment by louisreingold** [comment]
We've addressed the popup closing issues in Breakdance 1.4.2 RC 1 (same fixes are available in Breakdance 1.5 Beta 1.)

Thanks for the report!
