### ISSUE TITLE
HTML tag in title for table price element

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#907]
Currently, for the title of the formula in table price, it's not possible to add an html tag to the title, which is currently contained in div, so add this control and set the default tag to h3

**Comment by louisreingold** [comment]
<img width="633" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/6425257/b2bd449f-4975-4938-9842-8a6308baa9b5">

Just to be clear, you want to set the tag of the Title field?

> title of the formula

Formula? Please elaborate.

**Comment by louisreingold** [comment]
If it isn't the Title field that you want to set the tag of, please give me the CSS selector of the element you want to set the tag of.

**Comment by louisreingold** [comment]
This is what you want, yes? https://www.loom.com/share/cc83558e58bc485aaa8743a72d17db1e

**Comment by rodolphebertozzo** [comment]
yes @louisreingold, you are a genius ;)

**Comment by rodolphebertozzo** [comment]
By the way @louisreingold, why is the badge content encapsulated by a <span> tag, why not include it directly in the bde-pricing-table__price-area--badge class? 
![image](https://github.com/soflyy/breakdance-bugs/assets/56270626/ccab2178-fbbf-4832-9ca5-c07a3b4c55dc)

**Comment by louisreingold** [comment]
Because Accent > Typography > Effects wouldn't work without the span. Set a gradient background for that text and then look at the generated CSS if you want to see why.
