### ISSUE TITLE
Multi-step form - button text

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#909]
Offer the possibility of customizing the label of next-step and previous-step buttons; the user only has control over the current style.

**Comment by a-dubiel** [comment]
Unless I am missing something this is already available. 

<img width="274" alt="Screenshot 2023-07-31 at 13 20 52" src="https://github.com/soflyy/breakdance-bugs/assets/669243/df94bde8-84b3-44e3-96eb-700213a78898">

**Comment by rodolphebertozzo** [comment]
I apologize for the inconvenience and the unnecessary opening of this number. Thank you very much!
