### ISSUE TITLE
Can't translate string - Mini Cart element

### ISSUE THREAD

**Issue by FlorentNL** [soflyy/breakdance-bugs#911]
**What version of Breakdance are you using?**
1.4

**What browser are you using?**
Firefox 115.0.3 (64-bit)

**What operating system are you using?**
Windows

It seems that we can't edit the "Continue shopping" string in the Mini Cart element. I apologize in advance if I'm mistaken.

Best regards

**Comment by a-dubiel** [comment]
<img width="402" alt="Screenshot 2023-07-31 at 13 19 12" src="https://github.com/soflyy/breakdance-bugs/assets/669243/b52fb590-93a9-4dab-a5af-a45e2a4de544">

Hi @FlorentNL I just checked the element code and looks like this string is translatable.

**Comment by FlorentNL** [comment]
Hi @a-dubiel,

Thanks for the quick reply. Should't I find the edit option in this menu?

![Screenshot 2023-07-31 at 13-30-02 Breakdance Menu principal](https://github.com/soflyy/breakdance-bugs/assets/141027306/92635083-7540-4007-a871-72f7847b2fd8)

**Comment by a-dubiel** [comment]
Translating and editing strings are two different actions. What you originally requested (translating) is available. Unfortunately, we are not planning on providing ability to edit "Continue shopping" at this moment.

**Comment by FlorentNL** [comment]
@a-dubiel @louisreingold 

I'd be curious to understand the reasoning behind that decision, especially when it seems so easy to implement and the fact that we can find similar edit options all over the builder. 

This edit option would prevent non-English-speaking users from installing a plugin for a single string to translate. In my personal case, as I'm not willing to install a plugin for a single translation, I'll have to remove the 'Continue Shopping' link even though I find it quite practical.

With Divi, I wouldn't even have attempted to make such a request, but with you guys, I have faith and that's precisely why I chose to purchase your plugin.

Best regards
