### ISSUE TITLE
ACF content is not showing on your Blog page

### ISSUE THREAD

**Issue by orhanbilikvar** [soflyy/breakdance-bugs#912]
BD 1.4, Chrome, Windows

![a01](https://github.com/soflyy/breakdance-bugs/assets/48365764/c21d4f21-d3e0-40c1-bff2-5b51754d4940)

![a02](https://github.com/soflyy/breakdance-bugs/assets/48365764/89122141-c90b-41ed-af4c-9ea5046611f5)

**Comment by orhanbilikvar** [comment]
It appears when I do it with code.
(GT)

**Comment by louisreingold** [comment]
If you'd like technical support from the Breakdance team, email support@breakdance.com and we'd be happy to help.

I was not able to reproduce this based on your screenshots. If you'd like to something you're 100% sure is a bug, we need exact steps to reproduce.
