### ISSUE TITLE
ALT tag is not automatically updated from the media library

### ISSUE THREAD

**Issue by hoehl-ondema** [soflyy/breakdance-bugs#913]
Version 1.4.0
Browser: Chrome, Chrome (privat mode) 
macOS

 I think there is a big problem with the image gallery and all the images when you change the alt text in the media library.
 The alt tag is not automatically updated.

This is a big problem for SEO. And it is a lot of work for e.g. 20 images in a gallery. 
If I want or need to change the alt tag, 
I have to select the image in Breakdance,
 then open the media library, 
then reselect the image
 and then save the page. 

in the image gallery there are even more steps until the alt tag is updated. 
1. select the image via pen icon
2. click on CHOOSE and wait until the media lib is loading 
3. find the image in the media lib (finding the image can be very frustrating)
4. click image
5. click choose
6. click to close preview 
repeat each step per image.  
That is a lot of work.

I hope I am doing something wrong

**Comment by louisreingold** [comment]
We're tracking this feature request at https://breakdance.canny.io/features/p/alt-image-description-default-from-media-library
