### ISSUE TITLE
Mini Cart element - Font size for the value attribute isn't working

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#914]
**What version of Breakdance are you using?**

latest 1.4

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction  Steps**
The setting in the UI doesn't change the font-size.

<img width="893" alt="SCR-20230803-kmhb" src="https://github.com/soflyy/breakdance-bugs/assets/7188497/0ec0d710-232f-4ba2-b75d-ed142dc5c2b9">

**Comment by breakdancemoderator** [comment]
Thank you for the report; this has been fixed in Breakdance 2.0 Beta 3.
