### ISSUE TITLE
Popup Animations Don't Work in 1.4.1-rc.2 

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#916]
**What version of Breakdance are you using?**

1.4.1-rc.2 

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction  Steps**

Create a popup with an entrance and exit animation.  They don't work on the frontend.  This worked in 1.4.1-rc.1 but not in 1.4.1-rc.2.  I suspect it has something to do with the rollback to the previous iteration of the popup element.

**Comment by lalucioledigitale** [comment]
I confirm, same on me.

**Comment by louisreingold** [comment]
Thanks for the report. This is addressed in 1.4.2 RC 1 and 1.5 Beta 1.
