### ISSUE TITLE
Edit only access is a complete mess

### ISSUE THREAD

**Issue by digitalsmithy** [soflyy/breakdance-bugs#917]
BD 1.4rc1
WP6.2.2
Mac osx 13.4.1
Chrome

Login as editor. Go to page. Click 'Use default editor'. This should not be possible if editor has no BD edit access. You simply should not be allowed to edit BD pages - in BD or WP.
Still as editor. Click edit in BD. Yes - you get warning about permissions, but it's so ugly and you're now in BD builder. Now there's no way to leave the page except the browser Back button. Very poor UX.
You can enter preferences, and add breakpoints. No - they won't save - but the window shouldn't appear at all.
Choose Selector, and you can add as many as you like. You can't edit or save them, but again it's not a good UX.
If the user doesn't have permission to edit in BD, then the BD option should not appear in the admin column or the editor. And if the page is built in BD, there should either be no edit option at all, or certainly no 'use default editor' option.

**Comment by louisreingold** [comment]
This is addressed in Breakdance 1.6. Thanks for the report!
