### ISSUE TITLE
Richtext Tags are removed

### ISSUE THREAD

**Issue by flowww-dev** [soflyy/breakdance-bugs#919]
When adding some Tags like <sup></sup> in HTML Mode of the Richtext Editor and switch back to WYSIWYG Mode the Tags are removed.

**Comment by dreadedhamish** [comment]
I just found this also (1.5.0-1) - 
pasting a very simple html table into the HTML view:
if clicking text view - html tags are stripped.
if immediately closing the module - html is preserved. if reopened in text view - tags are stripped.

**Comment by louisreingold** [comment]
Tracking at https://breakdance.canny.io/admin/feedback/element-requests/p/full-rich-text-wysiwyg-element-like-tinymce
