### ISSUE TITLE
Checkout Builder - Checkout Coupon Form element - submitting coupon submits the whole form

### ISSUE THREAD

**Issue by jeffreyvandervet** [soflyy/breakdance-bugs#920]
**What version of Breakdance are you using?**
1.4.1-rc.1

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction  Steps**
Woocommerce Checkout Builder coupon not working. When submitting a coupon it submits the whole form instead of the coupon form only.

**Comment by jeffreyvandervet** [comment]
> The Checkout Coupon Form should be used outside the Checkout Builder element. Both are forms, so you technically can't have one form inside another.

True, but than you shouldn't be able to add it to the checkout builder. Other option is to make it work with Ajax.

**Comment by mchhyp** [comment]
@breakdancemoderator I don't know why is this removed as a bug and closed. This is still ongoing issue as even your support confirmed:
"This is an issue that we are aware of, but we do not have an estimate as to when a fix will be available.
As an immediate workaround, please see if moving the Checkout Form element outside of the Checkout Builder works for you."
Please mark it as open.

**Comment by breakdancemoderator** [comment]
The Checkout Coupon Form must be used outside the Checkout Builder element.

**Comment by jeffreyvandervet** [comment]
Maybe you can change it to make it not possible to add in the Checkout Builder? I think it's really confusing that you can place it there. Also design wise it's not fitable enough if you can't add it there.
