### ISSUE TITLE
Element Studio Preset Conditions

### ISSUE THREAD

**Issue by flowww-dev** [soflyy/breakdance-bugs#921]
If you add a custom preset and add some fields with conditions (for example textfield shows only when dropdown is set to 'my_value'), the conditions won't work.

**Comment by Hakira-Shymuy** [comment]
> If you add a custom preset and add some fields with conditions (for example textfield shows only when dropdown is set to 'my_value'), the conditions won't work.

@flowww-dev when you edit a "element preset" ? like to make changes to a preset that you saved?

**Comment by louisreingold** [comment]
Use %%CURRENTPATH%% in the condition

<img width="1096" alt="image" src="https://github.com/soflyy/breakdance-bugs/assets/6425257/c063dae2-8868-4aeb-8c70-29b2965a8ad5">

Check out the `posts-list-design.php` preset for an example.

**Comment by flowww-dev** [comment]
Ok, great, I'll check it ;-)
