### ISSUE TITLE
Global settings - Body letter spacing applied to headings

### ISSUE THREAD

**Issue by FlorentNL** [soflyy/breakdance-bugs#922]
**What version of Breakdance are you using?**

Version 1.4.1-rc.2

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**Reproduction  Steps**

I've applied letter spacing through Global Settings / Typography / Advanced / Body / Advanced. The problem is, the letter spacing also gets applied to headings via the following code:
`.breakdance {
	letter-spacing: -0.02em;
}`

Shouldn't my settings apply to .body instead of .breakdance?

Best regards

**Comment by louisreingold** [comment]
Intended behavior. Body applies to everything, headings apply to just headings.
