### ISSUE TITLE
Sticky Header

### ISSUE THREAD

**Issue by codingharz** [soflyy/breakdance-bugs#926]
**What version of Breakdance are you using?**
BD 1.4.1

**What browser are you using?**
Chrome

**What operating system are you using**?
Windows 10

**Reproduction Steps**
The sticky effect in the header is bugged. As soon as you activate sticky the background becomes transparent and also the disable on certain devices does not work

*The transparent background was a wrong setting for me

To reproduce please watch the video

**Reproduction Video**

https://www.loom.com/share/4cdc6cbb8cb84ab9a6aa6a167249aebf?sid=1f0a3263-2fd8-455d-9060-c4cec4955df6

**Comment by louisreingold** [comment]
I'm not able to reproduce this and your header has all sorts of settings that aren't shown in the video.

Please email support@breakdance.com and they'd be happy to help you.
