### ISSUE TITLE
ACF Options Page integration doesn't work with ACF 6.2's new "Crate Options Page With UI" feature

### ISSUE THREAD

**Issue by gyurmey2** [soflyy/breakdance-bugs#928]
ACF Options Page integration doesn't work with a [new feature](https://www.advancedcustomfields.com/blog/acf-6-2-0-released/#options-pages-ui).

**What version of Breakdance are you using?**

v1.5.0 beta 1

**Comment by breakdancemoderator** [comment]
Thanks for the report. While we can't reproduce it, dynamic data changes were made in Breakdance 2.0 Beta 1 that ensures all ACF fields will appear in the dynamic data chooser regardless of their settings.
