### ISSUE TITLE
Input field disappears when I select "Custom" values in Advanced settings.

### ISSUE THREAD

**Issue by udoro** [soflyy/breakdance-bugs#93]
Input field disappears when I select "Custom" values under Advanced > Wrapper > Spacing > padding and margin.
![image](https://user-images.githubusercontent.com/22454125/180575876-dfc26ec4-cf99-46fc-8ffd-0e82e14c6a3b.png)

**Comment by louisreingold** [comment]
This is solved in beta 4.
