### ISSUE TITLE
Editors in client mode cannot change slideshow images for section background

### ISSUE THREAD

**Issue by cabbagepancakes** [soflyy/breakdance-bugs#930]
Version 1.4.1 
Chrome
Windows

**Reproduction  Steps**
Create an editor user with Edit content access.
Create a section with a background slideshow of images. log out.
Login as editor.
Click on the section with the background slideshow.

**Comment by louisreingold** [comment]
After the client mode polish implemented in Breakdance 1.6 clients can no longer edit any aspect of the design. We recommend using ACF or similar for this purpose.
