### ISSUE TITLE
Gallery / Lightboxes - If using multiple option with filters enabled, lightbox only works on all and first gallery

### ISSUE THREAD

**Issue by PureFormCreative** [soflyy/breakdance-bugs#931]
When using the "Multiple" tab with "Filter" ON, in the Gallery. 

The "Light Box" only works on the first two buttons. The "All" and what ever the first gallery position is. 

So if you have made 3 additional galleries and you adjust the order of what is in 3rd, place and put it as the first button after the "ALL" It will open but the rest will not activate the "Light Box"

**What version of Breakdance are you using?**
v1.4.1

**What browser are you using?**
ARC

**What operating system are you using?**
OSX- 13.4.1

Example Image:
<img width="1173" alt="Screenshot 2023-08-14 at 4 02 37 PM" src="https://github.com/soflyy/breakdance-bugs/assets/142337166/8ee32228-06d2-44e1-ad8d-f8dfece287bd">

**Comment by louisreingold** [comment]
Can't reproduce using provided steps.

Here is me testing: https://www.loom.com/share/5322ca6bc02c4df5bda232b62dd9ee89

If you need technical support, email support@breakdance.com and we are always happy to help!
