### ISSUE TITLE
Border color control does not work in "Table price".

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#932]
When I want to change the border color of a price table, the color is not applied, so on the DOM I always have the base color printed, not the one I want.

**Comment by Hakira-Shymuy** [comment]
@rodolphebertozzo cant recreate this one

on the pricing element right? i did set a color on global settings  / brand to purple
if i change the color on pricing table / accent / border, it changes the color for the border
