### ISSUE TITLE
Rich Text: Automatically adds a paragraph to the list item

### ISSUE THREAD

**Issue by gyurmey2** [soflyy/breakdance-bugs#933]
![li](https://github.com/soflyy/breakdance-bugs/assets/113413673/7053b84f-7f59-4335-aea3-cc3bc98b1e80)

**What version of Breakdance are you using?**

v1.5.0 beta 1

**Comment by louisreingold** [comment]
Tracking at https://breakdance.canny.io/admin/feedback/element-requests/p/full-rich-text-wysiwyg-element-like-tinymce?boards=element-requests&sort=top
