### ISSUE TITLE
Setting Section Text Color Overrides Button Text Color

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#939]
When setting the text color of a section, it overrides the text color of a button in that section.  This is because the CSS that is output is something like this:

```
breakdance .bde-section-45-110 * {
    color: #FFF;
}
```
The CSS that is output needs to exclude button text colors.

**Comment by louisreingold** [comment]
Setting text colors on wrappers has been deprecated in Breakdance 1.6, so this won't be an issue going forward.
