### ISSUE TITLE
Multiple ACF Repeaters don't work

### ISSUE THREAD

**Issue by LambMediaGroup** [soflyy/breakdance-bugs#942]
I have 3 repeater elements using 3 different global blocks to create 3 sliders on the same page. The first one works as expected the second and third ones don't show anything. I get the arrows but no content and no pagination.

Steps to reproduce

Create a page called test
Create an ACF field group and apply it to the test page.
Set up 2 repeater fields
Call the first one Group1 and set up the following repeating fields inside it
  Title1
  Description1
  Link1
call the second one group2 and set up the following repeating fields inside it
  Title2
  Description2
  Link2
create a global block in breakdance called slider1 and add the ACF fields Title1 as text, Description1 as text and Link1 as the url of a button
create another global block in breakdance called slider2 and add the ACF fields Title2 as text, Description2 as text and Link2 as the url of a button
edit the test page in the WordPress editor and add a couple of dummy items to each of the repeater fields
edit the test page in breakdance and add a repeater element using the slider1 global block and the ACF field Group1
add another repeater element using the slider2 global block and the ACF field Group2
This shows correctly in the breakdance  editor but when viewed in the frontend only the first repeater works correctly.

**Comment by breakdancemoderator** [comment]
Thanks for the report. This is solved in Breakdance 2.0 Beta 1.
