### ISSUE TITLE
Disabling default Woo styles shouldn't result in "Call to undefined function Breakdance\WooCommerce\getActionsForCatalog()"

### ISSUE THREAD

**Issue by medianotions** [soflyy/breakdance-bugs#944]
Dear Breakdance Team,

I've got a fresh WordPress with WooCommerce and Breakdance (latest versions) and try to add the element Shop Page to the Shop Template. This is what happens:

<img width="1401" alt="Breakdance  Shop Page   All Product Archives 2023-09-07 at 5 18 37 PM" src="https://github.com/soflyy/breakdance-bugs/assets/124350976/7e4f1c16-ddc5-49d1-8e13-35c16219eacc">

Why is there a Call to undefined function Breakdance\WooCommerce\getActionsForCatalog()?

Thank you,
Bogdan

**Comment by medianotions** [comment]
I found the cause:

Breakdance WooCommerce Styles in the settings where disabled.

I think it would be reasonable to catch this and prompt a nice notice. 🙂

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
