### ISSUE TITLE
Drag and Drop in Structure panel broken in Safari / BD 1.5

### ISSUE THREAD

**Issue by Nicscott01** [soflyy/breakdance-bugs#945]
Using Safari Version 16.6 (17615.3.12.11.3, 17615) and Breakdance 1.5, the drag and drop within the Structure View stopped working. It DOES work in Chrome.

Create any elements on the page and then open the Structure view. Then try to drag/drop. It just won't go. The hand will grab, but the element won't move.

**Comment by medianotions** [comment]
I can confirm this bug, drag & drop in Safari stopped working.

**Comment by louisreingold** [comment]
@Nicscott01 @medianotions does this still happen in the latest version of Safari?

**Comment by medianotions** [comment]
Hi,

no in the latest version of Safari this problem is gone. 🙂

Best,
Bogdan
