### ISSUE TITLE
Value for Conditional Field "Current Date (WordPress)" can't be set

### ISSUE THREAD

**Issue by erik-cc** [soflyy/breakdance-bugs#946]
**Reproduce the bug:**
1. Select an element
2. Go to the "Settings" tab > Conditions > Edit Conditions
3. Create a new condition
4. Choose condition "Current Date (WordPress)"
5. The value input is not clickable

![grafik](https://github.com/soflyy/breakdance-bugs/assets/84032009/df4fada3-209e-4377-bca8-5f016742bea9)

**Breakdance version:** 1.5.0
**WordPress version:** 6.3.1 
**Browser:** Firefox and Chrome
**OS:** MacOS Ventura 13.2.1

**Comment by djrwp** [comment]
Yes I'm having the same issue.

BD 1.6.1
WP 6.4
<img width="783" alt="Screenshot 2023-11-21 at 15 41 32" src="https://github.com/soflyy/breakdance-bugs/assets/84224815/868cadf5-2d1d-4f2d-b7af-8dee34d4b3e0">

**Comment by djrwp** [comment]
Just tested on a fresh BD install with no other plugins active and still doesn't work unfortunately.

**Comment by nick-s5** [comment]
Also have this bug, has been around for a long time. I remember having it months ago and did not have a fix.

**Comment by louisreingold** [comment]
Thanks for the reports. This is solved in Breakdance 1.7 Beta 2: https://breakdance.com/breakdance-1-7-beta-2/
