### ISSUE TITLE
Product CPT cannot be used with Breakdance if WooCommerce isn't be installed

### ISSUE THREAD

**Issue by flowww-dev** [soflyy/breakdance-bugs#948]
BD cannot be used (is not listed in the bd settings) if the posttype has the slug "product" but woocommerce isn't used.

For example:
1. Add a new CPT with the slug 'product'.
2. Enable public and public querable and so on (all what BD needs).
3. Don't install WooCommerce / deactivate WooCommerce
4. Go to BD Settings posttypes
5. The Product CPT isn't listed

**Comment by louisreingold** [comment]
`product` is reserved by WooCommerce. Another slug should be used for your post type. Creating Breakdance content for a post type with slug of WooCommerce and then later installing WooCommerce on the same site would cause problems with Breakdance's Woo integration.
