### ISSUE TITLE
Add More Gutenberg Stuff To Bloat Eliminator?

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#955]
I'm on 1.5.  There is a file being enqueued...

`https://www.mysite.com/wp-content/plugins/breakdance/plugin/gutenberg/blocks/dist/blocks.style.build.css?ver=1693330229`

It is empty though and there is nothing in it.  Not sure what, if anything, it's used for but shouldn't it be removed if it's empty?

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
