### ISSUE TITLE
Gallery slider with infinite settings also duplicates elements in the Lightbox

### ISSUE THREAD

**Issue by danramzdev** [soflyy/breakdance-bugs#958]
When you create a gallery with a slider and with infinite options, the slider duplicates the elements to have this effect, but it also affects the lightbox since those duplicate elements of the slider are also displayed, in my opinion it should not be the expected operation.

1. Create a page.
2. Add a Gallery:
  - Link: Lightbox
  - Style > Layout > Type: Slider
  - Style > Layout > Slider > Settings > Infinite: Enabled
3. Go to frontend to click image and open lightbox, you will see the duplicate elements.
  
Elements of default Gallery:
![image](https://github.com/soflyy/breakdance-bugs/assets/32352812/eb5aa982-1cbd-4af8-9253-7b804f71bd77)

Lightbox duplicate elements (You can see duplicate thumbnails):
![image](https://github.com/soflyy/breakdance-bugs/assets/32352812/7f1d21f9-dfbb-43ff-b3f9-1b28c0dca007)

 - Breakdance version: 1.5.0
 - Browser & OS: Microsoft Edge & macOS Ventura 13.6
 - No errors in backend and no errors in frontend console

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
