### ISSUE TITLE
Control Slider Action not working in BD 1.6 beta

### ISSUE THREAD

**Issue by ninjaseo** [soflyy/breakdance-bugs#959]
Tested in beta 1.6 and confirmed by other user in this thread:

https://www.facebook.com/groups/breakdanceofficial/posts/6656634117705160/?comment_id=6672001856168386&notif_id=1696890194984722&notif_t=group_comment

It is no longer possible to control sliders in beta 1.6, using a button or link, it does not do anything.

![image](https://github.com/soflyy/breakdance-bugs/assets/14320586/2ba7c8ba-c647-44b4-91ee-d3a597d57626)

Reverting to BD 1.5 and everything works, upgrading to 1.6 beta and the action breaks so the buttons or links do not affect the slides.

**Comment by louisreingold** [comment]
Fixed in https://breakdance.com/breakdance-1-6-rc-1/

Thanks for the report!

**Comment by codingharz** [comment]
The error also exists in version 1.6.1 and in the 1.7 beta. 
For me, the error occurs in combination with the repeater field

**Comment by codingharz** [comment]
@louisreingold When can a fix be expected here?

**Comment by louisreingold** [comment]
@codingharz open a new issue with exact steps to reproduce the problem.
