### ISSUE TITLE
ACF custom fields stop working after update from 1.4.1 to any more recent version

### ISSUE THREAD

**Issue by BrockwayProd** [soflyy/breakdance-bugs#960]
You MUST include a clear description of the bug and EXACT steps to reproduce the bug or IT WILL BE CLOSED:

1. Have a WooCommerce archive page model
2. Have 1.4.1 version or earlier of Breakdance
3. Set some fields (image, background image or text) to pull data from an ACF field
4. Check that data is indeed pulled correctly to front end
5. Update to any newer version
6. Check the WooCommerce archive page again, data is nowblank on frontend

57s video showing the issue : https://d.pr/v/jIcdux

You should also include the following information:
 - Breakdance version : 1.4.1
 - Browser & OS : Any
 - PHP 7.4 / WP 6.3.1

**Comment by BrockwayProd** [comment]
@a-dubiel @louisreingold looks like you closed this one : https://github.com/soflyy/breakdance-bugs/issues/819
Withotu fixing the issue because user was not cooperating, but bug is still there and i am happy to do anything in order to help you resolve this bug.

**Comment by louisreingold** [comment]
Try https://breakdance.com/breakdance-1-6-rc-1/ and let me know if you can use your term fields properly.

**Comment by BrockwayProd** [comment]
Hi, i just applied the RC version, and indeed this time all elements based on ACF fields keeped working just fine.
Thanks for the fix.
