### ISSUE TITLE
License dont work

### ISSUE THREAD

**Issue by ushopkenneth** [soflyy/breakdance-bugs#962]
Hello,

I have an issue with my License
It dont work!

1. I have moved to a different host. Because I get a fault with memory! Or is it in the database!?
2. As I have another fault to I uninstalled Brakedance 1.5 Then I installed it again.
3. When I look for license it not working 
![234255057-3900edf1-d6be-4417-ab98-078fddbc1460](https://github.com/soflyy/breakdance-bugs/assets/147681571/d9b00c2b-9c61-469f-844f-538b1152e3a1)

Im using Chrome and Win10

**Comment by louisreingold** [comment]
Please contact support@breakdance.com for technical support. Our team is always happy to help you. :)
