### ISSUE TITLE
BrakeDance dont work!

### ISSUE THREAD

**Issue by ushopkenneth** [soflyy/breakdance-bugs#963]
I get a fault when im trying to edit in BreakDance

look in pictures!
![Skärmklipp](https://github.com/soflyy/breakdance-bugs/assets/147681571/bbd25718-84af-4d78-b819-8ef782b2754b)
![Skärmklipp1](https://github.com/soflyy/breakdance-bugs/assets/147681571/5d2e9890-a3ff-45ea-a5ea-35dcddc6f7e0)
![Skärmklipp2](https://github.com/soflyy/breakdance-bugs/assets/147681571/fbf36cd0-a7c7-4656-b6df-77ad61cefd6c)
![Skärmklipp3](https://github.com/soflyy/breakdance-bugs/assets/147681571/64f0f9ab-906f-4395-81be-fc5fe0295e77)
![Skärmklipp4](https://github.com/soflyy/breakdance-bugs/assets/147681571/f82aab7f-7bb9-473b-9ad7-c0349ad8f09b)

<html>
<body>

Version | 6.3.1
-- | --
Webbplatsspråk | sv_SE
Användarspråk | sv_SE
Tidszon | +02:00
Startsidans URL | https://ushop.se
Webbplatsens URL | https://ushop.se
Permalänkstruktur | /%postname%/
Använder denna webbplats HTTPS? | Ja
Är detta en nätverksinstallation (multisite)? | Nej
Kan vem som helst registrera sig på denna webbplats? | Nej
Ber webbplatsen sökmotorer att inte indexera den? | Nej
Standardinställning för kommentarer | Öppet
Typ av driftsmiljö | production

</body>
</html>

<html>
<body>

Namn | Breakdance Zero Theme (breakdance-zero)
-- | --
Version | 1.0.0
Författare | Breakdance Builder
Författarens webbplats | https://breakdance.com/
Huvudtema | Inget
Temafunktioner | core-block-patterns, menus, widgets-block-editor, post-thumbnails, title-tag, woocommerce, wc-product-gallery-zoom, wc-product-gallery-slider, wc-product-gallery-lightbox
Plats för temats filkatalog | /www/xxxxxx/public/wp-content/plugins/breakdance/plugin/themeless/themes/breakdance-zero
Automatiska uppdateringar | Inaktiverat

</body>
</html>

<html>
<body>

Serverarkitektur | Linux 5.4.0-1113-gcp x86_64
-- | --
Webbserver | nginx/1.24.0
PHP-version | 8.0.30 (Stöder 64-bitsvärden)
PHP SAPI | fpm-fcgi
Maxvärden för PHP inmatning | 10000
PHP-tidsgräns | 300
PHP-minnesgräns | 256M
Minnesgräns för PHP (endast för adminsidor) | 512M
Maximal inmatningstid | 300
Max filstorlek för filuppladdning | 128M
Största storlek för PHP post | 128M
cURL-version | 7.68.0 OpenSSL/1.1.1f
Är SUHOSIN installerat? | Nej
Är biblioteket Imagick tillgängligt? | Ja
Stöds snygga permalänkar? | Ja
.htaccess-regler | Specialregler har lagts till i din fil .htaccess.
Nuvarande tid | 2023-10-12T03:45:33+00:00

</body>
</html>

<html>
<body>

Utökning | mysqli
-- | --
Serverversion | 10.11.5-MariaDB-1:10.11.5+maria~ubu2004
Klientversion | mysqlnd 8.0.30
Användarnamn för databas | XXXXXX
Databasserver | localhost
Databasens namn | XXXXX
Tabellprefix | XXXXXXX
Databasens teckenuppsättning | utf8mb4
Databaskollationering | utf8mb4_unicode_520_ci
Maximal tillåten paketstorlek | 33554432
Maximalt antal anslutningar | 50

</body>
</html>

<html>
<body>

ABSPATH | /www/xxxx/public/
WP_HOME | Odefinierat
WP_SITEURL | Odefinierat
WP_CONTENT_DIR | /www/xxxxxx/public/wp-content
WP_PLUGIN_DIR | /www/xxxxxxx/public/wp-content/plugins
WP_MEMORY_LIMIT | 256M
WP_MAX_MEMORY_LIMIT | 512M
WP_DEBUG | Inaktiverat
WP_DEBUG_DISPLAY | Aktiverat
WP_DEBUG_LOG | Inaktiverat
SCRIPT_DEBUG | Inaktiverat
WP_CACHE | Inaktiverat
CONCATENATE_SCRIPTS | Odefinierat
COMPRESS_SCRIPTS | Odefinierat
COMPRESS_CSS | Odefinierat
WP_ENVIRONMENT_TYPE | Odefinierat
WP_DEVELOPMENT_MODE | Inaktiverat
DB_CHARSET | utf8
DB_COLLATE

<br class="Apple-interchange-newline">
</body>
</html>

<html>
<body>

Memory Usage information | Current memory WordPress Limit: 256MB    \|   Your usage now: 18MB
-- | --

</body>
</html>

 - Breakdance version 1.5
 - Chrome Win10

**Comment by louisreingold** [comment]
Error says you're out of memory. Increase your memory_limit until you don't run out of memory. Probably, your server or server config is underpowered for the site you're building. Our support team is always happy to help at support@breakdance.com.
