### ISSUE TITLE
Error 500 on Post Loop Builder (PHP 8) adding advanced alternates or static items

### ISSUE THREAD

**Issue by ninjaseo** [soflyy/breakdance-bugs#964]
- Breakdance version: 1.6 RC 1 (also occurred on 1.6 Beta 1)
- PHP version: 8.0 **(the error does not occur on PHP 7.4)**

I receive a 500 error when I try to add alternate or static items on the Post Loop Builder, using PHP 8.0 (it does not happen on 7.4)

(URL masked for privacy below)

### Video demonstrating the problem:
[https://share.cleanshot.com/qF2y6p1D](https://share.cleanshot.com/qF2y6p1D
)

### Error details 
Breakdance\AJAX\BreakdanceAjaxHandlerException: Undefined array key "position" in /home/public_html/wp-content/plugins/breakdance/plugin/ajax/api.php on 113

**Comment by louisreingold** [comment]
Thanks for the report! This will be solved in 1.6 final.
