### ISSUE TITLE
Upload fields not translatable on Forms

### ISSUE THREAD

**Issue by BrockwayProd** [soflyy/breakdance-bugs#966]
Steps to reproduce:
1. Have a site in any other language than English (French in this case)
2. Create a page with a form in it
3. Add an upload field
4. You cant change the wording or even translate it
 
Here a screenshot of  the result: https://d.pr/i/XIxjVG
And here a screenshot in the builder : https://d.pr/i/lORPrq

You should also include the following information:
 - Breakdance version : All
 - Browser & OS : Any

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.

**Comment by BrockwayProd** [comment]
Thanks, but because of tickets like that just behing ignored, and Louis overall behavior i changed builder.
