### ISSUE TITLE
Can't set height and width attributes to SVG Images

### ISSUE THREAD

**Issue by high2306** [soflyy/breakdance-bugs#968]
For example:
1. Create a page
2. Add an image using Image Element
3. Set the width and height of the image
4. Inspect the HTML output - both width and height are empty

Using any other format - PNG, JPG etc, the width are height are set as an attribute, but with SVG the attribute is always empty, even if we set it in the image element.

**Comment by louisreingold** [comment]
Duplicate: https://github.com/soflyy/breakdance-bugs/issues/923
