### ISSUE TITLE
Custom tag functionality to Posts List Heading

### ISSUE THREAD

**Issue by portseif** [soflyy/breakdance-bugs#97]
Posts List heading element comes as a standard H1-H6, but it would be nice to have:

- span
- custom

**Comment by louisreingold** [comment]
What specific custom tags are you looking for? Why do you want to make it a span?

**Comment by portseif** [comment]
> What specific custom tags are you looking for? Why do you want to make it a span?

Example use case would be having a Services menu with a CPT of Services. Within the menu, we don't want heading tags, but more-so an li, span, or div tags.

**Comment by louisreingold** [comment]
> Example use case would be having a Services menu with a CPT of Services. Within the menu, we don't want heading tags, but more-so an li, span, or div tags.

Use the upcoming Post Loop Builder element.

**Comment by louisreingold** [comment]
Support for `span` and `div` tags for Posts List titles will be available in the next beta.
