### ISSUE TITLE
Undefined array key "query" in Product List BD 1.6 rc

### ISSUE THREAD

**Issue by artur-burkalo** [soflyy/breakdance-bugs#972]
Error when setting a 'query' inside the product list

Warning: Undefined array key "query" in /Users/arturburkalo/Local Sites/bd-16-dev-with-de-17/app/public/wp-content/plugins/breakdance/subplugins/breakdance-woocommerce/util/products.php on line 34

**Comment by louisreingold** [comment]
Thanks for the report! This will be addressed in Breakdance 1.6 final.
