### ISSUE TITLE
Facebook Like button element not working

### ISSUE THREAD

**Issue by high2306** [soflyy/breakdance-bugs#973]
You MUST include a clear description of the bug and EXACT steps to reproduce the bug or IT WILL BE CLOSED:

For example:
1. Enter Facebook App ID in breakdance API settings
2. Insert facebook like button on a random page with its default settings
3. Open the page as a logged-out user and check if the button is there

Breakdance version: 1.5.0
Adding facebook share button element works, but when trying to add facebook like button it doesn't display on the front-end of the website.

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
