### ISSUE TITLE
Post List element throws Errors on RC 1.6

### ISSUE THREAD

**Issue by choegl** [soflyy/breakdance-bugs#974]
Put a Post List element on a regular page with no special filters. Works fine in 1.5, but in RC 1.6 I get an 500 error already on opening the page, and also on saving it.  Changes are saved in spite the error. Also, from the frontend the page behaves as intended.

After downgrading to 1.5 the error is gone.

Error Code: 500
Request Time: Mon, 23 Oct 2023 07:26:52 GMT
Request URI: https://creativbox.at/portfolio/?_breakdance_doing_ajax=yes&_ajax_nonce=5c1d347278
Request Type: POST

**REQUEST DETAILS**

Response Code: 500
Request Time: Mon, 23 Oct 2023 07:26:52 GMT
Request Type: POST
Request URL: https://creativbox.at/portfolio/?_breakdance_doing_ajax=yes&_ajax_nonce=5c1d347278
Body:
{
  "action": "breakdance_server_side_render",
  "properties": "{\"design\":{\"list\":{\"layout\":\"grid\",\"items_per_row\":{\"breakpoint_base\":3,\"breakpoint_tablet_landscape\":2},\"one_item_at\":\"breakpoint_tablet_portrait\",\"space_between_items\":{\"breakpoint_base\":{\"number\":20,\"unit\":\"px\",\"style\":\"20px\"}}},\"post\":{\"container\":{\"alignment\":\"center\"}},\"spacing\":{\"margin_top\":{\"breakpoint_base\":{\"number\":80,\"unit\":\"px\",\"style\":\"80px\"}}},\"filter_bar\":{\"style\":\"tabs\",\"position\":\"center\",\"separator\":{\"color\":\"#FFFFFF00\"},\"padding\":{\"horizontal\":{\"number\":25,\"unit\":\"px\",\"style\":\"25px\"}}}},\"content\":{\"post\":{\"title\":{\"disable\":false},\"meta\":null,\"taxonomy\":{\"disable\":true,\"type\":\"category\"},\"content\":{\"type\":\"excerpt\",\"excerpt_length\":200},\"button\":{\"disable\":false,\"button_text\":\"Details\"}},\"query\":null,\"filter_bar\":{\"enable\":false,\"type\":\"category\",\"all_filter\":true,\"all_label\":\"alle\"}}}",
  "parentProperties": "{}",
  "elementSlug": "EssentialElements\\Postslist",
  "triggeringDocument": 744,
  "breakdance_ajax_at_any_url": "true"
}

**ERROR DETAILS**

Breakdance\AJAX\BreakdanceAjaxHandlerException: Undefined array key "button" in /var/www/vhosts/creativbox.at/httpdocs/wp-content/plugins/breakdance/plugin/ajax/api.php on 113

**Comment by louisreingold** [comment]
Thanks for the report! This will be fixed in 1.6 final.
