### ISSUE TITLE
License key problem after renewal

### ISSUE THREAD

**Issue by orhanbilikvar** [soflyy/breakdance-bugs#975]
I renewed my subscription. However, it seems that the License key has not been renewed.
i can't update...

![lisans-01](https://github.com/soflyy/breakdance-bugs/assets/48365764/82227e6d-908c-4e7c-94ad-0556de7605ee)

![lisans-02](https://github.com/soflyy/breakdance-bugs/assets/48365764/1c4f5d0c-a059-4b5d-90af-433ea43dec66)

and i can't download 1.5

![lisans-03](https://github.com/soflyy/breakdance-bugs/assets/48365764/1be2d950-0916-4b2f-a8ae-311b01ad7b37)

**Comment by louisreingold** [comment]
Our support team can be reached at support@breakdance.com. They'd be happy to help you.
