### ISSUE TITLE
Copy pasting styles does not copy style settings in advanced

### ISSUE THREAD

**Issue by JeusuDigital** [soflyy/breakdance-bugs#976]
1. Create a page
2. Add an element such as DIV
3. Add some styles to the DIV via advanced menu then wrapper
4. Create another DIV element
5. Right click and copy styles from first DIV
6. Right click new DIV and paste design

Expected behaviour:
Second DIV includes all styles including those applied through advanced menu

Actual behaviour:
Second DIV only has styles that are applied through standard styles menu and advanced styles are not copied

Breakdance version: 1.6.0 (Though has been the case in older versions also)
Browser & OS: Chrome, Windows 11

**Comment by mikeingz** [comment]
That's because you have to use the **PASTE SETTINGS** if you want to paste the style from the Advanced menu

**Comment by JeusuDigital** [comment]
> That's because you have to use the **PASTE SETTINGS** if you want to paste the style from the Advanced menu

Doh! I can't believe I have never noticed that! Thanks
