### ISSUE TITLE
URGENT: In 1.6 editor role cannot set background image or styles of div/section/column

### ISSUE THREAD

**Issue by Bobolinos** [soflyy/breakdance-bugs#985]
URGENT: In 1.6 editor role cannot set background image or styles of div/section/column

**Comment by louisreingold** [comment]
Starting in 1.6, this is deliberate, correct behavior. We advise using dynamic data if you wish this make this type of thing editable by a client.

**Comment by Bobolinos** [comment]
@louisreingold, I don't understand why you guys would do this, but I have to live with it. From a clients perspective it's weird why he can change an image but not a background image. Going to give full rights to clients now. 
There is a canny here that is under review: https://breakdance.canny.io/features/p/editor-roles-to-elements
Hopefully things will bring much more options for setting clients rights like which fields they can edit and which modules they can add etc. Please do not force us how we should deal with clients. 

In the meantime, adding more classes to the UI would really help!
https://github.com/soflyy/breakdance-bugs/issues/755
