### ISSUE TITLE
Option to disable keyboard control setting for sliders

### ISSUE THREAD

**Issue by orhanbilikvar** [soflyy/breakdance-bugs#989]
Where more than one swiper element is used, the keyboard slides them all at the same time.
* keyboard: true / false

**Comment by orhanbilikvar** [comment]
![keyborad2023-11-09-09-26-42](https://github.com/soflyy/breakdance-bugs/assets/48365764/c7dc54c1-9409-4cbf-944a-897769936758)

**Comment by breakdancemoderator** [comment]
Thanks for the report. This has been addressed in Breakdance 2.0.
