### ISSUE TITLE
Bearkdance Zero Theme with "Keep Theme" leads to whacky div classes and DOM structure

### ISSUE THREAD

**Issue by dreadedhamish** [soflyy/breakdance-bugs#992]
The bug is if using the Breakdance Zero Theme with the "Keep Theme" setting leads to all sections of a page being wrapped in the <div class="breakdance">, all of them nested under the <body> which also has the class of 'breakdance'.  I'm assumign this is a bug because having the same class on different levels of the DOM heirachy is going to lead to drama - it did for me.

Steps to reproduce:
1. Clean install Breakdance Zero Theme, Breakdance.
2. Create page with some sections
3. Check Theme setting is "Disable theme"
4. View created page

Result:
```
<body class="breakdance ...>
   <header>
   <section>
   <section>
   <section> - this is the footer
</body>
```

5. Switch to "Keep Theme" and view page:

Result:

```
<body class="breakdance ...">
   <div class="breakdance">
      <header> - this is the header
   </div>
   <div class="breakdance">
      <section> 
      <section>
   </div>
   <div class="breakdance">
      <section> - this is the footer
   <div>
</body>
```

**Comment by jwarnox** [comment]
Same here, multiple wrapper divs with class of "breakdance", screenshot attached:
<img width="599" alt="Screenshot 2023-12-12 at 17 38 51" src="https://github.com/soflyy/breakdance-bugs/assets/35316/86d6f833-2051-4b94-a0be-38b1d0f5a9ca">

**Comment by JeusuDigital** [comment]
There was a previous issue I opened about this, Louis said it is by design and required: 

https://github.com/soflyy/breakdance-bugs/issues/547

https://github.com/soflyy/breakdance-bugs/issues/547#issuecomment-1323139921

> No, it is 100% necessary for visual consistency between the frontend and the builder. There are many edge cases. Sure, it looks like it works if you just put it on the body class, but it doesn't. Not really. Not in all cases.
> 
> This behavior won't change.

**Comment by dreadedhamish** [comment]
> There was a previous issue I opened about this, Louis said it is by design and required:
> 
> #547
> 
> [#547 (comment)](https://github.com/soflyy/breakdance-bugs/issues/547#issuecomment-1323139921)
> 
> > No, it is 100% necessary for visual consistency between the frontend and the builder. There are many edge cases. Sure, it looks like it works if you just put it on the body class, but it doesn't. Not really. Not in all cases.
> > This behavior won't change.

It cant't be absolutely necessary.
It's particularly bad as : 
1. it has 'breakdance' as a class on multiple levels of the DOM heirachy - I've had occasions where code that was shared wouldn't work because of this, and 
2. it inserts the 'breakdance' class even on pages where Breakdance isn't active.
